### ISSUE TITLE
阅读时疯狂弹窗显示请勿手动修改阅读记录

### ISSUE THREAD

**Issue by starringc** [MuiseDestiny/zotero-style#100]
![image](https://user-images.githubusercontent.com/107314214/216810639-042b5d9c-7f5d-46d7-8860-a7a8621d6b8e.png)
如图所示，经常疯狂弹出此窗口，几乎无法阅读。
后来发现在未分类条目中有一个新条目：
![image](https://user-images.githubusercontent.com/107314214/216810722-a86e5534-5d83-4bbc-865f-08cbf0084049.png)
猜测应该是这个的问题，期待修复

**Comment by MuiseDestiny** [comment]
已经重新上传2.0.9了，失误了，测试内容忘记删除了
