### ISSUE TITLE
style更新之后不能正常显示文献列表，但是老版本style可以正常使用

### ISSUE THREAD

**Issue by fengyuhang0113** [MuiseDestiny/zotero-style#1009]
总是会显示下列问题，请问这是怎么回事呀？
![image](https://github.com/MuiseDestiny/zotero-style/assets/153736660/42753e19-48a8-4c51-a937-7a31a2fb7cf7)

这是4.4.0版本的
![image](https://github.com/MuiseDestiny/zotero-style/assets/153736660/86a49e78-5018-4b13-a226-8196d9fc8fba)
这是更新后4.4.6版本的
![image](https://github.com/MuiseDestiny/zotero-style/assets/153736660/84fa1030-4c66-4c33-89f4-3ac5d321f945)
首页完全不显示文献列表了

**Comment by Fan-tas-tic** [comment]
同样的问题

**Comment by fengyuhang0113** [comment]
> 同样的问题

uu我去小红书上面找“经验盒子的店”这家客服解决了，你也可以去试试，不过解决之后就不能使用style的高能进度条了😥uu可以考虑考虑
