### ISSUE TITLE
Mac 无法修改列设置中的颜色

### ISSUE THREAD

**Issue by franco-ye** [MuiseDestiny/zotero-style#101]
在列设置中键入颜色代码确认后，颜色没有发生，windows下是正常的

**Comment by MuiseDestiny** [comment]
是所有列吗，还是哪一个

**Comment by franco-ye** [comment]
> 设置了之后，重新打开会被恢复为默认值，就是标题那列，其他列没有试，不知道怎么更改，麻烦大佬测试下了
<img width="237" alt="image" src="https://user-images.githubusercontent.com/110618725/217169100-e05db23c-35d6-4cee-adc2-056ae67135f7.png">

**Comment by MuiseDestiny** [comment]
麻烦有时间试试进度列呢

**Comment by franco-ye** [comment]
一样的大佬，颜色设置后，列宽刷新，但是依旧恢复默认值，而且发现了新毛病，不过应该是Zotero的问题，我是一个双屏用户，列太宽导致在副屏显示右键选项卡时，列设置会丢失
<img width="227" alt="image" src="https://user-images.githubusercontent.com/110618725/217170728-10ca78ba-ac2b-408c-b873-8e5f9cab8598.png">
<img width="199" alt="image" src="https://user-images.githubusercontent.com/110618725/217170808-a152c531-5710-4cca-bc2e-3108249eab15.png">

**Comment by MuiseDestiny** [comment]
好的，现在，你可以通过高级 编辑器 搜索zoterostyle来更改一些设置。我后面会尝试修复这个bug。

**Comment by franco-ye** [comment]
好的好的，静候；另外关于#标签列，是不是可以设置一些开关或者导入的功能，之前的标签都是不带#，所以识别不了

**Comment by MuiseDestiny** [comment]
> 好的好的，静候；另外关于#标签列，是不是可以设置一些开关或者导入的功能，之前的标签都是不带#，所以识别不了

https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.1
更新
