### ISSUE TITLE
nested tag: support multi-selection for AND query 多选功能

### ISSUE THREAD

**Issue by Raphael-Hao** [MuiseDestiny/zotero-style#1010]
[第一级多选](https://github.com/MuiseDestiny/zotero-style/issues/226#issuecomment-1523245697)
好像只可以在第一级的nested tag上支持AND操作，不同层级或者非第一级的nested tag不支持AND操作

**Comment by Raphael-Hao** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/234559109-e9a07950-b4f7-4ffb-89f7-d4b9a906086b.png)

**Comment by pengxy0** [comment]
确实需要这样的功能，期待٩(๑^o^๑)۶

**Comment by Gloogger** [comment]
赞同，能够在不同层级上使用AND操作可以很好地filter文献，希望能够加入！

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

更新获得此特性。
