### ISSUE TITLE
Zotero7 视图重大BUG，严重影响使用！！！

### ISSUE THREAD

**Issue by liuqi0314** [MuiseDestiny/zotero-style#1030]
BUG1：关闭Zotero之后，重新打开的视图不能恢复到最近的修改
BUG2：如图。

https://github.com/MuiseDestiny/zotero-style/assets/127284843/8ed83c6f-2720-4a56-a6e2-0f92bc4e60a3

![image](https://github.com/MuiseDestiny/zotero-style/assets/127284843/038e9dfb-2f65-47f7-bc1b-e026855c0f86)

**Comment by Cyan2077** [comment]
同样的问题出现，楼主应该改一下标题：列宽无法调节。这个问题特别严重，一会是没问题的，一会又会出现，至今没搞懂到底是什么导致的

**Comment by marrypoter2023** [comment]
同样的问题+1，和所有添加列的插件一起都会出现这个bug，从zotero7刚出就有了

**Comment by Cyan2077** [comment]
更新一下最新版的beta+最新版的style吧，博主已经解决这个问题了。
