### ISSUE TITLE
求助：加载zetero模块后，文献不能正确显示

### ISSUE THREAD

**Issue by lillness98** [MuiseDestiny/zotero-style#1039]
![image](https://github.com/user-attachments/assets/3804f9de-814e-4ff1-bf42-efcd1a3853e3)

**Comment by Summersyz** [comment]
我也遇到了这个问题

**Comment by 2302697214** [comment]
我也是

**Comment by MMYFeng** [comment]
同样的问题

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

**Comment by MuiseDestiny** [comment]
有bug请及时在zo内部建厂更新
