### ISSUE TITLE
关系图谱

### ISSUE THREAD

**Issue by ChinJCheung** [MuiseDestiny/zotero-style#104]
希望给个选项，后台不要绘制关系图谱

**Comment by ChinJCheung** [comment]
减少卡顿

**Comment by MuiseDestiny** [comment]
shift p关闭后不会绘制

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.4

安装此版本，可以尝试关闭/开启不常用功能，重启生效。默认全部开启。
