### ISSUE TITLE
Zotero 7 文献库变成空白

### ISSUE THREAD

**Issue by LuElls** [MuiseDestiny/zotero-style#1041]
<img width="1423" alt="截屏2024-07-16 12 37 58" src="https://github.com/user-attachments/assets/46796c52-8df7-40d6-baf3-efbbda152f7b">
<img width="1112" alt="截屏2024-07-16 12 38 24" src="https://github.com/user-attachments/assets/eff8320a-abc5-4374-87a9-8fb38acdf183">

**Comment by MuiseDestiny** [comment]
及时检查更新https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

**Comment by LuElls** [comment]
搞定啦！谢谢作者大大！！style真的是超级优秀的插件！！🥰
