### ISSUE TITLE
标题栏不能调整大小

### ISSUE THREAD

**Issue by Turbo0923** [MuiseDestiny/zotero-style#1042]
**不礼貌不回复，直接关闭**
![e42ece729fa46f7420de4a7886fbaae](https://github.com/user-attachments/assets/cea2d645-2c4b-4f95-b3eb-88f36483dbf9)
不能够调整期刊标签的大小

**Comment by MuiseDestiny** [comment]
禁用茉莉花，ctrl q退出。重新打开zo。多尝试几遍。
