### ISSUE TITLE
启用该插件，文献库条目无法显示

### ISSUE THREAD

**Issue by meethelen** [MuiseDestiny/zotero-style#1043]
请问启用该插件，文献库条目无法显示，这样的问题是什么情况呢，版本4.4.0
![Snipaste_2024-07-16_20-15-55](https://github.com/user-attachments/assets/c016642d-6ee1-4367-aaa5-baba5525ac69)

**Comment by ossianno** [comment]
我也遇到这个问题。

**Comment by ossianno** [comment]
我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。

**Comment by hsiaoching-liu** [comment]
> 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。

请问一下，那里可以下载4.5.8的插件？

**Comment by MichaelLyo** [comment]
> 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。

请问4.5.8在哪儿下载呢，release页最新的是4.4.0

**Comment by sora315** [comment]
> > 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。
> 
> 请问4.5.8在哪儿下载呢，release页最新的是4.4.0

在Zotero自带的插件管理里面选择检查更新

**Comment by zhaoyanxue666** [comment]
> > > 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。
> > 
> > 
> > 请问4.5.8在哪儿下载呢，release页最新的是4.4.0
> 
> 在Zotero自带的插件管理里面选择检查更新

谢谢，解决了，更新4.5.8确实可以了
![image](https://github.com/user-attachments/assets/04dc5a90-b3a0-43e5-b2a8-1727db0964fe)

**Comment by meethelen** [comment]
> 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。

我也解决了，谢谢你

**Comment by MichaelLyo** [comment]
> > > 我解决了。release里安装的是4.4.0版本，在插件管理页手动更新到4.5.8即可。
> > 
> > 
> > 请问4.5.8在哪儿下载呢，release页最新的是4.4.0
> 
> 在Zotero自带的插件管理里面选择检查更新

感谢！我也找到了，解决了问题
<img width="749" alt="image" src="https://github.com/user-attachments/assets/e0eca1bd-5332-4124-ae25-4690fc3e95e1">
具体位置在这儿

**Comment by Eyxxxxx** [comment]
本人目前使用 7.0.0-beta.91+3c6625f3c (64-bit) 版本，加上4.3.0版本的插件，感觉海星，这俩更新任意一个都会出好多bug的感觉。

**Comment by a-liys** [comment]
我check for updates后还是4.4.0怎么办呀

**Comment by ghostning** [comment]
感谢，排除到style这个插件的问题，来看issue，升级已解决。

**Comment by ghostning** [comment]
> 我check for updates后还是4.4.0怎么办呀

科学一下

**Comment by zouyi1998** [comment]
升级到最新4.5.8后，会和翻译插件起冲突导致软件崩溃，还是建议zotero 7和插件不要自动更新，用旧版zotero和插件。我现在的可用版本是这样的：
1. zotero 7：7.0.0-beta.95+694ccecf4 (64-bit)
2. Ethereal Style：4.3.5
3. Translate for Zotero：1.1.0-beta.55
4. Zotero Reading List：1.3.1

**Comment by deardeer7** [comment]
就离谱啊，我全新安装的zotero7，然后从release下的最新的4.4，结果就是zotero中间条目显示是空白的无法显示，禁用了style插件就好了，然后看到这个issue，软件内容check update更新到4.5.8就好了

**Comment by zouyi1998** [comment]
> 就离谱啊，我全新安装的zotero7，然后从release下的最新的4.4，结果就是zotero中间条目显示是空白的无法显示，禁用了style插件就好了，然后看到这个issue，软件内容check update更新到4.5.8解决了

你好，请问最新版zotero 7配合最新style会有软件崩溃的问题，我有点不敢更新了

**Comment by MuiseDestiny** [comment]
> > 就离谱啊，我全新安装的zotero7，然后从release下的最新的4.4，结果就是zotero中间条目显示是空白的无法显示，禁用了style插件就好了，然后看到这个issue，软件内容check update更新到4.5.8解决了
> 
> 你好，请问最新版zotero 7配合最新style会有软件崩溃的问题，我有点不敢更新了

不会有问题，最新已发布https://github.com/MuiseDestiny/zotero-style/releases/tag/4.6.0
