### ISSUE TITLE
The library page gets blank

### ISSUE THREAD

**Issue by YaproYoung** [MuiseDestiny/zotero-style#1047]
![error_page_zotero_style](https://github.com/user-attachments/assets/be3584d0-f37c-41c7-971a-9ff9c48954ad)
The page got blank when using the zotero-style plugin.

**Comment by YaoLiMuMu** [comment]
Identical error.

**Comment by whdecx** [comment]
It seems this can be solved by updating the plugin to 4.5.8 in zotero. https://github.com/MuiseDestiny/zotero-style/issues/1043#issuecomment-2232317614

**Comment by YaproYoung** [comment]
> It seems this can be solved by manually updating the plugin to 4.5.8 in zotero. [#1043 (comment)](https://github.com/MuiseDestiny/zotero-style/issues/1043#issuecomment-2232317614)

Thank you very much. It is resolved now.
