### ISSUE TITLE
影响因子栏和进度栏错误

### ISSUE THREAD

**Issue by TT5an** [MuiseDestiny/zotero-style#105]
![image](https://user-images.githubusercontent.com/50618104/217834568-c2ac7afb-3f31-4b33-ac34-bf179ca12074.png)
如图所示，影响因子栏和进度栏不对应，不能正确显示

**Comment by MuiseDestiny** [comment]
挺好的啊，哪里不对呢

**Comment by TT5an** [comment]
影响因子栏显示的是进度，进度不显示，而影响因子在其他里显示呢

**Comment by TT5an** [comment]
明白了，，有点误解了，您可以稍微改一下标题或者在文档里进行说明一下。

**Comment by MuiseDestiny** [comment]
> 这个条就是影响因子（所以我觉着在条边上加个数值也挺好），“进度”应该是批注分布，阅读进度应该在“标题”栏里，可以打开个pdf呆上几十秒，再加几个批注，就知道它们的作用了。“其它”里应该是影响因子的具体内容

加数字！

**Comment by MuiseDestiny** [comment]
@yfzhao20 
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.2

![image](https://user-images.githubusercontent.com/51939531/217988448-8ca0e399-9885-47ce-91d1-60bb50c382ac.png)

**Comment by TT5an** [comment]
> @yfzhao20 https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.2
> 
> ![image](https://user-images.githubusercontent.com/51939531/217988448-8ca0e399-9885-47ce-91d1-60bb50c382ac.png)

看到您的更新了，速度好快。能不能给您提个建议，把这个条显示也跟数字一样，都设置成可以自主设置是否显示。另外，很期待加上分区显示，这样就可以彻底删除IF插件了

**Comment by MuiseDestiny** [comment]
> > @yfzhao20 https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.2
> > ![image](https://user-images.githubusercontent.com/51939531/217988448-8ca0e399-9885-47ce-91d1-60bb50c382ac.png)
> 
> 看到您的更新了，速度好快。能不能给您提个建议，把这个条显示也跟数字一样，都设置成可以自主设置是否显示。另外，很期待加上分区显示，这样就可以彻底删除IF插件了

我把easyscholar全迁移过来吧

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218043580-bbf81b1d-a228-488a-aacf-3a53873f67a6.png)

https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3
安装最新版，打开`期刊标签`列

**Comment by TT5an** [comment]
卧槽，您这反馈速度太快了！感谢！
