### ISSUE TITLE
影响因子列是否可以增加设置，只显示数字而不显示进度条

### ISSUE THREAD

**Issue by zyx335588** [MuiseDestiny/zotero-style#106]
RT，小屏幕空间太有限了。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3
见最新版
![image](https://user-images.githubusercontent.com/51939531/218043214-27748a8c-4345-4861-a8dc-a7764348b8ab.png)

**Comment by MuiseDestiny** [comment]
只设置个sciif就可以了，然后关闭`影响因子`列。
另外，视图组可以解决你说的问题，创建一个影响因子视图，当你想查看影响因子时候，切换到这个视图即可

**Comment by zyx335588** [comment]
> 只设置个sciif就可以了，然后关闭`影响因子`列。 另外，视图组可以解决你说的问题，创建一个影响因子视图，当你想查看影响因子时候，切换到这个视图即可

👍👍👍， 谢谢大神！
视图组的确可以解决这个问题，但是相比直观的显示，会增加一步切换视图组的操作。

**Comment by zyx335588** [comment]
呃，更新到最新版后，主界面的中间信息区域直接空白不显示任何内容了，disable style插件后重启可恢复显示（1），再次enable style插件（2），再次变空白以下为操作（2）的输出日志：

(3)(+0045246): itemTree.render(). Displaying Item Tree

(3)(+0000546): itemTree.render(). Displaying Item Tree

(3)(+0007554): [Zotero Style] addStyle

(3)(+0000001): [Zotero Style] {}

(3)(+0000001): [Zotero Style] [WARNING] ItemTreeTool.addRenderCellHook overwrites an existing hook: title

(3)(+0000000): [Zotero Style] patching _displayColumnPickerMenu by zoterostyle-setting-title

(3)(+0000001): [Zotero Style] patching setColor by CalledRefresh

(3)(+0000002): Refreshing items list for item-tree-main-default

(4)(+0000005): CREATE TEMPORARY TABLE tmpSearchResults_EKyXc2Fd AS SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL)) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?)) AND itemID IN (SELECT itemID FROM collectionItems WHERE (collectionID IN (384))) [1]

(4)(+0000008): CREATE INDEX tmpSearchResults_EKyXc2Fd_itemID ON tmpSearchResults_EKyXc2Fd(itemID)

(4)(+0000001): SELECT GROUP_CONCAT(itemID) FROM items WHERE itemID IN (SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?))) AND (itemID IN (SELECT itemID FROM tmpSearchResults_EKyXc2Fd) OR itemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_EKyXc2Fd)) OR itemID IN (SELECT itemID FROM itemNotes WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_EKyXc2Fd))) [1]

(4)(+0000004): DROP TABLE IF EXISTS tmpSearchResults_EKyXc2Fd

(3)(+0000003): Refreshed open parents in 0 ms

(3)(+0000001): Updating tag selector from current view

(3)(+0000000): Creating tmpSearchResults_CClnylsV with 24 items

(3)(+0000006): itemTree.render(). Displaying Item Tree

(3)(+0000021): [Zotero Style] {}

(3)(+0000019): [Zotero Style] {}

(3)(+0000004): [Zotero Style] {}

(3)(+0000005): [Zotero Style] {}

(3)(+0000004): [Zotero Style] {}

(3)(+0000006): [Zotero Style] {}

(3)(+0000004): [Zotero Style] {}

(3)(+0000007): [Zotero Style] {}

(3)(+0000002): [Zotero Style] {}

(3)(+0000003): [Zotero Style] {}

(3)(+0000002): [Zotero Style] {}

(3)(+0000002): [Zotero Style] {}

(3)(+0000002): [Zotero Style] {}

(3)(+0000002): [Zotero Style] {}

(3)(+0000006): itemTree.render(). Displaying Item Tree

(2)(+0000009): Storing itemTree item-tree-main-default column prefs

(3)(+0000007): Columns title width 450.5

(3)(+0000000): Columns Tags width 68

(3)(+0000000): Columns firstCreator width 81

(3)(+0000000): Columns publicationTitle width 119

(3)(+0000000): Columns language width 41

(3)(+0000000): Columns archive width 80

(3)(+0000000): Columns dateAdded width 96.5

(3)(+0000001): Refreshing items list for item-tree-main-default

(4)(+0000003): CREATE TEMPORARY TABLE tmpSearchResults_wBagmziE AS SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID NOT IN (SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL) AND itemID NOT IN (SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL)) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?)) AND itemID IN (SELECT itemID FROM collectionItems WHERE (collectionID IN (384))) [1]

(3)(+0000001): zotcard@selectedItems: 0

(3)(+0000000): zoteropreview: getCitationPreview testing undefined

(3)(+0000000): zoteropreview: getCitationPreview done

(3)(+0000000): -------------------

(4)(+0000001): CREATE UNIQUE INDEX tmpSearchResults_CClnylsV_itemID ON tmpSearchResults_CClnylsV(itemID)

(4)(+0000014): CREATE INDEX tmpSearchResults_wBagmziE_itemID ON tmpSearchResults_wBagmziE(itemID)

(4)(+0000001): SELECT DISTINCT tagID || ':' || type FROM itemTags JOIN tags USING (tagID) WHERE 1 AND itemID IN (SELECT itemID FROM tmpSearchResults_CClnylsV UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_CClnylsV)) ORDER BY name COLLATE NOCASE

(4)(+0000000): SELECT GROUP_CONCAT(itemID) FROM items WHERE itemID IN (SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND itemID IN (SELECT itemID FROM items WHERE (libraryID=?))) AND (itemID IN (SELECT itemID FROM tmpSearchResults_wBagmziE) OR itemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_wBagmziE)) OR itemID IN (SELECT itemID FROM itemNotes WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_wBagmziE))) [1]

(3)(+0000002): Tags haven't changed

(3)(+0000001): Rendering tag selector

(3)(+0000002): Rendering tag list

(3)(+0000002): Tag selector updated

(4)(+0000008): DROP TABLE IF EXISTS tmpSearchResults_wBagmziE

(3)(+0000002): Refreshed open parents in 0 ms

(3)(+0000001): Updating tag selector from current view

(4)(+0000000): SELECT DISTINCT tagID || ':' || type FROM itemTags JOIN tags USING (tagID) WHERE 1 AND itemID IN (SELECT itemID FROM tmpSearchResults_CClnylsV UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM tmpSearchResults_CClnylsV)) ORDER BY name COLLATE NOCASE

(3)(+0000001): itemTree.render(). Displaying Item Tree

(3)(+0000012): [Zotero Style] {}

(3)(+0000001): [Zotero Style] {}

(3)(+0000008): Tags haven't changed

(3)(+0000000): Rendering tag selector

(3)(+0000002): Rendering tag list

(3)(+0000002): Tag selector updated

(3)(+0020149): [Zotero Style] listeningReader is running

(3)(+0010010): [Zotero Style] listeningReader is running

(3)(+0002323): [Zotero Better Notes] sync start

(3)(+0000000): [Zotero Better Notes] BN:Sync

(3)(+0000000): [Zotero Better Notes] [object Object]

(3)(+0007683): [Zotero Style] listeningReader is running

(3)(+0010005): [Zotero Style] listeningReader is running

(3)(+0009767): Getting contents of C:\Users\Flyboy\AppData\Roaming\Zotero\Zotero\Profiles\h5tlsdfb.default\treePrefs.json

(3)(+0000002): Writing column prefs of length 5749 to file C:\Users\Flyboy\AppData\Roaming\Zotero\Zotero\Profiles\h5tlsdfb.default\treePrefs.json

(3)(+0000234): [Zotero Style] listeningReader is running

(3)(+0002312): [Zotero Better Notes] sync start

(3)(+0000000): [Zotero Better Notes] BN:Sync

(3)(+0000001): [Zotero Better Notes] [object Object]

(3)(+0007692): [Zotero Style] listeningReader is running

(3)(+0010007): [Zotero Style] listeningReader is running
