### ISSUE TITLE
在文中标注了段落后，怎么在标注的内容上再进行划词

### ISSUE THREAD

**Issue by lLINLINLINl** [MuiseDestiny/zotero-style#1062]
如题，会默认拖拽文字
![QQ20240806-190445](https://github.com/user-attachments/assets/16667544-23c8-4802-96fd-8335e7a77a67)

**Comment by l7ee** [comment]
按住shift即可

**Comment by l7ee** [comment]
搞错了，是alt键

**Comment by lLINLINLINl** [comment]
> 搞错了，是alt键

感谢，解决了
