### ISSUE TITLE
Mac 列设置无效 期刊标签识别缺失率高

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#107]
1. 除了之前反馈的标题列进度的颜色设置无效以外，刚更新的期刊标签Fields修改后点击set也是无效的😂。
2. 期刊标签识别的缺失率很高：
3. 中文期刊的标签能识别吗？

**Comment by 17816712353** [comment]
4. 如果根据期刊名称识别标签的话，对于The and & 这些因为写法不同导致的期刊名称不同而识别不出来的问题不知道能不能解决。比如The Journal of Finance 和 Journal of Finance、比如Journal of Accounting and Economics 和 Journal of Accounting & Economics

**Comment by MuiseDestiny** [comment]
1. 我没有mac设备不太好解决
2. 我成功率还可以
3. 用的easyscholar的API中英文都可以，他有40种分类
4. 测试了一下，期刊不必太完美也可以得到结果，这个优化easyscholar官方api已经做了。Journal of Accounting and Economics和Journal of Accounting & Economics得到结果是一样的。

**Comment by 17816712353** [comment]
> * 我没有mac设备不太好解决
> * 我成功率还可以
> * 用的easyscholar的API中英文都可以，他有40种分类
> * 测试了一下，期刊不必太完美也可以得到结果，这个优化easyscholar官方api已经做了。Journal of Accounting and Economics和Journal of Accounting & Economics得到结果是一样的。

太强了！不过大佬我发现这些缺失的条目在“其他”框中都是有对应的信息的，为啥在期刊标签栏没有显示鸭？
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/68216639/218076444-0dc72c49-21ef-4b4a-a936-e86253fbeb16.png">

**Comment by MuiseDestiny** [comment]
> > * 我没有mac设备不太好解决
> > * 我成功率还可以
> > * 用的easyscholar的API中英文都可以，他有40种分类
> > * 测试了一下，期刊不必太完美也可以得到结果，这个优化easyscholar官方api已经做了。Journal of Accounting and Economics和Journal of Accounting & Economics得到结果是一样的。
> 
> 太强了！不过大佬我发现这些缺失的条目在“其他”框中都是有对应的信息的，为啥在期刊标签栏没有显示鸭？ <img alt="image" width="1246" src="https://user-images.githubusercontent.com/68216639/218076444-0dc72c49-21ef-4b4a-a936-e86253fbeb16.png">

我知道了，因为mac无法设置的bug，一些颜色无法正确读取。我修复下，一会帮我测试下。

**Comment by 17816712353** [comment]
> > > * 我没有mac设备不太好解决
> > > * 我成功率还可以
> > > * 用的easyscholar的API中英文都可以，他有40种分类
> > > * 测试了一下，期刊不必太完美也可以得到结果，这个优化easyscholar官方api已经做了。Journal of Accounting and Economics和Journal of Accounting & Economics得到结果是一样的。
> > 
> > 
> > 太强了！不过大佬我发现这些缺失的条目在“其他”框中都是有对应的信息的，为啥在期刊标签栏没有显示鸭？ <img alt="image" width="1246" src="https://user-images.githubusercontent.com/68216639/218076444-0dc72c49-21ef-4b4a-a936-e86253fbeb16.png">
> 
> 我知道了，因为mac无法设置的bug，一些颜色无法正确读取。我修复下，一会帮我测试下。

好叻，待命ing

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218077735-8b881dd5-739d-4109-aa6a-21e77877eb9e.png)

截图下这个，搜索`publicationTags`发给我看看

**Comment by 17816712353** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/68216639/218078024-f15de62c-4cf3-4a20-b782-e4326c3b7e99.png">


> ![image](https://user-images.githubusercontent.com/51939531/218077735-8b881dd5-739d-4109-aa6a-21e77877eb9e.png)
> 
> 截图下这个，搜索`publicationTags`发给我看看

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/68216639/218078046-4f834187-97be-4f72-8ae2-328570f8a7a0.png">

**Comment by MuiseDestiny** [comment]
opacity可以设置保存吗？

**Comment by 17816712353** [comment]
> 

可以保存，标题列的opacity也是可以设置保存的。此外都不行，set后再打开又变回去了

**Comment by 17816712353** [comment]
> opacity可以设置保存吗？

可以保存，标题列的opacity也是可以设置保存的。此外都不行，set后再打开又变回去了

**Comment by MuiseDestiny** [comment]
> 

只有输入类型的不能保存，我知道了，改一下

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3

![image](https://user-images.githubusercontent.com/51939531/218080609-e17075e2-932a-4444-bf6f-d77073f73b79.png)
重新上传了，下载安装试试

**Comment by 17816712353** [comment]
> https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3
> 
> ![image](https://user-images.githubusercontent.com/51939531/218080609-e17075e2-932a-4444-bf6f-d77073f73b79.png) 重新上传了，下载安装试试

Fields 能设置修改了，其他的还是不行。😂。
然后“其他”里有期刊标签信息的条目，在期刊标签列也没有显示出来。。
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/68216639/218081502-1e360731-4c90-435c-8873-9b7124a68901.png">

**Comment by 17816712353** [comment]
> > https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3
> > ![image](https://user-images.githubusercontent.com/51939531/218080609-e17075e2-932a-4444-bf6f-d77073f73b79.png) 重新上传了，下载安装试试
> 
> Fields 能设置修改了，其他的还是不行。😂。 然后“其他”里有期刊标签信息的条目，在期刊标签列也没有显示出来。。 <img alt="image" width="1266" src="https://user-images.githubusercontent.com/68216639/218081502-1e360731-4c90-435c-8873-9b7124a68901.png">

Fields 也是只能删，不能加

**Comment by MuiseDestiny** [comment]
> Fields 能设置修改了，其他的还是不行。😂。

就是能设置了，试试标题的进度条颜色能不能更改，一个个来

**Comment by MuiseDestiny** [comment]
意思是删除能保存，新填写的不能保存吧

**Comment by 17816712353** [comment]
> 意思是删除能保存，新填写的不能保存吧

是的，标题的进度条颜色目前也还改不了。

**Comment by MuiseDestiny** [comment]
再下载安装试试，其实刚刚上传错了）：

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218082906-4113d9c1-54e9-4f42-ab99-0564b5d60b49.png)
另外截图我看看输出日志，解决下`期刊标签`不显示

**Comment by 17816712353** [comment]
> 再下载安装试试，其实刚刚上传错了）：

标题的进度条颜色可以修改生效了。期刊标签列我还没试，因为一个也显示不出来了😂
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/218083058-a90cf546-7041-418a-83ca-4bfbfe515b20.png">

**Comment by 17816712353** [comment]
> 我猜是因为”change“事件windows和mac不同导致的（算是解决了）。期刊标签截图我看看错误日志

<img width="662" alt="image" src="https://user-images.githubusercontent.com/68216639/218083673-4b375c5a-375b-4eb9-98dd-989f19c23ced.png">
是这个吗？

**Comment by MuiseDestiny** [comment]
对的。看起来没有特殊报错

**Comment by MuiseDestiny** [comment]
再重新截图下
![image](https://user-images.githubusercontent.com/51939531/218084149-d465019c-0834-4e14-ac0a-eb8d5108a073.png)

**Comment by 17816712353** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/68216639/218084327-f0273efc-faa2-4b08-b37b-043b756cbb39.png">


> 再重新截图下
> ![image](https://user-images.githubusercontent.com/51939531/218084149-d465019c-0834-4e14-ac0a-eb8d5108a073.png)

**Comment by MuiseDestiny** [comment]
我也都不显示了，神奇

**Comment by 17816712353** [comment]
> 

😂😂。。。。。

**Comment by MuiseDestiny** [comment]
现在测试呢，重新下载

**Comment by 17816712353** [comment]
> 现在测试呢，重新下载

现在能出来的只有这么多。。

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/218087107-1fbfb155-9b5a-47b7-bcd2-f74046fe202e.png">

我比较了一下，成功显示的，“其他”里会比不能显示的多这么一串信息：
<img width="420" alt="image" src="https://user-images.githubusercontent.com/68216639/218087352-8fd78bcc-5432-47dc-9fff-80458e93c511.png">

**Comment by MuiseDestiny** [comment]
终于好了，是这样的，没显示的可能 期刊 是空的，或者没有你要显示的字段（设置里Fields）。

**Comment by MuiseDestiny** [comment]
是一个bug，再稍等

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218090960-244ebf6c-0faf-499d-8fb1-cb2e3c847971.png)
修复了。

**Comment by 17816712353** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/218090960-244ebf6c-0faf-499d-8fb1-cb2e3c847971.png)
> 修复了。
爱了爱了，已成功！！！

**Comment by 17816712353** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/218090960-244ebf6c-0faf-499d-8fb1-cb2e3c847971.png)
> 修复了。
> 爱了爱了，已成功！！！

作者大大，还有一个bug，辛苦您抽空瞄一眼，我发现当我在field里加入ssci后，界面就啥也没了。。不知道能不能修复😂。
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/218093421-93ecdf2f-0dbb-43d7-8b3f-c8c454d4a890.png">

还有一个小小的建议，有些期刊标签的键和值重复的话，显示出来就会很冗余，不知道有无办法可以调整（os：供参考哈，现在的状态已经大大超过我们这些使用者的预期了！！！）。
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/218093997-4cc2a1e8-46fa-474b-b288-271031a60698.png">

**Comment by MuiseDestiny** [comment]
对的，不显示键会节省空间，现在只是复刻easyscholar的效果。还是初期，会慢慢优化的。

> 我发现当我在field里加入ssci后，界面就啥也没了。。不知道能不能修复
加入其它的呢，重启后，加入的ssci还在不

**Comment by 17816712353** [comment]
> 还是初期，会慢慢优化的。
> 
> > 有些期刊标签的键和值重复的话
> > 这个是因为这个字段没适配，等我适配下。ei就适配了，只显示EI索引，而不是EI EI
> 
> > 我发现当我在field里加入ssci后，界面就啥也没了。。不知道能不能修复
> > 加入其它的呢，重启后，加入的ssci还在不

目前只有ssci出现这样的问题。

**Comment by MuiseDestiny** [comment]
重新下载安装试试，刚上传了

**Comment by 17816712353** [comment]
> 重新下载安装试试，刚上传了

不会崩溃了，但是没有显示ssci的标签。
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/68216639/218103669-86e89b34-0e84-4abf-acb4-c35c7519c4e7.png">

**Comment by MuiseDestiny** [comment]
我知道了，写错了这个地方

**Comment by 17816712353** [comment]
> > > 重新下载安装试试，刚上传了
> > 
> > 
> > 不会崩溃了，但是没有显示ssci的标签。 <img alt="image" width="1281" src="https://user-images.githubusercontent.com/68216639/218103669-86e89b34-0e84-4abf-acb4-c35c7519c4e7.png">
> 
> 发我一个有ssci的论文我测试下

Berkowitz et al.，2015，Journal of Financial Economics：Do property rights matter? Evidence from a property law Enactment.

**Comment by MuiseDestiny** [comment]
修复了，重新下

**Comment by 17816712353** [comment]
> 修复了，重新下

成功了，爱了爱了，太牛了吧！！！
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/218105723-44d0068c-1b95-4538-861d-dbe0c3cc721c.png">
应该没啥bug了，接下来就期待作者慢慢优化了！！大👍

**Comment by MuiseDestiny** [comment]
知道原因，已解决，主要是粗心，才留这么多bug

**Comment by MuiseDestiny** [comment]
重新下载安装解决

**Comment by 17816712353** [comment]
> 重新下载安装解决

已完美解决，祝作者大大科研顺利，paper多多！

**Comment by FakeTrader** [comment]
IEEE 旗下的期刊不显示标签，包括 TPAMI、TIP、TVCG 等，Extra 中有数据。

示例：
[10.1109/TPAMI.2018.2798607](https://doi.org/10.1109/TPAMI.2018.2798607)
[10.1109/TVCG.2020.3030418](https://doi.org/10.1109/TVCG.2020.3030418)

**Comment by MuiseDestiny** [comment]
> IEEE 旗下的期刊不显示标签，包括 TPAMI、TIP、TVCG 等，Extra 中有数据。
> 
> 示例： [10.1109/TPAMI.2018.2798607[ ](https://sci-hub.wf/10.1109/TPAMI.2018.2798607)](https://doi.org/10.1109/TPAMI.2018.2798607) [10.1109/TVCG.2020.3030418](https://doi.org/10.1109/TVCG.2020.3030418)

![image](https://user-images.githubusercontent.com/51939531/218252466-159f9df7-74aa-4664-ba3b-7ff2d04cf9e1.png)


![image](https://user-images.githubusercontent.com/51939531/218252437-27f3f929-417e-4a6f-8a31-7ecf8d691445.png)

**Comment by FakeTrader** [comment]
> > IEEE 旗下的期刊不显示标签，包括 TPAMI、TIP、TVCG 等，Extra 中有数据。
> > 示例： [10.1109/TPAMI.2018.2798607[ ](https://sci-hub.wf/10.1109/TPAMI.2018.2798607)](https://doi.org/10.1109/TPAMI.2018.2798607) [10.1109/TVCG.2020.3030418](https://doi.org/10.1109/TVCG.2020.3030418)
> 
> ![image](https://user-images.githubusercontent.com/51939531/218252466-159f9df7-74aa-4664-ba3b-7ff2d04cf9e1.png)
> 
> ![image](https://user-images.githubusercontent.com/51939531/218252437-27f3f929-417e-4a6f-8a31-7ecf8d691445.png)

我试了一下，如果期刊是 CCF A 类，就会出现问题：CCF 及之后的标签均不显示。

![ccfpost](https://user-images.githubusercontent.com/9635792/218256578-e9d22553-2dd1-415e-8ddb-5cdf67a65402.png)

![ccf](https://user-images.githubusercontent.com/9635792/218256579-f2584e63-0cad-426b-926e-1374c8249f39.png)

如果不是 A 类，则没有问题。

**Comment by MuiseDestiny** [comment]
> 如果不是 A 类，则没有问题。

太细了，确实是我写错了这部分

**Comment by MuiseDestiny** [comment]
@FakeTrader 
https://github.com/MuiseDestiny/zotero-style/releases/edit/2.1.4
重新上传了，重新下载安装修复

**Comment by FakeTrader** [comment]
> https://github.com/MuiseDestiny/zotero-style/releases/edit/2.1.4 重新上传了，重新下载安装修复

可以了，大佬给力 👍
