### ISSUE TITLE
论文评级无法快速设置

### ISSUE THREAD

**Issue by HydraCaesar** [MuiseDestiny/zotero-style#1088]
前段时间发现论文评级没法直接在论文列表里手动拖的方式进行设置，只能在论文详情的标签里面新建和评级的icon一样的标签才能显示
![image](https://github.com/user-attachments/assets/a139ef04-804e-4e07-b480-6d55b06ba7b4)
（这里没法直接拖动设置评级）
![image](https://github.com/user-attachments/assets/a518357d-681e-4835-8c3c-511fce045820)
只能在这里新建标签
![image](https://github.com/user-attachments/assets/d00a0349-c4a8-4235-9476-e74a6a132458)
zotero版本是7.0
![image](https://github.com/user-attachments/assets/8f23181d-280f-458a-996f-c85ace424e2c)
style版本是4.7.6

**Comment by ZJunSong** [comment]
我也遇到同样的问题

**Comment by HydraCaesar** [comment]
> 我也遇到同样的问题

我用一个很怪的方法解决了，在列设置里面，设置无评星时的icon为-
这样就能直接拖动评级了，现在还不知道为什么空格不行，只能zotero7的交互逻辑说有点怪
