### ISSUE TITLE
mac没有“列设置”的选项

### ISSUE THREAD

**Issue by Silbrigs** [MuiseDestiny/zotero-style#109]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/62649486/218105926-8b27b375-ea9d-4e96-a79f-026b8bad5b69.png">

**Comment by MuiseDestiny** [comment]
是点击style添加的列吗（如标题，进度，标签。。。）

**Comment by Silbrigs** [comment]
是的


Polygon ***@***.***> 于2023年2月10日周五 21:58写道：

**Comment by Silbrigs** [comment]
> 是点击style添加的列吗（如标题，进度，标签。。。）
就是在顶上的导航栏右键添加的，所以是我操作哪里有问题了嘛？ 前两天刚升级了mac的最新版本

**Comment by MuiseDestiny** [comment]
> > 是点击style添加的列吗（如标题，进度，标签。。。）
> > 就是在顶上的导航栏右键添加的，所以是我操作哪里有问题了嘛？ 前两天刚升级了mac的最新版本

是第一次使用这个插件吗，如果是：
![image](https://user-images.githubusercontent.com/51939531/218245914-ae7d12dd-e50b-4c65-a95a-84b5dd5521e9.png)
比如`期刊`是zotero本身就有的列，没有列设置。在`标签`、`进度`、`标题`上会有列设置。

不是第一次使用，那以前`列设置`是正常的吗

**Comment by Silbrigs** [comment]
> > > 是点击style添加的列吗（如标题，进度，标签。。。）
> > > 就是在顶上的导航栏右键添加的，所以是我操作哪里有问题了嘛？ 前两天刚升级了mac的最新版本
> 
> 是第一次使用这个插件吗，如果是： ![image](https://user-images.githubusercontent.com/51939531/218245914-ae7d12dd-e50b-4c65-a95a-84b5dd5521e9.png) 比如`期刊`是zotero本身就有的列，没有列设置。在`标签`、`进度`、`标题`上会有列设置。
> 
> 不是第一次使用，那以前`列设置`是正常的吗

是第一次使用的

**Comment by MuiseDestiny** [comment]
猜测有可能是插件冲突，试试禁用其它插件看看能恢复正常不，实在不行用下面的方法

![image](https://user-images.githubusercontent.com/51939531/218256119-416b05e7-f481-4f17-a616-6c4c58b17fbb.png)

**Comment by Silbrigs** [comment]
CSSCI可以了，不过是不支持北大核心嘛？我还加入了北大核心，但是没显示出来。

**Comment by MuiseDestiny** [comment]
> CSSCI可以了，不过是不支持北大核心嘛？我还加入了北大核心，但是没显示出来。

我不清楚，应该是支持的，fields加入pku，有可能没显示的并不是北大核心？
https://easyscholar.cc/console/query，你可以在这里搜索，如果是，但没显示出，可以反馈给我，附上出问题的文献pdf或链接
![image](https://user-images.githubusercontent.com/51939531/218257155-eb5c86c7-bb4e-4772-b2fc-efb9041288c6.png)

**Comment by Silbrigs** [comment]
> 

可以啦，加入pku就行了，提个小建议~ 可以考虑一下直接用“北核”代替全称，这样字段也可以短点，视觉效果舒服些

**Comment by MuiseDestiny** [comment]
> 可以啦，加入pku就行了，提个小建议~ 可以考虑一下直接用“北核”代替全称，这样字段也可以短点，视觉效果舒服些

中，现在是复刻easycholar（他这么叫的），后期开一个讨论如何使用简称，或者提供自定义

**Comment by Silbrigs** [comment]
嗯嗯可以考虑，反正大家平时生活中也都是直接说北核的，问题不大
