### ISSUE TITLE
更改了标注的配色方案，但是zotero中显示的还是自带的配色方案（之前变成了新增的配色方案，但有时候会突然又变回去）

### ISSUE THREAD

**Issue by windbd** [MuiseDestiny/zotero-style#1093]
- 标注的配色方案
![image](https://github.com/user-attachments/assets/2e2f6863-180b-459b-a571-d9604cf378ce)
- zotero中显示
![image](https://github.com/user-attachments/assets/03368997-1425-4963-8b46-d3eaef526b09)

**Comment by windbd** [comment]
现在在设置中先关闭“Annotation colors”功能，再重新开启“Annotation colors”，发现可以正常使用

**Comment by MuiseDestiny** [comment]
![image](https://github.com/user-attachments/assets/23df4b91-fd3f-47ef-8ce5-9253a910042b)

更新到最新插件：[如何更新](https://gitee.com/MuiseDestiny/plugins#3-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0)，把这个改成0

**Comment by MuiseDestiny** [comment]
因为部分用户因为style导致条目持续加载中，设置了延迟加载。
