### ISSUE TITLE
2.13版本标签中怎么显示 SCI 升级版分区

### ISSUE THREAD

**Issue by AlexLee1992** [MuiseDestiny/zotero-style#111]
在 field 中怎么设置能够显示sci 升级版分区

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218235945-a85f4a10-89e3-4fb3-89a7-9d925c4a2d1a.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218235982-573136c7-237a-4194-8b4b-aec65881a103.png)
类似：可以看下`其它`下面，如果想让它显示`环境科学2区域xxx`，可以在fields中填写`sciUpSmall`
