### ISSUE TITLE
标注的颜色名称无法修改

### ISSUE THREAD

**Issue by pekideer** [MuiseDestiny/zotero-style#1124]
shift+p进入标注后，只能点最下面的加号，对于已添加的标注，无法修改、删除。
（在阅读界面，无法正常显示标注，这个可能是和其他软件的冲突导致的，所以才进style修改标注）![image](https://github.com/user-attachments/assets/7a63ee04-006e-4331-a412-01eec08d6cb5)

**Comment by pekideer** [comment]
我通过禁用插件，发现translate for zotero ethereal style ethereal reference 会影响标签的正常显示。这时，可能是由于我在style里设置了很多标签颜色（又无法编辑删除）的原因，有些pdf可以正常显示标注，有的则不能显示。而且在启动zotero、切换到阅读页面时，正常显示的标注一瞬间就消失不显示了。
我推测是style接管了软件的标注颜色定义，解决办法就是在style里把杂乱的标签颜色删除即可（但现在无法编辑）。

**Comment by math-positive-function** [comment]
我遇到的相同的问题,

**Comment by w1718w** [comment]
> 我通过禁用插件，发现translate for zotero ethereal style ethereal reference 会影响标签的正常显示。这时，可能是由于我在style里设置了很多标签颜色（又无法编辑删除）的原因，有些pdf可以正常显示标注，有的则不能显示。而且在启动zotero、切换到阅读页面时，正常显示的标注一瞬间就消失不显示了。 我推测是style接管了软件的标注颜色定义，解决办法就是在style里把杂乱的标签颜色删除即可（但现在无法编辑）。

无法编辑可以先去设置-高级-编辑器 里面搜索style，找到extensions.zotero.zoterostyle.annotationColors和extensions.zotero.zoterostyle.annotationColorsGroups然后恢复默认设置

**Comment by math-positive-function** [comment]
似乎 右键长按就可以删除

**Comment by Bottlecui** [comment]
有相似的问题，每一栏的颜色可以长按右键删除（最少剩2个），但一整条栏删除不了

**Comment by MuiseDestiny** [comment]
![image](https://github.com/user-attachments/assets/bef2f6eb-71f8-4406-bc76-1e3fa6e7da0c)

点恢复按钮
