### ISSUE TITLE
最新稳定版zotero 7.0.5 无法使用4.8.8 版本的style 插件

### ISSUE THREAD

**Issue by Jones-match** [MuiseDestiny/zotero-style#1129]
最新的zotero 7.0.5可以成功安装插件
![Snipaste_2024-09-18_15-25-09](https://github.com/user-attachments/assets/16ac7ea6-bfdc-4c54-8ed7-b06ac522cf29)
但在pdf 阅读时没有修改背景色的按钮
![Snipaste_2024-09-18_15-26-44](https://github.com/user-attachments/assets/d7d60e77-3a55-4b5d-94e2-02bad01d7b39)

在设置界面也没有style的相关选项

![Snipaste_2024-09-18_15-27-13](https://github.com/user-attachments/assets/99a21aba-7fcd-4b9d-ba97-8d88e650cfa4)

**Comment by reoLantern** [comment]
+1，出现了相同的问题

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

4.9.5最新
