### ISSUE TITLE
插件冲突导致无法使用问题

### ISSUE THREAD

**Issue by bianhaotian** [MuiseDestiny/zotero-style#113]
单独style自己使用的时候肯定是正常的，稍微多开几个插件就不行了，已经把citation和期刊信息获取的插件都关掉了。不知道是否能够调整，或者说就是只能选其一。
<img width="674" alt="image" src="https://user-images.githubusercontent.com/74863953/218247568-406339ac-2435-4924-bdb8-ef6bbded9905.png">

**Comment by MuiseDestiny** [comment]
> 单独style自己使用的时候肯定是正常的，稍微多开几个插件就不行了，已经把citation和期刊信息获取的插件都关掉了。不知道是否能够调整，或者说就是只能选其一。

应该是没有冲突的，注意下翻译插件，参考文献插件都要是最新版。

首先试一下重新下载style最新版安装。或者能测试出来具体跟谁冲突吗？

**Comment by MuiseDestiny** [comment]
冲突的主要原因是好几个插件都用到了一个公共的东西，这个公共部分代码有所调整就会有一定的冲突。以后会越来越稳定的，冲突越来越少。

**Comment by bianhaotian** [comment]
MuiseDestiny/zotero-style
竟然是Del Item With Attachment，我觉得很不可能冲突的插件。
另外想问一下啊，影响因子有的条目没有出现是数据缺失吗？但我看extra中的sciif他是有信息的。
2023-02-11
| |
边昊天
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年02月11日 16:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [MuiseDestiny/zotero-style] 插件冲突导致无法使用问题 (Issue #113) |

单独style自己使用的时候肯定是正常的，稍微多开几个插件就不行了，已经把citation和期刊信息获取的插件都关掉了。不知道是否能够调整，或者说就是只能选其一。

应该是没有冲突的，注意下翻译插件，参考文献插件都要是最新版。

首先试一下重新下载style最新版安装。或者能测试出来具体跟谁冲突吗？

**Comment by bianhaotian** [comment]
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/74863953/218248057-1dd00d5c-bd33-406b-a364-58807130651c.png">

**Comment by bianhaotian** [comment]
> 

是啊，你们的工作让我们的科研更加方便~

**Comment by MuiseDestiny** [comment]
Del Item With Attachment也用了这个公共代码，作者（Del Item With Attachment的）升级一下就不冲突了

**Comment by bianhaotian** [comment]
补充一下，scite,更新影响因子，reference，citation都是不冲突的

**Comment by MuiseDestiny** [comment]
> 影响因子有的条目没有出现是数据缺失吗？
调整下列宽，太窄了没显示出来

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218248178-3bf378fc-814b-4628-8a30-2229bf20f9af.png)
鼠标按住调整

**Comment by bianhaotian** [comment]
> 

那我需要跟Del Item With Attachment的作者反馈吗，我应该怎么告知，他能精准的进行修改？

**Comment by bianhaotian** [comment]
是进度条中的缺失，期刊标签中可以通过拉长正确显示。
<img width="353" alt="image" src="https://user-images.githubusercontent.com/74863953/218248249-87ed087d-d004-4571-9f51-c831cd7c1beb.png">

**Comment by MuiseDestiny** [comment]
噢噢，我理解错了，这里有sciif吗
![image](https://user-images.githubusercontent.com/51939531/218248287-70879a88-62eb-47f4-bf1a-67e025a46ee3.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218248308-bd0c8d85-e3fc-4a8b-a76c-ed43d6d04995.png)
3h前更新的可以安装试试

**Comment by bianhaotian** [comment]
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/74863953/218248325-0c45f8ef-b54c-4400-ae35-480f7d4be9d1.png">
是这样的

**Comment by MuiseDestiny** [comment]
试试把其它里内容都删除看看能自动刷新出来不

**Comment by MuiseDestiny** [comment]
我晓得了，等我更新下

**Comment by bianhaotian** [comment]
3h前更新的也不行，刚刚试了新下重装。重启zotero后会导致直接题录变白的（不兼容）。

**Comment by bianhaotian** [comment]
> 

感谢，更新完我来测试

**Comment by bianhaotian** [comment]
> 试试把其它里内容都删除看看能自动刷新出来不

顺带问一下，插件的更新逻辑是什么。每次打开zotero自动更新吗？

**Comment by MuiseDestiny** [comment]
> > 试试把其它里内容都删除看看能自动刷新出来不
> 
> 顺带问一下，插件的更新逻辑是什么。每次打开zotero自动更新吗？

在安装界面检查吧，不太清楚这个

**Comment by bianhaotian** [comment]
> 清楚

哦哦哦 我的意思是您style这个插件，因为你刚才提到尝试清除extra字段，所以想问下style插件拉取期刊和citation信息添加到extra字段中是怎么判断是否需要拉取的。

**Comment by MuiseDestiny** [comment]
> > 清楚
> 
> 哦哦哦 我的意思是您style这个插件，因为你刚才提到尝试清除extra字段，所以想问下style插件拉取期刊和citation信息添加到extra字段中是怎么判断是否需要拉取的。

自动更新的，只要这个字段勾选，自动获取数据并渲染

**Comment by MuiseDestiny** [comment]
重新下载https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3安装试试
![image](https://user-images.githubusercontent.com/51939531/218249445-9796aaa0-acdd-4653-8dc3-3a1521839194.png)
只要是数字，都可以在这里设置，比如sciif，sciif5，jci，同时注意设置一下Max，是整个条的最大值

**Comment by bianhaotian** [comment]
显示了。不过期刊标签中也存在缺失。
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/74863953/218249902-9059872d-171d-45a9-8367-d84e3dac5e7a.png">

**Comment by MuiseDestiny** [comment]
你设置显示的是sciif5，但是这个条目只有sciif，没有sciif5

**Comment by bianhaotian** [comment]
是的 看到了

**Comment by bianhaotian** [comment]
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/74863953/218251581-5e0e6eee-e6d2-48cb-b922-1a9362e87c68.png">
不过这个关系图谱怎么不见了

**Comment by bianhaotian** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/74863953/218251581-5e0e6eee-e6d2-48cb-b922-1a9362e87c68.png">
> 
> 不过这个关系图谱怎么不见了

shift p 来了

**Comment by MuiseDestiny** [comment]
@bianhaotian shift+p能开启吧

**Comment by MuiseDestiny** [comment]
@bianhaotian 
https://github.com/MuiseDestiny/zotero-style/issues/48
截图挺好看的，欢迎贴图到这里

**Comment by bianhaotian** [comment]
> @bianhaotian shift+p能开启吧

可以 搞定了

**Comment by bianhaotian** [comment]
> 



> @bianhaotian #48 截图挺好看的，欢迎贴图到这里

好~
