### ISSUE TITLE
评级和简记能否在两个电脑上同步

### ISSUE THREAD

**Issue by ftdlee1104** [MuiseDestiny/zotero-style#1130]
**不礼貌不回复，直接关闭**

我有3台电脑，能否支持多设备间 评级和简记的同步。

同时，感谢您新添加的视图组快捷键，但点击加载特别慢，而且有点卡

**Comment by MuiseDestiny** [comment]
慢 卡是正常的 不要频繁切换

`评级和简记`本身就支持同步的
