### ISSUE TITLE
全文翻译生成的网页上传至云端后在ipad中的zotero读取呈现乱码

### ISSUE THREAD

**Issue by ydbsbrhh** [MuiseDestiny/zotero-style#1136]
全文翻译生成的网页上传至云端后在ipad中的zotero读取呈现乱码，麻烦能否在生成全文翻译的网页时加上<meta charset="UTF-8">标签，在ipad上看很重要，万分感谢！！

**Comment by ydbsbrhh** [comment]
加上UTF-8声明标签

**Comment by MuiseDestiny** [comment]
好
请尝试：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

**Comment by ydbsbrhh** [comment]
试了 很好用 谢谢
