### ISSUE TITLE
reference与style冲突，同时启用无法检索条目

### ISSUE THREAD

**Issue by hxhxg** [MuiseDestiny/zotero-style#115]
![image](https://user-images.githubusercontent.com/70049986/218283507-c399e526-f1a0-49b8-8e77-af23f8685e66.png)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style
解决了吗

**Comment by hxhxg** [comment]
> https://github.com/MuiseDestiny/zotero-style 解决了吗

没有，只能启用一个插件，同时开两个插件就无法检索条目

**Comment by MuiseDestiny** [comment]
更新一下就好了，在github上重新下最新版安装

**Comment by hxhxg** [comment]
> 更新一下就好了，在github上重新下最新版安装

我试过了两个插件都重新下载最新版进行安装，但还是有这个问题
