### ISSUE TITLE
优化一下key和values重复导致的冗长问题

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#116]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/68216639/218289528-718adc2c-297d-4bd4-8fd8-c8d50cfbeb64.png">

然后希望fields可以多一些，比如easyscholar上的北大核心之类的～如果能优化一下key和values重复导致的冗长问题就更好了。
<img width="156" alt="image" src="https://user-images.githubusercontent.com/68216639/218289560-09ef382a-39d8-40f3-a489-1651a15075cd.png">

**Comment by MuiseDestiny** [comment]
cssci小bug，马上修复

**Comment by MuiseDestiny** [comment]
重新安装即可
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.4

**Comment by 17816712353** [comment]
已解决，作者这个功能真的太牛了，都可以单开一个插件作为卖点了！

**Comment by zyx335588** [comment]
希望能添加一个控制面板，类似easyScholar那样，让大家自行选择需要的数据，有些数据也不是每个人都需要，放在extra也没意义

**Comment by MuiseDestiny** [comment]
> 希望能添加一个控制面板，类似easyScholar那样，让大家自行选择需要的数据，有些数据也不是每个人都需要，放在extra也没意义

理解你的意思，只在extra保存需要显示的数据，对于不需要显示的不保存。但是都保存，可以清晰看到这个期刊支持哪些fields，方便设置，而且如果只保存要显示的fields，需要二次请求es的api。

期刊标签，本身是有设置的，可以做到easycholar那样的面板，也可以100%还原es（但是100%还原，不如让es作者本人来做这方面的功能），时间精力有限。
