### ISSUE TITLE
请问期刊标签设置在哪里呢

### ISSUE THREAD

**Issue by DharmaBums1991** [MuiseDestiny/zotero-style#117]
就是这个界面，从哪里进入呢。https://github.com/MuiseDestiny/zotero-style/releases/tag/2.1.3

**Comment by DharmaBums1991** [comment]
此外视图组里只能增加一个视图，没有新增视图选项了

**Comment by MuiseDestiny** [comment]
1.
右键任意列，勾选期刊标签，就会显示了

2.
https://github.com/MuiseDestiny/zotero-style#%E8%A7%86%E5%9B%BE%E7%BB%84%E5%8A%9F%E8%83%BD
视图组建议阅读下readme

**Comment by DharmaBums1991** [comment]
> 右键任意列，勾选期刊标签，就会显示了
> 
> 
> https://github.com/MuiseDestiny/zotero-style#%E8%A7%86%E5%9B%BE%E7%BB%84%E5%8A%9F%E8%83%BD 视图组建议阅读下readme

1、可以显示，我意思这个设置参数怎么调出来。
![image](https://user-images.githubusercontent.com/73206153/218291006-04424779-4d3c-4b63-b867-dd5da4bb3ca7.png)
2、视图组我这里只能新增一个，增加完了之后就没有新增选项了。
![image](https://user-images.githubusercontent.com/73206153/218291051-57bbb95c-501c-4f58-89a9-31921070a5e3.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218291187-49a6b137-4894-4666-ab1f-333efeed5c8c.png)

因为当前视图已经保存过了，所有不能重复添加，改变当前视图后才会显示（readme有说明）

**Comment by DharmaBums1991** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/218291187-49a6b137-4894-4666-ab1f-333efeed5c8c.png)
> 
> 因为当前视图已经保存过了，所有不能重复添加，改变当前视图后才会显示（readme有说明）

明白了，非常感谢，刚发现是因为用副屏了，右键单击后菜单刚好去副屏了，结果就没有列设置选项，拖一下就好了。
