### ISSUE TITLE
插件导致新版zotero只能显示5种颜色

### ISSUE THREAD

**Issue by zyx335588** [MuiseDestiny/zotero-style#118]
Zotero官方在新版beta中PDF阅读器高亮等位置增加了3种颜色，将在6.0.22中实际应用。貌似style插件会导致PDF阅读器中的高亮只显示前5种颜色。

> [Zotero forum](https://forums.zotero.org/discussion/comment/427977/#Comment_427977)  
> In the latest [Zotero beta](https://www.zotero.org/support/beta_builds), we've added three additional highlight colors in the PDF reader and note editor and restored the ability to set text colors in notes. These changes will be included in Zotero 6.0.22.

具体表现为高打开PDF文件时仍为8种颜色，但是选中一次弹窗后，就只有5种颜色了。
希望能够改善。

**Comment by MuiseDestiny** [comment]
style支持无数种颜色，shift p点击标注

**Comment by zyx335588** [comment]
但是官方现在的弹窗就有8种，大多数情况是够用的，没必要增加一步shift p去切换啊

**Comment by MuiseDestiny** [comment]
> 但是官方现在的弹窗就有8种，大多数情况是够用的，没必要增加一步shift p去切换啊

可以shift p点击标注，创建官方的八种颜色。然后使用它就可以了。只需要修改这一次。

**Comment by zyx335588** [comment]
好的。但是个人感觉插件还是不要改变官方的操作为好。

**Comment by zyx335588** [comment]
我不清楚这个issue为什么现在被关闭了，应该不止我一个人会遇到这个问题。
希望作者后续更新时，能够恢复官方的8种默认颜色。而不是让用户去自己设置。

**Comment by MuiseDestiny** [comment]
好的，还有哪些地方不一样插件改的，我以后注意

**Comment by zyx335588** [comment]
点赞，作者已经很棒了！
官方额外的三种颜色代码，目前有需要的可以使用：
    ['general.magenta', '#e56eee'],
    ['general.orange', '#f19837'],
    ['general.gray', '#aaaaaa']

**Comment by MuiseDestiny** [comment]
[
	['general.yellow', '#ffd400'],
	['general.red', '#ff6666'],
	['general.green', '#5fb236'],
	['general.blue', '#2ea8e5'],
	['general.purple', '#a28ae5'],
	['general.magenta', '#e56eee'],
	['general.orange', '#f19837'],
	['general.gray', '#aaaaaa']
];

<https://github.com/zotero/pdf-reader/blob/f720ff8348cfe2b0b548fe9683e02523ef2f378b/src/lib/colors.js>

**Comment by MuiseDestiny** [comment]
为啥这么喜欢官方的颜色啊，我觉得很普通。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218300525-aad23043-e396-4169-8e4a-e31308ee0bb2.png)

这么设置可以恢复官方颜色。

但我觉得五个颜色刚刚好。对于Zotero这样的升级，由于一些代码逻辑，插件不太好恢复8个颜色。但可以设置当点击+创建颜色组时候创建的是官方默认的八个颜色。
