### ISSUE TITLE
标签无法显示

### ISSUE THREAD

**Issue by syuuraku** [MuiseDestiny/zotero-style#1180]
Style: 5.2.0

昨天还能显示标签，今天突然无法显示。在右侧列表可以看到标签，但在中间标签列看不到。
![image](https://github.com/user-attachments/assets/fa860edb-e254-4448-b874-1cf2e779554c)

**Comment by MuiseDestiny** [comment]
![image](https://github.com/user-attachments/assets/951b036f-78fb-4e00-a585-318c76c31995)


`/`开头的是状态标签，你可以开启状态栏查看
