### ISSUE TITLE
不要自动填充extra

### ISSUE THREAD

**Issue by byhwsh** [MuiseDestiny/zotero-style#119]
因为我extra想安排其他的字符，所以请问是否可以设置，不要让分区自动填充extra？

**Comment by MuiseDestiny** [comment]
> 因为我extra想安排其他的字符，所以请问是否可以设置，不要让分区自动填充extra？

#标签可以吗（安排其他字符）？或者有其它储存建议吗。我觉得这个期刊标签也不用同步，放在哪里都可以的。

**Comment by MuiseDestiny** [comment]
我个人也觉得放在extra有点碍眼了

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/218309645-b2e12158-9400-4ce4-bed5-77d673d42f7d.png)

@byhwsh大概是希望设置用户 自定义   字段，用于存储用户自己的数据。参考translator插件的“标题翻译、摘要翻译”字段功能
![image](https://user-images.githubusercontent.com/104330036/218310100-3aaeeba4-f6a6-46a2-bbd0-80e9ddf8cb86.png)

我自己也跟@byhwsh一样，习惯把“系列标题”字段用于存储对文章的简要概括，把“系列”字段用于给文章编号。
![image](https://user-images.githubusercontent.com/104330036/218309968-653b092d-06a1-4990-936f-6894dc949208.png)

**Comment by MuiseDestiny** [comment]
@1067237855 我理解的是
![image](https://user-images.githubusercontent.com/51939531/218310476-278d0ee2-f31e-4e53-ab33-d8dfead4b486.png)
这里放的东西有点乱，ta想在`其它`里做一些标记

**Comment by 1067237855** [comment]
> @1067237855 我理解的是 ![image](https://user-images.githubusercontent.com/51939531/218310476-278d0ee2-f31e-4e53-ab33-d8dfead4b486.png) 这里放的东西有点乱，ta想在`其它`里做一些“标记”

是的，是这个意思没错。我以前也是在“其它”里面放东西（用户  标记）。
//
//
//

所以我的一个想法是给用户提供一个专门放用户“标记”的位置。（PS：endnote就有类似的功能）
具体想法如下，仅供参考：

> ![image](https://user-images.githubusercontent.com/104330036/218309645-b2e12158-9400-4ce4-bed5-77d673d42f7d.png)
> 
> @byhwsh大概是希望设置用户 自定义 字段，用于存储用户自己的数据。参考translator插件的“标题翻译、摘要翻译”字段功能 ![image](https://user-images.githubusercontent.com/104330036/218310100-3aaeeba4-f6a6-46a2-bbd0-80e9ddf8cb86.png)
> 
> 我自己也跟@byhwsh一样，习惯把“系列标题”字段用于存储对文章的简要概括，把“系列”字段用于给文章编号。 ![image](https://user-images.githubusercontent.com/104330036/218309968-653b092d-06a1-4990-936f-6894dc949208.png)

**Comment by MuiseDestiny** [comment]
#标签 不好用吗，还可以分类显示的

**Comment by 1067237855** [comment]
> #标签 不好用吗，还可以分类显示的

好用，非常好用，点赞👍👍👍👍👍。之所以会有上面的讨论，主要是考虑到以下几个方面：
1.有的用户长期将其它作为“标记”列所以没法舍弃“其它”，迁移成本太高
2.有的是因为用户习惯不同导致，比如不希望污染“标签”，或者不希望有大量标签产生
3.有的用户不了解#标签的用法，所以还在用传统的办法，而没有用#标签

**Comment by MuiseDestiny** [comment]
> 

好的，我再定义一列吧，名字有建议吗

**Comment by 1067237855** [comment]
> 好的，我再定义一列吧，名字有建议吗
short notes？short texts？自定义？用户笔记？

列名称可以自定义吗？🤭我要求是不是有点过分了😄

**Comment by 1067237855** [comment]
用户的好多想法没必要都一定实现，比如我自己提的只是一些想法，好多华而不实。望大佬仔细考察后再决定弄不弄

**Comment by MuiseDestiny** [comment]
> > 好的，我再定义一列吧，名字有建议吗
> > short notes？short texts？自定义？用户笔记？
> 
> 列名称可以自定义吗？🤭我要求是不是有点过分了😄

可以的，之前想过做这个，可以开放。但是最终还是要存在`其它`里，里面数据不能太长
