### ISSUE TITLE
style2.1.5 Map乱码

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-style#120]
![image](https://user-images.githubusercontent.com/104330036/218308961-450f3aa6-b8a7-48f7-a5b5-c2a046592ba4.png)

**Comment by MuiseDestiny** [comment]
> ![image](https://user-images.githubusercontent.com/104330036/218308961-450f3aa6-b8a7-48f7-a5b5-c2a046592ba4.png)

删除重新设置下，我第一次打开也乱码，不知道为啥

**Comment by 1067237855** [comment]
> > ![image](https://user-images.githubusercontent.com/104330036/218308961-450f3aa6-b8a7-48f7-a5b5-c2a046592ba4.png)
> 
> 删除重新设置下，我第一次打开也乱码，不知道为啥

![image](https://user-images.githubusercontent.com/104330036/218310584-2f67ca69-75d3-48aa-ac6c-a8817bb71749.png)
SCI分区的设置，多少还有些问题。需要优化一下

**Comment by MuiseDestiny** [comment]
区分大小写的，严格匹配

**Comment by MuiseDestiny** [comment]
建议设置SCI=,空着就会直接显示Q1了，不然这样设置显示的是Q Q1

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218310804-b6739b63-fc0d-4c2b-af92-2e741ae22b46.png)

**Comment by 17816712353** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/218310804-b6739b63-fc0d-4c2b-af92-2e741ae22b46.png)

如果空着，期刊标签没有变化。。
<img width="481" alt="image" src="https://user-images.githubusercontent.com/68216639/218353604-61eb8b4c-1708-42c0-b457-76c3cacd8929.png">

**Comment by 1067237855** [comment]
> 如果空着，期刊标签没有变化。


等大佬修复吧，可以暂时这样设置
![image](https://user-images.githubusercontent.com/104330036/218354444-1fbc339f-94eb-4c71-966c-b300e11bdd5d.png)

**Comment by MuiseDestiny** [comment]
已经修复了，更新一下就好了

**Comment by MuiseDestiny** [comment]
@17816712353 
![image](https://user-images.githubusercontent.com/51939531/218354857-64346f1e-d7a0-4982-80e4-b74f99cbb237.png)

window上是上下居中对齐的，但是看你截图好像是顶端对齐了

![image](https://user-images.githubusercontent.com/51939531/218354903-fb9c2b9b-9820-4b7e-9c22-7a0bf184e096.png)

**Comment by 17816712353** [comment]
> @17816712353 ![image](https://user-images.githubusercontent.com/51939531/218354857-64346f1e-d7a0-4982-80e4-b74f99cbb237.png)
> 
> window上是上下居中对齐的，但是看你截图好像是顶端对齐了
> 
> ![image](https://user-images.githubusercontent.com/51939531/218354903-fb9c2b9b-9820-4b7e-9c22-7a0bf184e096.png)

还真的是唉，我自己都没发现。大佬细节👍

**Comment by MuiseDestiny** [comment]
但是没有mac没法优化了。

**Comment by MuiseDestiny** [comment]
@17816712353 是不是#标签也是顶端对齐

**Comment by 17816712353** [comment]
> @17816712353 是不是#标签也是顶端对齐

是的
<img width="956" alt="image" src="https://user-images.githubusercontent.com/68216639/218355873-d3628056-fdff-4000-b853-9a1fabc7af3c.png">

**Comment by MuiseDestiny** [comment]
> > @17816712353 是不是#标签也是顶端对齐
> 
> 是的 <img alt="image" width="956" src="https://user-images.githubusercontent.com/68216639/218355873-d3628056-fdff-4000-b853-9a1fabc7af3c.png">

我试试修复下

**Comment by MuiseDestiny** [comment]
截图看看效果哈，放zotero安装目录下吧，能正常显示吗

**Comment by 17816712353** [comment]
> 截图看看效果哈，放zotero安装目录下吧，能正常显示吗

<img width="950" alt="image" src="https://user-images.githubusercontent.com/68216639/218362693-5abf55d1-b70e-485d-bb82-4bbe5fc19d93.png">
看不到期刊标签信息，fields不好对照着填😂。

**Comment by MuiseDestiny** [comment]
> > 截图看看效果哈，放zotero安装目录下吧，能正常显示吗
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/68216639/218362693-5abf55d1-b70e-485d-bb82-4bbe5fc19d93.png">
> 
> 看不到期刊标签信息，fields不好对照着填😂。

我会把所有支持字段放在readme

**Comment by 17816712353** [comment]
> > > 截图看看效果哈，放zotero安装目录下吧，能正常显示吗
> > 
> > 
> > <img alt="image" width="950" src="https://user-images.githubusercontent.com/68216639/218362693-5abf55d1-b70e-485d-bb82-4bbe5fc19d93.png">
> > 看不到期刊标签信息，fields不好对照着填😂。
> 
> 我会把所有支持字段放在readme

👍👍，爱了爱了

**Comment by MuiseDestiny** [comment]
reference也放本地了，阅读进度需要同步不能放本地的
