### ISSUE TITLE
独立窗口时自定义颜色不起作用

### ISSUE THREAD

**Issue by 91ankt0n** [MuiseDestiny/zotero-style#1202]
**不礼貌不回复，直接关闭**
开发者你好，感谢制作zotero style。因为本人有大量比较阅读需求所以经常使用独立窗口阅读多个pdf文件。当pdf以独立窗口打开时，配置的自定义颜色和pdf滤色将无法应用到独立窗口上。请问目前有设置可以绕过这个问题吗？如果暂时没有的话希望作者可以考虑增加这个feature。谢
![7681732774492_ pic](https://github.com/user-attachments/assets/e425e43f-4c14-41ce-89f8-b6e8363e7919)
谢。
![7691732774507_ pic](https://github.com/user-attachments/assets/56e65ca1-cb2f-47c9-b46c-c578c3aacb62)

**Comment by MuiseDestiny** [comment]
不考虑适配独立窗口，建议使用zo内标签页打开
