### ISSUE TITLE
离线账户的不更新期刊标签

### ISSUE THREAD

**Issue by appwcn** [MuiseDestiny/zotero-style#1203]
你好！
我的zotero软件，安装zotero style后，无法同步期刊标签（点更新-期刊标签），电脑没反应。

我猜想，是不是因为没有登陆zotero账号？我的zotero库有5000多条目，非常卡。因此，我参照 https://www.zotero.org/support/kb/multiple_profiles 的方法，建立了多个小库。每个小库都是离线使用，不登陆zotero账号，数据保存在本地。我会在每个子库上重新安装zotero style，并正常配置greenfrog api等信息。可是，这些子库无法使用zotero style更新期刊标签。
zotero 7.0.10
ethereal style 5.3.1

**Comment by MuiseDestiny** [comment]
期刊标签的列设置 需要写密钥

`并正常配置greenfrog api等信息`这是另一个插件 和 期刊标签显示无关
