### ISSUE TITLE
[Feature request] Favorites for saved search

### ISSUE THREAD

**Issue by dschaehi** [MuiseDestiny/zotero-style#1208]
The favorites feature is really nice, but supports "real" collections only.
It would be nice if one add saved searches to the favorites.

**Comment by MuiseDestiny** [comment]
Ok

**Comment by MuiseDestiny** [comment]
<img width="257" alt="image" src="https://github.com/user-attachments/assets/26fcad59-4c07-4a14-95f2-1f31f5926201" />

Update to 5.3.5

by

![image](https://github.com/user-attachments/assets/b6d89247-f3b4-402d-8dfe-e15e1f386064)

or

[zotero-style.xpi](https://github.com/MuiseDestiny/zotero-style/releases/download/5.3.5/zotero-style.xpi)

**Comment by dschaehi** [comment]
Thank you!
