### ISSUE TITLE
影响因子column的柱状图

### ISSUE THREAD

**Issue by cjlCMU** [MuiseDestiny/zotero-style#121]
![image](https://user-images.githubusercontent.com/102497540/218367568-f7ef1b28-0093-46a5-8dbe-522cbd5f1445.png)
影响因子column的柱状图可以增加一个不显示的选项吗?只显示info,谢谢MuiseDestiny老师

**Comment by MuiseDestiny** [comment]
添加了设置
![image](https://user-images.githubusercontent.com/51939531/218369348-9bef7a79-2ee3-41d2-befb-400622d3b293.png)

![image](https://user-images.githubusercontent.com/51939531/218369400-a1717315-4932-4055-b040-93033851f547.png)

但是期刊标签可以只显示数字啊

**Comment by cjlCMU** [comment]
> 

哈哈,谢谢老师,这样可以多一种选择,让这个插件更加完美,感谢老师的无私奉献

**Comment by MuiseDestiny** [comment]
重新下载安装最新版本获取这个功能
