### ISSUE TITLE
CCF会议标签

### ISSUE THREAD

**Issue by 16131zzzzzzzz** [MuiseDestiny/zotero-style#122]
现在好像CCF只有期刊的标签，希望有会议的标签，会议名单可以参照https://www.ccf.org.cn/Academic_Evaluation/By_category/，如果有时间加上不胜感激

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/108#issuecomment-1425922710

试试es支持的自定义数据集满足需求不，这个需要登陆，如果效果好可以后面添加登录以获取这个数据集

**Comment by wang-jh18-SVM** [comment]
同求，希望能添加功能，在zotero里显示会议的CCF标签，不胜感谢！试了前面朋友推荐的es，确实也挺好用

**Comment by Murphy-404** [comment]
easyScholar上面的期刊等级查询是支持显示会议信息的，我猜测问题可能是zotero获取的数据无法很好地和easyscholar匹配，目前手动试了二十多篇，都没有能不修改内容就成功的，比如说很多会议信息最后有括号包含的会议名缩写，一旦带有这种信息那easyscholar就识别不出来了。
easyscholar本身也说会议标签无法很好地识别……参见下图（计算机方向的文献看的很不爽......）
![image](https://user-images.githubusercontent.com/45585739/223610159-3a1c9dbb-5585-446f-ad01-c8ac05aacffc.png)

**Comment by FairyMeng** [comment]
+1+1真的太需要这个功能了

**Comment by MuiseDestiny** [comment]
已支持

**Comment by FairyMeng** [comment]
只有曾经有期刊标签的那部分才能获得ccf标签么？我更新了最新的版本，请问我还需要什么额外设置么
<img width="606" alt="image" src="https://user-images.githubusercontent.com/67990749/224643935-c04715f2-c116-4924-a6b7-906dd4ea663d.png">

**Comment by MuiseDestiny** [comment]
> 只有曾经有期刊标签的那部分才能获得ccf标签么？我更新了最新的版本，请问我还需要什么额外设置么 <img alt="image" width="606" src="https://user-images.githubusercontent.com/67990749/224643935-c04715f2-c116-4924-a6b7-906dd4ea663d.png">

过一段时间支持。es会开放密钥

**Comment by Matt-V50** [comment]
## 请问会议长标题应以哪一个为主

CVPR和ICCV的期刊读取标准不同

复现步骤：
1. 在es中增加自定义数据集
  Computer Vision And Pattern Recognition
  International conference on computer vision
2. 新增条目
  - 会议论文集标题：International conference on computer vision
      会议名称：ICCV
      得到预期结果
  - 会议论文集标题：ICCV
      会议名称：International conference on computer vision
       **未得到预期结果**
  - 会议论文集标题：CVPR
      会议名称：Computer Vision and Pattern Recognition
      得到预期结果
  - 会议论文集标题：Computer Vision and Pattern Recognition
      会议名称：CVPR
      **未得到预期结果**
