### ISSUE TITLE
Error: 'openColorPopup'

### ISSUE THREAD

**Issue by gaochuanchao** [MuiseDestiny/zotero-style#123]
版本:2.1.6
用zotero自带的pdf阅读器尝试切换颜色时, 会弹出下方的错误提示.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/22146315/218613058-ce5fe43c-2830-4171-ab54-8fa45def5b2f.png">

刚开始打开文件时没问题, 但是在我用完自定义的颜色(用鼠标划词标颜色)后再点这个系统自带的颜色切换就会出现这个错误提醒

**Comment by MuiseDestiny** [comment]
奇怪，每个pdf都会出现这种错误吗

**Comment by gaochuanchao** [comment]
> 拿了几个没读过的pdf试了试,都会出现类似的情况. 感觉可能是颜色组调用的问题, 系统默认调用它默认提供的颜色组. 不知道是不是这里有啥冲突. 不过这个错误并不影响使用, 毕竟通过划词也可以标颜色.

**Comment by atmomomo** [comment]
Same here.

**Comment by MuiseDestiny** [comment]
知道了，你的zotero可能不是最新的beta版，这几个颜色是beta版加入的。

![image](https://user-images.githubusercontent.com/51939531/218647468-490d6c8d-d2fc-41d5-a359-0b32b4aeb20d.png)

**Comment by atmomomo** [comment]
It worked like a charm in the beta version, thanks!
