### ISSUE TITLE
[Error]无法打开AnnotationPopup

### ISSUE THREAD

**Issue by yodaliu0414** [MuiseDestiny/zotero-style#128]
![image](https://user-images.githubusercontent.com/50686783/218949250-b759e778-b140-4729-b88f-ca32ab455691.png)

在文内添加批注，选择任一颜色后，再次点击tag标签的右上角三个点或正文上方的颜色按钮后出现问题。（颜色按钮出现问题名称：openColorPopup）。如果打开Zotero以后不添加批注，直接修改批注，则不出现报错。

因为图中的报错内容无法复制，所以只能提供截图，抱歉。其它可复制的bug report 见下。

[JavaScript Error: "Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Error: Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Error: Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Error: Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Error: Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "Error: Localized string not available for general.magenta" {file: "chrome://zotero/content/xpcom/intl.js" line: 133}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Error connecting to server. Check your Internet connection."]

[JavaScript Error: "Error connecting to server. Check your Internet connection."]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

version => 6.0.20, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.20, extensions => DOI Manager (1.4.2, extension), Mdnotes for Zotero (0.2.3, extension), ZotFile (5.1.2, extension), Zotero Update Journal Information (0.3.6, extension), Jasminum (0.2.4, extension), Zotero PDF Translate (0.9.8, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.20, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.20, extension), Zotero Reference (0.2.6, extension), Zotero Style (2.1.7, extension), Zutilo Utility for Zotero (3.10.0, extension, disabled), Zotero Tag (0.3.0, extension, disabled), Chartero (1.3.2, extension, disabled)

**Comment by yodaliu0414** [comment]
另，根据Error报错尝试打开和关闭梯子，将梯子调整为全局模式，均无效果

**Comment by MuiseDestiny** [comment]
升级下zotero beta版本

**Comment by yodaliu0414** [comment]
> 

已解决，谢谢！

**Comment by EllenShi** [comment]
你好！请问你如何解决的呢？我昨天也出现了这个问题，重启zotero，重启电脑，更新到最新版，各种方法试过很多次，现在还是没有解决。

**Comment by yodaliu0414** [comment]
> 你好！请问你如何解决的呢？我昨天也出现了这个问题，重启zotero，重启电脑，更新到最新版，各种方法试过很多次，现在还是没有解决。

在zotero documentation里找到beta version，安装beta版

**Comment by EllenShi** [comment]
原来这样。我用的是zotero 稳定版，没用beta 版本。算了，我还是使用style 的早期版本吧。。谢谢你！

> > 你好！请问你如何解决的呢？我昨天也出现了这个问题，重启zotero，重启电脑，更新到最新版，各种方法试过很多次，现在还是没有解决。
> 
> 在zotero documentation里找到beta version，安装beta版
