### ISSUE TITLE
你好，今天打开之后出现关系图谱且之前的阅读进度条全部都不见了，怎么解决

### ISSUE THREAD

**Issue by sprouting-pixel** [MuiseDestiny/zotero-style#129]
阅读进度条怎么保存

**Comment by MuiseDestiny** [comment]
安装了冲突插件了呀

**Comment by sprouting-pixel** [comment]
我的插件页面有时候可以打开有时候打不开，现在就打不开了:(

**Comment by sprouting-pixel** [comment]
![image](https://user-images.githubusercontent.com/79639932/218956031-1c82fcec-fbea-4717-ad94-ce35856090d6.png)

**Comment by sprouting-pixel** [comment]
这里有插件冲突了吗？好久没有添加过插件了，今天打开就没有阅读进度了:(

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/126

和这个类似

**Comment by sprouting-pixel** [comment]
现在可以正常使用了，如果之后还出现类似问题再来更新，谢谢大佬
