### ISSUE TITLE
和 Del item 插件冲突，同时打开后，无法显示条目。

### ISSUE THREAD

**Issue by free521521521** [MuiseDestiny/zotero-style#130]
和 Del item 插件冲突，同时打开后，无法显示条目。
https://github.com/redleafnew/delitemwithatt
关闭其中一个，另一个才能正常工作。

**Comment by ngh2014** [comment]
我和你遇到的问题一样，我的不是二者冲突，而是只要enable zotero-style插件后如果关闭软件再打开就不显示条目，disable之后重启软件就可以显示。

**Comment by free521521521** [comment]
> 我和你遇到的问题一样，我的不是二者冲突，而是只要enable zotero-style插件后如果关闭软件再打开就不显示条目，disable之后重启软件就可以显示。

问题一样，您描述得更加清晰。👍🏻

**Comment by MuiseDestiny** [comment]
很快会修复。

**Comment by MuiseDestiny** [comment]
最新版，已解决
