### ISSUE TITLE
存储的数据会导致引用文献混乱

### ISSUE THREAD

**Issue by YYXC1993** [MuiseDestiny/zotero-style#135]
前两天写论文输出引用文献时，发现引用文献输出多了一堆乱七八糟的信息，今天研究插件时发现是这个插件导致的。

**Comment by MuiseDestiny** [comment]
是使用了其他字段导致的，用del插件把其他字段清除就可以了

**Comment by MuiseDestiny** [comment]
现在最新版不用其他字段了

**Comment by YYXC1993** [comment]
好的，谢谢

**Comment by YYXC1993** [comment]
这些信息好像是Addon item里面的。这些不是单独列出来的吗？

**Comment by YYXC1993** [comment]
还有，请问那些fields怎么设置的，我没找到快捷键，看了你的readme，没看到如何进入那个界面

**Comment by MuiseDestiny** [comment]
> 还有，请问那些fields怎么设置的，我没找到快捷键，看了你的readme，没看到如何进入那个界面

右键期刊标签，列设置

**Comment by MuiseDestiny** [comment]
在期刊标签上右键，对应是设置期刊标签；
你截图是在标题上右键，对应是设置标题。

**Comment by YYXC1993** [comment]
好奇怪，可以了。在给您回复时，我还特意试了好几次在期刊标签上右键，结果没出来任何东西，可能是我这电脑上zotero总出问题，包括自带的引用也总是容易出问题。重启了zotero，右键出现了新的列设置。感谢作者！
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月22日(星期三) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MuiseDestiny/zotero-style] 存储的数据会导致引用文献混乱 (Issue #135)





 
在期刊标签上右键，对应是设置期刊标签；
 你截图是在标题上右键，对应是设置标题。
