### ISSUE TITLE
Mac端 字体似乎有些问题？

### ISSUE THREAD

**Issue by franco-ye** [MuiseDestiny/zotero-style#136]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/110618725/219247528-43ba4786-3072-43c2-9b80-0afecf452538.png">
可能是内置的中文字段的字体不匹配？体现在期刊标签列，另外想请问下大佬期刊标签的信息是实时刷新的吗？很棒的插件

**Comment by 1067237855** [comment]
参考https://github.com/MuiseDestiny/zotero-style/issues/120

> <img alt="image" width="506" src="https://user-images.githubusercontent.com/110618725/219247528-43ba4786-3072-43c2-9b80-0afecf452538.png">
> 
> 可能是内置的中文字段的字体不匹配？体现在期刊标签列，另外想请问下大佬期刊标签的信息是实时刷新的吗？很棒的插件

**Comment by MuiseDestiny** [comment]
刷新是自动完成的，用户无需关心它的
