### ISSUE TITLE
旧版Zotero-style插件设置如何清除

### ISSUE THREAD

**Issue by 11good11** [MuiseDestiny/zotero-style#138]
以前安装旧版style插件设置的标签标注显示再标题前面，请问这该如何清除。

**Comment by MuiseDestiny** [comment]
不用清除，重新设置就可以

**Comment by 11good11** [comment]
找不到设置选项呀，shift+p里面没有相关设置

**Comment by MuiseDestiny** [comment]
看下readme

**Comment by 11good11** [comment]
你好，问题依然存在，标签与标题同时显示在标题里面，还是没法清楚，在首选项中编辑器的zotero.zoterostyle.tag中设置了改变了数值，依旧没有任何改变，需要卸载最新的插件装旧版的然后再设置回来，再装新版就好吗？😂

**Comment by MuiseDestiny** [comment]
> 你好，问题依然存在，标签与标题同时显示在标题里面，还是没法清楚，在首选项中编辑器的zotero.zoterostyle.tag中设置了改变了数值，依旧没有任何改变，需要卸载最新的插件装旧版的然后再设置回来，再装新版就好吗？😂

https://www.bilibili.com/video/BV1cT411X7zS?t=650.9

**Comment by 11good11** [comment]
感谢感谢，终于搞清楚了，
