### ISSUE TITLE
mac用户 shift+p无法调用/reference

### ISSUE THREAD

**Issue by wingwingyang** [MuiseDestiny/zotero-style#140]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/47018319/219377466-9cc2c9d7-f5b1-4e51-ac25-a25f5e305482.png">
shift+p调出的是这个界面，无法输入/reference，也无法使用任何命令，下载的是目前的最新版本，想请教一下怎么才能使用这个功能？

**Comment by MuiseDestiny** [comment]
看参考文献嘛，推荐你使用https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.4

**Comment by wingwingyang** [comment]
> 

原来是开新作了呀，支持一波！
