### ISSUE TITLE
编码

### ISSUE THREAD

**Issue by ForSmile0** [MuiseDestiny/zotero-style#145]
![图片](https://user-images.githubusercontent.com/105116435/219643224-3ea42a96-6c7a-467f-bb0f-58dad7ebf643.png)
编码有点问题

**Comment by MuiseDestiny** [comment]
手动输入一下吧，不影响使用，手动输入一次就好了
```
★ •
```

**Comment by ForSmile0** [comment]
> 手动输入一下吧，不影响使用，手动输入一次就好了
> 
> ```
> ★ •
> ```

确实不影响使用，Thank You ！！
