### ISSUE TITLE
Generators of this plugin verbal abuse  customer and it functions do not perform on Mac  此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户

### ISSUE THREAD

**Issue by ghost** [MuiseDestiny/zotero-style#149]
该插件不适用于mac，shift p调动不出应有选项，进度条随缘出现，随时消失。
耐着性子重新安装启动多次无果。给作者留言请教，从头到尾很礼貌，对面回答不看问题直接拽得二五八万，继续礼貌询问，多说了一句也是可以为了可以优化插件，希望回复时候稍微看点问题走点心，人直接开怼，还把我的讨论删了。
大家看看他论坛这么久除了他自己一条帖子，其他都呆不长，懂的都懂。
有本事的解决问题，没本事的发泄情绪？
请大家一起抵制这种使用体验差、作者态度差，只会在小红书和B站营销的的垃圾插件。

**Comment by MuiseDestiny** [comment]
![Screenshot_2023-02-18-22-51-16-31](https://user-images.githubusercontent.com/51939531/219903697-b921fc60-ac2d-461f-806d-2edde1db2400.jpg)

**Comment by MuiseDestiny** [comment]
> 大家看看他论坛这么久除了他自己一条帖子
你说的是讨论吧，现在有第二条了，一般大家发在issue

> 只会在小红书和B站营销
这是一个免费开源插件，我也没有营销

> 请大家一起抵制这种使用体验差、作者态度差
可以看看这么多issue，我哪一个是像你说的态度差，至于使用体验差，我不知道你为什么还要使用

> 还把我的讨论删了。
看上一个图，你的最后一个回复，说要删楼，我就直接帮你删除讨论了

**Comment by volatile-static** [comment]
@chesnut1 哥们你连readme都没看明白就上来问，人家说你两句咋还就破大防了呢？
咱都是搞科研的，你用人家插件不会自己研究研究吗？b站小红书那么多介绍视频你就看看呗，难道你看人家文献看不懂就直接发邮件质问作者吗？
我们做插件的也都是研究生啊，哪个不是天天顶着导师push抽时间来维护插件给大家用？你有M1芯片你了不起，我们上哪搞那么多设备去适配啊？
说实话我们做开源的还**不就图个开心么**，又不指望他赚钱，你们爱用不用啊，又不是我们求着你用，用的人多对我们有半毛钱好处吗？你这么抵制一个开源软件，除了恶心人以外，对我们也没半毛钱影响的。

**Comment by MuiseDestiny** [comment]
你不清楚这个垃圾插件的成长过程，就批判它，我不怪你，但你这种别人理应为你服务的态度我很批判。

在这里讲一下插件发展过程。

就是一个很简单的，随便写写的插件，我在这个插件里真的只是随便写写，想写什么功能写什么。

一开始他只有两个功能，显示标题进度条和只显示标题。进度条灵感来自B站高能进度条。我觉得这种显示效果挺有意思，就发了B站。得到了一些人的喜欢。后来有开发者为Zotero带来了工具箱，它可以轻易实现为Zotero增加一个列，我就重新写了style，版本号在2.0.0以后。期间，视图组切换快捷键，高能进度条UI优化，期刊标签的优化，影响因子的数字显示，进度列的显示风格数据存储方式等等等等，都是用户提出的优化建议，正是他们在推动着插件的更新迭代。我有一期视频说我与他们完成了双向奔赴。这个过程对我很治愈，因为某些事情，我确实把一部分时间寄托于写代码来遗忘时间。

**Comment by 1067237855** [comment]
> @chesnut1 哥们你连readme都没看明白就上来问，人家说你两句咋还就破大防了呢？ 咱都是搞科研的，你用人家插件不会自己研究研究吗？b站小红书那么多介绍视频你就看看呗，难道你看人家文献看不懂就直接发邮件质问作者吗？ 我们做插件的也都是研究生啊，哪个不是天天顶着导师push抽时间来维护插件给大家用？你有M1芯片你了不起，我们上哪搞那么多设备去适配啊？ 说实话我们做开源的还**不就图个开心么**，又不指望他赚钱，你们爱用不用啊，又不是我们求着你用，用的人多对我们有半毛钱好处吗？你这么抵制一个开源软件，除了恶心人以外，对我们也没半毛钱影响的。

👍👍👍👍👍赞同！！！！
不管怎么讲，开源软件都被人怼，还被人抵制，伤心啊！！！！

**Comment by chesnut1** [comment]
大半夜看到这条，我不睡觉也高低跟你整两句，真绝了，找了两水军在这骂我+去issue里刷好评，什么东西！我还没开始抵制呢有的人破大防满嘴喷粪！是不是垃圾实践检真知，至少在我电脑上，它就是个垃圾，我凭什么不能发？我发是我的自由，你们人多嘴贱就是我不能发的理由？我昨天重新测试一遍，在mac电脑上，完全用不了任何功能，除非每一次新打开后重新安装。

我骂不过你们，我留个言还不行了？不爽联系github删issue啊？你这软件抄的谁你清楚，你refer人家软件了吗？我写邮件问问github答不答应

少把微博那套见不得人的控评搬来github，这里发言自由，你让我用不惯别用，那你看不惯你别看啊！回你吗呢？骂你吗呢？小红书B站谁营销狗知道！笑死了，断章取义还得是你，怎么不发我前面好好问你的，你拽的二五八万似的？一句小心翼翼让你走点心回复直接破大房，怎么了？这辈子接受不了异议？
![IMG_7348](https://user-images.githubusercontent.com/125680060/219909935-13efdde4-7d1f-413b-823d-b45c7f1c805c.jpg)


> @chesnut1 哥们你连readme都没看明白就上来问，人家说你两句咋还就破大防了呢？ 咱都是搞科研的，你用人家插件不会自己研究研究吗？b站小红书那么多介绍视频你就看看呗，难道你看人家文献看不懂就直接发邮件质问作者吗？ 我们做插件的也都是研究生啊，哪个不是天天顶着导师push抽时间来维护插件给大家用？你有M1芯片你了不起，我们上哪搞那么多设备去适配啊？ 说实话我们做开源的还**不就图个开心么**，又不指望他赚钱，你们爱用不用啊，又不是我们求着你用，用的人多对我们有半毛钱好处吗？你这么抵制一个开源软件，除了恶心人以外，对我们也没半毛钱影响的。

你不在乎你在这狗叫什么呢？那么多**嘴很脏吧？研究生满嘴喷粪？少给我带节奏，从没觉得m1了不起，我说明是什么系统用不了是对我的评论负责，没说全部系统。昨天我删了小红书，几乎mac用户用你们插件都有各种问题，是我瞎说？还是你们东西垃圾，自己想想。睁开你的狗眼，看看世界吧，别活在自己梦里。我21年电脑，你跟我说你们适配不了，你冲我吼什么？你是研究生我也是，我花半天时间在你们的垃圾插件上，和作者沟通还被恶心到我不能说？就你会骂人？没教养的东西，收收你国内的戾气，这不是你自己的小红书。还是那句话，不能心态开放，不能接受批评，你上线干什么？你营销干什么？你一点好处没有你不愿回复，你删了呀，你别做呀，怎么一头占着好一头还在这放狗屁呢？相信我，你恶心我比我恶心你更甚。你们这种操作，也着实令人恶心。一口一个无所谓，一口一个没好处，你营销干嘛你心里清楚。想拉资本也得看看你做的什么东西，用户反馈如何，被抄的软件答不答应，issue绝不删。最后想告诉你：真特们狗！

**Comment by volatile-static** [comment]
我成水军了
乐

**Comment by MuiseDestiny** [comment]
> 我成水军了 乐

哈哈哈哈哈

**Comment by chesnut1** [comment]
我也是第一次抵制，你们哪个学校哪个导师，牛逼你留下，我来问问你导知不知道你嘴这么臭

> 我成水军了 乐

**Comment by MuiseDestiny** [comment]
> 我也是第一次抵制，你们哪个学校哪个导师，牛逼你留下，我来问问你导知不知道你嘴这么臭
> 
> > 我成水军了 乐

抵制有效，鼓励抵制

**Comment by chesnut1** [comment]
放心，会认真对待的，就冲你们东西做得垃圾，一句异议听不得还要一个阴阳怪一个满嘴大粪，没德行，没教养的玩意儿

**Comment by MuiseDestiny** [comment]
![IMG_20230219_114828](https://user-images.githubusercontent.com/51939531/219917100-0d8a873e-77d2-4a7d-9fa9-10095a62c66e.jpg)


尽力帮你宣传了，希望你抵制愉快

**Comment by windingwind** [comment]
乐，插眼后排看猴

**Comment by chesnut1** [comment]
> ![IMG_20230219_114828](https://user-images.githubusercontent.com/51939531/219917100-0d8a873e-77d2-4a7d-9fa9-10095a62c66e.jpg)
> 
> 尽力帮你宣传了，希望你抵制愉快

哇哦，好大的官威啊，我好害怕啊，继续找水军来骂？2023了一个插件还要翻墙出来搞起专制独裁了呢，每一句都透露着无限优越感。你挂我，你挂，我问问github同不同意你恶意攻击用户, endnote同不同意你抄袭。

**Comment by chesnut1** [comment]
> 乐，插眼后排看猴

记得一遍喷粪一边照镜看自己

**Comment by 1067237855** [comment]
我成水军了
乐

**Comment by MuiseDestiny** [comment]
> > ![IMG_20230219_114828](https://user-images.githubusercontent.com/51939531/219917100-0d8a873e-77d2-4a7d-9fa9-10095a62c66e.jpg)
> > 尽力帮你宣传了，希望你抵制愉快
> 
> 哇哦，好大的官威啊，我好害怕啊，继续找水军来骂？2023了一个插件还要翻墙出来搞起专制独裁了呢，每一句都透露着无限优越感。你挂我，你挂，我问问github同不同意你恶意攻击用户, endnote同不同意你抄袭。

你不是用户，谢谢

**Comment by windingwind** [comment]
> > 乐，插眼后排看猴
> 
> 记得一遍喷粪一边照镜看自己

1. 这么急着对号入座啊？我说你是猴了吗？什么石砸狗叫🤣
2. 我喷粪了吗？🤣
没有发言逻辑建议先重修小学语文捏
乐

**Comment by chesnut1** [comment]
“本插件正在遭受一位用户抵制”，狗写的？github你开的？凭什么由你定义谁是用户？我就单枪匹马一个普通用户，如果挂我能让其他用户发现、用到更好的插件，我觉得值得。2023还搞挂人呢，继续，你们小团体人多，喷粪心齐，也是好事。

**Comment by chesnut1** [comment]
> > > 乐，插眼后排看猴
> > 
> > 
> > 记得一遍喷粪一边照镜看自己
> 
> 1. 这么急着对号入座啊？我说你是猴了吗？什么石砸狗叫🤣
> 2. 我喷粪了吗？🤣
>    没有发言逻辑建议先重修小学语文捏
>    乐

我没有哪句表述不清楚的，嘴贱建议回家让你妈妈扇你巴掌再开口，这都能成优越感，真可怜。

**Comment by MuiseDestiny** [comment]
> “本插件正在遭受一位用户抵制”，狗写的？github你开的？凭什么由你定义谁是用户？我就单枪匹马一个普通用户，如果挂我能让其他用户发现、用到更好的插件，我觉得值得。2023还搞挂人呢，继续，你们小团体人多，喷粪心齐，也是好事。

那里的用户是github用户，说你不是用户，不是插件用户。

**Comment by windingwind** [comment]
> 记得一遍喷粪

> 我没有哪句表述不清楚的，嘴贱建议回家让你妈妈扇你巴掌再开口，这都能成优越感，真可怜。

你别急呀，我哪里喷粪了？觉得自己能表述清楚麻烦解释一下呀🤣
另外直接人身攻击到底谁比较喷粪啊🤣

> 这都能成优越感

> 真可怜

谁在那边假装站在道德高地，通过假装可怜别人获得优越感我不说🤭

**Comment by chesnut1** [comment]
你真可怜，在你眼里道德都是假装，恶臭

> > 记得一遍喷粪
> 
> > 我没有哪句表述不清楚的，嘴贱建议回家让你妈妈扇你巴掌再开口，这都能成优越感，真可怜。
> 
> 你别急呀，我哪里喷粪了？觉得自己能表述清楚麻烦解释一下呀🤣 另外直接人身攻击到底谁比较喷粪啊🤣
> 
> > 这都能成优越感
> 
> > 真可怜
> 
> 谁在那边假装站在道德高地，通过假装可怜别人获得优越感我不说🤭

**Comment by chesnut1** [comment]
> > > ![IMG_20230219_114828](https://user-images.githubusercontent.com/51939531/219917100-0d8a873e-77d2-4a7d-9fa9-10095a62c66e.jpg)
> > > 尽力帮你宣传了，希望你抵制愉快
> > 
> > 
> > 哇哦，好大的官威啊，我好害怕啊，继续找水军来骂？2023了一个插件还要翻墙出来搞起专制独裁了呢，每一句都透露着无限优越感。你挂我，你挂，我问问github同不同意你恶意攻击用户, endnote同不同意你抄袭。
> 
> 你不是用户，谢谢

请把我的issue也置顶，谢谢你

**Comment by MuiseDestiny** [comment]
本来就是置顶的，这位用户。

**Comment by windingwind** [comment]
> 你真可怜，在你眼里道德都是假装，恶臭

不会好好说话是吧🤣真可怜我？哥们家里揭不开锅了要饿死了速速v我50，您不是比较有道德比较可怜我吗🤣

> 觉得自己能表述清楚麻烦解释一下呀🤣 另外直接人身攻击到底谁比较喷粪啊🤣

另外这么有逻辑有道德的高素质人士倒是正面回答我的问题呀🤣

**Comment by chesnut1** [comment]
首先我不是男的，你默认我男的，性别歧视不说，你说话真的丢人显眼，没德行没教养的玩意儿，我不会回复了。

**Comment by MuiseDestiny** [comment]
你辩论可以造谣就不对了，我没有团伙。没有向你收费，你没有任何损失。

**Comment by chesnut1** [comment]
> 本来就是置顶的，这位用户。 但是建议你先中文再英文。你太看得起垃圾插件了，没多少外国人用的。

我怎么安排语言顺序都跟你有关系了？你凭什么？没外国人用想想自己的问题，至少github看得到。

**Comment by MuiseDestiny** [comment]
> > 本来就是置顶的，这位用户。 但是建议你先中文再英文。你太看得起垃圾插件了，没多少外国人用的。
> 
> 我怎么安排语言顺序都跟你有关系了？你凭什么？没外国人用想想自己的问题，至少github看得到。

我知道啊，因为垃圾。

**Comment by chesnut1** [comment]
> 你辩论可以造谣就不对了，我没有团伙。没有向你收费，你没有任何损失。

真可悲，损失没损失是我界定不是你界定。造谣没造谣的，都有聊天记录，作者加水军语言攻击是事实，挂我是事实，别说没用的，我投诉到底。

**Comment by windingwind** [comment]
> 首先我不是男的，你默认我男的

我哪里默认您男的了？我说`哥们要饿死了v我50`当然是指的我了🤣别装外宾看不懂中文，外宾不至于英文标题还洋泾浜🤣
您潜意识默认我默认对您性别歧视，是不是该反思下自己根深蒂固潜意识里的性别歧视啊🤣

> 你说话真的丢人显眼，没德行没教养的玩意儿

这两句话连起来我一时都不知道你是在骂我还是在骂自己，乐

> 我不会回复了

经典说不过就逃跑是吧，三十六计是给你学明白了🤣
别跑啊哥们我还指着看乐子呢，辩经辩不过，骂也骂不过，您是懂战略转移的🤣

**Comment by MuiseDestiny** [comment]
> > 你辩论可以造谣就不对了，我没有团伙。没有向你收费，你没有任何损失。
> 
> 真可悲，损失没损失是我界定不是你界定。造谣没造谣的，都有聊天记录，作者加水军语言攻击是事实，挂我是事实，别说没用的，我投诉到底。

加油！如果能赔偿，我愿意赔偿。

**Comment by chesnut1** [comment]
> > 首先我不是男的，你默认我男的
> 
> 我哪里默认您男的了？我说`哥们要饿死了v我50`当然是指的我了🤣别装外宾看不懂中文，外宾不至于英文标题还洋泾浜🤣 您潜意识默认我默认对您性别歧视，是不是该反思下自己根深蒂固潜意识里的性别歧视啊🤣
> 
> > 你说话真的丢人显眼，没德行没教养的玩意儿
> 
> 这两句话连起来我一时都不知道你是在骂我还是在骂自己，乐
> 
> > 我不会回复了
> 
> 经典说不过就逃跑是吧，三十六计是给你学明白了🤣 别跑啊哥们我还指着看乐子呢，辩经辩不过，骂也骂不过，您是懂战略转移的🤣

跟你多说一句都让人想吐，学学你同伙，至少还有语言表达还算清楚。我装什么？你少丢人了吧，会英语就是装外宾，瞧你那狭隘样，自己一口一个哥们，还说我默认性别歧视？脑子有粪还得是你，单纯不想跟你这种败类扯，啊呸！

**Comment by chesnut1** [comment]
> > > 你辩论可以造谣就不对了，我没有团伙。没有向你收费，你没有任何损失。
> > 
> > 
> > 真可悲，损失没损失是我界定不是你界定。造谣没造谣的，都有聊天记录，作者加水军语言攻击是事实，挂我是事实，别说没用的，我投诉到底。
> 
> 加油！如果能赔偿，我愿意赔偿。前提你不是免费使用本插件。

还是那句话，轮不上你评判，github会评价。github上都免费，但是语言暴力+挂人+独裁你们独一家，少把戾气带出墙，这里不是你小红书，有人会管。一条别删

**Comment by windingwind** [comment]
> 会英语就是装外宾

哈哈哈，装外宾是指看不懂中文，笑死

> 自己一口一个哥们

哈哈哈，我自己男的我不能自称哥们啊？您是不是对男性歧视啊？什么只可我负天下人不可天下人负我

怎么说不回复我了还回复我啊？您的原则底线呢🤣

**Comment by volatile-static** [comment]
好家伙，原来是个黄皮白心的母狗

**Comment by windingwind** [comment]
别骂人🤐什么对面先开的腔？那没事了

**Comment by chesnut1** [comment]
> 好家伙，原来是个黄皮白心的母狗
这条留好，贱嘴子。种族歧视+性别歧视，你连个人都不配当。

**Comment by MuiseDestiny** [comment]
请问你在别的平台也是这样吗？感觉别人都充满恶意，就去攻击别人。

**Comment by chesnut1** [comment]
> 请问你在别的平台也是这样吗？感觉别人都充满恶意，就去攻击别人。还喜欢幻想别人都是团伙，都是水军，是不是有必要调理下自己呢。是不是有那个大x呢

滚吧你，三个骂我一个，还有B脸说呢

**Comment by MuiseDestiny** [comment]
> 滚吧你，三个骂我一个，还有B脸说呢

你骂我了，像你说的github会评价。

**Comment by MuiseDestiny** [comment]
不陪你了，好自为之。

**Comment by chesnut1** [comment]
我每一条一回复，你们点unlike，不是都趴在键盘前骂是什么啊？不需要回了，一条一条解释，给你脸了。随你，我单枪匹马，但我不怕，草！奉陪到底！垃圾东西

**Comment by volatile-static** [comment]
https://github.com/volatile-static/Chartero/discussions/35
帮你宣传了一下，不谢

**Comment by windingwind** [comment]
精彩回放：让我们看看是谁一口一个哥们

![image](https://user-images.githubusercontent.com/33902321/219922792-2570bd24-53f0-4752-a734-eb7fef4875f5.png)

噢！原来是我们亲爱的@chesnut1

> 瞧你那狭隘样，自己一口一个哥们，还说我默认性别歧视？

哈哈哈，原话送还给你。什么搬石砸脚

**Comment by chesnut1** [comment]
中南大学电磁AI组传来狗叫？你放心，你丢人丢到国外了，你们导师会为你买单

**Comment by chesnut1** [comment]
> 精彩回放：让我们看看是谁一口一个哥们
> 
> ![image](https://user-images.githubusercontent.com/33902321/219922792-2570bd24-53f0-4752-a734-eb7fef4875f5.png)
> 
> 噢！原来是我们亲爱的@chesnut1
> 
> > 瞧你那狭隘样，自己一口一个哥们，还说我默认性别歧视？
> 
> 哈哈哈，原话送还给你。什么搬石砸脚

没智商你就滚吧低能儿，你叫我妈不等于我也要叫你妈。你是女的你就是跪的起不来了，你是男的，就你妈生你的时候跪的起不来了。难产儿

**Comment by 1067237855** [comment]
这标题起的就离谱
> Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户

作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！

**Comment by chesnut1** [comment]
> 这标题起的就离谱
> 
> > Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户
> 
> 作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！

你他妈狗叫什么？他是你爸你跪下来给他舔吧，畜生！不收钱，你他妈的，他没放二维码？打死你妈逼，你是被打大的吧，贱种

**Comment by chesnut1** [comment]
> 这标题起的就离谱
> 
> > Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户
> 
> 作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！

离谱你妈的烂逼，你妈逼的恶狗水军，装你妈的孙子呢？同时回复还装路人？你他妈认识他你出门撞死你个贱逼东西

**Comment by chesnut1** [comment]
> 这标题起的就离谱
> 
> > Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户
> 
> 作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！

什么别人家自己家？烂逼东西，谁允许你规定谁是谁家的？草泥马的烂逼！凭什么我不能在这回复，有种你他妈删除啊，傻逼。你妈死了吧你脑子有泡

**Comment by volatile-static** [comment]
它急了它急了
哈哈哈哈哈哈哈哈哈

**Comment by 1067237855** [comment]
> 它急了它急了 哈哈哈哈哈哈哈哈哈

确实

**Comment by chesnut1** [comment]
> 它急了它急了 哈哈哈哈哈哈哈哈哈

你个逼样的已经被举报了，还这么开心呀。狗逼中南大学有你也是倒霉了，先关心自己能不能毕业吧烂鸡巴东西

**Comment by volatile-static** [comment]
你是小学生吗？骂人就这水平。。。

**Comment by 1067237855** [comment]
> 你是小学生吗？骂人就这水平。。。

唉😔

**Comment by chesnut1** [comment]
> 它急了它急了 哈哈哈哈哈哈哈哈哈

你他妈逼等着好吧，你删不删无所谓，已经录屏了。哎，没错就被你们几个贱逼齐上阵骂急了，就搞你怎么样，我有的是时间，慢慢玩

**Comment by chesnut1** [comment]
> 你是小学生吗？骂人就这水平。。。

就冲你那句黄皮白狗的，你等着看多少人骂你吧，狗逼别跑

**Comment by chesnut1** [comment]
> 你是小学生吗？骂人就这水平。。。
希望AIRLab的谢主任能处理，嘻嘻

**Comment by MuiseDestiny** [comment]
> > 这标题起的就离谱
> > > Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户
> > 
> > 
> > 作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！
> 
> 你他妈狗叫什么？他是你爸你跪下来给他舔吧，畜生！不收钱，你他妈的，他没放二维码？打死你妈逼，你是被打大的吧，贱种

我无语了，你要是女生，说出这种话，你没有资格批判任何人。

**Comment by MuiseDestiny** [comment]
你可以把这里分享给你认识的所有学校老师，公道自在人心。

**Comment by K-Nick** [comment]
前排插眼看猴

**Comment by K-Nick** [comment]
@MuiseDestiny 让它自己玩吧..浪费这种时间不值得

**Comment by MuiseDestiny** [comment]
> @MuiseDestiny 让它自己玩吧..浪费这种时间不值得

好

**Comment by skumato** [comment]
不是，没必要吧，一个开源软件的开源插件不好用你直接关掉不就行了吗，没必要苦大仇深的骂人吧还骂的这么脏

**Comment by skumato** [comment]
建议作者关掉吧，浪费时间又浪费周日的心情...

**Comment by K-Nick** [comment]
我真服了...这个人咋这么多小号啊..
搁这把github当微博玩是吧

**Comment by skumato** [comment]
额如果我没看错的话是这个人先骂人的吧，这也能共情上的吗？还有不要AOE其他人吧就事论事呗

**Comment by K-Nick** [comment]
1. 我觉得作者语气硬并不是针对你，大家搞科研学业都很忙，如果是解答问题，一般是就事论事。如果您感觉被针对，作者故意搞你心态，我觉得是您应该反思一下自己玻璃心的问题。
2. 我使用的是M1 Pro的版本，你提出的几个问题，比如进度条偶尔不正常显示，我也有遇到过。然而，我的核心是读文献并纳为己用，并不是在插件上精益求精，因而像作者提供的这种插件，有更多功能很好，部分没达到预期也ok。我能理解功能不达预期时的沮丧，但请你意识到zotero是一个【读论文的软件】。
3. 不要拿”为了其他用户更好的体验“来说事，请你务必意识到，**这是一个开源插件**，作者放二维码是开源的一个传统罢了。当你这样的人多了，把开源者搞的心寒，再无人开源时，你还能说你是为了其他用户更好的体验吗？

**Comment by K-Nick** [comment]
> > 这标题起的就离谱
> > > Generators of this plugin verbal abuse customer and it functions do not perform on Mac 此插件不适用Mac，作者连同团伙语言暴力、专制独裁用户
> > 
> > 
> > 作者免费开源软件，每天费心费力地开发，给你用你这还不知足。用别人的东西，还跑到别人家里乱吼乱叫，我算是开了眼了。有人跑到自己家如果这个样子，还需要专制独裁？就该乱棍打死！！！爱用不用，不用滚！！！
> 
> 你他妈狗叫什么？他是你爸你跪下来给他舔吧，畜生！不收钱，你他妈的，他没放二维码？打死你妈逼，你是被打大的吧，贱种

以及诸如此类，这不是正常人交流的语句。请不要把微博上打拳喷人那一套放到github上，非常感谢。
如果你非要揪着volatile-static说的几句话不放，请便。

**Comment by chesnut1** [comment]
> @K-Nick 你这人不长眼啊？ 你跟上面一个人回复的一模一样 你才是小号吧？ 说一句就怼 果然楼主说的是真的 跑了跑了一群下头男 @chesnut1 你会举报吗？我给你分享链接！
> 
> > 我真服了...这个人咋这么多小号啊.. 搁这把github当微博玩是吧

谢谢姐妹，已经举报了。你也不用回他们，疯狗只会用疯狗的思想把你逼疯。这些都是这个叫MuiseDestiny作者找来的，你可以看看我刚开始跟他交流，从头到尾我都没有不尊重他，他听了一句为了他们插件更好就疯了，召集N个男的来骂我。时间耽误了，心弄糟了。莫名其妙被骂母狗，我必追诉到底，已在跟中南大学和这个实验室联系，一个别想跑。

**Comment by skumato** [comment]
> > @chesnut1 哥们你连readme都没看明白就上来问，人家说你两句咋还就破大防了呢？ 咱都是搞科研的，你用人家插件不会自己研究研究吗？b站小红书那么多介绍视频你就看看呗，难道你看人家文献看不懂就直接发邮件质问作者吗？ 我们做插件的也都是研究生啊，哪个不是天天顶着导师push抽时间来维护插件给大家用？你有M1芯片你了不起，我们上哪搞那么多设备去适配啊？ 说实话我们做开源的还**不就图个开心么**，又不指望他赚钱，你们爱用不用啊，又不是我们求着你用，用的人多对我们有半毛钱好处吗？你这么抵制一个开源软件，除了恶心人以外，对我们也没半毛钱影响的。
> 
> @skumato 我怎么看到这个人先喷的？ 难道不是单纯这一伙人不爽人家说他们软件不好嘛？你急什么呀 蝈男帮蝈男 不要face 我就不爽他骂留学生了？怎么了？

我在说她觉得开源软件不好用直接删了就行没有必要骂作者因为作者没有骂她，他骂留学生全体肯定不对啊，你把他拉黑不就完了，能交流就交流不能交流直接溜呗大家都平和一点不要骂人不要戾气这么重
我只是在找插件的时候正好翻到这个插件过来看看甚至都没下载，我也是M1知道有些软件很难兼容到，如果不适配的话你发个issue作者有空适配的话就会回复你的

**Comment by MuiseDestiny** [comment]
我很在意mac用户，因为我觉得mac版本的zotero比window好看太多。mac出问题的地方我尽量解决了，比如标签不上下对齐，设置不生效，但是手里没有mac设备问题暂时没有完全解决。就像citation插件，mac无法使用快速引用，一直没有得到解决。在此感谢mac用户，在明知有缺点的情况下仍然使用插件。

**Comment by MuiseDestiny** [comment]
> > @K-Nick 你这人不长眼啊？ 你跟上面一个人回复的一模一样 你才是小号吧？ 说一句就怼 果然楼主说的是真的 跑了跑了一群下头男 @chesnut1 你会举报吗？我给你分享链接！
> > > 我真服了...这个人咋这么多小号啊.. 搁这把github当微博玩是吧
> 
> 谢谢姐妹，已经举报了。你也不用回他们，疯狗只会用疯狗的思想把你逼疯。这些都是这个叫MuiseDestiny作者找来的，你可以看看我刚开始跟他交流，从头到尾我都没有不尊重他，他听了一句为了他们插件更好就疯了，召集N个男的来骂我。时间耽误了，心弄糟了。莫名其妙被骂母狗，我必追诉到底，已在跟中南大学和这个实验室联系，一个别想跑。

你可拉倒吧！就你和你小号说的这些话你已经没有脸让第二个人知道才对。

**Comment by MuiseDestiny** [comment]
> 你也不用回他们
因为来回切换账号挺麻烦吧

**Comment by chesnut1** [comment]
> 姐妹zju应该是浙江大学 你再搜一下看看 可以搜项目 网暴者不要放过 你发小红书和微博也会有千千万万姐妹支持你的 别怕！
> 
> > > @K-Nick 你这人不长眼啊？ 你跟上面一个人回复的一模一样 你才是小号吧？ 说一句就怼 果然楼主说的是真的 跑了跑了一群下头男 @chesnut1 你会举报吗？我给你分享链接！
> > > > 我真服了...这个人咋这么多小号啊.. 搁这把github当微博玩是吧
> > 
> > 
> > 谢谢姐妹，已经举报了。你也不用回他们，疯狗只会用疯狗的思想把你逼疯。这些都是这个叫MuiseDestiny作者找来的，你可以看看我刚开始跟他交流，从头到尾我都没有不尊重他，他听了一句为了他们插件更好就疯了，召集N个男的来骂我。时间耽误了，心弄糟了。莫名其妙被骂母狗，我必追诉到底，已在跟中南大学和这个实验室联系，一个别想跑。
> 
> <img alt="Screenshot 2023-02-19 at 08 13 55" width="305" src="https://user-images.githubusercontent.com/125790992/219938812-c4344178-a59f-4f8a-b615-0783f871ffe4.png">

好！谢谢姐妹！

**Comment by chesnut1** [comment]
> 姐妹zju应该是浙江大学 你再搜一下看看 可以搜项目 网暴者不要放过 你发小红书和微博也会有千千万万姐妹支持你的 别怕！
> 
> > > @K-Nick 你这人不长眼啊？ 你跟上面一个人回复的一模一样 你才是小号吧？ 说一句就怼 果然楼主说的是真的 跑了跑了一群下头男 @chesnut1 你会举报吗？我给你分享链接！
> > > > 我真服了...这个人咋这么多小号啊.. 搁这把github当微博玩是吧
> > 
> > 
> > 谢谢姐妹，已经举报了。你也不用回他们，疯狗只会用疯狗的思想把你逼疯。这些都是这个叫MuiseDestiny作者找来的，你可以看看我刚开始跟他交流，从头到尾我都没有不尊重他，他听了一句为了他们插件更好就疯了，召集N个男的来骂我。时间耽误了，心弄糟了。莫名其妙被骂母狗，我必追诉到底，已在跟中南大学和这个实验室联系，一个别想跑。
> 
> <img alt="Screenshot 2023-02-19 at 08 13 55" width="305" src="https://user-images.githubusercontent.com/125790992/219938812-c4344178-a59f-4f8a-b615-0783f871ffe4.png">

好，我会的，谢谢！

**Comment by MuiseDestiny** [comment]
> 

我不跟小号说话只跟大号，如果你不是ta，那么我只跟ta说话。你随便骂，我不跟你理论。你不是ta那么你不了解事情的全貌，我不怪你。

**Comment by yadelohim** [comment]
什么下头男，用你的软件是给你面子，弄不懂就肯定是你的软件的问题，还有人敢帮你反驳，居然还敢假定我们的性别，我们这些用户批评你就得受着，我们小仙女说话难听点怎么了，你们这些国楠能和我们比吗[doge]

**Comment by chesnut1** [comment]
你们发了什么又再狗叫什么搬弄什么是非我懒得翻，我不认为在被一群男的集体语言暴力长达几小时并毫无歉意后反击有任何问题。帖子我录屏了，既然你们对github不屑一顾，连别的用户都持否定猖獗态度，那简简单单，谁喷粪谁负责，对每句话负责。我相信山东科技大也好浙江大学也好，会给一个公正的处理。不会再做任何回复。

**Comment by MuiseDestiny** [comment]
> 

嗯已经被开除了，联系那没用

**Comment by chesnut1** [comment]
我找我的，用不着你教，装什么B呢 不知道你在读研？本科也是山东科技大学的，真给你们学校遭黑，呸！就出你这种不明是非的败类了。别怂啊，有种你让你狗腿@volatile-static 别删他那条骂我是“黄皮白种母狗”的啊。删了我也有录屏，从骂人那句一直到ID，装B骂人就别委屈！你妈被骂母狗不知道你不去找学校？一群败类，理想结果，集体开除。

**Comment by MuiseDestiny** [comment]
> 不会再做任何回复。

言而无信

**Comment by MuiseDestiny** [comment]
不会闭嘴我帮你

**Comment by MuiseDestiny** [comment]
由于提出这个问题的人账号已注销，此贴我关闭了，如果从哪里知道这个issue，特地来看看，就当看一乐，不必较真。
