### ISSUE TITLE
“好家伙，原来是个黄皮白心的母狗” --作者和他的水军骂的，大家看图吧，极端恶臭的一群

### ISSUE THREAD

**Issue by chesnut1** [MuiseDestiny/zotero-style#151]
好家伙，原来是个黄皮白心的母狗

_Originally posted by @volatile-static in https://github.com/MuiseDestiny/zotero-style/issues/149#issuecomment-1435866715_

**Comment by chesnut1** [comment]
<img width="880" alt="Screenshot 2023-02-18 at 23 00 24" src="https://user-images.githubusercontent.com/125680060/219922610-9f8a14af-1aa2-4c9d-8f9c-d18736fae677.png">

**Comment by chesnut1** [comment]
<img width="978" alt="Screenshot 2023-02-19 at 05 40 20" src="https://user-images.githubusercontent.com/125680060/219922629-0da315a2-0961-48bc-8658-1ef292967d09.png">

**Comment by MuiseDestiny** [comment]
图穿错了把，容易暴露隐私的

**Comment by MuiseDestiny** [comment]
如果发，请发全，如果在这里断章取义我就删除了

**Comment by MuiseDestiny** [comment]
把你骂人部分也发上去

**Comment by MuiseDestiny** [comment]
给你五分钟时间

**Comment by chesnut1** [comment]
> 图穿错了把，容易暴露隐私的
这是威胁？那你就再加一条

**Comment by MuiseDestiny** [comment]
> 给你五分钟时间

这句话你会觉得我有优越感对吗，对你，我现在确实有。

**Comment by chesnut1** [comment]
> 如果发，请发全，如果在这里断章取义我就删除了

瞧你那贱种样

**Comment by MuiseDestiny** [comment]
> > 如果发，请发全，如果在这里断章取义我就删除了
> 
> 瞧你那贱种样

嗯，还有三分钟

**Comment by chesnut1** [comment]
> 如果发，请发全，如果在这里断章取义我就删除了

首先，看看谁先骂的，再次issue里我一条没删，希望你们也别删

**Comment by MuiseDestiny** [comment]
不好意思，你没时间了

**Comment by chesnut1** [comment]
活在现实世界，少装霸总，懂点法。

**Comment by MuiseDestiny** [comment]
> 活在现实世界，少装霸总，懂点法。

这句话从你嘴里说出来，多少有点滑稽可笑

**Comment by volatile-static** [comment]
@chesnut1 不要再颠倒黑白了，回去仔细看看究竟是谁先骂人的

**Comment by chesnut1** [comment]
倒计时？不是你？怎么报复，你说

**Comment by chesnut1** [comment]
> @chesnut1 不要再颠倒黑白了，回去仔细看看究竟是谁先骂人的

你最严重，闭嘴吧，希望你有妈

**Comment by MuiseDestiny** [comment]
> 倒计时？不是你？怎么报复，你说

你要报复我？还是什么意思

**Comment by chesnut1** [comment]
> @chesnut1 不要再颠倒黑白了，回去仔细看看究竟是谁先骂人的

张口闭口黄皮白母狗的，你好好等着

**Comment by MuiseDestiny** [comment]
太可怕了，要被报复了。

**Comment by chesnut1** [comment]
> > 倒计时？不是你？怎么报复，你说
> 
> 你要报复我？还是什么意思

呵呵笑死了，真一群智障了。倒计时的是你，威胁我传错图暴露隐私的是你，怎么成我报复了。不想跟你说，狗都不如

**Comment by MuiseDestiny** [comment]
> > > 倒计时？不是你？怎么报复，你说
> > 
> > 
> > 你要报复我？还是什么意思
> 
> 呵呵笑死了，真一群智障了。倒计时的是你，威胁我传错图暴露隐私的是你，怎么成我报复了。不想跟你说，狗都不如

我不如你
