### ISSUE TITLE
是否考虑添加多个屏蔽标签设置

### ISSUE THREAD

**Issue by Molisa95** [MuiseDestiny/zotero-style#152]
大佬你好！
最近在使用#标签功能时，发现貌似是没有涉及屏蔽多个词的功能
以我个人使用为例，需要同时屏蔽“unread”和“done”两个标签，但是目前貌似不支持，只能固定屏蔽一个标签，请问是否可以考虑增加此功能？

**Comment by MuiseDestiny** [comment]
可以前面加一个前缀/然后填写~~/屏蔽这个前缀开头的标签

**Comment by Molisa95** [comment]
Get！十分感谢~
