### ISSUE TITLE
可以自己选择关闭进度和进度数据同步功能吗？

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#154]
mac一个小bug（不知道win有没有）
通过在“我的文库”里打开没有读过的文献PDF，zotero主界面会自动跳到同步数据文件中的对应新生成的笔记文件，挺麻烦的，又要拉上去，折叠同步文件，重新打开原来的我的文库文献界面，打开新文献后又要循环上述步骤。

或者能否自己选择关闭进度条的数据存储功能，或者关闭进度条功能？

**Comment by 17816712353** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/68216639/220002611-b51617e6-f44c-43e1-b6c3-5c05473dd9bb.png">

**Comment by 17816712353** [comment]
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/68216639/220002611-b51617e6-f44c-43e1-b6c3-5c05473dd9bb.png">

在zotero浏览新文献肯定是很频繁的，如果每次都这样，随着同步的笔记个数越来越多，切换界面的卡顿和折叠会更明显。

**Comment by MuiseDestiny** [comment]
> mac一个小bug（不知道win有没有） 通过在“我的文库”里打开没有读过的文献PDF，zotero主界面会自动跳到同步数据文件中的对应新生成的笔记文件，挺麻烦的，又要拉上去，折叠同步文件，重新打开原来的我的文库文献界面，打开新文献后又要循环上述步骤。
> 
> 或者能否自己选择关闭进度条的数据存储功能，或者关闭进度条功能？

优化下你看看哈

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.1

试试，应该不会自动选择了

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.1
重新下载安装此版本试试

**Comment by 17816712353** [comment]
优秀！已正常！

**Comment by MuiseDestiny** [comment]
> 优秀！已正常！

那我关了，再有问题再开

**Comment by 17816712353** [comment]
> > 优秀！已正常！
> 
> 那我关了，再有问题再开

作者大大，这个问题又出现了😂。我本来想关闭进度条功能然后删掉同步文件，但是发现连着标签对齐也一起没了，这两个功能可以分拆成两个吗？

**Comment by MuiseDestiny** [comment]
> > > 优秀！已正常！
> > 
> > 
> > 那我关了，再有问题再开
> 
> 作者大大，这个问题又出现了😂。我本来想关闭进度条功能然后删掉同步文件，但是发现连着标签也一起出来了，这两个功能可以分拆成两个吗？又不想要标题进度，又想要标签隐藏（贪心脸） <img alt="image" width="708" src="https://user-images.githubusercontent.com/68216639/221386933-f5a9d5d9-a69a-4431-b8be-fc5282c94b98.png">

可以提供单独关闭数据记录的设置，就不产生新的笔记了。
