### ISSUE TITLE
关于插件中的配置文件zoteroStyle和addonItem的问题

### ISSUE THREAD

**Issue by dreamMilk** [MuiseDestiny/zotero-style#155]
对于zoteroStyle文件在迁移旧版数据后是否可以直接移动到回收站，然后删除（清空回收站）
对于addonItem文件生成的条目出现在每篇文献的所有笔记下
![微信截图_20230220150724](https://user-images.githubusercontent.com/42259923/220036585-cfc4e300-6373-4c3e-b760-466989e55206.png)
是否有好的解决方案，避免笔记受到干扰，同时保证插件的正常工作

因为两个文件关系到插件的运行，不敢随意删改，望作者可以帮忙解惑🙏🙏🙏

**Comment by MuiseDestiny** [comment]
> 对于zoteroStyle文件在迁移旧版数据后是否可以直接移动到回收站

可以的

> 对于addonItem文件生成的条目出现在每篇文献的所有笔记下

更新最新版试试

**Comment by dreamMilk** [comment]
对于addonItem的问题，更新后重启zotero仍然存在
![image](https://user-images.githubusercontent.com/42259923/220043195-91ffe346-88c3-4af3-8797-5686765c4033.png)
![image](https://user-images.githubusercontent.com/42259923/220043412-cdb4dcd1-7141-46c7-9853-ff535ecf2d4f.png)

**Comment by MuiseDestiny** [comment]
最新2.2.2特意解决这个问题的，看下可以在github上下载安装不

**Comment by dreamMilk** [comment]
卸载原版本后，使用github上的xpi文件安装后版本还是2.2.1，不知道是不是我的操作有问题（ps：上述问题仍然存在）

**Comment by MuiseDestiny** [comment]
> 卸载原版本后，使用github上的xpi文件安装后版本还是2.2.1，不知道是不是我的操作有问题（ps：上述问题仍然存在）

稍等，我看看

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/220056058-e9d7083e-ee0f-41a2-934a-fc00f62af41a.png)

直接删除了吧，但不要在回收站在此删除（不要彻底删除）
