### ISSUE TITLE
能否自定义publication tag呢？

### ISSUE THREAD

**Issue by LynnXie00** [MuiseDestiny/zotero-style#156]
本人是，商科在读博士……您预设的tag我都用不上啊…… 我们是按照ABDC list 排序的…… 也就是，有一个excel表，标明从A+, A, B, C 等级的期刊……

**Comment by MuiseDestiny** [comment]
> 本人是，商科在读博士……您预设的tag我都用不上啊…… 我们是按照ABDC list 排序的…… 也就是，有一个excel表，标明从A+, A, B, C 等级的期刊……

不是我预设的哦，是easyscholar，它会对A+，B。。。类似的匹配等级的。

比如
```ts
swjtu(s: string) {
    let key = "SWJTU", value = s;
    let rank
    if (s == "A++") {
      rank = 1
    } else if (s == "A+") {
      rank = 2
    } else if (s == "A") {
      rank = 3
    } else if (s == "B+") {
      rank = 4
    } else if (s == "B") {
      rank = 5
    } else if (s == "C") {
      rank = 5
    }
    return { rank, key, value }
  },
```

**Comment by 1067237855** [comment]
个人感觉他困惑的原因是以下两点：
第一：
![image](https://user-images.githubusercontent.com/104330036/220132229-24bbdfc4-0fc8-4861-b4d4-7a99e5dd27cf.png)
上图位置写上网址/链接：https://github.com/MuiseDestiny/zotero-style#%E6%9C%9F%E5%88%8A%E6%A0%87%E7%AD%BE

第二：
下图位置进行文字说明
![image](https://user-images.githubusercontent.com/104330036/220134504-89f6f079-bbdb-4183-b99c-9c9bde894e4b.png)

**Comment by MuiseDestiny** [comment]
> 个人感觉他困惑的原因是以下两点： 第一： ![image](https://user-images.githubusercontent.com/104330036/220132229-24bbdfc4-0fc8-4861-b4d4-7a99e5dd27cf.png) 上图位置写上网址/链接：https://github.com/MuiseDestiny/zotero-style#%E6%9C%9F%E5%88%8A%E6%A0%87%E7%AD%BE
> 
> 第二： 下图位置进行文字说明 ![image](https://user-images.githubusercontent.com/104330036/220134504-89f6f079-bbdb-4183-b99c-9c9bde894e4b.png)

哈哈哈。是这样的，但我对这些字段也不太懂，欢迎了解的朋友PR。

**Comment by LynnXie00** [comment]
哦，是因为我的zotero上根本不显示设置的UI界面，只有advanced config....所以上述截图我也压根儿在我的电脑上见不到……这应该也算一个bug了……而且我的电脑是英文界面的，没法让这个插件里的中文正常显示…… 但是zotero里面的论文或者别的啥用中文了，是能显示的

**Comment by LynnXie00** [comment]
> 

Easy scholar 的评级很明显不太包括商科orz 我大量的文献都是没有publication tag的。好吧，只能忍痛割爱这个功能了

**Comment by MuiseDestiny** [comment]
> > 
> 
> Easy scholar 的评级很明显不太包括商科orz 我大量的文献都是没有publication tag的。好吧，只能忍痛割爱这个功能了

不包括的话，这个功能就用不了了，很遗憾

**Comment by FakeTrader** [comment]
分级数据参考 https://easyscholar.cc/document/detail#数据来源

**Comment by MuiseDestiny** [comment]
> 👍👍👍👍👍
> 
> > 分级数据参考 [https://easyscholar.cc/document/detail#数据来源](https://easyscholar.cc/document/detail#%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%BA%90)
> 
> 数据来源 若以下信息，与颜色块上的提示信息不同，则以后者为准。
> 
> CCF: 《中国计算机学会推荐国际学术会议和期刊、中文科技期刊目录-2019、计算领域高质量科技期刊分级目录》，数据集从高到低分为：A(T1), B(T2), C(T3)。 SWUFE :《西南财经大学学术期刊目录2018》，数据集从高到低分为：A+, A, B, C。 CUFE：《中央财经大学期刊目录（2019版）》，数据集从高到低分为：AAA, AA, A。 SSCI：《JCR-分区-影响因子-2022(2022.6.28).pdf》，数据集从高到低分为：Q1, Q2, Q3, Q4。 SCI：《JCR-分区-影响因子-2022(2022.6.28).pdf》，数据集从高到低分为：Q1, Q2, Q3, Q4。 SCIIF：《JCR-分区-影响因子-2022(2022.6.28).pdf》，easyScholar将影响因子从10, 4, 2, 1, 0分为5个等级。 JCI：《JCR-分区-影响因子-2022(2022.6.28).pdf》，easyScholar将JCI指数从3, 1, 0.5, 0 分为4个等级。 SCIIF(5)：由于还未收集到最新5年影响因子数据，所以仍沿用2021年的数据。easyScholar将5年影响因子从10, 4, 2, 1, 0分为5个等级。 A&HCI：《JCR-分区-影响因子-2022(2022.6.28).pdf》。该数据集只有一个等级。 FDU：[《复旦大学学位与研究生教育国内期刊指导目录（2018年1月修订）》](http://www.gs.fudan.edu.cn/32/08/c2811a143880/page.htm)，数据集从高到低分为：A, B。 SJTU：[《上海交通大学SCISCIE论文A档B档期刊分类目录及其他刊物等级参考(2018.5)》](https://me.sjtu.edu.cn/notice/12152.html)，数据集从高到低分为：A, B。 XMU：《厦门大学人文社科核心学术期刊目录（2017）》，该数据集只有一个等级：一类。 CSSCI：《CSSCI来源期刊、扩展版目录2021-2022》。数据集从高到低分为：CSSCI， CSSCI扩展版。 RUC：《中国人民大学核心期刊目录2017》，数据集从高到低分为：A+, A, A-, B。 CSCD：《中国科学引文数据库来源期刊列表（2021-2022 年度）》，数据集从高到低分为： 核心库，扩展库。 SWJTU：《西南交通大学学术期刊分级目录（2017年修订版）》，数据集从高到低分为：A++, A+, A, B+, B。 UIBE：《对外经济贸易大学科研奖励外文核心期刊专题分类目录》,数据集从高到低分为： A, A-, B。 PKU：[《中文核心期刊要目总览》（2020年版）》](https://kjc.snut.edu.cn/info/1030/2353.htm)，该数据集只有一个等级。 XDU：《关于发布《西安电子科技大学高水平期刊目录（2021年）》的通知》，数据集从高到低分为： 一类贡献度，二类贡献度。 SDUFE：[《山东财经大学学术期刊分类目录》](https://yjsy.sdufe.edu.cn/info/1042/2279.htm)，数据集从高到低分为： 特类期刊, A1, A2, B, C。 EI：《CPXSourceList062022.xlsx》，该数据集只有一个等级。 NJU：《南京大学超一流、学科群一流、SCI A区和B区期刊目录.xlsx》，数据集从高到低分为： 超一流期刊（学科群一流期刊）, A, B。 中国科技核心期刊目录：《2021年版中国科技核心期刊目录.pdf》, 该数据集只有一个等级。 CQU：《重庆大学人文社会科学类、自然科学类期刊分级目录》，数据集从高到低分为：A（权威期刊）， B（重要期刊）， C。 HHU：《河海大学高质量论文期刊及学术会议目录（自然科学类，不含计算机科学与技术、软件工程学科）》，数据集从高到低分为：A类，B类，C类。 AJG：《ABS-2021.pdf》英文约1700种。数据集从高到低分为：4*, 4, 3, 2, 1 XJU：《新疆大学2020版自然科学、人文社科学术期刊目录，2021年人文社科学术期刊调整目录》。数据集从高到低分为：一区， 二区， 三区，四区， 五区。 CUG：《中国地质大学科技类、人文社科类期刊分区总汇》。数据集从高到低分为：T1, T2, T3, T4, T5 FMS：[FMS管理科学高质量期刊推荐列表(2022)](http://www.fms-journal.net/) 。数据集从高到低分为：A(T1), B(T2), C, D。 SCU：《四川大学-高质量科技期刊及学术会议分级参考方案（暂行）-2021年4月.xlsx》。数据集从高到低分为：A, A-, B, C, D, E UTD24：《互联网公开收集》， 该数据集只有一个等级。 FT50：《互联网公开收集》 ，该数据集只有一个等级。 中科院升级版：微信小程序：《中科院文献情报分区中心表2022年12月最新》数据集从高到低分为1区，2区，3区，4区。 中科院基础版：微信小程序：《中科院文献情报分区中心表2021年12月最新》数据集从高到低分为1区，2区，3区，4区。 中科院预警：《国际期刊预警名单(试行)-2021.12.31》 ，该数据集只有一个等级。 Yangtze：《长江大学自然科学高质量期刊（中国期刊）分级目录（2021版）.pdf》数据集从高到低分为T1, T2, T3。 ZJU：《浙江大学国内学术期刊分级目录指南·2020版.pdf》数据集从高到低分为国内一级学术期刊，国内一级核心期刊。

太强了，能写到readme吗

**Comment by 1067237855** [comment]
> 太强了，能写到readme吗


建议加一下readme目录
![image](https://user-images.githubusercontent.com/104330036/220356541-d5481e2d-6d14-4e7d-8fc5-d00606f07116.png)

现在功能太多了，readme可得好好写一下  或者  **最好**是将大佬录制的视频链接放在readme里。不然用户会有好多操作小问题，例如readme看不明白

**Comment by MuiseDestiny** [comment]
> > 太强了，能写到readme吗
> 
> 建议加一下readme目录 ![image](https://user-images.githubusercontent.com/104330036/220356541-d5481e2d-6d14-4e7d-8fc5-d00606f07116.png)
> 
> 现在功能太多了，readme可得好好写一下 或者 **最好**是将大佬录制的视频链接放在readme里。不然用户会有好多操作小问题，例如readme看不明白

确实多，还杂。欢迎有时间PR~。

**Comment by seifer08ms** [comment]
> > 
> 
> Easy scholar 的评级很明显不太包括商科orz 我大量的文献都是没有publication tag的。好吧，只能忍痛割爱这个功能了

自己动手加 easy scholar 的数据啊
