### ISSUE TITLE
高能进度条失效

### ISSUE THREAD

**Issue by HTDream** [MuiseDestiny/zotero-style#162]
![image](https://user-images.githubusercontent.com/125957332/220281421-f93f4acb-0242-4c8d-a7e3-93762331273e.png)
文献阅读后，题目背景有阅读进度了，但是进度一栏没有显示了，请问怎么修复

**Comment by MuiseDestiny** [comment]
readme有介绍，这俩显示的不是同一个东西哦。
https://github.com/MuiseDestiny/zotero-style#%E8%BF%9B%E5%BA%A6

**Comment by MuiseDestiny** [comment]
想让进度显示，多做一些标注吧

**Comment by HTDream** [comment]
哦哦，明白了，高能进度条是标注的数量。明白了，感谢感谢
