### ISSUE TITLE
重新打开软件时列顺序会被打乱

### ISSUE THREAD

**Issue by Molisa95** [MuiseDestiny/zotero-style#163]
1. 调整好的列顺序，重新打开时会自动调整到一个固定顺序，没能很好保存，如，我本将标签设置为第一列，附件设置为最后一列，关闭后重新打开成了如下顺序
![image](https://user-images.githubusercontent.com/52652817/220288210-6ed94830-1019-4fd9-88f3-61da976a1647.png)
2. 此外，不同视图下，列顺序的调整会相互影响，比如我在第一个视图里把标签放在标题列之前，在第三个视图把标签放调整到标题之后，再回到第一个视图会发现标签列被调整到标题之后了。
辛苦大佬看看能否解决这两个问题，十分感谢！

**Comment by MuiseDestiny** [comment]
现在视图组只保存一个列的显示还是不显示，至于顺序列宽确实没有保存。等有时间把这些也加上去

**Comment by Molisa95** [comment]
十分感谢，大佬威武！列宽也十分需要！赞赞赞！

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.4

已预发布。

**Comment by drxxy98** [comment]
你好，这个问题还是存在。。是我的版本不够新吗

**Comment by 484614372** [comment]
您好，确实是这样，不知为何，目前最新for 7beta，仍然存在问题
具体为：打开三四秒内不显示style插件图标、列顺序重置、列宽不能修改、以及之前版本更新中的功能例如直接update view group的功能没有发现
