### ISSUE TITLE
选中条目拖动会导致大范围空白及文本错乱

### ISSUE THREAD

**Issue by KaKaafh** [MuiseDestiny/zotero-style#166]
选中条目拖动会导致大范围空白及文本错乱
![wenti](https://user-images.githubusercontent.com/125976439/220332346-5962c46b-72f0-4f0a-a295-295b717fcc92.png)

**Comment by MuiseDestiny** [comment]
还真是的。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.2.4

已修复。安装后还有问题可以重开这个issue
