### ISSUE TITLE
视图组的增强：导出所需字段

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#169]
经常在自己做PPT，或者写笔记的时候，或者发给别人的时候，需要复制某一篇文献的信息。以这样的格式：（作者，年份，期刊），
如果直接复制条目，出来的信息是包含了比较完整的参考文献形式的信息，很长，需要自己删掉在保留自己的信息。
作者的视图组提供了一个思路，能不能通过预先设置，来复制当前视图组所展示的期刊信息，比如我现在是的列是：作者，年份，期刊，那我复制此时的文献信息，复制出来的就只包括（作者，年份，期刊），可以很方便在制作PPT或者思维导图的时候使用。

不知道这个实现起来难不难。
或者就干脆脱离视图组，直接提供一个复制自定义字段组合的功能，一些不成熟的功能想法，供作者参考～

**Comment by MuiseDestiny** [comment]
better-bixtex是不是做这个的，我用的不多，感觉好像可以实现你说的功能。

**Comment by 17816712353** [comment]
> better-bixtex是不是做这个的，我用的不多，感觉好像可以实现你说的功能。

那个插件是我印象里是索引，而且速度很慢，挺卡的，导出的印象里也是缩写缩写缩写。

**Comment by hujie12306** [comment]
> 经常在自己做PPT，或者写笔记的时候，或者发给别人的时候，需要复制某一篇文献的信息。以这样的格式：（作者，年份，期刊）， 如果直接复制条目，出来的信息是包含了比较完整的参考文献形式的信息，很长，需要自己删掉在保留自己的信息。 作者的视图组提供了一个思路，能不能通过预先设置，来复制当前视图组所展示的期刊信息，比如我现在是的列是：作者，年份，期刊，那我复制此时的文献信息，复制出来的就只包括（作者，年份，期刊），可以很方便在制作PPT或者思维导图的时候使用。
> 
> 不知道这个实现起来难不难。 或者就干脆脱离视图组，直接提供一个复制自定义字段组合的功能，一些不成熟的功能想法，供作者参考～

修改quick copy的引用样式，ctrl+shift+C

**Comment by 1067237855** [comment]
该功能zotcard已经做过了，而且比你构想的还要强大。比word中的文献引用功能还好用。支持全字段  **自定义** 样式。
![image](https://user-images.githubusercontent.com/104330036/221158748-f50f588f-56d2-4ec8-9810-8d25b98f8b5d.png)




> 经常在自己做PPT，或者写笔记的时候，或者发给别人的时候，需要复制某一篇文献的信息。以这样的格式：（作者，年份，期刊）， 如果直接复制条目，出来的信息是包含了比较完整的参考文献形式的信息，很长，需要自己删掉在保留自己的信息。 作者的视图组提供了一个思路，能不能通过预先设置，来复制当前视图组所展示的期刊信息，比如我现在是的列是：作者，年份，期刊，那我复制此时的文献信息，复制出来的就只包括（作者，年份，期刊），可以很方便在制作PPT或者思维导图的时候使用。
> 
> 不知道这个实现起来难不难。 或者就干脆脱离视图组，直接提供一个复制自定义字段组合的功能，一些不成熟的功能想法，供作者参考～
