### ISSUE TITLE
关于闪退的问题

### ISSUE THREAD

**Issue by caoths** [MuiseDestiny/zotero-style#173]
I would like to ask, I installed the latest version of style and reference after each click to open a directory, zotero will automatically flash, but if I just click on the directory under the pdf will not flash, what is the reason for this, the previous style and reference does not seem to have this problem it

**Comment by MuiseDestiny** [comment]
自动刷新吗，能录一下视频看看吗。

新版有个快捷筛选，点击条目标题前logo是会刷新的。

**Comment by caoths** [comment]
不知道是不是自动刷新，就是打开zotero，然后打开一个条目，zotero就自己关闭了，闪退了，可能还是和其他版本不兼容吧

**Comment by caoths** [comment]
之前您的style我安装了还没出现过闪退，我打算换回来之前您的版本，因为新出的很多功能，都没有看明白有什么好用处，但是翻译按句这个还是有用的，只是不知道怎么启用这个功能还

**Comment by MuiseDestiny** [comment]
> 之前您的style我安装了还没出现过闪退，我打算换回来之前您的版本，因为新出的很多功能，都没有看明白有什么好用处，但是翻译按句这个还是有用的，只是不知道怎么启用这个功能还

先用旧版，最近更新没太大（一般用不到）。

**Comment by caoths** [comment]
好的，谢谢您，刚才试了，发现这回也没有闪退了，还是用的style和reference最新的版本，
