### ISSUE TITLE
奇偶数行颜色设置出错

### ISSUE THREAD

**Issue by KaKaafh** [MuiseDestiny/zotero-style#181]
会出现连续两行有颜色，两行没颜色的情况
<img width="843" alt="bug" src="https://user-images.githubusercontent.com/125976439/222022886-a78bd709-e02e-455c-9a63-528bcaa9a700.png">

**Comment by MuiseDestiny** [comment]
所有collection都会出现吗，还是根据某个字段排序后产生的，怎么复现这个bug

**Comment by 1067237855** [comment]
正常现象，这个功能刚出的时候就有这个BUG，也不影响使用，不用管他都行
