### ISSUE TITLE
页签栏锁死

### ISSUE THREAD

**Issue by Saunak626** [MuiseDestiny/zotero-style#184]
![image](https://user-images.githubusercontent.com/34276206/222059574-efd3ae06-21d9-4f3a-9204-bc980c132e9a.png)
更新插件之后出现了页签栏锁死的情况。当前打开的pdf还可以滚动浏览，但是无法切换到其他页签上。有时候卡顿一下会恢复，有时候要重启才行。同时出现了切换到页签，该页签自动到最右侧的情况

**Comment by MuiseDestiny** [comment]
我也卡，我以为我电脑卡，我看看修复

**Comment by Saunak626** [comment]
> 我的没有出现卡顿现象，但也出现了点击任意一个打开的pdf它会自动移到最后一个（最右侧），这是新功能吗？

我感觉这个特性用处不大，而且没有关闭的选项。更新里也没写，可能是bug

**Comment by MuiseDestiny** [comment]
> 我的没有出现卡顿现象，但也出现了点击任意一个打开的pdf它会自动移到最后一个（最右侧），这是新功能吗？

bug，但我没出现过

**Comment by Saunak626** [comment]
> > 我的没有出现卡顿现象，但也出现了点击任意一个打开的pdf它会自动移到最后一个（最右侧），这是新功能吗？
> 
> bug，但我没出现过

我遇到这个bug的使用情况是已经打开了很多页签，并且打开了右侧的标签面板
![image](https://user-images.githubusercontent.com/34276206/222080439-fbfc9ed6-d1d6-46b6-af50-076234e1215d.png)

这个新的嵌套标签不知道是不是和zotero tag有冲突，因为也是触发一些tag的规则的同时发生了卡顿和bug。
这些插件的自动触发规则可能存在冲突，也许是对于触发动作的识别存在问题

**Comment by MuiseDestiny** [comment]
> > 我的没有出现卡顿现象，但也出现了点击任意一个打开的pdf它会自动移到最后一个（最右侧），这是新功能吗？
> 
> bug，但我没出现过

出现的（没观察这么仔细）我改一下

**Comment by MuiseDestiny** [comment]
修复了，少了几个参数，就每次选tab变成重新打开了，重新打开会触发zotero tag的一些事件，这可能也是卡顿的原因

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.3.2

还卡顿重开此问题
