### ISSUE TITLE
[Feature Request] #标签横向竖向排序

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-style#187]
一直有一个疑问：多个标签的时候，标签、#标签  是按照什么顺序排列的？
有时候特别希望某个标签在最前面（尤其强迫症犯了的时候，特别希望“液晶弹性体”整齐划一放置在最前面），有些时候重要的标签放置在后面很容易被遮挡。
#标签/多级标签  通过标签嵌套一定程度上解决了这一问题，
但仍然希望让多个标签 #A、#B、#C、#A/B时是按照自己希望的顺序排列，比如通过加特殊符号或数字定义排列顺序* - ~ ！0123

多个标签的时候，标签、#标签  是按照什么顺序排列的？求教大佬

![image](https://user-images.githubusercontent.com/104330036/222117586-b0e7850e-1784-41f8-a26a-5b2b5a224ab2.png)

**Comment by 1067237855** [comment]
Shift+P里面的标签位置和颜色功能不太会用，不太好用。如果可以移到下图这个位置起作用的话，效果可能会好用一些
![image](https://user-images.githubusercontent.com/104330036/222124952-201682a5-e674-46fa-afd0-d3a44c9358b3.png)

**Comment by woodwm** [comment]
标签排序应该是字母顺序，这个是 Zotero 内定的，好像没有选项可以修改。

**Comment by 1067237855** [comment]
哦，懂了。大佬开发的#标签 是按照添加时间排序呀。我说怎么没法改前后顺序，按照字母排序死活没找到规律😂

zotero自带的竖向标签  是否排序无所谓，影响不大。

**Comment by holderhe** [comment]
强迫症表示这个排序功能很有需求，希望大佬能够尽快开发出来

**Comment by MuiseDestiny** [comment]
> 强迫症表示这个排序功能很有需求，希望大佬能够尽快开发出来

已经是a_z排序了

**Comment by holderhe** [comment]
> 

在视图组也是吗？小白没找到怎么操作的，求大佬详解一下

**Comment by MuiseDestiny** [comment]
> 在视图组也是吗？小白没找到怎么操作的，求大佬详解一下

视图组是要求输入position的，数字越小越靠前

**Comment by holderhe** [comment]
> > 在视图组也是吗？小白没找到怎么操作的，求大佬详解一下
> 
> 视图组是要求输入position的，数字越小越靠前

这个position指的是什么，小白不是很懂，是指标签前面加上123方便排在前面么？

**Comment by 1067237855** [comment]
2.3.3#标签排序，不管用，依旧是按照添加顺序排序的。无法按照0-9、a-z排序
 
> 已经是a_z排序了

**Comment by holderhe** [comment]
> 2.3.3#标签排序，不管用，依旧是按照添加顺序排序的。无法按照0-9、a-z排序
> 
> > 已经是a_z排序了

我仔细尝试了一下，的确是a-z排序，所以自定义排序还是一个有需求的东西，不知道有没有其他办法可以实现

**Comment by 1067237855** [comment]
不，是按照添加时间顺序排列的

![image](https://user-images.githubusercontent.com/104330036/222937208-4faee150-8a8d-4140-99ed-9e8bd37eb76e.png)




> 我仔细尝试了一下，的确是a-z排序，所以自定义排序还是一个有需求的东西，不知道有没有其他办法可以实现

**Comment by MuiseDestiny** [comment]
> 

定义几个abc开头的标签试试

**Comment by MuiseDestiny** [comment]
我不知道对中文怎么排序的，你可以用abcd前缀，然后用match过滤掉abcd前缀来达到排序目的。

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/222937427-3164b264-7aed-49ec-a2e1-f2f1c11795e8.png)

**Comment by holderhe** [comment]
> 不，是按照添加时间顺序排列的
> 
> ![image](https://user-images.githubusercontent.com/104330036/222937208-4faee150-8a8d-4140-99ed-9e8bd37eb76e.png)
> 
> > 我仔细尝试了一下，的确是a-z排序，所以自定义排序还是一个有需求的东西，不知道有没有其他办法可以实现

这个我没有仔细看，因为大部分标签是自动添加的，这些是按a-z排序的，不过我自己添加的的确是都在后面，可能是按先时间后字母排序的

**Comment by MuiseDestiny** [comment]
> ![image](https://user-images.githubusercontent.com/104330036/222937427-3164b264-7aed-49ec-a2e1-f2f1c11795e8.png)

重新下载最新版呢，可能我覆盖上传加的这个功能。不行等会我增强下排序

**Comment by MuiseDestiny** [comment]
想要什么交互实现排序功能

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/222937850-7c331702-c009-4802-82b3-31cc9d46e794.png)

@holderhe 是这个意思不？希望  标签  **ab重要** 通过加上数字放置在最前面

**Comment by 1067237855** [comment]
跟文件夹排序类似

![image](https://user-images.githubusercontent.com/104330036/222937946-6cd95a1b-ef51-4ce1-9e8e-95afb1f5abc8.png)

**Comment by MuiseDestiny** [comment]
或者你给想优先展示的标签指派颜色和位置位置写的小就靠前。渲染时候优先渲染有颜色的标签。

**Comment by 1067237855** [comment]
试了指派颜色的办法，可以行得通👍，总感觉不太好用
@holderhe 你试一下吧是不是想要的效果。步骤：选中条目，shift+P， 标签，指派颜色和位置
![image](https://user-images.githubusercontent.com/104330036/222938375-edc3f961-2449-4f79-ac60-d4e585386ffe.png)

> 或者你给想优先展示的标签指派颜色和位置位置写的小就靠前。渲染时候优先渲染有颜色的标签。

**Comment by MuiseDestiny** [comment]
> 

Zotero里优先排序就是这个逻辑，再创造一个逻辑有点不好适应。

**Comment by 1067237855** [comment]
嗯嗯，不管怎么样，能解决问题就好。

 
> Zotero里优先排序就是这个逻辑，再创造一个逻辑有点不好适应。

**Comment by holderhe** [comment]
> 

@1067237855 按照您的建议，在这个地方我好像无法保存，退出后还是原来的样子，是我操作有误还是其他地方需要设置

**Comment by holderhe** [comment]
> 想要什么交互实现排序功能

@MuiseDestiny 其实主要目的就是想有在视图组里的标签也能一个自定义排序功能，想按照a-z或者其他方式都行，这样可以方便把一些标签放在前面，毕竟视图组的显示内容有限，想一眼就能知道这篇文献的要点毕竟需要这个功能

**Comment by MuiseDestiny** [comment]
那我优化下az排序吧，需要优先的前面打一个A就可以了

**Comment by 1067237855** [comment]
需要多试几次，不一定哪次就成功了😂，我也是多次尝试后才成功的



> @1067237855 按照您的建议，在这个地方我好像无法保存，退出后还是原来的样子，是我操作有误还是其他地方需要设置

**Comment by holderhe** [comment]
> 那我优化下az排序吧，需要优先的前面打一个A就可以了

感谢大佬的付出！


@1067237855 重装重启目前都还不行，我多试试看，看能不能保存

**Comment by MuiseDestiny** [comment]
试试看https://github.com/MuiseDestiny/zotero-style/releases/tag/2.3.5

**Comment by holderhe** [comment]
完美达到我的强迫症需求，感谢大佬！
