### ISSUE TITLE
更新到最新版zoterostyle插件后，右键选择修改标注颜色，出现如图所示错误， 之前版本的标注颜色修改不会出现这个问题 

### ISSUE THREAD

**Issue by Elodie-0117** [MuiseDestiny/zotero-style#188]
![220921223-0a8a70f1-f3f2-4a76-b58c-b464fe977b3d](https://user-images.githubusercontent.com/126692797/222178861-7c97daf6-ecc1-434b-915d-58c3a68e2d42.png)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/123

**Comment by Elodie-0117** [comment]
> #123
我试过更新到zotero beta版本 这个问题还是在 只要是使用不是官方的那6种颜色组合之外的组合 就一直会出现这个错误提示，几个星期以前的style插件颜色标注还没有这个问题，是这几个星期才出现的，我尝试安装旧版本插件，这个问题也还是在

**Comment by MuiseDestiny** [comment]
理论上这个错误其实一直在控制台有的，应该不会影像正常使用。但一直这么报错，有点影响使用了。它报错意思是ocean.blue在语言本地化过程中没有找到，zotero是多语言的，如果设置英文ocean.blue会被显示成blue中文就是一个颜色名称。

但是我印象中没有设置过ocean.blue这个颜色名称，general.blue是对的。总之你使用支持语言本地化ocean.blue这个关键词的Zotero版本。

**Comment by Elodie-0117** [comment]
> 理论上这个错误其实一直在控制台有的，应该不会影像正常使用。但一直这么报错，有点影响使用了。它报错意思是ocean.blue在语言本地化过程中没有找到，zotero是多语言的，如果设置英文ocean.blue会被显示成blue中文就是一个颜色名称。
> 
> 但是我印象中没有设置过ocean.blue这个颜色名称，general.blue是对的。总之你使用支持语言本地化ocean.blue这个关键词的Zotero版本，就不会保报错，或者不要改颜色名称。

我把颜色名字全部换成general.这样的官方名字之后，所有报错都没有了，可以正常使用自己设置的颜色了，开心， 非常感谢🙏 太厉害了
