### ISSUE TITLE
2.3.3 白屏了！！！

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-style#192]
最新版#标签 中输入

static getTagMatch(tag: string) {
  const rawString = Zotero.Prefs.get(`${config.addonRef}.textTagsColumn.match`) as string
  const res = rawString.match(/\/(.+)\/(\w*)/)
  let regex: RegExp;
  // 是正则表达式
  if (res) {
    regex = new RegExp(res[1], res[2])
  }
  // 不以xxx开头
  else if (rawString.startsWith("~~")) {
    regex = new RegExp(`^([^${rawString.slice(2)}].+)`)
  }
  // 以xxx开头
  else {
    regex = new RegExp(`^${rawString}(.+)`)
  }
  const arr = tag.match(regex)
  return (arr && arr.slice(1).join("")) || ""
}

# 白屏了

![image](https://user-images.githubusercontent.com/104330036/222422075-95eaf348-08ea-4941-853b-c7413f6929b5.png)

**Comment by 1067237855** [comment]
复制粘贴后白屏😂
![image](https://user-images.githubusercontent.com/104330036/222423986-8bf2e1b1-7e28-436a-b643-5c6798edbc3b.png)

现在disabled zotero style后白屏消失，zotero恢复正常
求style #标签 的恢复方法

**Comment by MuiseDestiny** [comment]
是这样的，那段代码是用来看他运行逻辑的，不是输入在这里的。

**Comment by 1067237855** [comment]
修好了
