### ISSUE TITLE
#Tags列显示了所有标签，不只是带#的标签

### ISSUE THREAD

**Issue by xchyyb** [MuiseDestiny/zotero-style#199]
![image](https://user-images.githubusercontent.com/78303344/222607358-640f5afe-c352-4370-a5c6-0ae9af0ee5dc.png)
更新到2.3.3版本后出现图中的问题，请问该如何解决

**Comment by 1067237855** [comment]
对#标签 的  列设置 重新配置一下，即可解决（原本的~~#符号依然支持）
### 有更高需求可以用正则表达式实现，如下

![image](https://user-images.githubusercontent.com/104330036/222629134-07686449-f4c4-482e-b31c-c323329df8d3.png)

https://github.com/MuiseDestiny/zotero-style

**Comment by ngh2014** [comment]
我直接返祖，向高级功能say bye了
![image](https://user-images.githubusercontent.com/67650419/222650112-7f63ec48-7296-4851-a141-a0d8ca334d0c.png)
