### ISSUE TITLE
实时更新变为手动更新

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-style#207]
真的是越来越棒了！赞！
不过也遇到了一些问题，
我zotero中条目太多了（上万，有点emmmm），导致现在使用 zotero-style v2.2.7即之后的插件很卡，所以我在想，
方案1. 这么多功能能否设置是否开启？比如可以手动把标签分组功能禁用了
方案2. 添加类似“手动刷新”的功能，比如现在统计某个文件夹中条目数量的功能，应该是实时更新的吧，能否添加一个按钮，点击这个按钮之后才会刷新数量，这样的话，可以有效减少卡顿。

谢谢

**Comment by MuiseDestiny** [comment]
都可以禁用，手动刷新有空加

**Comment by Geo123abc** [comment]
> 

嗯嗯，我感觉功能已经很强了，后期可以想办法改善一下流畅度
我前阵子刚换的固态硬盘，然后zotero的流畅度变得很好，今天 zotero-style  从 v1.x.x  版本升级之后，发现卡的不行，现在是回退、停留在 v2.2.6 流畅度和之前一样，

期待改善流畅度

**Comment by MuiseDestiny** [comment]
> 

最近没时间优化，提供彻底关闭按钮吧

**Comment by Geo123abc** [comment]
增加首选项功能设置
你可以关闭你不需要的功能，或者在你的设备上表现欠佳的功能

重启生效 重启生效 重启生效

https://github.com/MuiseDestiny/zotero-style/releases/tag/2.4.0
