### ISSUE TITLE
最新2.4.0版本不显示关系图谱

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [MuiseDestiny/zotero-style#208]
![image](https://user-images.githubusercontent.com/76084234/223106019-b09c8149-3733-40bd-89c2-e47407b93a33.png)
![image](https://user-images.githubusercontent.com/76084234/223106086-122b47ba-eb14-4648-8d20-3000df7229b1.png)

**Comment by MuiseDestiny** [comment]
shift p也调不出来吗

**Comment by MuiseDestiny** [comment]
> 谢谢，可以了，原来还需要shift+P调用出来，我以为可以直接显示的😅😅
好的，但是这个功能一直没优化我以为没人用了都
