### ISSUE TITLE
Zotero Style 2.4.0右键单击“#标签”不显示“列设置”

### ISSUE THREAD

**Issue by ChangzhengNo1** [MuiseDestiny/zotero-style#213]
![image](https://user-images.githubusercontent.com/127208498/223422012-5e105142-285b-4ae0-bcbe-dcacca64913f.png)

**Comment by YvetteYY123** [comment]
刚遇到，不要全屏就可以

**Comment by ChangzhengNo1** [comment]
> 刚遇到，不要全屏就可以

好的谢谢，我这里也确实可以这样解决

**Comment by MuiseDestiny** [comment]
怎么全屏会导致这种情况的，我想试试

**Comment by ChangzhengNo1** [comment]
> 怎么全屏会导致这种情况的，我想试试

刚试了试：
1. 笔记本连接了几个显示器，在笔记本的屏幕全屏下不显示“列设置”（但缩小窗口又有了）；
2. 软件在拓展屏幕全屏功能正常。

软件插件均是最新版，win1022H2

**Comment by YvetteYY123** [comment]
> > 怎么全屏会导致这种情况的，我想试试
> 
> 刚试了试：
> 
> 1. 笔记本连接了几个显示器，在笔记本的屏幕全屏下不显示“列设置”（但缩小窗口又有了）；
> 2. 软件在拓展屏幕全屏功能正常。
> 
> 软件插件均是最新版，win1022H2

我也是连接了显示器

**Comment by MuiseDestiny** [comment]
> > > 怎么全屏会导致这种情况的，我想试试
> > 
> > 
> > 刚试了试：
> > 
> > 1. 笔记本连接了几个显示器，在笔记本的屏幕全屏下不显示“列设置”（但缩小窗口又有了）；
> > 2. 软件在拓展屏幕全屏功能正常。
> > 
> > 软件插件均是最新版，win1022H2
> 
> 我也是连接了显示器

对。好久之前就有反馈哆显示器不出现。
