### ISSUE TITLE
目录列的文献数是否可以设置？

### ISSUE THREAD

**Issue by baileichao** [MuiseDestiny/zotero-style#216]
**Is your feature request related to a problem? Please describe.**
显示每级目录有多少篇文献这个功能很好用啊，心心念念了好久，目前我看这个功能就是前面以灰色数字显示当前分类的文献数，而后面以黑色数字数量的整个目录的文献数，但是像我实际上只需要当前目录的文献数，而当我点击开一个子目录后，再显示对应子目录的文献数，要不然按目前的显示方式，感觉很乱的样子，或者可能想个办法同时显示这两个数据，让其变得更美观一点，或者给一个功能，想显示一个文献数，就一个，想显示两个，就选择两个。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MuiseDestiny** [comment]
> **Is your feature request related to a problem? Please describe.** 显示每级目录有多少篇文献这个功能很好用啊，心心念念了好久，目前我看这个功能就是前面以灰色数字显示当前分类的文献数，而后面以黑色数字数量的整个目录的文献数，但是像我实际上只需要当前目录的文献数，而当我点击开一个子目录后，再显示对应子目录的文献数，要不然按目前的显示方式，感觉很乱的样子，或者可能想个办法同时显示这两个数据，让其变得更美观一点，或者给一个功能，想显示一个文献数，就一个，想显示两个，就选择两个。
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

ipad上是只显示当前，不显示总的，可以去掉总的
