### ISSUE TITLE
如果是中文，会同时显示“等”和et al

### ISSUE THREAD

**Issue by kimdumping** [MuiseDestiny/zotero-style#222]
由于未更改`Creator`的列设置，导致的等和et al同时出现。

对作者进行列设置
Format里填入：`${firstCreator}`
就显示正常了

**Comment by MuiseDestiny** [comment]
请清空提示内容输入你的问题

**Comment by leichaoL** [comment]
@MuiseDestiny 目前无论作者有几个或者中英文论文，都会直接在第一作者后面加上et al.。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/224011641-50108181-98cf-4d75-a284-d06f5a56ffc6.png)
默认设置是这样的，需要列设置改一下

![image](https://user-images.githubusercontent.com/51939531/224011774-4d08a651-c2a6-4207-8029-36c0976252ff.png)


> @MuiseDestiny 目前无论作者有几个或者中英文论文，都会直接在第一作者后面加上et al.。

**Comment by MuiseDestiny** [comment]
如果没有更改显示作者位数的需求，可以在首选项关闭这个功能的
