### ISSUE TITLE
nested tag: support multi-selection for AND query 多选功能

### ISSUE THREAD

**Issue by mangost** [MuiseDestiny/zotero-style#226]
Zotero原装的tag支持多选tags，多选的tags构成AND逻辑。

Style的nested tag支持选择一个任意层级的tag，例如，如果存在tags r/a 和 r/b，则可以选择r，构成OR逻辑（r/a OR r/b）。

这两个功能都很好用。我建议在nested tag中实现多选tag的功能，并且多选的tag之间是AND逻辑（例如, 多选x和r实现 x AND (r/a OR r/b) ）。

这样能实现更强大的查询功能，做到快速定位，也可以一定程度替代用excel管理文献，方便综述撰写。

谢谢

---

Zotero's original tags support multi-selection tags, and multi-selection tags is combined by AND.

Style's nested tag supports selection of a tag at any level. For example, if there are tags r/a and r/b, you can select r to combine these tags by AND (r/a OR r/b).

Both are useful. I suggest to implement the function of multi-select tags for the nested tags, and combine selected tags by AND, eg, selection of x and r =  x AND (r/a OR r/b). 

In this way, it can achieve more powerful query function, achieve rapid positioning, and can also replace the use of excel to manage documents to a certain extent, which is convenient for summary writing.

Thanks

**Comment by MuiseDestiny** [comment]
嵌套标签是一个很具体的东西，比如A/B/C如果你想看C选C即可。如果你想看所有以A开头的，选A即可。这里的选A就是多选。

> 如果存在tags r/a 和 r/b，则可以选择r，构成OR逻辑（r/a OR r/b）。

插件本身就是你所描述的逻辑

**Comment by mangost** [comment]
我想增加的是AND逻辑。

比如，同时有 x 和 r/a，选x和r实现 x AND r/a。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/234559109-e9a07950-b4f7-4ffb-89f7-d4b9a906086b.png)

**Comment by Raphael-Hao** [comment]
好像只可以在第一级的nested tag上支持AND操作，不同层级或者非第一级的nested tag不支持AND操作
