### ISSUE TITLE
【ChatGPT】交互体验优化建议

### ISSUE THREAD

**Issue by mtuwei** [MuiseDestiny/zotero-style#233]
您好！

首先感谢开发了这款很实用的插件，特别是引入了【ChatGPT】。

请问在后续插件完善过程中，对于【ChatGPT】这一功能，可否类实现类似【沙拉查词/OpenAI translator】等浏览器插件的【划词翻译】交互体验（如下图示），谢谢。

![image](https://user-images.githubusercontent.com/32591958/224368501-1eaafc86-0098-4adf-bcb1-ca3dca6220cc.png)

**Comment by MuiseDestiny** [comment]
翻译这一块很多软件在做，zotero也有翻译插件，并且加入了chatGPT。所以这一块偏离style，且有其他工具做了。style做出来，不会比他们好。

**Comment by mtuwei** [comment]
> 翻译这一块很多软件在做，zotero也有翻译插件，并且加入了chatGPT。所以这一块偏离style，且有其他工具做了。style做出来，不会比他们好。

了解了，谢谢答复。
