### ISSUE TITLE
中文有的期刊无法获取到期刊级别、分级等信息。

### ISSUE THREAD

**Issue by baileichao** [MuiseDestiny/zotero-style#236]
例如我的文献当中有一个“清华大学学院（自然科学版）”的论文，该期刊是“北大核心、CA、JST、EI、CSCD、WJCI”，但是插件里面的期刊标签列，一个内容都没有显示，我是在设置里面显示了cscd和EI的。下面的武汉大学学报，同样是EI和cscd，也是没有显示出来。
![xuanxuan_20230312_131621](https://user-images.githubusercontent.com/57392772/224525803-c7dd398f-d4a5-453e-8c87-53057952bffc.png)

**Comment by MuiseDestiny** [comment]
如果都没显示出来可以考虑是不是字段填错了，请参考readme填

**Comment by baileichao** [comment]
这个应该不是字段错误问题，因为你看看上面贴的图，比如那个地球信息科学学报，就是EI，它就显示出来了，但是下面两个框出来的也是，确没有显示出来，现在想来是不是这个期刊标签链接的数据源的问题呢？

**Comment by baileichao** [comment]
如果是数据源的问题，那就不知道是不是换一个数据源要好一些呢？

**Comment by MuiseDestiny** [comment]
> 如果是数据源的问题，那就不知道是不是换一个数据源要好一些呢？

欢迎制作这种数据源
