### ISSUE TITLE
目录文献数量显示问题

### ISSUE THREAD

**Issue by baileichao** [MuiseDestiny/zotero-style#237]
如图，我这一级目录是地质灾害，但是因为这个一级目录里面没有文献，所以后面的文献数量显示为空，而它下面有两个二组上当，因为这两个二级目录里面有文献，所以的是6和5，但是如果我把这个一级目录一折叠的话，就无法看到二级目录里面有多少文献了，因为折叠后它只显示一级目录的文献数量，为空，感觉这样子好像也不对，我自己感觉一级目录应该显示包括一级目录在内的所有级别目录的文献数量，而不仅单单是显示它一个级别的，如果二级目录没有文献，但是二级对应的三级目录下面有文献，那二级目录也应该显示包括二级和三级目录的总文献量，以此类推。这样子才合理。 
![image](https://user-images.githubusercontent.com/57392772/224525909-f35b5b53-aedd-4c77-9331-12f228ae6e2f.png)
![xuanxuan_20230312_132153](https://user-images.githubusercontent.com/57392772/224526055-008e1727-fa12-4567-87fe-06f9ef960f2d.png)

**Comment by MuiseDestiny** [comment]
参考ipad上的显示逻辑。之前是可以显示自己和所有子孙的。有人提出那样不美观。所以现在跟ipad一致，只显示它里面有多少。

**Comment by LuisWangYubin** [comment]
> 参考ipad上的显示逻辑。之前是可以显示自己和所有子孙的。有人提出那样不美观。所以现在跟ipad一致，只显示它里面有多少。

您好，可不可以保留这两种显示，然后让用户自己选择，应该也有很多人喜欢累加的那种。

**Comment by MuiseDestiny** [comment]
> > 参考ipad上的显示逻辑。之前是可以显示自己和所有子孙的。有人提出那样不美观。所以现在跟ipad一致，只显示它里面有多少。
> 
> 您好，可不可以保留这两种显示，然后让用户自己选择，应该也有很多人喜欢累加的那种。

可以的

**Comment by MuiseDestiny** [comment]
但不知道设置放在哪里合适

**Comment by baileichao** [comment]
正如[LuisWangYubin](https://github.com/LuisWangYubin)所说，我是喜欢这种父目录可以显示子目录所有文献量的形式的。

**Comment by baileichao** [comment]
前面版本是对的，父目录也会显示子目录里面的文献数量，最近发现又不显示了，Zotero6，style2.6.7

**Comment by MuiseDestiny** [comment]
> 前面版本是对的，父目录也会显示子目录里面的文献数量，最近发现又不显示了，Zotero6，style2.6.7

取决于你的zotero的设置吧

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/7c3c9931-8aa1-4c85-b92d-6a968ef3962a)

**Comment by baileichao** [comment]
这里是设置了的，但是目录显示还是只显示父目录的文献数量。
![image](https://github.com/MuiseDestiny/zotero-style/assets/57392772/a2be0705-c7a1-4393-a4fa-f5b3ecbcd2e7)
如上图里面的“空间分析”目录，里面有子目录，但是父目录并不显示子目录的数量。
