### ISSUE TITLE
关系图谱同年同姓的两个条目会被错误归为一个点

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [MuiseDestiny/zotero-style#239]
关系图谱同年同姓但不同名字的两个条目会被错误归为一个点，建议使用出版年+姓+**名**来区别

**Comment by MuiseDestiny** [comment]
对，有这个bug，因为ob网页版用的链接（比如https://help.obsidian.md/Obsidian/Index）既做名字又做id。但是到了zotero里用作者年份其实是不太合适的。

如果自己绘制，可以解决这个问题。只是目前obsidian比较流畅。
像connectedpapers，svg的在zotero里很卡。
![image](https://user-images.githubusercontent.com/51939531/224536880-4cf90491-619c-4f04-a4ed-001454ea83a2.png)

**Comment by MuiseDestiny** [comment]
> 不好意思，还没用过ob，不太懂，是“插件采用了ob网页版自动绘制的关系图谱，作者只能用姓，不能用姓+名”的意思嘛

能的，有空优化下
