### ISSUE TITLE
响应时间过慢，运行过程中跳转文件夹或搜索直接全部空白

### ISSUE THREAD

**Issue by swenqing** [MuiseDestiny/zotero-style#240]
![image](https://user-images.githubusercontent.com/37140550/224599718-be893508-8a24-4cab-9531-1319b3a61430.png)

**Comment by MuiseDestiny** [comment]
插件冲突了可能

**Comment by Bioerjzy** [comment]
> 插件冲突了可能

大佬，我遇到了同样的问题，然后我关了所有的插件，同样是空白的。
![image](https://user-images.githubusercontent.com/69882352/224624187-41dfadfb-2c10-4fc5-831d-2a55b15b4b5e.png)

**Comment by compegant** [comment]
刚刚更新的一波，也是出现空白，吓死我了。不知道是和哪个插件冲突了，排查不出来，只有把zotero style禁用后，重启zotero才搞定，这个是我的插件列表。
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/39365278/224624956-973ce4d2-39a6-4441-a56b-2b175275cc49.png">

**Comment by MuiseDestiny** [comment]
重新下载安装最新版

**Comment by MuiseDestiny** [comment]
> 刚刚更新的一波，也是出现空白，吓死我了。不知道是和哪个插件冲突了，排查不出来，只有把zotero style禁用后，重启zotero才搞定，这个是我的插件列表。 <img alt="image" width="1194" src="https://user-images.githubusercontent.com/39365278/224624956-973ce4d2-39a6-4441-a56b-2b175275cc49.png">

哈哈，我的原因。少写了一句话

**Comment by LHH-Ghost** [comment]
> 重新下载安装最新版

大佬你好，请问什么时候能更新好呢？

**Comment by compegant** [comment]
> 哈哈，我的原因。少写了一句话

又安装了新版本，已解决。🤣要是没看到之前已打开的文件预览界面，确定数据还在的话，估计已经哭晕在厕所了。

**Comment by MuiseDestiny** [comment]
> > 哈哈，我的原因。少写了一句话
> 
> 又安装了新版本，已解决。🤣要是没看到之前已打开的文件预览界面，确定数据还在的话，估计已经哭晕在厕所了。

没有的，人任何插件都不会清空你数据，只会在渲染上有点问题的
