### ISSUE TITLE
期刊标签update错误

### ISSUE THREAD

**Issue by Molisa95** [MuiseDestiny/zotero-style#250]
以COR期刊为例，期刊标签是正确的，在期刊位置点击标签，显示更新后，变为了空白
点击前：
![image](https://user-images.githubusercontent.com/52652817/224939720-d9ca111c-9d65-4a7a-8b3c-7e49740ebaf3.png)
点击后
![image](https://user-images.githubusercontent.com/52652817/224939777-c083d016-8b1b-41af-9c4d-c774e35f11c3.png)

**Comment by MuiseDestiny** [comment]
还有这种事

**Comment by Molisa95** [comment]
> 还有这种事

是的，就很神奇，这个期刊是“COMPUTERS & OPERATIONS RESEARCH”

10.1016/j.cor.2013.12.003
大佬，可以用这个doi试一下

其他很多期刊用起来没问题，一点击就更新为最新的了，看是否要设计一个防止查询结果为空时删除原标签的策略之类的？

**Comment by wsy0810** [comment]
我也出现了期刊标签错误的问题，Computers & Education，更新之前标签正确，更新后只显示JCI，其他分区都不显示了

**Comment by MuiseDestiny** [comment]
> Computers & Education，

需要更新，有一个版本不登陆只能获取部分标签

**Comment by wsy0810** [comment]
> > Computers & Education，
> 
> 需要更新，有一个版本不登陆只能获取部分标签

已经是最新版。
我把&改成了and就能正常获取所有标签了，不知道是怎么回事

**Comment by MuiseDestiny** [comment]
刚刚修复了
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.4.5

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/225198371-35f1f6ce-4e25-4bd8-ac6e-4f6f50b6f49f.png)

是bug，感谢反馈
