### ISSUE TITLE
插件功能菜单

### ISSUE THREAD

**Issue by Saunak626** [MuiseDestiny/zotero-style#252]
![image](https://user-images.githubusercontent.com/34276206/224950020-81bed715-1b2c-4973-9f7f-77fa755fa3e5.png)
目前这个选项似乎是要重启才能生效，并且在无法在zotero内进行更新

**Comment by MuiseDestiny** [comment]
重启生效，是这样的。

**Comment by MuiseDestiny** [comment]
因为是彻底关闭，只能重启时候不加载它才能彻底关闭。正在运行的东西，突然关闭有风险。
