### ISSUE TITLE
视图组更新失败和更换列位置后无法进行列设置的bug

### ISSUE THREAD

**Issue by Lyn6969** [MuiseDestiny/zotero-style#255]
**Describe the bug**
1. 视图组更新失败
我设置了标签视图用来显示标签， 然后我按照readme的说明，长按标签视图出现更新界面（图1），点击update之后好像我的标签视图并没有更新，单击最上面的视图切换按钮，又会切换到我最开始新建这个视图组时候的的样式。是我哪里操作不对吗？
2. 无法进行列设置
我添加了期刊标签的列，我把期刊标签放在了最右面，但是单击右键之后没有列设置的按钮，需要点击一下恢复列顺序，然后才会出现列设置，设置好之后才能恢复原来的位置。

**Expected behavior**
1. 能够正常更新视图组
2. 新添加的列无论在哪里都可以进行列设置。

**Screenshots**
图1
![image](https://user-images.githubusercontent.com/42564665/225202305-99fa375f-fc5b-4dd9-b2ce-99b16d851dea.png)
图2
![image](https://user-images.githubusercontent.com/42564665/225202618-d604b90f-9752-4b75-9034-b470f52b8f53.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Version （zotero）:6.0.22
 - Version(zotero-style): 1.0.11
**Smartphone (please complete the following information):**
 - Version [
**Additional context**

**Comment by Lyn6969** [comment]
我刚刚发现了一个更神奇的事情，因为我有竖接一个分屏，当我没有把zotero全屏的时候，在期刊标签上单击右键会在主屏幕上显示菜单，此时是正常的（有列设置按钮），如下图所示：
![image](https://user-images.githubusercontent.com/42564665/225203620-88d680f4-9adb-4959-81f1-b5625da458d5.png)
但是当我把zotero全屏的时候，在期刊标签上单击右键会在我的竖分屏上显示菜单，此时就缺少了列设置按钮：
![image](https://user-images.githubusercontent.com/42564665/225203772-203db6d9-a057-49cc-b535-1a97863fa8b5.png)
这也太离奇了

**Comment by Lyn6969** [comment]
抱歉，版本写错了，style版本是2.4.5

**Comment by MuiseDestiny** [comment]
分屏没有列设置是正常已知bug

**Comment by MuiseDestiny** [comment]
新的视图需要点击新增视图按钮，不需要更新

**Comment by Lyn6969** [comment]
> 分屏没有列设置是正常已知bug

好的，知道了，谢谢您

**Comment by Lyn6969** [comment]
> 新的视图需要点击新增视图按钮，不需要更新

我是想把现在的视图更新一下，也需要新增吗

**Comment by MuiseDestiny** [comment]
更新是为了修改名称和位置。如果你更新的是当前视图会更新列顺序列宽。你在A视图去更新B，B该显示什么还是显示什么。

**Comment by Lyn6969** [comment]
> 更新是为了修改名称和位置。如果你更新的是当前视图会更新列顺序列宽。你在A视图去更新B，B该显示什么还是显示什么。

我懂了，意思是如果新添加了内容（比如新添加了一列），只能新增视图对吧？

**Comment by MuiseDestiny** [comment]
> > 更新是为了修改名称和位置。如果你更新的是当前视图会更新列顺序列宽。你在A视图去更新B，B该显示什么还是显示什么。
> 
> 我懂了，意思是如果新添加了内容（比如新添加了一列），只能新增视图对吧？

对的。更新只更新列顺序，宽度，名称。

**Comment by Lyn6969** [comment]
好的，抱歉，是我理解错更新视图的意思了，只是调整顺序和列宽。但是我觉得这个可不可以作为一个新的功能呢？因为不断有新的列新的功能出来，如果能直接更新就更好了，您有这方面的打算吗？

**Comment by MuiseDestiny** [comment]
> 好的，抱歉，是我理解错更新视图的意思了，只是调整顺序和列宽。但是我觉得这个可不可以作为一个新的功能呢？因为不断有新的列新的功能出来，如果能直接更新就更好了，您有这方面的打算吗？

可以滴。

**Comment by Lyn6969** [comment]
> > 好的，抱歉，是我理解错更新视图的意思了，只是调整顺序和列宽。但是我觉得这个可不可以作为一个新的功能呢？因为不断有新的列新的功能出来，如果能直接更新就更好了，您有这方面的打算吗？
> 
> 可以滴。

好的，期待！谢谢您的回复！
