### ISSUE TITLE
怎么之前设置的视图组全没了，现在用起来特别不方便

### ISSUE THREAD

**Issue by YYXC1993** [MuiseDestiny/zotero-style#256]
怎么之前设置的视图组全没了，现在用起来特别不方便了，我都习惯了

**Comment by YYXC1993** [comment]
我发现我今天给老板的2.4.2是可以的，但是我的电脑，目前只能退回到2.3.3才有视图组

**Comment by MuiseDestiny** [comment]
更新会写更新了什么，如果用一个版本稳定，可以选择不更新。
