### ISSUE TITLE
关系视图怎么切换分类

### ISSUE THREAD

**Issue by icemoon** [MuiseDestiny/zotero-style#258]
### Bug描述
平台：Mac
Zotero版本：6.0.23
zotero-style版本：2.4.5

没找到切换视图分类的方法，一直都只显示默认视图
<img width="699" alt="image" src="https://user-images.githubusercontent.com/4971369/225374654-f1913cb2-9e1b-46cf-9828-a471b3f011b9.png">

**Comment by MuiseDestiny** [comment]
![225193206-d1f2de54-0e02-4ae3-b543-dc415bbbea69](https://user-images.githubusercontent.com/51939531/225465488-b1e33bd4-5ef8-4b45-9b5a-9fb3ee5101d3.png)

最下面几个点，跟视图组差不多

**Comment by MuiseDestiny** [comment]
鼠标靠近才会显示，不然自动隐藏
