### ISSUE TITLE
中文期刊的期刊标签无内容

### ISSUE THREAD

**Issue by buruquzibi** [MuiseDestiny/zotero-style#263]
不好意思打扰作者了，我发现我的zotero中的中文文献期刊标签没有内容出现，但是英文期刊显示正常，我已经对照readme，确认自己的列设置填写准确。而且同样一篇文章，我在google scholar搜索后，easyscholar可以显示出期刊标签，我也更新了最新发布的插件，也没有解决，不知道问题出在哪里。
列设置截图：
![image](https://user-images.githubusercontent.com/49910441/225674695-b2ca7ecf-852e-43f2-8593-4d85a3d81de0.png)
zotero显示：
![image](https://user-images.githubusercontent.com/49910441/225675493-15f1a1bf-7487-450f-9b65-4e1cae04a0b9.png)
easyscholar查询某一篇中文文献的结果：
![image](https://user-images.githubusercontent.com/49910441/225675755-a5a621e2-85e1-4f50-a266-6dc73dba7033.png)

是不是因为我使用了Jasminum插件，自动根据文件名从知网上抓取信息了，导致期刊标签无法显示？
感谢作者百忙之中抽空答复，谢谢！

**Comment by MuiseDestiny** [comment]
稍等，我试试你截图的文献

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/225787949-d38b34c6-ecfe-466d-ba05-7e441a7c2032.png)

已修复，下载这个-1试试

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/225787984-09126548-8b56-4871-b095-a8c9b5d0367a.png)

**Comment by buruquzibi** [comment]
我下载了最新的插件，问题已解决。感谢作者百忙之中修复问题，感谢！
