### ISSUE TITLE
关系图谱显示的是style的graph view

### ISSUE THREAD

**Issue by Gninuhs** [MuiseDestiny/zotero-style#264]
今天打开zotero的时候关系图谱显示变成了这样，点击每个节点会跳转到相应的网页链接，请问这应该怎么解决呀？
（关联文献什么的都还在 只是图谱显示不对劲）

![c1abc6eb97324a42cdd22d3c4c99e25](https://user-images.githubusercontent.com/128078687/225706837-35bf7cba-cb67-4153-9ded-d38f48eeb0f0.png)

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/225781546-2dfb0f04-02dc-4b31-9bd0-fb0706acf9a0.png)
最下面切换视图

**Comment by MuiseDestiny** [comment]
对的，如楼上所说。还没来得及更新readme，有时间更新下它哈。

**Comment by zhangwendaa** [comment]
> 对的，如楼上所说。还没来得及更新readme，有时间更新下它哈。

请问如何更新readme

**Comment by MuiseDestiny** [comment]
> > 对的，如楼上所说。还没来得及更新readme，有时间更新下它哈。
> 
> 请问如何更新readme

fork后，在自己的仓库修改然后pull request就可以了。欢迎贡献～

**Comment by 1067237855** [comment]
> 请问如何更新readme

可以帮大佬跟新一下，估计大佬会很欢迎，哈哈
![image](https://user-images.githubusercontent.com/104330036/225793894-ca4e4f5c-6a11-4798-b0f5-a51588bce734.png)

**Comment by Gninuhs** [comment]
太感谢啦！
