### ISSUE TITLE
关系图谱一直显示默认图谱，双击刷新无效

### ISSUE THREAD

**Issue by xchyyb** [MuiseDestiny/zotero-style#268]
![image](https://user-images.githubusercontent.com/78303344/225811887-2c7cda20-d7fb-4494-808d-bb5cf1218393.png)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/266

**Comment by baskgithub** [comment]
这是新版本的特性，请把鼠标🖱移动到靠近下边缘，就可以看到好几种关系图谱的选项了。平时是隐藏的。

**Comment by xchyyb** [comment]
好的，已解决，谢谢
