### ISSUE TITLE
只要执行知网助手，zotero首选项界面就会立即出现bug，多个插件界面包括zotero-style消失

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [MuiseDestiny/zotero-style#271]
![image](https://user-images.githubusercontent.com/76084234/225827994-f032dce4-f679-4e90-b4dc-941db5865b0a.png)
![image](https://user-images.githubusercontent.com/76084234/225828041-5057712f-1a75-4043-b60c-040bc653d0f7.png)

**Comment by MuiseDestiny** [comment]
还真是的，神奇的

**Comment by MuiseDestiny** [comment]
> 又试了一下，使用绿青蛙插件的更新条目元数据，一样可以触发这个bug

好细节，怎么发现的啊
