### ISSUE TITLE
鼠标右键条目，不出现功能框

### ISSUE THREAD

**Issue by Elodie-0117** [MuiseDestiny/zotero-style#274]
鼠标右键条目，无论多少次都没有反应，不出现功能框：
![image](https://user-images.githubusercontent.com/126692797/225877634-db64ca97-9c67-4c7d-b031-162e27b31a95.png)

调成窗口整理模式后：
![image](https://user-images.githubusercontent.com/126692797/225877894-efbe582d-b177-458d-b2d2-6a88b0a01f22.png)

再回来，功能窗口才会延迟出现：
![image](https://user-images.githubusercontent.com/126692797/225877806-fdee59aa-d9f3-4e2c-bd36-82415c55e833.png)

不知道除了我还有人遇到这种情况吗？是更新这个插件的问题，还是我自身电脑哪里的问题？感谢知情人告知

**Comment by MuiseDestiny** [comment]
禁用style再试试呢

**Comment by Elodie-0117** [comment]
> 禁用style再试试呢

禁用style后，再重启zotero， 就没有这个问题了，再启动style，这个问题也没了。
之前重启zotero，问题也还在，应该就是禁用style再启动style， 这个问题就消失了。

**Comment by zhuyue0927** [comment]
还是没有解决，请问有没有大佬帮忙修复一下
