### ISSUE TITLE
标注的标签没能显示在左下角，故无法通过标签直接定位标注

### ISSUE THREAD

**Issue by leichaoL** [MuiseDestiny/zotero-style#280]
### Bug描述
根据[B站演示视频](https://www.bilibili.com/video/BV15V4y19711/)，我在pdf文件中添加标注：
![image](https://user-images.githubusercontent.com/66906588/226151432-43e35b46-bb4b-4c8f-bca2-a604afa7a66c.png)

但是无法显示在主界面左下角nested tags中
![image](https://user-images.githubusercontent.com/66906588/226151449-57ac0bd6-98d6-4410-bba3-6db2e61f75d8.png)
`#测试`，`#测试1`，`#测试2`均为条目标签，可以正常显示。但是标注中新增的嵌套标签`#测试1/测试子集`和`#测试3`均没能显示。

   参考[#232](https://github.com/MuiseDestiny/zotero-style/issues/232)重启了插件和Zotero，没能解决问题。我的插件版本一直跟着GitHub更新，一直存在该问题。

**Comment by leichaoL** [comment]
[#232 ](https://github.com/MuiseDestiny/zotero-style/issues/232)

**Comment by MuiseDestiny** [comment]
#标签的match怎么填写的

**Comment by leichaoL** [comment]
> 

填写的`#`

**Comment by leichaoL** [comment]
> #标签的match怎么填写的

填写的`#`
![image](https://user-images.githubusercontent.com/66906588/226152145-799e6b7a-0115-49cc-a3e6-c26eaba174ed.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/226152158-eb5aeff3-c8f8-490d-98e7-94e4aae2f6d1.png)

在最新版发布，安装这试试

**Comment by leichaoL** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/226152158-eb5aeff3-c8f8-490d-98e7-94e4aae2f6d1.png)
> 
> 在最新版发布，安装这试试

还是无法显示，删除了之前的插件重启Zotero后再安装的test版本。也多次重启过Zotero。我可以给你提供什么让你方便定位Bug吗？

**Comment by MuiseDestiny** [comment]
> > ![image](https://user-images.githubusercontent.com/51939531/226152158-eb5aeff3-c8f8-490d-98e7-94e4aae2f6d1.png)
> > 在最新版发布，安装这试试
> 
> 还是无法显示，删除了之前的插件重启Zotero后再安装的test版本。也多次重启过Zotero。我可以给你提供什么让你方便定位Bug吗？

你可以打开错误日志，然后在pdf中做一个标注，增加一个嵌套标签，然后把错误信息发到这里

**Comment by MuiseDestiny** [comment]
你也可以禁用其它所有插件，除了style，再试试这个功能是否正常。如果还不正常，就是style的问题了（优先试一下中这个）。

**Comment by leichaoL** [comment]
禁用了其他所有插件，仍然不行。启用日志之后，我不确定具体问题具体在哪，所以我把全部日志附在下面。麻烦大佬了。
[Debug Output.txt](https://github.com/MuiseDestiny/zotero-style/files/11010532/Debug.Output.txt)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/227170243-bc285fe5-0896-4323-9ec3-12e9712ed7eb.png)
