### ISSUE TITLE
最近几个版本的插件，按shift+P功能框是空的？

### ISSUE THREAD

**Issue by Elodie-0117** [MuiseDestiny/zotero-style#286]
好像是从上个星期开始的最近几个插件更新后，按shift+P功能框是空的？
![image](https://user-images.githubusercontent.com/126692797/226380545-9c059113-161a-4e78-86a8-db0008aaae97.png)

试过卸载重装插件，退出zotero重启，电脑重启，都没有用

**Comment by MuiseDestiny** [comment]
有ref插件吗，把它禁用重启试试呢

**Comment by Elodie-0117** [comment]
> 有ref插件吗，把它禁用重启试试呢

嗯 reference禁用重启功能框出现啦
