### ISSUE TITLE
文档中的嵌套标签不能在嵌套标签中显示

### ISSUE THREAD

**Issue by youyouhdhd** [MuiseDestiny/zotero-style#293]
### Bug描述
在文档中选中某句话加#标签无法在嵌套标签列表显示
![Clip_20230322_170336](https://user-images.githubusercontent.com/54936458/226852977-a898faca-4571-407c-90f9-127113c6e2cb.png)

![Clip_20230322_170411](https://user-images.githubusercontent.com/54936458/226853277-480ac739-5a2b-431d-ba10-fb04b0c125fd.png)

**Comment by leichaoL** [comment]
我也有这个问题[ #280](https://github.com/MuiseDestiny/zotero-style/issues/280) ，你先试试作者给我说的解决方案（虽然没能解决我的问题

**Comment by MuiseDestiny** [comment]
能录个视频吗。太长可以上传临时网盘https://musetransfer.com/

**Comment by youyouhdhd** [comment]
https://musetransfer.com/s/y2bi3r6n2 请点击链接获取《无主题 - 窗口 2023-3-23 14-10-33.mp4》, 有效期至3月30日
已经上传啦，大佬看一下

**Comment by youyouhdhd** [comment]
> 能录个视频吗。太长可以上传临时网盘能录个视频吗。太长可以上传临时网盘能录个视频吗。太长可以上传临时网盘[https://musetransfer.com/https://musetransfer.com/https://musetransfer.com/](https://musetransfer.com/)

已经上传啦，大佬看一下
https://musetransfer.com/s/y2bi3r6n2 请点击链接获取《无主题 - 窗口 2023-3-23 14-10-33.mp4》, 有效期至3月30日

**Comment by MuiseDestiny** [comment]
好的，收到啦

**Comment by leichaoL** [comment]
> 

@MuiseDestiny 我可以，怎么远程呢

**Comment by MuiseDestiny** [comment]
todesk控制码发我邮箱吧，muisedestiny@gmail.com
