### ISSUE TITLE
进度json同步失败

### ISSUE THREAD

**Issue by zhaofangguo** [MuiseDestiny/zotero-style#295]
### Bug描述
在一台ubuntu18.04的电脑上设置好json文件本地存储，并使用坚果云进行同步。在另一台win10电脑上设置本地存储文件为坚果云中存储的json文件，打开zotero之后并没有显示和ubuntu电脑相同的进度，而是原本win10电脑自身的阅读进度。
json文件内容：
{"1":{},"4":{"readingTime":{"page":11,"data":{"0":10}}},"5":{"readingTime":{"page":16,"data":{"0":40,"1":1140,"2":870}}},"6":{"readingTime":{"page":11,"data":{"2":280,"3":490,"4":30}}},"8":{"readingTime":{"page":9,"data":{"0":10}}},"9":{},"10":{},"11":{},"12":{},"13":{"readingTime":{"page":3,"data":{"2":10}}},"14":{"readingTime":{"page":16,"data":{"0":10,"6":10,"14":10,"15":10}}},"15":{},"16":{"readingTime":{"page":19,"data":{"0":20,"1":20,"2":10,"3":10,"4":140,"5":20}}},"17":{},"18":{"readingTime":{"page":23,"data":{"0":630,"2":730,"3":30,"4":240,"5":70,"6":440,"7":30,"8":240,"9":80,"10":820,"11":500,"12":1070,"13":360,"15":10,"16":20,"17":80,"18":140,"22":20}}},"19":{},"20":{"readingTime":{"page":248,"data":{"0":10,"1":10}}},"21":{},"22":{},"23":{},"24":{},"25":{},"26":{},"27":{},"28":{"readingTime":{"page":14,"data":{"0":40,"1":10,"2":10,"3":60,"6":10,"8":10,"9":30,"10":10,"11":10}}},"29":{"readingTime":{"page":8,"data":{"0":560,"1":540,"2":1520,"3":1390,"4":670,"6":10,"7":30}}},"30":{},"31":{},"32":{},"33":{},"34":{"readingTime":{"page":8,"data":{"0":10,"2":10,"6":10}}},"35":{},"36":{"readingTime":{"page":8,"data":{"0":590,"1":780,"2":1990,"3":1300,"4":190,"7":10}}},"37":{"readingTime":{"page":9,"data":{"0":10}}},"38":{"readingTime":{"page":7,"data":{"0":90}}},"39":{"readingTime":{"page":30,"data":{"0":10,"1":10,"4":10,"5":10,"7":10,"15":10}}},"40":{"readingTime":{"page":7,"data":{"0":10}}},"41":{"readingTime":{"page":17,"data":{"0":120,"3":330,"4":70,"15":10}}},"42":{"readingTime":{"page":18,"data":{"0":530,"1":1420,"2":1630,"3":3080,"4":1070,"5":1320,"6":730,"7":950,"8":20,"9":20,"10":110,"14":10,"15":40,"16":80}}},"43":{"readingTime":{"page":17,"data":{"0":70,"1":10,"2":10,"12":10,"13":10,"16":10}}},"44":{},"45":{"readingTime":{"page":8,"data":{"0":620,"1":500,"2":300,"3":630,"4":410,"5":40,"6":50}}},"46":{},"47":{"readingTime":{"page":7,"data":{"0":470,"1":750,"2":500,"3":200,"4":30,"5":190}}},"48":{},"49":{},"50":{"readingTime":{"page":20,"data":{"0":20,"2":10,"4":120,"5":780,"6":1110,"7":890,"8":1160,"9":1060,"10":810,"11":780,"12":460,"13":140,"14":740,"15":40,"16":140,"19":10}}},"51":{},"52":{},"53":{},"54":{"readingTime":{"page":12,"data":{"0":270,"1":510,"2":1100,"3":960,"4":590,"5":540,"6":50,"7":20,"8":20,"9":20,"10":10}}},"55":{"readingTime":{"page":16,"data":{"0":10,"6":10}}},"56":{"readingTime":{"page":12,"data":{"0":160,"1":970,"2":1010,"3":630,"4":1360,"5":100,"7":10,"9":10,"11":10}}},"63":{},"64":{},"84":{},"96":{},"102":{},"107":{},"108":{},"109":{},"110":{},"112":{},"125":{},"126":{},"132":{},"135":{},"139":{},"147":{},"152":{},"153":{},"156":{},"157":{},"158":{},"171":{},"174":{"readingTime":{"page":10,"data":{"0":10,"1":10}}},"175":{},"178":{},"192":{},"196":{},"200":{},"212":{},"220":{},"223":{},"244":{},"294":{"readingTime":{"page":20,"data":{"0":10,"2":10,"3":10}}},"295":{},"301":{},"302":{"readingTime":{"page":36,"data":{"0":10,"2":10}}},"314":{"readingTime":{"page":10,"data":{"0":30,"2":30,"3":10,"4":10,"6":10}}},"322":{},"339":{},"340":{},"341":{},"342":{},"343":{},"344":{},"345":{},"346":{"readingTime":{"page":20,"data":{"0":10}}},"347":{},"351":{},"352":{},"353":{},"354":{},"355":{},"357":{},"358":{},"359":{},"360":{"readingTime":{"page":6,"data":{"0":20,"1":10}}},"361":{},"362":{},"363":{},"364":{},"365":{},"366":{},"367":{},"368":{},"369":{},"370":{},"371":{},"372":{},"373":{},"374":{"readingTime":{"page":3,"data":{"0":10}}},"375":{},"376":{},"381":{},"382":{},"383":{},"384":{},"385":{},"386":{},"388":{"readingTime":{"page":19,"data":{"0":20}}},"389":{},"390":{},"391":{},"392":{},"394":{},"404":{"readingTime":{"page":8,"data":{"1":10,"3":70,"4":170}}},"407":{},"408":{},"409":{},"411":{},"412":{},"413":{},"414":{},"415":{},"421":{"readingTime":{"page":14,"data":{"0":40}}},"422":{},"423":{},"424":{},"425":{},"426":{},"436":{},"442":{},"443":{},"444":{},"445":{},"449":{},"450":{},"451":{},"452":{},"453":{},"454":{},"455":{},"456":{},"457":{},"458":{},"476":{},"479":{},"487":{},"488":{},"489":{},"490":{},"500":{},"501":{},"502":{},"628":{},"630":{},"632":{},"633":{},"635":{},"637":{},"638":{},"639":{},"640":{},"641":{},"643":{},"644":{},"645":{},"695":{},"696":{"readingTime":{"page":8,"data":{"0":20,"1":30,"4":100,"5":280,"6":10,"7":30}}},"697":{"readingTime":{"page":17,"data":{"0":30,"1":10,"5":10,"10":10,"16":10}}},"698":{},"699":{},"726":{},"727":{"readingTime":{"page":20,"data":{"0":20,"2":10,"11":10,"12":10,"13":10,"14":10,"18":10}}},"734":{},"742":{"readingTime":{"page":8,"data":{"0":810,"1":890,"2":210,"3":580,"4":60}}},"748":{},"758":{},"760":{},"773":{},"792":{"readingTime":{"page":18,"data":{"0":10}}},"793":{},"794":{},"796":{},"798":{},"799":{},"800":{},"827":{},"828":{},"830":{"readingTime":{"page":17,"data":{"0":10}}},"831":{},"832":{},"839":{"readingTime":{"page":14,"data":{"0":10}}},"840":{},"842":{},"843":{},"844":{},"845":{},"846":{},"847":{},"849":{"readingTime":{"page":15,"data":{"0":950,"1":580,"2":1230,"3":350,"4":220,"5":140,"7":20,"8":60,"9":630,"10":650,"11":330,"12":50,"13":10}}},"850":{},"851":{},"852":{},"853":{},"854":{},"856":{},"857":{},"858":{},"864":{},"893":{},"919":{},"920":{},"921":{"readingTime":{"page":8,"data":{"0":20,"3":10,"4":10}}},"922":{"readingTime":{"page":7,"data":{"0":20,"2":10,"3":10,"4":10,"5":20}}},"926":{},"927":{},"1144":{}}

win10电脑zotero设置：
![image](https://user-images.githubusercontent.com/64003943/226981138-8d4fc969-2644-4d82-8550-66b76b91360f.png)
另外我在win10电脑上重新设置了一个新的json文件测试，发现zotero中显示的进度数目和json文件中显示的不符，例如zotero中有10个文献有进度记录，但json文件中只有一条数据。而且在json文件中生成的条目信息和实际论文并不相符，例如
json文件为：
![image](https://user-images.githubusercontent.com/64003943/226982805-f9f34699-0df9-43ba-98c2-04db1309726b.png)
但软件中的显示为：
![image](https://user-images.githubusercontent.com/64003943/226982928-9f6d25c8-2142-4a9a-918f-b36372e4d923.png)

还有一个问题，因为ubuntu和win下的zotero目录不同，所以不知道json文件中的数字所对应的文献在两个系统中是否相同。

**Comment by MuiseDestiny** [comment]
根据2.5.4发布操作即可修复同步失效。如果还有问题可以reopen

**Comment by volatile-static** [comment]
？

**Comment by FairyMeng** [comment]
能不能求一个好心人告诉我如何设置好json文件本地存储？？我找了半天都没找到
