### ISSUE TITLE
希望增加期刊 JCR 分区列，并显示IF的具体数值

### ISSUE THREAD

**Issue by Markwongs** [MuiseDestiny/zotero-style#298]
关于期刊 IF 和分区：
1. 目前的 IF 用进度条的形式显示，很直观，希望在进度条上显示具体的 IF 数值；
2. 希望增加期刊 JCR 分区显示。

**Comment by MuiseDestiny** [comment]
> 希望在进度条上显示具体的 IF 数值；

已经实现，IF的列设置

> 希望增加期刊 JCR 分区显示

如果es支持，填入相应字段就可以，插件不产生数据。
![image](https://user-images.githubusercontent.com/51939531/227715266-7c057286-1d1e-40c3-9354-7b53e771d15b.png)
