### ISSUE TITLE
2.5.3版本 check for updates 没有反应

### ISSUE THREAD

**Issue by kimdumping** [MuiseDestiny/zotero-style#300]
<img width="1000" alt="WeChate803e33817298ee3772860f52080dab1" src="https://user-images.githubusercontent.com/44020658/227760405-07659c65-7c8f-4259-a2ce-11c82c57a23c.png">
ru tu如图

**Comment by MuiseDestiny** [comment]
手动下载安装一下，git忘记上传了导致的。
