### ISSUE TITLE
[Bug] Zotero Style 图标显示问题

### ISSUE THREAD

**Issue by zer0yu** [MuiseDestiny/zotero-style#303]
系统为 macOS 13.2.1
 zotero 版本为 6.0.23
Zotero Style 插件版本为 2.5.4

具体情况，Zotero Style 图标 不正常显示，不耽误显示，但是按钮图片确实显示不出来
![image](https://user-images.githubusercontent.com/16551733/228139772-35791a12-8e3b-46d5-aaea-755e8c5b834e.png)

**Comment by Zaiyu-Li** [comment]
Mac上显示也异常，win缩放后也显示不出来

**Comment by MuiseDestiny** [comment]
最新版已修复
