### ISSUE TITLE
调整不了宽度

### ISSUE THREAD

**Issue by sjads** [MuiseDestiny/zotero-style#304]
![image](https://user-images.githubusercontent.com/96932407/228152961-58e2c95b-f5c8-4014-89be-7cb2c4958bc8.png)
调整不了列名宽度

**Comment by MuiseDestiny** [comment]
有类似问题，联系远程了

**Comment by MuiseDestiny** [comment]
修复结果出来通知你

https://github.com/MuiseDestiny/zotero-style/issues/290

**Comment by sjads** [comment]
谢谢大佬
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月28日 15:04
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [MuiseDestiny/zotero-style] 调整不了宽度 (Issue #304)
        
      
    
  

修复结果出来通知你
#290

**Comment by xinggue** [comment]
我的情况和#290完全一致，在首选项里去掉graph view之后重启就重新能够调整zotero原生列宽。若能修复感激不尽，谢谢大佬！

**Comment by MuiseDestiny** [comment]
> 我的情况和#290完全一致，在首选项里去掉graph view之后重启就重新能够调整zotero原生列宽。若能修复感激不尽，谢谢大佬！

感谢提供线索
