### ISSUE TITLE
升级后嵌套标签失效，#标签无显示

### ISSUE THREAD

**Issue by xhk96** [MuiseDestiny/zotero-style#311]
![image](https://user-images.githubusercontent.com/108168165/228439355-efeb4f69-e14e-49e0-8baf-7cd76b1c8437.png)

**Comment by xhk96** [comment]
升级指更新插件版本

**Comment by MuiseDestiny** [comment]
#标签 列设置，看下Match的值

**Comment by xhk96** [comment]
已修改为/，重新显示，多谢回复及帮助
