### ISSUE TITLE
shift+p无法都为空

### ISSUE THREAD

**Issue by sometimesstudy** [MuiseDestiny/zotero-style#312]
shift+p里没有栏目，是与其他插件冲突了吗

**Comment by nanyeglm** [comment]
应该是冲突了，把其他插件都禁用之后就恢复了，测试了一下，Zotero PDF Translate、Zotero PDF Preview等插件的使用在我这都会导致shift+p显示为空。
此时把zotero-style插件disable再enable可以恢复，不过再次重启zotero之后就又不行了，不知道是什么原因
