### ISSUE TITLE
加强版GPT

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-style#316]
老板，是否考虑一下这个项目，加速读文献？

[PaperGPT/README_CN.md at c960b87e1ad7f910d5ddce404d9c980ef990bbdd · CUGbaoyi/PaperGPT](  https://github.com/CUGbaoyi/PaperGPT/blob/c960b87e1ad7f910d5ddce404d9c980ef990bbdd/README_CN.md  )    

[关于“Zotero API Key” · Issue #1 · CUGbaoyi/PaperGPT](  https://github.com/CUGbaoyi/PaperGPT/issues/1  )

**Comment by MuiseDestiny** [comment]
我看了下应该可以实现，我提供几个接口，让实现起来更方便。
