### ISSUE TITLE
关于更新期刊标签的一些bug和建议

### ISSUE THREAD

**Issue by medecine-max** [MuiseDestiny/zotero-style#320]
开发者您好：
您开发的插件很好用，但是不知道为什么，我的zotero无法使用这个插件来更新期刊标签（publication tags），请开发者麻烦排查下，
zotero 6.0.23
zotero style 2.5.4
（不知道是不是软件问题，或者插件有bug，推荐一个项目，这个项目的插件在浏览器上使用是很不错的，如何可以借鉴更新if和一些元数据的方式就更好了，谢谢开发者）
EasyPubMed插件链接：https://github.com/naivenaive/EasyPubMed

**Comment by Nixiak-nan** [comment]
#319

**Comment by medecine-max** [comment]
谢谢大佬~
