### ISSUE TITLE
功能建议-显示“期刊或出版社”

### ISSUE THREAD

**Issue by Loticyang** [MuiseDestiny/zotero-style#324]
首先感谢作者的辛苦贡献，对zotero软件改进不少。

发帖是建议一个功能。
![WeChat截图_20230405185103](https://user-images.githubusercontent.com/8101717/230059786-7a8e9911-fb1a-47ec-bfb2-d42da24edc27.png)

如图，在一般情况下，我们科研所需要的是【期刊文章】，但偶尔也会添加一些【图书】。对于【图书】，它只有【出版社】而无【期刊】。

如果我们在【列设置】中勾选显示【期刊】，则对于【图书】而言，看不到它的【出版社】。如果勾选显示【期刊】+【出版社】，则对于【期刊文章】而言，在【出版社】一列又无内容需要显示，浪费一列的空间。

因此，建议 增加一个 “期刊或出版社”的【列】，对于【期刊文章】，该列显示 【期刊的名称】；对于【图书】，则自动切换成显示【出版社】。

不知道我表达得是否清楚。
供考虑，谢谢开发者。

**Comment by MuiseDestiny** [comment]
很清楚！可行

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/234518937-c94f50b6-0f45-4f36-ae22-62a71606532a.png)

可以设置候补字段，在Publication列为空时，会从预设值的候补字段查找可用并显示。

**Comment by MuiseDestiny** [comment]
下个版本发布

**Comment by Loticyang** [comment]
谢谢，收到。非常聪明的解决办法。
