### ISSUE TITLE
Allow user to customise what symbol signals a sub-tag

### ISSUE THREAD

**Issue by JonathanBrazil** [MuiseDestiny/zotero-style#330]
Before using this plugin I created sub-tags using:

"Tag: subtag" 

Or 

"Tag -subtag"

Instead of renaming my tags to use / instead of : or - it would be easier if there was a feature where the user can edit what symbol that signals a sub-tag. As I understand it this is currently only set to a forward slash.

**Comment by MuiseDestiny** [comment]
Yes, this feature was originally developed to mimic Obsidian. A standard nested tag in Obsidian is `#Tag1/Tag2`. As a tribute to Obsidian. The plugin is currently only open to modify the beginning of nested tags, in other words you can set it not to start with `#`. But for the intermediate link symbol `/` temporarily w not open. But the later development can be considered open.

**Comment by JonathanBrazil** [comment]
Thanks for letting me know!

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/230528478-1fb4d565-0eb5-4dc8-ad21-6d6fb54c42a1.png)

Provide option includes `/` and `-` and more.

**Comment by JonathanBrazil** [comment]
<3 amazing. Thank you. I wonder if adding a similar dropdown or input on changing the tag symbol '#' is worthwhile? 

Or maybe just a link to some instructions. 

As a new user, this took me a second to figure out.
