### ISSUE TITLE
关系图谱的related无显示

### ISSUE THREAD

**Issue by Bai529** [MuiseDestiny/zotero-style#338]
其余三个图谱都可以正常显示，但是related在文献有关联的情况下是空白
![QQ截图20230407173824](https://user-images.githubusercontent.com/98310083/230585825-b0565a49-81a1-4e6d-884f-bfc1661ed45e.png)
请问一下这个问题应该如何解决？

**Comment by MuiseDestiny** [comment]
> 其余三个图谱都可以正常显示，但是related在文献有关联的情况下是空白 ![QQ截图20230407173824](https://user-images.githubusercontent.com/98310083/230585825-b0565a49-81a1-4e6d-884f-bfc1661ed45e.png) 请问一下这个问题应该如何解决？

你选择的分类是哪一个，里面有多少条目。截图和描述给的信息太少，无法做出进一步判断。

**Comment by Bai529** [comment]
您好，非常抱歉我的信息不够充分，我重新截了完整的图。请问是否是由于我的关联文献太少无法形成关系图，我仅在该文件夹中关联两篇文献。
![QQ截图20230407173824](https://user-images.githubusercontent.com/98310083/230587153-875a95ae-0377-4d3c-b9e6-9a26b0741491.png)

**Comment by MuiseDestiny** [comment]
稍等，马上解决

**Comment by Bai529** [comment]
十分感谢，麻烦了

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.0

重新下载解决

**Comment by Bai529** [comment]
问题解决了！谢谢
