### ISSUE TITLE
从2.5.0开始插件视图组丢失并不可用，shift+p空白，无法关闭功能选项

### ISSUE THREAD

**Issue by seifer08ms** [MuiseDestiny/zotero-style#341]
**不礼貌不回复，直接关闭**
已经通过删除pref.js里的选项，卸载重启后安装其他版本试验过了。 试过升级到最新2.6.0，也试过降级到2.2.4,2.4.x等多个版本，出现很多问题：
1. 视图组丢失， 并且右键菜单中没有视图图的选项了，这个问题在我升级降级的每个版本中都持续存在。
2. 无法关闭功能选项。 无论是通过高级编辑器还是插件自带的选项里面的开启和关闭，重启zotero之后全部自动重置为开启。
3. shift+p空白， 这个问题只在我降级过的某一个版本中得到解决，其余版本均空白，无法升级还是降级。

问题是否是从2.5.0开始的我无法确定了，似乎是自动升级上来的。之前有过刚刚熟悉折叠标题并习惯了后自动升级就给去掉了，现在是又习惯了视图组后，似乎又是自动升级后全丢了并且我现在升级降级都无法解决。

请问我该怎么办

**Comment by seifer08ms** [comment]
我已经把reference citation插件都更新到最新了

**Comment by MuiseDestiny** [comment]
试过禁用所有其他插件没

**Comment by MuiseDestiny** [comment]
这种情况感觉是插件启动时候初始化失败了

**Comment by seifer08ms** [comment]
> 试过禁用所有其他插件没

没有禁用过全部，我只是一开始禁用过issue看到的他们提示过有可能冲突的部分插件。
另外，我的图谱功能倒一直正常。
我刚刚又试验了降级到2.1.9后，右键菜单又出现视图组了，但再升级回去又消失了。
我一会再看看禁用所有插件吧

**Comment by seifer08ms** [comment]
禁用了全部其他插件了，还是不行：
并且我发现2.1.9虽然出现视图组了，但不能保存。
换成新版本那些问题还照旧： 没有视图组，选项和设置都不保存，但rate保存了

**Comment by MuiseDestiny** [comment]
> 禁用了全部其他插件了，还是不行： 并且我发现2.1.9虽然出现视图组了，但不能保存。 换成新版本那些问题还照旧： 没有视图组，选项和设置都不保存，但rate保存了

找个时间远程？

**Comment by seifer08ms** [comment]
> > 禁用了全部其他插件了，还是不行： 并且我发现2.1.9虽然出现视图组了，但不能保存。 换成新版本那些问题还照旧： 没有视图组，选项和设置都不保存，但rate保存了
> 
> 找个时间远程？

感谢，您今天晚上八点方便吗？或者明天晚上？
用todesk行吗？我这边还要准备其他什么吗

**Comment by MuiseDestiny** [comment]
> > > 禁用了全部其他插件了，还是不行： 并且我发现2.1.9虽然出现视图组了，但不能保存。 换成新版本那些问题还照旧： 没有视图组，选项和设置都不保存，但rate保存了
> > 
> > 
> > 找个时间远程？
> 
> 感谢，您今天晚上八点方便吗？或者明天晚上？ 用todesk行吗？我这边还要准备其他什么吗

到时候控制码发我邮箱2274466799@qq.com

**Comment by seifer08ms** [comment]
> 

好的，谢谢

**Comment by seifer08ms** [comment]
太牛了，手到病除
