### ISSUE TITLE
有什么办法能不要新建进度条的条目，主要只想使用标签和字段功能。

### ISSUE THREAD

**Issue by xzl9696** [MuiseDestiny/zotero-style#35]
有什么办法能不要新建进度条的条目，主要想使用标签对齐和字段功能。可不可以设置一个开关，关闭之后就不会自动新建zotero style 的笔记，因为我的只想用标签对齐功能。辛苦开发者了。

**Comment by MuiseDestiny** [comment]
把zoterostyle条目删除即可，具体看readme

**Comment by xzl9696** [comment]
好的，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月18日(周日) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MuiseDestiny/ZoteroStyle] 有什么办法能不要新建进度条的条目，主要只想使用标签和字段功能。 (Issue #35)




 
把zoterostyle条目删除即可，具体看readme
