### ISSUE TITLE
Publications Tags某个期刊不显示

### ISSUE THREAD

**Issue by Saunak626** [MuiseDestiny/zotero-style#365]
你好，npj Digital Medicine这个期刊不知道为什么不显示，试了几种缩写好像都没有找到。
![image](https://user-images.githubusercontent.com/34276206/231618336-9a894aeb-9e3c-47d3-97ef-8514adfb4db6.png)
![image](https://user-images.githubusercontent.com/34276206/231618114-feace3a1-7c5a-466d-8664-f2d76104979b.png)
![image](https://user-images.githubusercontent.com/34276206/231618197-73dddddb-001c-4761-afc6-6dfa6bea90df.png)
![image](https://user-images.githubusercontent.com/34276206/231618285-512f078e-c4bd-4ec3-ad99-16ec97ace980.png)

**Comment by MuiseDestiny** [comment]
点击不显示的期刊标签的空白会强制刷新，出来的结果可以参考得到fields
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.0
