### ISSUE TITLE
期刊标签显示的颜色怎么感觉变得暗淡了

### ISSUE THREAD

**Issue by coisini-95** [MuiseDestiny/zotero-style#367]
大佬好，更新后这个期刊标签显示怎么好像变暗了，色调不明亮了
![图片](https://user-images.githubusercontent.com/78250635/232005249-fc56f05c-3155-430d-868c-ed8464b58e8b.png)

**Comment by MuiseDestiny** [comment]
透明度，字体颜色啥的

**Comment by coisini-95** [comment]
好的好的感谢
