### ISSUE TITLE
关于联动Citexs

### ISSUE THREAD

**Issue by DiaoSpace** [MuiseDestiny/zotero-style#368]
**不礼貌不回复，直接关闭**
UP你好，我是你的粉丝之一，最近我发现一个类似于Connected Paper 的中文网站，叫做Citexs, 网址如下：https://www.citexs.com/Paperpicky，感觉在文献可视化方面做得比较好，但是由于本人非计算机专业，无法实现与Zotero的互动。因此想UP出手，并且建议可以与Citexs合作，帮他们在Zotero建立服务、宣传以及功能维护，同时自己能够获得报酬。

**Comment by franco-ye** [comment]
如果是这样的功能，是不是https://www.researchrabbitapp.com/home <Research Rabbit>更好些，带了Zotero的字段导入

**Comment by MuiseDestiny** [comment]
已经做了connected papers

![image](https://user-images.githubusercontent.com/51939531/234468211-1ea5a0b0-dfad-4072-81ca-a5a6c5c0b36b.png)

![image](https://user-images.githubusercontent.com/51939531/234468234-49761fda-843e-48d0-87c5-7b57fef42dcf.png)

**Comment by franco-ye** [comment]
大佬 如果对researchcch rabbit下手 是不是能想办法 过滤一下文件 rabbit会把item下 全部的文件都导入 及其不美观，是不是可以靠大佬 屏蔽一下呢？

**Comment by MuiseDestiny** [comment]
> 大佬 如果对researchcch rabbit下手 是不是能想办法 过滤一下文件 rabbit会把item下 全部的文件都导入 及其不美观，是不是可以靠大佬 屏蔽一下呢？

不会做他，它画的图我觉得难看

**Comment by franco-ye** [comment]
哈哈哈 那没事 现在已经很棒了！！ zotero style  感恩大佬
