### ISSUE TITLE
“影响因子”和“期刊标签”是一直更新（勤奋更新）吗？

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-style#369]
**不礼貌不回复，直接关闭**

我zotero中，文献条目上万，之前一直不卡，但是昨天 style 插件填写 easyscholar 的key 之后变得卡顿

分析：
1. 填easyscholar key之后，无论是否显示“影响因子”和“期刊标签”这两栏，zotero能明显有卡顿；
2. 把easyscholar key删除之后，无论是否显示两栏，zotero和之前一样顺滑；

推测：填key之后，“影响因子”和“期刊标签”两栏信息是勤奋更新（相对于关系图的惰性更新）

可能的改进方案：类似“关系谱图”功能，增加一个开关，以便于填了key之后，用户可以手动控制是勤奋更新，还是惰性更新“影响因子”和“期刊标签”。

大佬考虑一下？

**Comment by Geo123abc** [comment]
[如何让期刊标签不自动更新，只在点击条目的期刊标签的时候触发更新 · Issue #358 · MuiseDestiny/zotero-style](  https://github.com/MuiseDestiny/zotero-style/issues/358  )    

和这个issue重合了

**Comment by MuiseDestiny** [comment]
等更完了就好了，会存本地文件，下次读缓存。等你啥时候不zotero打开让它更就好了。

**Comment by Geo123abc** [comment]
> 等更完了就好了，会存本地文件，下次读缓存。等你啥时候不zotero打开让它更就好了。

那我再试试，

我也考虑放着让他更新，所以昨天网上就没关机，但是今天还是有点卡

我本来考虑是不是多显示了“影响因子”和“期刊标签”这两列的原因（之前使用 Pubpeer Plugin for Zotero 或者是 scite Plugin for Zotero，多了两列引用量计算之类的栏，然后zotero就很卡），但是今天不显示“影响因子”和“期刊标签”这两栏，仍然很卡

删除easyscholar key之后就不卡了，难道是还没更新完全？

我再试一下吧，谢谢回复

**Comment by Geo123abc** [comment]
> 等更完了就好了，会存本地文件，下次读缓存。等你啥时候不zotero打开让它更就好了。

有两个问题
1. 如果有调用key更新的话，zotero右下角是不是会有一个通知？
2. 更新的频率有上限？

**Comment by MuiseDestiny** [comment]
> > 等更完了就好了，会存本地文件，下次读缓存。等你啥时候不zotero打开让它更就好了。
> 
> 有两个问题
> 
> 1. 如果有调用key更新的话，zotero右下角是不是会有一个通知？
> 2. 更新的频率有上限？

可能会通知吧。更新是一个个的1s间隔

**Comment by Geo123abc** [comment]
> > > 等更完了就好了，会存本地文件，下次读缓存。等你啥时候不zotero打开让它更就好了。
> > 
> > 
> > 有两个问题
> > 
> > 1. 如果有调用key更新的话，zotero右下角是不是会有一个通知？
> > 2. 更新的频率有上限？
> 
> 可能会通知吧。更新是一个个的1s间隔

谢谢，我在easyscholar 后台观察调用次数

可能我文献太多了

**Comment by Geo123abc** [comment]
[Release 2.6.2 · MuiseDestiny/zotero-style](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.2  )，期刊标签更新修改为被动触发：期刊标签需要 Shift+P 主动更新，或点击空白的期刊标签更新
