### ISSUE TITLE
创建者不显示

### ISSUE THREAD

**Issue by q1164012062** [MuiseDestiny/zotero-style#371]
**不礼貌不回复，直接关闭**

![@F C(ID71Z 7W~UU2SJV$QQ](https://user-images.githubusercontent.com/64342152/232208002-e85ae390-e8dd-489c-9b65-4ea146f57954.png)
如图所示，关闭style插件就可以显示了

**Comment by MuiseDestiny** [comment]
右键创建者的列设置截图看看

**Comment by q1164012062** [comment]
![微信截图_20230415182050](https://user-images.githubusercontent.com/64342152/232208144-d33a12b8-99d9-4186-acce-cc8616c8f3cd.png)

**Comment by MuiseDestiny** [comment]
你更改了

**Comment by q1164012062** [comment]
好的，怎么改回来，谢谢！

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/232208206-128a4bcd-3bd4-48bc-b79a-2b314022796d.png)

https://www.notion.so/Zotero-Style-bc2aebbbb6df4b7baa858e376e4fc5be#347b36d76f944edf943c0a77fda63947

1.8 创建者

**Comment by q1164012062** [comment]
好了，谢谢大佬！
