### ISSUE TITLE
IF和greenfog有冲突

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-style#372]
https://github.com/redleafnew/zotero-updateifsE
IF开启后会被Greenfog的替换掉，能强制覆盖吗？

谢谢

**Comment by MuiseDestiny** [comment]
> https://github.com/redleafnew/zotero-updateifsE IF开启后会被Greenfog的替换掉，能强制覆盖吗？
> 
> 谢谢

谁覆盖谁啊

**Comment by llity** [comment]
Greenfog覆盖了style的IF式样。

**Comment by MuiseDestiny** [comment]
> Greenfog覆盖了style的IF式样。

让style再覆盖它它吗，我记得青蛙是可以设置显示哪一列的，首选项关闭青蛙的影响因子试试

**Comment by llity** [comment]
确认关闭可以，需要重启一次zotero生效。谢谢
