### ISSUE TITLE
标题前面突然有了已读未读的标签显示了

### ISSUE THREAD

**Issue by coisini-95** [MuiseDestiny/zotero-style#376]
您好，今天打开zotero突然发现标题的开头显示了已读未读的标签，那个列设置里的tag我也没打开，它怎么就自动显示了，重启软件好像没变化
![图片](https://user-images.githubusercontent.com/78250635/232937884-53a8ea41-97c0-4df3-be69-f5e6e5ac43ea.png)

**Comment by MuiseDestiny** [comment]
插件影响，可能是翻译插件。

**Comment by MuiseDestiny** [comment]
你在插件管理问号关闭插件再开启就好了。

**Comment by coisini-95** [comment]
哦哦确实是翻译插件的原因，我把两个插件都关了再开启，还是会显示，昨天还没有，奇怪

**Comment by MuiseDestiny** [comment]
因为以前有个延迟启动，最近一次更新我给去掉了。有时间解决这个冲突吧

**Comment by MuiseDestiny** [comment]
> ，我把两个插件都关了再开启，还是会显示

因为zotero的标签本身就是显示标题前面的。style给他移动到新的一列了

**Comment by coisini-95** [comment]
好的感谢大佬
