### ISSUE TITLE
阅读进度渲染好像跟翻译插件冲突了

### ISSUE THREAD

**Issue by coisini-95** [MuiseDestiny/zotero-style#377]
打扰了，刚发现阅读进度不显示了，也重新选择了阅读进度的本地储存，还是没用，但是关了翻译插件后，就正常显示了；之后再打开翻译插件，阅读进度立马没了，都不用关闭软件重启。
![图片](https://user-images.githubusercontent.com/78250635/233069626-23f03e1c-3ce3-439f-a043-717ef181642d.png)
![图片](https://user-images.githubusercontent.com/78250635/233069636-18130c95-0899-494b-8413-0e51212bd8fb.png)

**Comment by MuiseDestiny** [comment]
好的，修复一下

**Comment by coisini-95** [comment]
感谢大佬，辛苦了

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.3
