### ISSUE TITLE
PDF页的tab消失，不知道是哪一个插件引起。

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-style#386]
目前只有translate的tab，而且会重复，之前好像讨论过tab消失、重复的bug，但不知道是怎么引起的。谢谢
<img width="469" alt="image" src="https://user-images.githubusercontent.com/11771112/233908171-ac26722d-dd6c-42b7-b2a8-c9df5d37b554.png">

**Comment by llity** [comment]
测试是zbn测试版的问题，然后gpt可能引起tab重复。

**Comment by MuiseDestiny** [comment]
更新翻译插件修复
