### ISSUE TITLE
关于“标签”的功能异常

### ISSUE THREAD

**Issue by LGRemdo** [MuiseDestiny/zotero-style#387]
尊敬的作者，我无法正常在左下角的标签栏显示完整的内容，并且shift+p的内容也没有“标签”选项。因此，我需要向您寻求帮助。（我目前就enable两个插件，一个style，一个tag）
![image](https://user-images.githubusercontent.com/54077803/234018820-9a78078d-0ec2-4b7a-b77e-4e77b45a1b53.png)

**Comment by MuiseDestiny** [comment]
> 我无法正常在左下角的标签栏显示完整的内容

建立一个#标签

> 并且shift+p的内容也没有“标签”选项

选中一个带有标签的条目后shift+p

shift+p显示的命令是动态的。

**Comment by LGRemdo** [comment]
> > 我无法正常在左下角的标签栏显示完整的内容
> 
> 建立一个#标签
> 
> > 并且shift+p的内容也没有“标签”选项
> 
> 选中一个带有标签的条目后shift+p
> 
> shift+p显示的命令是动态的。

非常棒，成功解决了我的问题，感谢作者！
