### ISSUE TITLE
BUG：Shift+鼠标左键拖动条目至文件夹 功能失效

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-style#389]
### zotero自带功能：
1.鼠标左键拖动条目至某个文件夹：复制条目
2.shift+鼠标左键拖动条目至某个文件夹：**移动**条目

### 开启zotero style后移动条目功能失效：
1.鼠标左键拖动条目至某个文件夹：复制条目
2.shift+鼠标左键拖动条目至某个文件夹：**复制**条目

**Comment by MuiseDestiny** [comment]
如装了citation，关闭引用列后移动

**Comment by 1067237855** [comment]
好像是citations的原因👍
> 如装了citation，关闭引用列后移动
