### ISSUE TITLE
请问怎么关掉点击条目，右下角跳出期刊标签的那个功能呢？

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-style#396]
可以关掉这个功能，但是开启“标签期刊”这一列吗？
![CleanShot 2023-04-28 at 14 19 31@2x](https://user-images.githubusercontent.com/50101175/235069747-9f7aea5c-0b3e-47ea-9810-bbcb0660ef8d.png)

**Comment by yzy1228682367** [comment]
这个每次点击条目都会出现，让电脑有点卡。

**Comment by MuiseDestiny** [comment]
不要点期刊标签那里就不出现了。无法关闭。

或者需要看期刊标签再开，防止误触。

**Comment by MuiseDestiny** [comment]
> 这个每次点击条目都会出现，让电脑有点卡。

不会让电脑卡。

**Comment by yzy1228682367** [comment]
> 不要点期刊标签那里就不出现了。无法关闭。
> 
> 或者需要看期刊标签再开，防止误触。

哦哦哦，原来是这样呀，我说为什么有时候出现，有时候不出现嘞。感谢大大❤️
