### ISSUE TITLE
嵌套标签如何开启

### ISSUE THREAD

**Issue by MrLittleShark** [MuiseDestiny/zotero-style#398]
**不礼貌不回复，直接关闭**
作者你好，我这里没有显示嵌套标签，请问如何开启【2.6.5版本】
![image](https://user-images.githubusercontent.com/112299157/235350770-5de54fcc-dc58-4339-a432-554afd068baa.png)
![image](https://user-images.githubusercontent.com/112299157/235350776-8ac2dfe7-733b-4422-b41a-2d951af4d585.png)

**Comment by MuiseDestiny** [comment]
#标签的列设置，看下Match，或者设置#开头的标签

**Comment by MrLittleShark** [comment]
> 

可以了，谢谢大大 ！
