### ISSUE TITLE
点击某论文的期刊标签，右侧栏随机出现某论文的批注

### ISSUE THREAD

**Issue by RobRicardo** [MuiseDestiny/zotero-style#402]
作者您好，我在点击某论文的期刊标签后，右侧栏会随机出现某论文的批注。请问这个是bug还是什么问题？有解决的办法吗？

**Comment by RobRicardo** [comment]
![Snipaste_2023-05-01_15-52-37](https://user-images.githubusercontent.com/108347697/235426076-497057a9-b2ed-4f5f-be6f-113c15b9cb7d.jpg)

**Comment by MuiseDestiny** [comment]
这是新功能

**Comment by 1067237855** [comment]
请教如何启用和关闭该功能，没有找到[标注预览](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.5)的开关

> 这是新功能

**Comment by MuiseDestiny** [comment]
用旧版本，新版本暂未提供开关

**Comment by 1067237855** [comment]
主要是没找到怎么开启该功能。更新到最新版，没有显示 [标注预览](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.5)。
PS：其它插件已经全部disabled，可以排除插件冲突导致的不显示[标注预览](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.5)。
> 用旧版本，新版本暂未提供开关

**Comment by MuiseDestiny** [comment]
> 主要是没找到怎么开启该功能。更新到最新版，没有显示 [标注预览](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.5)。 PS：其它插件已经全部disabled，可以排除插件冲突导致的不显示[标注预览](https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.5)。
> 
> > 用旧版本，新版本暂未提供开关

我理解错了，你是想要这个功能，然后新版本不显示吗。

**Comment by MuiseDestiny** [comment]
标注预览就是在切换分类时候发生。然后随便点整个条目，标注预览就会消失了

**Comment by llity** [comment]
@MuiseDestiny 配置一个tab独立显示标注吧，这样更直观。显示整个分类的标注就太多了。

**Comment by RobRicardo** [comment]
> 标注预览就是在切换分类时候发生。然后随便点整个条目，标注预览就会消失了

主要是我想点一下期刊标签看一下期刊的其他分类标准，就会出现这个标注预览。

**Comment by MuiseDestiny** [comment]
> +1非常赞同，在右侧加一列（类似于preview插件能够在”信息“列中进行“PDF预览”一样，咱们可以在”笔记“列中加一个类似的，进行“标注预览”），每个条目的标注可以清晰地预览。只读取一个条目的批注，应该会减少卡顿。
> 
> ![image](https://user-images.githubusercontent.com/104330036/235599843-bcb8e052-1adb-4eac-8ed2-98c81b14397c.png)
> 
> > @MuiseDestiny 增加配置一个tab独立显示标注吧，这样更直观。整个分类的标注可能找不到重点。

Doing

**Comment by MaggieLeung666** [comment]
请问为什么我的不显示影响因子等呀
![image](https://github.com/MuiseDestiny/zotero-style/assets/144437582/2751fb08-05dd-446d-83a5-9aa077d81d67)

**Comment by xlnn** [comment]
> 这是新功能

作者您好，这个自动添加上的论文批注如何关闭？谢谢！
