### ISSUE TITLE
[bug]关于读取easyscholar接口数据时忽略了自定义数据集的问题

### ISSUE THREAD

**Issue by Rphone** [MuiseDestiny/zotero-style#407]
类似的问题在Issue #363 有提到过，经过分析代码发现
在src/modules/utils.ts 第29行开始解析easyscholar接口的数据，当读取easyscholar官方数据集为null时，
代码第37行直接`return 0;`，此时如果用户的自定义数据集有数据返回的话会得不到解析的机会
事实上对于很多会议类的文章，由于会议通常带简写和年份，官方数据集很难直接匹配到，因此很多人倾向于用可以模糊匹配的自定义数据集（例如CCF）才更为准确，我自己尝试修复了这个问题，准备提交一个PR，如果您觉得合适的话可以考虑合并

修复前
<img width="576" alt="image" src="https://user-images.githubusercontent.com/45196588/235667476-203f2394-f907-412b-9fd9-d5980cbb7d5f.png">
修复后的效果
<img width="597" alt="image" src="https://user-images.githubusercontent.com/45196588/235667572-9cd04308-19af-4a4c-a378-9e01fe7bb3d8.png">

**Comment by MuiseDestiny** [comment]
感谢贡献！
