### ISSUE TITLE
重启zotero后进度条全部消失

### ISSUE THREAD

**Issue by FairyMeng** [MuiseDestiny/zotero-style#410]
**不礼貌不回复，直接关闭**
目前的版本为2.6.3 五一前还有进度条 回来上班重启了一下进度条都消失了
没找到很相关的issue 所以想请问作者需要怎么修复

**Comment by MuiseDestiny** [comment]
目前最新2.6.6

**Comment by MuiseDestiny** [comment]
> 进度条都消失了

进度只是可能不渲染，源数据不会消失的

**Comment by FairyMeng** [comment]
> 目前最新2.6.6

您好 我更新到最新了 只有今早阅读的两篇显示出进度条了 但之前的好像都没有了 有什么办法能找到之前的进度吗

**Comment by MuiseDestiny** [comment]
> > 目前最新2.6.6
> 
> 您好 我更新到最新了 只有今早阅读的两篇显示出进度条了 但之前的好像都没有了 有什么办法能找到之前的进度吗

重启试试，还不行发todesk远程控制

**Comment by FairyMeng** [comment]
我重启了一下电脑 发现还是不太行
ToDesk设备代码:880 986 046
临时密码:d2v4r5sz
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=PbgVAMCGsn4XzeGGdzzic
麻烦您了

**Comment by MuiseDestiny** [comment]
> 我重启了一下电脑 发现还是不太行 ToDesk设备代码:880 986 046 临时密码:d2v4r5sz 点击链接直接进行远程控制： https://wechat.todesk.com/invite-page?id=PbgVAMCGsn4XzeGGdzzic 麻烦您了

密码失效，升级下todesk免密码连接

**Comment by FairyMeng** [comment]
> > 我重启了一下电脑 发现还是不太行 ToDesk设备代码:880 986 046 临时密码:d2v4r5sz 点击链接直接进行远程控制： https://wechat.todesk.com/invite-page?id=PbgVAMCGsn4XzeGGdzzic 麻烦您了
> 
> 密码失效，升级下todesk免密码连接

我改成了每日更新临时密码  w4craej3

**Comment by MuiseDestiny** [comment]
> > > 我重启了一下电脑 发现还是不太行 ToDesk设备代码:880 986 046 临时密码:d2v4r5sz 点击链接直接进行远程控制： https://wechat.todesk.com/invite-page?id=PbgVAMCGsn4XzeGGdzzic 麻烦您了
> > 
> > 
> > 密码失效，升级下todesk免密码连接
> 
> 我改成了每日更新临时密码 w4craej3

好像有个锁屏密码啊

**Comment by FairyMeng** [comment]
> 
我来啦！现在可以了嘛？

**Comment by MuiseDestiny** [comment]
> > 
> 
> 我来啦！现在可以了嘛？

能看到画面，不能控制

**Comment by FairyMeng** [comment]
> > > 
> > 
> > 
> > 我来啦！现在可以了嘛？
> 
> 能看到画面，不能控制

123456 锁屏密码
我也不知道为啥你不能控制 我找找

**Comment by MuiseDestiny** [comment]
加我微信muisedestiny

**Comment by siazon** [comment]
所以最后是怎么解决的？Issue怎么关闭了

**Comment by FairyMeng** [comment]
> 所以最后是怎么解决的？Issue怎么关闭了
我们的问题可能不太一样 如果你没有删除过的话 作者说所有的信息都存储在item项里面，但是我当时没有这个 所以没法恢复 就结束了
