### ISSUE TITLE
关闭了进度条功能，但仍然出现addon item条目

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#412]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/68216639/236145029-4dfaecaf-52e8-483f-8b1f-5afde3dc9255.png">
<img width="988" alt="image" src="https://user-images.githubusercontent.com/68216639/236145059-de3afd5f-cedf-48f1-9ff6-a2a919c9a3e6.png">
作者好，插件中我只保留了期刊标签和视图组功能，但是没打开一篇新文献，仍然会在我的文库中出现新的addon item条目下的注释文件～

**Comment by MuiseDestiny** [comment]
用2.6.0
