### ISSUE TITLE
希望#标签的内容可以以不同的颜色显示

### ISSUE THREAD

**Issue by tfeilyu** [MuiseDestiny/zotero-style#418]
**不礼貌不回复，直接关闭**
<img width="184" alt="image" src="https://user-images.githubusercontent.com/47890516/236737533-5b17dc46-56e5-4198-82f3-c8bf06176ca1.png">
如果不同标签显示不同的颜色那就更棒啦，希望大佬可以更新～

**Comment by MuiseDestiny** [comment]
> **不礼貌不回复，直接关闭** <img alt="image" width="184" src="https://user-images.githubusercontent.com/47890516/236737533-5b17dc46-56e5-4198-82f3-c8bf06176ca1.png"> 如果不同标签显示不同的颜色那就更棒啦，希望大佬可以更新～

可以设置，紫色是默认颜色

**Comment by tfeilyu** [comment]
> > **不礼貌不回复，直接关闭** <img alt="image" width="184" src="https://user-images.githubusercontent.com/47890516/236737533-5b17dc46-56e5-4198-82f3-c8bf06176ca1.png"> 如果不同标签显示不同的颜色那就更棒啦，希望大佬可以更新～
> 
> 可以设置，紫色是默认颜色

但是设置之后还是所有标签只能显示一种颜色，如果可以对不同的标签显示不同的颜色，会更好看，更方便～ 希望可以更新，感谢大佬

**Comment by MuiseDestiny** [comment]
> > > **不礼貌不回复，直接关闭** <img alt="image" width="184" src="https://user-images.githubusercontent.com/47890516/236737533-5b17dc46-56e5-4198-82f3-c8bf06176ca1.png"> 如果不同标签显示不同的颜色那就更棒啦，希望大佬可以更新～
> > 
> > 
> > 可以设置，紫色是默认颜色
> 
> 但是设置之后还是所有标签只能显示一种颜色，如果可以对不同的标签显示不同的颜色，会更好看，更方便～ 希望可以更新，感谢大佬

就是不同标签不同颜色，指派颜色。

**Comment by tfeilyu** [comment]
> > > > **不礼貌不回复，直接关闭** <img alt="image" width="184" src="https://user-images.githubusercontent.com/47890516/236737533-5b17dc46-56e5-4198-82f3-c8bf06176ca1.png"> 如果不同标签显示不同的颜色那就更棒啦，希望大佬可以更新～
> > > 
> > > 
> > > 可以设置，紫色是默认颜色
> > 
> > 
> > 但是设置之后还是所有标签只能显示一种颜色，如果可以对不同的标签显示不同的颜色，会更好看，更方便～ 希望可以更新，感谢大佬
> 
> 就是不同标签不同颜色，指派颜色。

啊？请这个怎么设置啊 大佬，是列设置里面吗？还是在zotero自带的分配颜色？系统自带的只能分配9个😭
<img width="152" alt="image" src="https://user-images.githubusercontent.com/47890516/236742609-ac8d2e87-ba5e-495d-8de7-76fcc1b1ba2e.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/47890516/236742642-8fa90de2-7023-4572-b2dc-212aa4b03c21.png">

**Comment by MuiseDestiny** [comment]
选中条目shift p点标签

**Comment by Physics-Lee** [comment]
尝试了很久也没能修改颜色。“选中条目shift p点标签”之后颜色并不改变。

**Comment by MuiseDestiny** [comment]
<img width="981" alt="Image" src="https://github.com/user-attachments/assets/1f826bfa-dd12-4c13-8ca2-db6b18fcb477" />
