### ISSUE TITLE
进度条信息存储

### ISSUE THREAD

**Issue by Jinshijiming** [MuiseDestiny/zotero-style#421]
1.用了一下，note的存储模式下找不到进度条存在哪里（没有新建note）。
2.本地存储的话，在阅读新的文献后不能及时更新json文件，关掉重启进度会丢失
3.可不可以直接在文库里面建一个存储文档，方便随着文库一起同步。

**Comment by MuiseDestiny** [comment]
> note的存储模式下找不到进度条存在哪里

搜索Addon Item

> 在阅读新的文献后不能及时更新json文件，关掉重启进度会丢失

可以的

> 可不可以直接在文库里面建一个存储文档，方便随着文库一起同步。

新建的json你可以指定为你新建的存储文档

**Comment by Saunak626** [comment]
现在还需要使用Addon Item里的项吗？我记得有次更新好像是不再用Addon Item存数据了？

**Comment by MuiseDestiny** [comment]
> 现在还需要使用Addon Item里的项吗？我记得有次更新好像是不再用Addon Item存数据了？

需要配置本地json

**Comment by wsgwzlr** [comment]
> 需要配置本地json

你好，请问如何将原有的在Addon Item中的数据迁移到本地json中呢？
