### ISSUE TITLE
zotero卡顿

### ISSUE THREAD

**Issue by Liuy811** [MuiseDestiny/zotero-style#422]
使用插件后，打开zotero加载时间很长，而且很卡顿，非常卡，禁用之后能够恢复正常。有尝试将其他插件逐个禁用再依次启用，目前排查到style在win版zotero中很卡，请问此类问题有什么好的解决办法吗？

**Comment by MuiseDestiny** [comment]
style会导致卡顿（功能太多）。禁用style部分功能。
