### ISSUE TITLE
shift+p页面也没有进度条等选项

### ISSUE THREAD

**Issue by TangKC0813** [MuiseDestiny/zotero-style#426]
你好，我是一个研0小白，最近才开始琢磨zotero
想问一下您，我安装了zotero style插件，但是shift+p快捷界面里只有“标签”和“期刊标签”这两个选项
想问问您，是不是哪里出了问题？

我的联系方式是1606074126@qq.com，还请多多指教，感激不尽！！！

**Comment by MuiseDestiny** [comment]
你描述的是正常的。想要更多命令，选中条目后按shift p
