### ISSUE TITLE
shift+p快捷界面的命令问题

### ISSUE THREAD

**Issue by TangKC0813** [MuiseDestiny/zotero-style#427]
感谢制作者之前的回复，刚才登陆后快捷界面有四个命令选项
但是出现了一个问题，我改了一个标题颜色（就是标题下进度条的底色），然后shift+p里又只有两个选项了，这个是什么原因？

**Comment by MuiseDestiny** [comment]
shift p里面的命令是动态的，是看你操作对象的。如果你没有选中带有进度的条目，shift p后就是两条命令
