### ISSUE TITLE
标签间距问题

### ISSUE THREAD

**Issue by isPengLu** [MuiseDestiny/zotero-style#43]
在Mac环境下，同一个emoji多次重复作为一个标签，则该标签与右侧其他正常标签的间距会变大。emoji重复的次数越多，间距越大。如图：
<img width="211" alt="截屏2023-01-05 23 41 32" src="https://user-images.githubusercontent.com/44140709/210894214-aed0a385-a92d-4b13-a1a0-73f2f58cffed.png">

**Comment by MuiseDestiny** [comment]
多个星星我好像专门适配过，在win上没问题，可能mac上变化了。我想想怎么解决

**Comment by MuiseDestiny** [comment]
试试我仓库zotero-style预览版

**Comment by isPengLu** [comment]
<img width="109" alt="截屏2023-01-09 17 50 53" src="https://user-images.githubusercontent.com/44140709/211362715-0c1a362d-b31b-4c6c-82d1-aa1b55d38c50.png">
哈哈哈哈 这个可能是mac的emoji的问题？

**Comment by isPengLu** [comment]
<img width="136" alt="截屏2023-01-09 17 53 15" src="https://user-images.githubusercontent.com/44140709/211363206-4841ae7a-e645-4334-b7cf-948ad7501ee0.png">

如果用字符版本的星星就会好很多 虽然间距也比较大

**Comment by MuiseDestiny** [comment]
https://stackoverflow.com/a/54369605
用了这里提到的一个包，修复了

**Comment by isPengLu** [comment]
<img width="397" alt="截屏2023-01-10 16 14 20" src="https://user-images.githubusercontent.com/44140709/211589229-bf604b5a-8630-4e83-b3fa-07e023b1e33d.png">

是最新的1.5吗，mac上还是这样的

<img width="411" alt="截屏2023-01-10 16 19 31" src="https://user-images.githubusercontent.com/44140709/211590299-f8758129-3321-473e-bb52-14729cb5bf9a.png">
<img width="187" alt="截屏2023-01-10 16 20 07" src="https://user-images.githubusercontent.com/44140709/211590679-2ec67a26-e58e-410a-bb69-02f66bab32b7.png">

**Comment by MuiseDestiny** [comment]
> <img alt="截屏2023-01-10 16 14 20" width="397" src="https://user-images.githubusercontent.com/44140709/211589229-bf604b5a-8630-4e83-b3fa-07e023b1e33d.png">
> 
> 是最新的1.5吗，mac上还是这样的
> 
> <img alt="截屏2023-01-10 16 19 31" width="411" src="https://user-images.githubusercontent.com/44140709/211590299-f8758129-3321-473e-bb52-14729cb5bf9a.png">
> 
> <img alt="截屏2023-01-10 16 20 07" width="187" src="https://user-images.githubusercontent.com/44140709/211590679-2ec67a26-e58e-410a-bb69-02f66bab32b7.png">



> <img alt="截屏2023-01-10 16 14 20" width="397" src="https://user-images.githubusercontent.com/44140709/211589229-bf604b5a-8630-4e83-b3fa-07e023b1e33d.png">
> 
> 是最新的1.5吗，mac上还是这样的
> 
> <img alt="截屏2023-01-10 16 19 31" width="411" src="https://user-images.githubusercontent.com/44140709/211590299-f8758129-3321-473e-bb52-14729cb5bf9a.png">
> 
> <img alt="截屏2023-01-10 16 20 07" width="187" src="https://user-images.githubusercontent.com/44140709/211590679-2ec67a26-e58e-410a-bb69-02f66bab32b7.png">

刚发的1.5.1试试

**Comment by isPengLu** [comment]
<img width="146" alt="截屏2023-01-11 10 28 14" src="https://user-images.githubusercontent.com/44140709/211768932-466993fd-4b30-4910-8412-c9203f57264e.png">

非文字的emoji间距好很多，如果再小一些就好了，不行的话这样已经很好了 🫡

**Comment by MuiseDestiny** [comment]
> <img alt="截屏2023-01-11 10 28 14" width="146" src="https://user-images.githubusercontent.com/44140709/211768932-466993fd-4b30-4910-8412-c9203f57264e.png">
> 
> 非文字的emoji间距好很多，如果再小一些就好了，不行的话这样已经很好了 🫡

可以设置的，见readme搜索`zoterostyle`好像是tags.margin

**Comment by MuiseDestiny** [comment]
> <img alt="截屏2023-01-11 10 28 14" width="146" src="https://user-images.githubusercontent.com/44140709/211768932-466993fd-4b30-4910-8412-c9203f57264e.png">
> 
> 非文字的emoji间距好很多，如果再小一些就好了，不行的话这样已经很好了 🫡

顺便问下，用起来卡不卡

**Comment by isPengLu** [comment]
用了一天下来，卡顿的感觉就比较明显了。具体表现有：
1. 用数字快捷键添加标签需要过几秒才会有反应
2. 右键条目有较高几率不能即时弹出菜单
3. 全选不够流畅

**Comment by MuiseDestiny** [comment]
> 用了一天下来，卡顿的感觉就比较明显了。具体表现有：
> 
> 1. 用数字快捷键添加标签需要过几秒才会有反应
> 2. 右键条目有较高几率不能即时弹出菜单
> 3. 全选不够流畅

确实，如果文献很多，巨卡

**Comment by isPengLu** [comment]
大佬加油，我觉得这个插件的功能都很好用。

顺便问一下，那个shift+P的功能可以设置一个按钮关掉吗，因为好像除了PDF阅读界面外的分屏选项外没有用处

**Comment by MuiseDestiny** [comment]
> 大佬加油，我觉得这个插件的功能都很好用。
> 
> 顺便问一下，那个shift+P的功能可以设置一个按钮关掉吗，因为好像除了PDF阅读界面外的分屏选项外没有用处

这个以后慢慢加功能进去。不按shift+p就不会出现啊，为啥要去掉。

**Comment by isPengLu** [comment]
哈哈哈，如果加功能就不用去了，主要是强迫症

**Comment by MuiseDestiny** [comment]
等优化好卡顿把设置加进去
