### ISSUE TITLE
pdf文件自动添加addon item条目笔记

### ISSUE THREAD

**Issue by liyunxi326** [MuiseDestiny/zotero-style#433]
每次打开一个未阅读的pdf，右侧笔记栏下的所有笔记栏中会自动添加一个addon item笔记，笔记内容如下：W9CAAU9R {”readingTime“：{”page“：7，”data“：{”0“：470，”1“：1810，”2“：1600，”3“：1510，”4“：40，”5“：20，”6“：130}}}
怎么操作才能取消这个功能？

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/c9d4d007-34ee-403f-b846-91cb9393e389)

这个style.json需要你提前新建好，然后选择它，再选择File。重启zotero。删除以前生成的笔记即可。

**Comment by liyunxi326** [comment]
style.json文件是什么格式呢？word文档就可以吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-style] pdf文件自动添加addon item条目笔记 (Issue #433)





 

 
这个style.json需要你提前新建好，然后选择它，再选择File。重启zotero。删除以前生成的笔记即可。

**Comment by liyunxi326** [comment]
按您的提示操作成功啦！万分感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-style] pdf文件自动添加addon item条目笔记 (Issue #433)





 

 
这个style.json需要你提前新建好，然后选择它，再选择File。重启zotero。删除以前生成的笔记即可。

**Comment by MontelukastNa** [comment]
> style.json

请问style.json内部内容需要写什么呀？ 谢谢 完全不懂的新手

**Comment by BugBubbles** [comment]
太感谢了，帮了大忙！可以在需要的位置新建一个json文件，内容甚至可以为空，也可以是Zotero-syle导出的配置json文件，然后选中该文件，zotero-style就不会在文献库里面产生笔记和addon item啦
