### ISSUE TITLE
你好，新添加的论文对应的期刊标签不显示

### ISSUE THREAD

**Issue by WangXinrui333** [MuiseDestiny/zotero-style#435]
您好，新添加的论文对应的期刊标签不显示，以前添加的论文，也只有一半显示了期刊标签，还有很多不显示期刊标签。

![image](https://github.com/MuiseDestiny/zotero-style/assets/43985584/a4c78ae4-eecd-4340-b5da-cd201dc1988b)
点一下条目时，右下角显示如下：
![image](https://github.com/MuiseDestiny/zotero-style/assets/43985584/ed16d32f-28a5-4bac-8042-5f019c618a69)
但是该条目的期刊标签依然为空。

**Comment by MuiseDestiny** [comment]
是否配置密钥

**Comment by WangXinrui333** [comment]
> 是否配置密钥
请问如何配置？

**Comment by MuiseDestiny** [comment]
> > 是否配置密钥
> > 请问如何配置？

readme有小红书教程参考下

**Comment by WangXinrui333** [comment]
> 

谢谢！

**Comment by WangXinrui333** [comment]
> > > 是否配置密钥
> > > 请问如何配置？
> 
> readme有小红书教程参考下

已解决，原来我重装了新版本，密钥要重新设置，多谢！
