### ISSUE TITLE
关于配置es密钥后 点击条目shift+P 不出现“影响因子”命令行的相关问题

### ISSUE THREAD

**Issue by jennyQinJN** [MuiseDestiny/zotero-style#441]
zotero版本6.0.26
zotero style版本2.6.6
操作系统 windows
已配置easyscholar密钥，在"影响因子_列"和"期刊标签_列"已显示调用easyscholar API的数据。如图1
![image](https://github.com/MuiseDestiny/zotero-style/assets/40830538/ce14ae85-4df5-42f8-87b0-237b72494876)
但shift+P中只显示"期刊标签_操作"，不显示“影响因子_操作”。如图2
![image](https://github.com/MuiseDestiny/zotero-style/assets/40830538/3723c5ff-cb7b-47c7-807b-3613d461ab0d)
p.s.

1. 插件中仅保留了zotero style插件（排除其他插件冲突）
2. “影响因子_操作”指的是shift+P“影响因子”命令行

### 疑问1：在shift+P中是否取消了“影响因子”命令行操作？
“影响因子_操作”指的是shift+P“影响因子”命令行
是不是我配置依然存在问题导致shift+P不出现“影响因子_操作”，还是在style2.6.6中由于和“期刊标签_列”的field重合，在shift+P中移除了“影响因子_操作”，仅保留“期刊标签_操作”？
我看到在release2.6.2中，“期刊标签_操作”是进入一个“友好化es密钥配置页面”，这个功能可以操作成功。如下图3给出的示例。
![image](https://github.com/MuiseDestiny/zotero-style/assets/40830538/277fc2ec-1ece-4dc5-90d8-5a2602b904ed)

或者说，在style 2.6.6中对一个条目 shift+P之后，最多出现四个操作：如图4？

1. 高能进度条
2. 标签
3. 标注
4. 期刊标签

![image](https://github.com/MuiseDestiny/zotero-style/assets/40830538/9856099b-f123-4a1b-a2b5-4c95d6ee03d8)
图4

### 疑问2：【shift+P->单击“影响因子”->查看期刊分区】功能
https://www.bilibili.com/video/BV1BA411R7hb
在该视频1:24 如图5，shift+P->单击“影响因子”，显示该“期刊的名称、ISSN、影响因子、中科院分区”。
这个通过【shift+P->单击“影响因子”->查看期刊分区】功能在zotero style 2.6.6中操作是否需要其他设置？例如，easyscholar 开通会员?
![image](https://github.com/MuiseDestiny/zotero-style/assets/40830538/54ac7331-c42e-429d-8aa1-b78c19499034)
图5
由于我没有解决疑问1，所以并不能实现视频中这部分功能。 

望回复，谢谢。

**Comment by MuiseDestiny** [comment]
移除了，但是你可以看下视频发布日期安装对应的release的插件，可以实现对应效果

**Comment by jennyQinJN** [comment]
不懂extension代码，看之前版本的Source Code好难，先不整这个看分区这个功能了。
谢谢开发大佬的回复~
