### ISSUE TITLE
星标列，不显示星星，而是乱码

### ISSUE THREAD

**Issue by NeroAsmarr** [MuiseDestiny/zotero-style#442]
<img width="667" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/44702685/4f2146da-8ad1-4c65-bcfd-26afc3dcaeea">

如图，然后点击调整评分也没变化，但是extra列会显示rate=1，=0这种变化。

我的相关环境是，mac m1，zotero6

**Comment by MuiseDestiny** [comment]
列设置，重新填写一下。
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/fdc2f306-dd1d-49ae-8a86-4ddb111c241b)
