### ISSUE TITLE
开发者您好，AMI这个数据集所有等级显示的都是一个颜色，请问是为什么呢？

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-style#444]
![CleanShot 2023-06-11 at 20 57 42@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/d2864042-44ca-4ebb-bc56-f4550d71266b)

**Comment by yzy1228682367** [comment]
还有国家社科基金这个也是
![CleanShot 2023-06-11 at 21 00 55@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/cbf1f4a2-c84f-416f-9bf9-1235e7487aa4)

**Comment by yzy1228682367** [comment]
这是这两个数据集在easyscholar上的截图
![CleanShot 2023-06-11 at 21 01 45@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/a786d45a-4e1d-42b1-822a-0ab7ecad5e21)
![CleanShot 2023-06-11 at 21 01 53@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/38815eb3-8035-41ac-a826-ebe2782e0613)

**Comment by MuiseDestiny** [comment]
因为我这没有适配它的颜色。只适配了官方数据集，用户上传没有。es官方最近也要出插件。到时候可以直接用他们的。

**Comment by yzy1228682367** [comment]
明白啦 谢谢

**Comment by MuiseDestiny** [comment]
有时间会适配

**Comment by yzy1228682367** [comment]
感谢~个人觉得AMI对于社会科学来说是仅次于CSSCI以及北大核心的评价指标啦~

**Comment by yzy1228682367** [comment]
> 因为我这没有适配它的颜色。只适配了官方数据集，用户上传没有。es官方最近也要出插件。到时候可以直接用他们的。
他们说放弃了😭

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/bf677927-a8f7-4e85-8b3f-1b427178ab67)

https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.7

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/ce268c97-aaf5-4f9a-8551-5484651455cd)

**Comment by MuiseDestiny** [comment]
已经解决，如未解决reopen
