### ISSUE TITLE
评级列和期刊标签出现乱码

### ISSUE THREAD

**Issue by sxchen-med** [MuiseDestiny/zotero-style#445]
**不礼貌不回复，直接关闭**
评级列星星看不见了；期刊标签原本的“北大中文核心”默认缩写是“北核”，现在变成了“北大中文核心”，打开列设置有乱码
<img width="212" alt="微信截图_20230611222450" src="https://github.com/MuiseDestiny/zotero-style/assets/92013578/4955fd1e-9dd9-4c77-bc8f-e2da6dd6d8ce">
环境是win10

**Comment by MuiseDestiny** [comment]
北大中文核心=北核, SCIIF=IF, SCIIF(5)=IF(5), SCI基础版=中科院,

重新填写一下，中文乱码是正常的

**Comment by cesaryuan** [comment]
> 北大中文核心=北核, SCIIF=IF, SCIIF(5)=IF(5), SCI基础版=中科院,
> 
> 重新填写一下，中文乱码是正常的

我这里的【评级】列星星也不见了
![image](https://github.com/MuiseDestiny/zotero-style/assets/35998162/68a5e08e-40d8-4d54-bcc9-27888f596185)

**Comment by iCycads** [comment]
评级标签遇到同样的问题. win10. 搞了一天还没解决.

**Comment by furyphoenix** [comment]
评级乱码，mac。希望尽快修复。

**Comment by MuiseDestiny** [comment]
回答无数遍了，右键列设置

**Comment by ZivNice** [comment]
在“列设置”里面

![image](https://github.com/MuiseDestiny/zotero-style/assets/20898065/772c9df4-5594-4418-b650-4ee860a2e77a)

**Comment by Joyzison** [comment]
> 回答无数遍了，右键列设置
但是右键列设置后出现的是期刊标签列的设置，没有这个mark选项
