### ISSUE TITLE
zotero style 2.6.7 ranking 乱码

### ISSUE THREAD

**Issue by zouwenxin66** [MuiseDestiny/zotero-style#446]
**不礼貌不回复，直接关闭**
#zotero style 2.6.7 ranking 乱码
<img width="557" alt="屏幕截图 2023-06-12 142120" src="https://github.com/MuiseDestiny/zotero-style/assets/81804985/5a092e7a-78b8-440a-a234-83fc312099d7">

**Comment by MuiseDestiny** [comment]
列设置，重新填写一下

**Comment by DaxuanCCC** [comment]
用的mac版，右键点击rating之后没有column setting这个选项，请问如何解决呀？
