### ISSUE TITLE
2.6.7 自定义pdf背景色，当鼠标选中文本时背景色消失，变为原始的白色

### ISSUE THREAD

**Issue by kkkzh** [MuiseDestiny/zotero-style#447]
只修改了background-color的颜色。可以正常显示配置的pdf背景色。但是当鼠标选中文本高亮时，背景色就会消失，变为白色。松开鼠标，背景色又会恢复。
只有自定义pdf背景色会出现这个问题，里面内置的配色没这个问题。

**Comment by MuiseDestiny** [comment]
重新下载最新版安装解决
