### ISSUE TITLE
“期刊标签”栏的中科院分期、影响因子显示问题

### ISSUE THREAD

**Issue by coool-sheep** [MuiseDestiny/zotero-style#450]
1. 希望可以选择关掉中科院分区显示。以前期刊标签栏都只有SCI分区，最近不知道为什么，打开后一直都是中科院分区也显示，还在SCI分区前面，找不到关掉的方法。
2. 希望可以手动补充期刊标签分类。有些期刊没有分区信息，我理解有些期刊可能信息不好找，但是不知道在哪里可以手动补充分类？
3. 影响因子不显示问题。之前我记得是有IF=...的选项的，现在怎么没了啊。
![image](https://github.com/MuiseDestiny/zotero-style/assets/57223448/97268564-f4fb-45e8-8d5a-fdeec27ed026)

**Comment by MuiseDestiny** [comment]
看下readme，自己去配置一下他们。

**Comment by MuiseDestiny** [comment]
是因为你一直使用的默认的，但是新版本里默认的配置改了，所以更新后就变化了。需要你自己配置。

sciwarn, sci, sciif5, cssci, xju, AMI, ccf

北大中文核心=北核, SCIIF=IF, SCIIF(5)=IF(5), SCI基础版=中科院,

#ffe2dd, #e8deee, #dbeddb, #fadec9, #e9e8e7

我的配置

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/f02c896c-bdcb-4552-b8a8-b6ce514a807e)

**Comment by coool-sheep** [comment]
好的，十分感谢解答！之前没有注意可以设置~
