### ISSUE TITLE
会议类型条目无法正常显示“期刊标签”

### ISSUE THREAD

**Issue by youngfish42** [MuiseDestiny/zotero-style#454]
需求：我希望在期刊和会议条目正常显示CCF的查询结果。

我的问题是，目前只有期刊类型的条目可以正常显示（见图1），会议类型的条目虽然可以通过 easyScholar 查询到结果，但结果并没有显示在“期刊标签”列（见图2）。

![图1](https://github.com/MuiseDestiny/zotero-style/assets/38998412/aad62551-299d-4b7b-bba0-c513aca3e8fc)

![图2](https://github.com/MuiseDestiny/zotero-style/assets/38998412/d47bfebe-a1e6-42d4-a29d-ee513d7ab400)

我的“期刊标签”列的配置如下图
![图片](https://github.com/MuiseDestiny/zotero-style/assets/38998412/fc01cd9e-cfb7-44e7-a92f-6f821323ee44)

**Comment by MuiseDestiny** [comment]
1密钥有没有配置
2es有没有充钱

免费的现在只提供基础字段，据我所知cff是自定义字段，需要订阅服务

**Comment by youngfish42** [comment]
> 1密钥有没有配置 2es有没有充钱
> 
> 免费的现在只提供基础字段，据我所知cff是自定义字段，需要订阅服务

1.密钥有配置
2.es不充值也可以配置几个自定义字段，我目前只配置了ccf。

从图1可以很明显看到，对于期刊条目并显示了CCF的结果。
从图2的右下角可以看到，es给出了正确的CCF rank的结果，但并未在条目中显示。

**Comment by MuiseDestiny** [comment]
是不是最近更新后不显示的，可能写出bug了

**Comment by youngfish42** [comment]
> 是不是最近更新后不显示的，可能写出bug了

我使用的是 2.6.7 版，确实没尝试更早的版本

**Comment by seifer08ms** [comment]
我es充钱了，也是点击列后查询到es搜索的会议ccf rank结果，不能更新到出版列上。我也是用的2.6.7。

**Comment by Polylanger** [comment]
兄弟，你在 Field 里边加一个大写的 “CCF” 试一下。
![image](https://github.com/MuiseDestiny/zotero-style/assets/13899655/693dd6f6-d657-4bc2-bb65-58e59aad8e32)

easyscholar的官方CCF数据集的标识是小写的 ccf，数据集社区中有一个标识为大写CCF的数据集，zotero-style目测是默认大小写敏感，你把大小写都写上去两个就都能显示出来了
![image](https://github.com/MuiseDestiny/zotero-style/assets/13899655/b650ad44-5074-4383-ba9b-abba7c9667d6)

我肉眼观察了一下，官方和社区数据集大部分互为补充，只有个别情况会出现二者同时都有数据，都有数据的时候，在easyscholar的接口响应结果像下面这样，customRank中包含CCF，officialRank中有ccf：
```json
{
    "code": 200,
    "msg": "SUCCESS",
    "data": {
        "customRank": {
            "rankInfo": [
                {
                    "uuid": "1614919989423271936",
                    "abbName": "CCF",
                    "oneRankText": "A",
                    "twoRankText": "B",
                    "threeRankText": "C"
                },
                {
                    "uuid": "1676584188322156544",
                    "abbName": "CCF_CN",
                    "oneRankText": "A",
                    "twoRankText": "B",
                    "threeRankText": "C"
                }
            ],
            "rank": [
                "1614919989423271936&&&1"
            ]
        },
        "officialRank": {
            "all": {
                "swufe": "A+",
                "uibe": "B",
                "sdufe": "特类期刊",
                "swjtu": "A+",
                "ruc": "A",
                "nju": "A",
                "xju": "二区",
                "cug": "工程技术T2",
                "ccf": "A",
                "sciif": "8.9",
                "sci": "Q1",
                "sciBase": "工程技术2区",
                "sciUp": "计算机科学2区",
                "eii": "EI",
                "scu": "计算机科学B",
                "sciif5": "8.9",
                "fms": "B",
                "jci": "1.82"
            },
            "select": {
                "swufe": "A+",
                "uibe": "B",
                "sdufe": "特类期刊",
                "swjtu": "A+",
                "ruc": "A",
                "nju": "A",
                "xju": "二区",
                "cug": "工程技术T2",
                "ccf": "A",
                "sciif": "8.9",
                "sci": "Q1",
                "sciBase": "工程技术2区",
                "sciUp": "计算机科学2区",
                "eii": "EI",
                "scu": "计算机科学B",
                "sciif5": "8.9",
                "fms": "B",
                "jci": "1.82"
            }
        }
    }
}
```
这种情况下，在 zotero-style 上会显示两个相同的标签
![image](https://github.com/MuiseDestiny/zotero-style/assets/13899655/5c50093c-cc82-4e7d-ae67-c7eef5bb67e9)

**Comment by youngfish42** [comment]
> 兄弟，你在 Field 里边加一个大写的 “CCF” 试一下。 ![image](https://user-images.githubusercontent.com/13899655/263250945-693dd6f6-d657-4bc2-bb65-58e59aad8e32.png)
> 
> easyscholar的官方CCF数据集的标识是小写的 ccf，数据集社区中有一个标识为大写CCF的数据集，zotero-style目测是默认大小写敏感，你把大小写都写上去两个就都能显示出来了 ![image](https://user-images.githubusercontent.com/13899655/263255447-b650ad44-5074-4383-ba9b-abba7c9667d6.png)
> 
> 我肉眼观察了一下，官方和社区数据集大部分互为补充，只有个别情况会出现二者同时都有数据，都有数据的时候，在easyscholar的接口响应结果像下面这样，customRank中包含CCF，officialRank中有ccf：
> 
> ```json
> {
>     "code": 200,
>     "msg": "SUCCESS",
>     "data": {
>         "customRank": {
>             "rankInfo": [
>                 {
>                     "uuid": "1614919989423271936",
>                     "abbName": "CCF",
>                     "oneRankText": "A",
>                     "twoRankText": "B",
>                     "threeRankText": "C"
>                 },
>                 {
>                     "uuid": "1676584188322156544",
>                     "abbName": "CCF_CN",
>                     "oneRankText": "A",
>                     "twoRankText": "B",
>                     "threeRankText": "C"
>                 }
>             ],
>             "rank": [
>                 "1614919989423271936&&&1"
>             ]
>         },
>         "officialRank": {
>             "all": {
>                 "swufe": "A+",
>                 "uibe": "B",
>                 "sdufe": "特类期刊",
>                 "swjtu": "A+",
>                 "ruc": "A",
>                 "nju": "A",
>                 "xju": "二区",
>                 "cug": "工程技术T2",
>                 "ccf": "A",
>                 "sciif": "8.9",
>                 "sci": "Q1",
>                 "sciBase": "工程技术2区",
>                 "sciUp": "计算机科学2区",
>                 "eii": "EI",
>                 "scu": "计算机科学B",
>                 "sciif5": "8.9",
>                 "fms": "B",
>                 "jci": "1.82"
>             },
>             "select": {
>                 "swufe": "A+",
>                 "uibe": "B",
>                 "sdufe": "特类期刊",
>                 "swjtu": "A+",
>                 "ruc": "A",
>                 "nju": "A",
>                 "xju": "二区",
>                 "cug": "工程技术T2",
>                 "ccf": "A",
>                 "sciif": "8.9",
>                 "sci": "Q1",
>                 "sciBase": "工程技术2区",
>                 "sciUp": "计算机科学2区",
>                 "eii": "EI",
>                 "scu": "计算机科学B",
>                 "sciif5": "8.9",
>                 "fms": "B",
>                 "jci": "1.82"
>             }
>         }
>     }
> }
> ```
> 
> 这种情况下，在 zotero-style 上会显示两个相同的标签 ![image](https://user-images.githubusercontent.com/13899655/263258411-5c50093c-cc82-4e7d-ae67-c7eef5bb67e9.png)


可行，非常感谢！

**Comment by Lrynoa** [comment]
我这边更新期刊时显示publication tags not found，请问要怎么办呢？

**Comment by MuiseDestiny** [comment]
> ion tags not found，请问要怎么办呢？

看下期刊是否拼错 是简称

**Comment by Lrynoa** [comment]
> > ion tags not found，请问要怎么办呢？
> 
> 看下期刊是否拼错 是简称

您好，我已经解决了这个问题。虽然不知道怎么解决的。我想请问style能够更新”期刊标签“和”引用数“，但为什么【列】中没有[引用数]的展示呢？

**Comment by LiHui1116** [comment]
请问这个publication tags在zotero里怎么设置呢？就是下面那个图里的设置在哪？

> > 兄弟，你在 Field 里边加一个大写的 “CCF” 试一下。 ![image](https://user-images.githubusercontent.com/13899655/263250945-693dd6f6-d657-4bc2-bb65-58e59aad8e32.png)
> > easyscholar的官方CCF数据集的标识是小写的 ccf，数据集社区中有一个标识为大写CCF的数据集，zotero-style目测是默认大小写敏感，你把大小写都写上去两个就都能显示出来了 ![image](https://user-images.githubusercontent.com/13899655/263255447-b650ad44-5074-4383-ba9b-abba7c9667d6.png)
> > 我肉眼观察了一下，官方和社区数据集大部分互为补充，只有个别情况会出现二者同时都有数据，都有数据的时候，在easyscholar的接口响应结果像下面这样，customRank中包含CCF，officialRank中有ccf：
> > {
> >     "code": 200,
> >     "msg": "SUCCESS",
> >     "data": {
> >         "customRank": {
> >             "rankInfo": [
> >                 {
> >                     "uuid": "1614919989423271936",
> >                     "abbName": "CCF",
> >                     "oneRankText": "A",
> >                     "twoRankText": "B",
> >                     "threeRankText": "C"
> >                 },
> >                 {
> >                     "uuid": "1676584188322156544",
> >                     "abbName": "CCF_CN",
> >                     "oneRankText": "A",
> >                     "twoRankText": "B",
> >                     "threeRankText": "C"
> >                 }
> >             ],
> >             "rank": [
> >                 "1614919989423271936&&&1"
> >             ]
> >         },
> >         "officialRank": {
> >             "all": {
> >                 "swufe": "A+",
> >                 "uibe": "B",
> >                 "sdufe": "特类期刊",
> >                 "swjtu": "A+",
> >                 "ruc": "A",
> >                 "nju": "A",
> >                 "xju": "二区",
> >                 "cug": "工程技术T2",
> >                 "ccf": "A",
> >                 "sciif": "8.9",
> >                 "sci": "Q1",
> >                 "sciBase": "工程技术2区",
> >                 "sciUp": "计算机科学2区",
> >                 "eii": "EI",
> >                 "scu": "计算机科学B",
> >                 "sciif5": "8.9",
> >                 "fms": "B",
> >                 "jci": "1.82"
> >             },
> >             "select": {
> >                 "swufe": "A+",
> >                 "uibe": "B",
> >                 "sdufe": "特类期刊",
> >                 "swjtu": "A+",
> >                 "ruc": "A",
> >                 "nju": "A",
> >                 "xju": "二区",
> >                 "cug": "工程技术T2",
> >                 "ccf": "A",
> >                 "sciif": "8.9",
> >                 "sci": "Q1",
> >                 "sciBase": "工程技术2区",
> >                 "sciUp": "计算机科学2区",
> >                 "eii": "EI",
> >                 "scu": "计算机科学B",
> >                 "sciif5": "8.9",
> >                 "fms": "B",
> >                 "jci": "1.82"
> >             }
> >         }
> >     }
> > }
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这种情况下，在 zotero-style 上会显示两个相同的标签 ![image](https://user-images.githubusercontent.com/13899655/263258411-5c50093c-cc82-4e7d-ae67-c7eef5bb67e9.png)
> 
> 可行，非常感谢！
