### ISSUE TITLE
文献的被引次数

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [MuiseDestiny/zotero-style#455]
建议大佬把文献的被引次数的功能也能整合进插件中。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/3c77aca4-7a9b-4fa6-9be4-7787c80db8ba)

**Comment by MuiseDestiny** [comment]
暂未开放

**Comment by mzcxiaohuanxiong** [comment]
谢谢大佬的回复，辛苦，坐等开放


小孟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月16日(星期五) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-style] 文献的被引次数 (Issue #455)





 
暂未开放
