### ISSUE TITLE
评级显示问题

### ISSUE THREAD

**Issue by shao12781566** [MuiseDestiny/zotero-style#456]
你好，在更新到最新版本后，评级部分出现乱码
![image](https://github.com/MuiseDestiny/zotero-style/assets/57243196/72766092-b251-46cd-b343-3a9a021fb4ef)
如上图

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues?q=%E8%AF%84%E7%BA%A7

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/445
