### ISSUE TITLE
“最近添加”和“最近修改”自定义搜索

### ISSUE THREAD

**Issue by youngfish42** [MuiseDestiny/zotero-style#457]
插件版本：2.6.7

![图片](https://github.com/MuiseDestiny/zotero-style/assets/38998412/60ce87ca-fb4e-41bc-a5dc-790e7b0ffd3b)

如上图所示，有两个问题：
问题1：当在多个设备上使用 Zotero-style 的时候，会出现多组的“最近添加”和“最近修改”文件夹。（比如我这里是两个设备在使用，那就出现了两组。删除多余的文件夹后，再次打开Zotero又会出现）
问题2：“Rencent Added”拼写有误。

**Comment by MuiseDestiny** [comment]
> 插件版本：2.6.7
> 
> ![图片](https://user-images.githubusercontent.com/38998412/246651466-60ce87ca-fb4e-41bc-a5dc-790e7b0ffd3b.png)
> 
> 如上图所示，有两个问题： 问题1：当在多个设备上使用 Zotero-style 的时候，会出现多组的“最近添加”和“最近修改”文件夹。（比如我这里是两个设备在使用，那就出现了两组。删除多余的文件夹后，再次打开Zotero又会出现） 问题2：“Rencent Added”拼写有误。

确实没考虑多设备同步问题

**Comment by youngfish42** [comment]
> > 插件版本：2.6.7
> > ![图片](https://user-images.githubusercontent.com/38998412/246651466-60ce87ca-fb4e-41bc-a5dc-790e7b0ffd3b.png)
> > 如上图所示，有两个问题： 问题1：当在多个设备上使用 Zotero-style 的时候，会出现多组的“最近添加”和“最近修改”文件夹。（比如我这里是两个设备在使用，那就出现了两组。删除多余的文件夹后，再次打开Zotero又会出现） 问题2：“Rencent Added”拼写有误。
> 
> 确实没考虑多设备同步问题

或许这个功能也可以由用户自己选择开启或关闭？（那么就只需要在1个设备上开启就好了）

**Comment by MuiseDestiny** [comment]
有道理，这样可以解决

**Comment by youngfish42** [comment]
> 有道理，这样可以解决

当然，更好的做法是，在添加这俩筛选搜索前，检查一下有没有和这俩重名的文件夹~

**Comment by luchaoqi** [comment]
+1 多设备碰到了同样的问题

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.8

修复了

**Comment by immobilization** [comment]
请问，这两项搜索功能可以关闭吗？

**Comment by MuiseDestiny** [comment]
> 请问，这两项搜索功能可以关闭吗？

降级插件即可

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/8764a859-4c00-4a30-aa06-3aec73d4c4c7)


zotero7版本将支持关闭

**Comment by sdrzhlchx** [comment]
> 插件版本：2.6.7
> 
> ![图片](https://user-images.githubusercontent.com/38998412/246651466-60ce87ca-fb4e-41bc-a5dc-790e7b0ffd3b.png)
> 
> 如上图所示，有两个问题： 问题1：当在多个设备上使用 Zotero-style 的时候，会出现多组的“最近添加”和“最近修改”文件夹。 （比如我这里是两个设备在使用，那就出现了两组。 删除多余的文件夹后，再次打开Zotero又会出现） 问题2：“Rencent Added”拼写有误。

你好，我是多次下载Zotero在一个电脑上，也出现这种问题了，请问怎么解决呢？

**Comment by Hwenshuo** [comment]
您好，请问在适用zotero7的最新插件中为什么没有这个recent选项了呢？
![image](https://github.com/user-attachments/assets/49207c6c-54c7-47bf-8890-9a4070d789c4)
