### ISSUE TITLE
Addon Settings are blank

### ISSUE THREAD

**Issue by jordanmsmith** [MuiseDestiny/zotero-style#464]
I am only an English speaker, so I included a translation from Google Translate. Sorry if it is poor.
我只會說英語，所以我添加了谷歌翻譯的翻譯。 抱歉，如果很窮。

# Issue
## The addon settings are blank in the tab for "Zotero Style"
“Zotero Style”選項卡中的插件設置為空
![Screenshot 2023-06-24 063150](https://github.com/MuiseDestiny/zotero-style/assets/66657650/7f2f9f10-7b57-4872-88c8-b733417c22d7)

## This is also true for your other addon "Zotero Reference"
這對於您的其他插件“Zotero Reference”也是如此
![Screenshot 2023-06-24 063556](https://github.com/MuiseDestiny/zotero-style/assets/66657650/d6657566-ef5f-4e19-a439-3ff97204ae44)

## Other addons do not seem to have this issue
其他插件好像沒有這個問題
![Screenshot 2023-06-24 063725](https://github.com/MuiseDestiny/zotero-style/assets/66657650/f8032a5b-d0cc-472c-abd9-cd0df49a8748)

I can still edit the settings manually in prefs.js, so it is mostly just a slight inconvenience.
我仍然可以在 prefs.js 中手動編輯設置，所以這主要只是有點不便。

# Info and things I have tried
我嘗試過的信息和事情

* Running latest Zotero 7 beta build
* Running latest version of the addon
* Windows 64bit
* I completely uninstalled Zotero and removed all settings, and then reinstalled and the issue persisted

* 運行最新的 Zotero 7 beta 版本
* Windows 64位
* 我完全卸載了 Zotero 並刪除了所有設置，然後重新安裝，問題仍然存在

**Comment by MuiseDestiny** [comment]
Sorry, I have fixed it but not release. I will release these soon.

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.8
