### ISSUE TITLE
mac M1 pro 好像不适配是吗？？？

### ISSUE THREAD

**Issue by QinghuaHao** [MuiseDestiny/zotero-style#465]
我用mac M1有一部分功能没办法使用，比如进度～和调色

**Comment by MuiseDestiny** [comment]
可以的，只要zotero可以使用，插件就可以

**Comment by QinghuaHao** [comment]
> 可以的，只要zotero可以使用，插件就可以

但是我的进度用不了，设置里面也很多项没办法用，您告诉我怎么设置一下吗，我可以把截图发给您

**Comment by QinghuaHao** [comment]
> 可以的，只要zotero可以使用，插件就可以

sorry， 我的问题可以用
