### ISSUE TITLE
关于一些功能的疑问

### ISSUE THREAD

**Issue by ku-zhen** [MuiseDestiny/zotero-style#47]
1. **如下菜单没有视图设置选项：**

![image](https://user-images.githubusercontent.com/61906420/211545321-5d8f0969-3033-492a-9c7c-fc41116ae10c.png)

2. **命令面板除了前三列，其他几天命令无反应：**

![image](https://user-images.githubusercontent.com/61906420/211545447-780c256a-41e1-42fc-bd8f-1f520e334b83.png)

3. **有时命令面板为空：**

![image](https://user-images.githubusercontent.com/61906420/211545938-1a07db95-b28b-485f-801b-f15f4b84c803.png)

以上问题，请问是我操作不当，还是版本不兼容？

- OS：Windows10
- Zotero：6最新版

**Comment by MuiseDestiny** [comment]
停用老版本，装新版本（1.5.0）试试，不建议长期使用，有些东西还没优化好，可能有点卡
