### ISSUE TITLE
无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容

### ISSUE THREAD

**Issue by 1263892066** [MuiseDestiny/zotero-style#471]
zotero版本6.0.26
安装Green Frog的时候提示：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。
麻烦楼主答疑，谢谢！！

**Comment by MuiseDestiny** [comment]
好像问错地方了。

**Comment by xunx911** [comment]
一样的问题

**Comment by SmartNan** [comment]
下载最新的版本，安装的过程中显示：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。zotero版本6.0.26
麻烦楼主看看！

**Comment by yangluom** [comment]
下载最新的版本，安装的过程中显示：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。zotero版本6.0.26
麻烦楼主看看！

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/9099d3d2-5efb-4cf9-ad96-782343c75baa)
