### ISSUE TITLE
期刊标签中自定义数据集读取后在zotero里面显示不出来

### ISSUE THREAD

**Issue by shuaiyb** [MuiseDestiny/zotero-style#472]
您好！打扰您，想跟您咨询一下，就是目前我用的zotero7 ，2.6.8的style版本，在使用期刊标签读取自定义数据集时遇到问题。
第一个问题是在新导入的文献上，我点击期刊标签，在旁边的小窗口会显示已经读取了，但是在期刊标签这一栏不会显示出来。

![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/79e1543a-0121-447d-ae64-7e83479f0fe4)
第二个问题是，在之前没更新的时候读取出来的记录，再重新点击期刊标签获取后，自定义的那栏会消失。
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/c50ca2ad-d2a2-41ea-abcf-6a9c73f36d21)
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/fc4f0ad5-9e09-4630-9613-1cdef156a11a)
这是我的设置，不知道是哪里出了问题，我试过其他的非自定义的都行。
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/c2b8b6d4-fdd8-49b5-9ec7-99f571a637cd)
麻烦您帮忙看看，谢谢啦

**Comment by MuiseDestiny** [comment]
为了复现bug，需要确认下面的信息：
1. 如何在es里添加这个自定义数据集，显示CPU
2. 提供一个可以显示CPU的期刊名称

**Comment by shuaiyb** [comment]
你好，es里面添加这个数据集是在自定义数据库里面，在期刊标签中对应的fileds是CPU
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/20781daa-8ff9-4e28-80ed-ac7f77456ef2)
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/9ad8e928-ac6c-4ef4-b727-029f3bb15975)

2.可以显示CPU的期刊名称：Cell；正常来讲会显示权威期刊或者CPU权威
麻烦您帮忙看看，谢谢啦！

**Comment by shuaiyb** [comment]
> 为了复现bug，需要确认下面的信息：
> 
>     1. 如何在es里添加这个自定义数据集，显示CPU
> 
>     2. 提供一个可以显示CPU的期刊名称

你好，es里面添加这个数据集是在自定义数据库里面，在期刊标签中对应的fileds是CPU

![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/308bce50-a185-46d4-9261-1ef7d8348114)
![图片](https://github.com/MuiseDestiny/zotero-style/assets/124781989/49f4b482-aa71-440d-a1ea-34191f27093e)


2.可以显示CPU的期刊名称：Cell；正常来讲会显示权威期刊或者CPU权威
麻烦您帮忙看看，谢谢啦！

**Comment by MuiseDestiny** [comment]
找到原因：CPU是官方提供的字段，用自定义字段时候冲突。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/9ea2cb1d-27cc-4251-87a2-07b5b6e6d496)


zotero7测试正常

https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-zo7-472.xpi

**Comment by MuiseDestiny** [comment]
如未解决reopen

**Comment by shuaiyb** [comment]
> 如未解决reopen

能看看大佬您的列设置么，我这边还是没什么变化，读取后还是出现不了，之前的也会消失，谢谢您。

**Comment by MuiseDestiny** [comment]
> https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-zo7-472.xpi

不应该啊是https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-zo7-472.xpi这个版本嘛

**Comment by shuaiyb** [comment]
是的，我卸载了再重新装的，😭好奇怪，我再摸索一下，field那里写的CPU，不知道是不是哪里设置出问题了。发自我的 iPhone在 2023年6月30日，21:18，Polygon ***@***.***> 写道：﻿

https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-zo7-472.xpi

不应该啊是https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-zo7-472.xpi这个版本嘛
