### ISSUE TITLE
如何通过{placeholder}获取杂志的信息？

### ISSUE THREAD

**Issue by LamFTS** [MuiseDestiny/zotero-style#474]
开发者您好，我在使用zotcard的模板功能，里面有一些{palceholder}是可以直接获取文献的信息的，比如模板里的${title}在创建笔记时候会自动填充上文章的标题，${publicationTitle}就可以获取期刊名称等等，请问一下，zotero style里的`期刊标签`里的内容，比如分区、影响因子等内容，能否通过{palceholder}的形式获取呢？

**Comment by MuiseDestiny** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/521

参考我为better notes写的。

期刊标签并非简单的文本，而是复杂的html语言，需要特殊手段读取。

**Comment by LamFTS** [comment]
不知道是哪里操作有误，我插入模板的时候会显示下面的错误：
![图片](https://github.com/MuiseDestiny/zotero-style/assets/53118840/5d760bde-27cc-40b2-9409-b765f0a9a542)

**Comment by MuiseDestiny** [comment]
> 不知道是哪里操作有误，我插入模板的时候会显示下面的错误： ![图片](https://user-images.githubusercontent.com/53118840/249719324-5d760bde-27cc-40b2-9409-b765f0a9a542.png)

是基于better notes系的，我不了解ztcard语法，这个只做参考，不能直接复制粘贴。

**Comment by LamFTS** [comment]
可是这个就是better notes模板提示的错误信息。:(
