### ISSUE TITLE
评级显示出现Bug

### ISSUE THREAD

**Issue by Kaergo** [MuiseDestiny/zotero-style#476]
![IP`45JF0`SW~%`W{{Z0FGB2](https://github.com/MuiseDestiny/zotero-style/assets/54634271/ca4019d8-e53e-488c-aa6e-e2f6a5b3b3f8)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues?q=%E8%AF%84%E7%BA%A7

**Comment by Kaergo** [comment]
好的谢谢
