### ISSUE TITLE
请问嵌套标签为什么会变成这样了呢？

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-style#477]
**不礼貌不回复，直接关闭**
![CleanShot 2023-07-03 at 10 45 43@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/3629a727-55df-4b9b-80b4-470d8e37fb8f)

**Comment by yzy1228682367** [comment]
![CleanShot 2023-07-03 at 11 13 37@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/1cc84afa-da11-42ce-8368-141f1b3a26a5)
会不会跟这里有关系呢？这里的Nested tag link symbol选中了以后仍然是空白的。

**Comment by MuiseDestiny** [comment]
你的插件版本，看到你的截图是zotero6，不能使用最新版。用2.6.7

**Comment by yzy1228682367** [comment]
![CleanShot 2023-07-03 at 21 33 38@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/916ce7a0-d789-414a-9e01-02f4acfd1b24)
是2.6.7耶，但是还是会出现上述情况。

**Comment by MuiseDestiny** [comment]
我觉得好像是插件的默认设置没有配置到你的zo里

**Comment by MuiseDestiny** [comment]
明天远程看看吧 可以b站私信我联系

**Comment by yzy1228682367** [comment]
好滴 谢啦❤️
