### ISSUE TITLE
期刊标签失效，嵌套标签显示所有标签，请问应该怎么操作？

### ISSUE THREAD

**Issue by AlephZr** [MuiseDestiny/zotero-style#482]
原本使用是正常的，但是某天就突然发现变了，也不知道是不是因为自己误操作了什么，但我近期应该没有改过设置。

1. 现在的嵌套标签会显示整个文献库里的所有标签：
![image](https://github.com/MuiseDestiny/zotero-style/assets/38972838/fe143c5c-e06a-4c48-82da-61e9aa64eb2d)
灰色的就是其他分类中的标签，原本是不显示的。
在切回默认标签的时候是正常的：
![image](https://github.com/MuiseDestiny/zotero-style/assets/38972838/47e8ab26-80bc-4c83-9aea-1895c02f1aca)
只有当前子分类的标签

2. 期刊标签之前是正常的，但现在空了：
![image](https://github.com/MuiseDestiny/zotero-style/assets/38972838/6c7f530a-7ebd-4420-b9f4-8cfce9a21b86)
我尝试重新设置easyscholar解决这个问题。但是现在的shift+p里没有期刊标签，只有更新期刊标签，而且不知道为什么better notes的模板也在这里：
![image](https://github.com/MuiseDestiny/zotero-style/assets/38972838/983930aa-617f-4051-a7da-793592c089a5)
如果点击更新期刊标签则会有这样的提示：
![image](https://github.com/MuiseDestiny/zotero-style/assets/38972838/9b8d2da9-74c1-4729-870b-fb2768657cf6)

3. 当时最明显的改变是评级中的符号变成了乱码，不过这个问题好解决，重新设置评级符号就行。

我用的是Windows系统，插件版本2.6.7，zotero版本是6.0.26。
这个情况其实有一段时间了，不过之前忙于其他事，没有顾上这边。而且也想尝试重启软件，重启电脑能不能行，但目前为止都没有解决。

请问这种情况有没有解决的办法？嵌套标签和期刊标签都挺好用的，现在这样用不了很可惜。

**Comment by MuiseDestiny** [comment]
降级2.6.7

**Comment by AlephZr** [comment]
> 降级2.6.7

现在是2.6.7，请问降到哪个版本比较合适呢？

**Comment by AlephZr** [comment]
已解决。重建一个zotero环境，然后在干净的环境中安装插件就能恢复正常。
这么看的话更像是某个地方的设置有误，但奇怪的是出问题前后我并没有改过设置。
