### ISSUE TITLE
style 有些列不显示，如引用数，在设置里面已经启用该功能。

### ISSUE THREAD

**Issue by jlu511** [MuiseDestiny/zotero-style#484]
style 有些列不显示，如引用数，在设置里面已经启用该功能。
7.0.0-beta.16+1766f8bb5 (64-bit)
[zotero-style-0702.xpi](https://github.com/MuiseDestiny/zotero-style/releases/download/2.6.8/zotero-style-0702.xpi)
WIn10 64bit
1、设置里面已经启用全部功能，
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/fb254603-b668-4e4d-966e-ff84c42e8411)
2、列，里面没有引用数这个列的选项。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/b6d3f064-039a-471c-9315-9835e7bf1837)
3、在设置里面只打开引用数，其它关闭，列里面也不显示引用数的列。

**Comment by jlu511** [comment]
更多列的选项里面也没有，引用数这个列

**Comment by MuiseDestiny** [comment]
未开放
