### ISSUE TITLE
全文翻译导出到笔记后，如果删除该笔记，再次点击翻译，生成的新笔记会是undefined

### ISSUE THREAD

**Issue by Nesln** [MuiseDestiny/zotero-style#496]
如题
感谢大大为这个插件的无私奉献
# undefined

* * *

# Abstract

**Comment by MuiseDestiny** [comment]
很有可能和储存有关，
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/e15dc51a-0db6-4eae-a684-91e8821b982c)

设置成这样应该就不会有问题了

**Comment by Nesln** [comment]
感谢大大的及时回复！ 
我的系统，MacOS ventura 13.0 M1 silicon
zotero及相关插件均按照您的b站视频所要求的版本进行安装
根据您提供的方法：
1.我测试了十几篇文献，均有类似的问题
2.目前通过手动指定storage似乎不能解决问题，如图，一篇pdf在刚开始翻译的时候会在右下角的窗口处快速的加载翻译到哪个段落，但是在翻译过一次之后，就不会再进行这一步，而是直接提示translating.... done!，返回的内容则是undefined
<img width="333" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/80193160/87441f4d-20b9-43d1-8cde-3323a96da0c3">

对应style.json的文件：
"W5U95WWY":{"readingTime":{"page":10,"data":{"0":10,"1":60,"2":300,"3":40,"4":110,"5":60}}},

对应的pdf文件
[Wu 等 - 2022 - Air pollution as a risk factor for Cognitive Impai.pdf](https://github.com/MuiseDestiny/zotero-style/files/12109126/Wu.-.2022.-.Air.pollution.as.a.risk.factor.for.Cognitive.Impai.pdf)


正常翻译内容：
<img width="506" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/80193160/5da984ab-8917-4f06-bffe-38ae7677316b">

异常翻译内容：
<img width="481" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/80193160/ede2b597-66ee-4a9b-897b-5b99ad745251">

**Comment by Nesln** [comment]
向您说声对不起，我还想补充一个信息——
就是我在指定好style的storage，并再次重启zotero后  shift+P呼出的zotero-style菜单里只有“高能进度条、标注、更新期刊标签、更新被引数”等四个选项了，全文翻译的那个选项丢失了:)

**Comment by MuiseDestiny** [comment]
明天有时间修复这个bug

**Comment by Geo123abc** [comment]
> 如题 感谢大大为这个插件的无私奉献
> 
> # undefined
> # Abstract

[一篇文献使用“全文翻译”之后不能再次使用“全文翻译” · Issue #501 · MuiseDestiny/zotero-style](  https://github.com/MuiseDestiny/zotero-style/issues/501  )    

和这个是一个问题，重新下载最新版（版本号也是 v2.7.0,但是文件发生了改变）解决。

**Comment by Nesln** [comment]
问题已经得到了解决，即下载latest version v2.70
