### ISSUE TITLE
使用得时候发现#标签这一个选项没了，退回2.6.7和2.6.6也不能解决

### ISSUE THREAD

**Issue by isYanzhe** [MuiseDestiny/zotero-style#497]
![微信图片_20230720202216](https://github.com/MuiseDestiny/zotero-style/assets/55132509/58b4baf3-9274-4f84-915e-6e6e248d7d40)

想请问下这可能是什么原因以及怎么修复

**Comment by MuiseDestiny** [comment]
这个不是bug。你要选中一个`带有标签`的文献后按shift+p
