### ISSUE TITLE
shift+P 无法唤出命令窗口

### ISSUE THREAD

**Issue by TalkingSomething** [MuiseDestiny/zotero-style#50]
我的shift+P 会因为热键冲突，直接在搜索栏搜索P。无法调出命令窗口，有什么解决的办法吗？谢谢

**Comment by MuiseDestiny** [comment]
> 我的shift+P 会因为热键冲突，直接在搜索栏搜索P。无法调出命令窗口，有什么解决的办法吗？谢谢

shift+p调出prompt弹窗是老版本功能，新版本还没来得及加，准备做到工具箱，所有创建都可以在这里创建命令（要过段时间）。

**Comment by TalkingSomething** [comment]
好的，非常感谢，期待新版本

**Comment by MuiseDestiny** [comment]
2.0.1可以了
