### ISSUE TITLE
一篇文献使用“全文翻译”之后不能再次使用“全文翻译”

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-style#501]
一篇文献使用“全文翻译”之后不能再次使用“全文翻译”，
即使把原来的翻译删除了，第二次翻译也只是生成一个只有 两个标题的空note

**Comment by MuiseDestiny** [comment]
重新下载最新版解决。

**Comment by Geo123abc** [comment]
谢谢你，太厉害了

**Comment by Geo123abc** [comment]
请教一下 Grobid 这个依赖他们提供的网络服务吧？

**Comment by MuiseDestiny** [comment]
是他们的服务，用的人多了可能grobid会关闭服务。

**Comment by Geo123abc** [comment]
> 是他们的服务，用的人多了可能grobid会关闭服务。

我是看了note的标签，看到了“Grobid ”这个生词，然后查了一下，发现新大陆的感觉，PDF太需要这样的工具了

他们那个模型能离线部署吗？看了下，不太懂编程，也没整明白

**Comment by MuiseDestiny** [comment]
> > 是他们的服务，用的人多了可能grobid会关闭服务。
> 
> 我是看了note的标签，看到了“Grobid ”这个生词，然后查了一下，发现新大陆的感觉，PDF太需要这样的工具了
> 
> 他们那个模型能离线部署吗？看了下，不太懂编程，也没整明白

能，docker很方便。semantics很多工作基于它。

但是grobid的解析也会存在断落文字丢失问题。

**Comment by Geo123abc** [comment]
> > > 是他们的服务，用的人多了可能grobid会关闭服务。
> > 
> > 
> > 我是看了note的标签，看到了“Grobid ”这个生词，然后查了一下，发现新大陆的感觉，PDF太需要这样的工具了
> > 他们那个模型能离线部署吗？看了下，不太懂编程，也没整明白
> 
> 能，docker很方便。semantics很多工作基于它。
> 
> 但是grobid的解析也会存在断落文字丢失问题。

那挺好，希望官方能长久下去

这个也解疑了一个长期困扰我的问题，Connected Papers之类网站把文献连接起来的原理，应该就是通过Grobid 这样的工具提取reference，然后再进行文献引用链接，不过中间肯定还有很多细节需要处理

题外话：
6月份我是用浏览器插件[Immersive Translate](  https://github.com/immersive-translate  )   +GPT3.5 翻译PDF还可以，感觉翻译效果少了很多机器味道，读起来也很自然，但是最近不行了，可能是GPT请求限制，这个插件有个优点就是可以使用[多个gpt的key做负载均衡](https://immersivetranslate.com/docs/services/openai/#:~:text=%E6%B2%89%E6%B5%B8%E5%BC%8F%E7%BF%BB%E8%AF%91%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%20API%20Key%20%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1%2C%20%E8%AF%B7%E5%9C%A8%E5%A1%AB%E5%86%99%E7%9A%84%E6%97%B6%E5%80%99%E7%94%A8%E8%8B%B1%E6%96%87%E9%80%97%E5%8F%B7%20%2C%20%E5%88%86%E9%9A%94%E4%B8%8D%E5%90%8C%E7%9A%84%20key)。

在使用zotero style全文翻译时， zotero pdf translate翻译引擎设置为GPT，也不太行，成功率低，不知道zotero pdf translate引入多个key机制之后会不会好点，我在[这里](https://github.com/windingwind/zotero-pdf-translate/issues/460#issuecomment-1643417376)提了一下，等下我去那边开个issue吧

**Comment by MuiseDestiny** [comment]
> Connected Papers之类网站把文献连接起来的原理

Semantrics那边做好了文献的向量，这些工作不是cp做的，他们应该也是用S2的接口

**Comment by Geo123abc** [comment]
> > Connected Papers之类网站把文献连接起来的原理
> 
> Semantrics那边做好了文献的向量，这些工作不是cp做的，他们应该也是用S2的接口

原来如此，这些东西得用起来，不然是累赘，而不是垫脚石

其实对于zotero style，我不知道能不能出一个功能，一键更新文献库或者某个文件夹中文献的相互引用关系，这个可能会触发服务商请求的限制

我目前都是看到好文章，然后再把这篇文章的参考文献通过web of science导入到zotero，然后查重、合并条目，这种手工搞，效率贼低

**Comment by MuiseDestiny** [comment]
> > > Connected Papers之类网站把文献连接起来的原理
> > 
> > 
> > Semantrics那边做好了文献的向量，这些工作不是cp做的，他们应该也是用S2的接口
> 
> 原来如此，这些东西得用起来，不然是累赘，而不是垫脚石
> 
> 其实对于zotero style，我不知道能不能出一个功能，一键更新文献库或者某个文件夹中文献的相互引用关系，这个可能会触发服务商请求的限制
> 
> 我目前都是看到好文章，然后再把这篇文章的参考文献通过web of science导入到zotero，然后查重、合并条目，这种手工搞，效率贼低

可以，[cp插件](https://github.com/MuiseDestiny/zotero-connected-papers)也做出来了。

没精力搞这些，而且我搞这些也不是专业的，肯定没有cp弄得好。

**Comment by Geo123abc** [comment]
> > > > Connected Papers之类网站把文献连接起来的原理
> > > 
> > > 
> > > Semantrics那边做好了文献的向量，这些工作不是cp做的，他们应该也是用S2的接口
> > 
> > 
> > 原来如此，这些东西得用起来，不然是累赘，而不是垫脚石
> > 其实对于zotero style，我不知道能不能出一个功能，一键更新文献库或者某个文件夹中文献的相互引用关系，这个可能会触发服务商请求的限制
> > 我目前都是看到好文章，然后再把这篇文章的参考文献通过web of science导入到zotero，然后查重、合并条目，这种手工搞，效率贼低
> 
> 可以，[cp插件](https://github.com/MuiseDestiny/zotero-connected-papers)也做出来了。
> 
> 没精力搞这些，而且我搞这些也不是专业的，肯定没有cp弄得好。

厉害了
