### ISSUE TITLE
2.6.7嵌套标签bug

### ISSUE THREAD

**Issue by zhaoyunzyq** [MuiseDestiny/zotero-style#502]
**不礼貌不回复，直接关闭**
大大您好，为什么我的嵌套标签会发生如图的显示bug，每个字都会被认为是一层嵌套标签
![image](https://github.com/MuiseDestiny/zotero-style/assets/140182628/12ec1ba6-cb93-4753-9062-0dcdd0be2737)
设置里面也会出现无法选择的情况
![image](https://github.com/MuiseDestiny/zotero-style/assets/140182628/cf672731-4fd5-47d7-8f3f-3f3ce5498c32)
fei'ch非常喜欢style插件，满足了非常多我想要的功能，所以拜托大大能够帮忙解决一下，非常感谢

**Comment by MuiseDestiny** [comment]
尝试降级，你的插件版本可能太高了

**Comment by zhaoyunzyq** [comment]
好的好的谢谢大大，但是降级了是不是就没法使用那个全文翻译的功能了呐

**Comment by MuiseDestiny** [comment]
报告下出问题的zotero版本和插件版本

**Comment by Dirtyuri** [comment]
遇到了同样的问题，我用的是zotero 6.0.26，插件版本2.6.7，尝试降级至2.6.6和2.6.5均无法解决

**Comment by zhaoyunzyq** [comment]
zotero版本是6.0.26，插件版本就是2.6.7，我也是降级之后依然有这个问题

> 报告下出问题的zotero版本和插件版本

**Comment by TAOYi92** [comment]
zotero版本是6.0.26，插件版本就是2.6.7，遇到同样的问题，希望作者大大抽空看一下，感谢！
> 报告下出问题的zotero版本和插件版本

**Comment by githubonmylab** [comment]
我也遇到了相同的问题

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/602
