### ISSUE TITLE
更新期刊标签和更新被引数失效

### ISSUE THREAD

**Issue by Geemiing** [MuiseDestiny/zotero-style#504]
**不礼貌不回复，直接关闭**
![image](https://github.com/MuiseDestiny/zotero-style/assets/116059276/adc0b7ad-1364-4b1d-b586-4589c5b4d257)

显示如图，不知道是不是我操作不对还是大家现在都不能显示

**Comment by Geemiing** [comment]
期刊标签找到了 需要更新密钥 但是引用数还是不能更新

**Comment by MuiseDestiny** [comment]
引用尚未开放还在开发中
