### ISSUE TITLE
不能加载旧版本的阅读进度

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/zotero-style#51]
你好 按照新版本之后不能加载旧版本的阅读进度 并且同步到其他设备上也没有进度

**Comment by MuiseDestiny** [comment]
> 你好 按照新版本之后不能加载旧版本的阅读进度 并且同步到其他设备上也没有进度

是这样子的，由于我之前测试失误，把我的老版本数据搞没了。要做数据迁移需要老版本数据做测试，方便把你笔记（记录了进度数据）发我做测试吗。

**Comment by Mashmall** [comment]
非常荣幸 请问怎么给你呢

**Comment by Mashmall** [comment]
我看了一下啊 zoterosytle文件是可以同步的 但是另一个设备不显示进度，

**Comment by MuiseDestiny** [comment]
> 非常荣幸 请问怎么给你呢

邮箱33699@outlook.com

**Comment by MuiseDestiny** [comment]
> 我看了一下啊 zoterosytle文件是可以同步的 但是另一个设备不显示进度，

看看文献库有几个Addon Item，删除其中多余创建的一个。

多个设备使用建议等插件产生的条目同步过来后启用插件，不然会出现多个设备创建多个的bug，需要手动删除。

**Comment by Mashmall** [comment]
嗯嗯 目前就是同步没问题 另一个设备加载不出进度 无论是1.4.6 还是1.5.1版本 发rdf文件给你了

**Comment by MuiseDestiny** [comment]
> 嗯嗯 目前就是同步没问题 另一个设备加载不出进度 无论是1.4.6 还是1.5.1版本 发rdf文件给你了

十分感谢！

**Comment by Mashmall** [comment]
期待新功能 谢谢

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/212476865-f114202c-42f3-4d49-a8b6-772cb2398831.png)
用你的数据迁移的结果。邀请你测试。

**Comment by Mashmall** [comment]
你好十分感谢 测试了一下 2.00和2.01版本 shift+p之后不显示下面的选项，并且esc按键无效 退不出来，是我操作的问题吗，请指导

**Comment by MuiseDestiny** [comment]
点中ZoteroStyle条目后shift+P

**Comment by Mashmall** [comment]
实现了 太强大了 但是我觉得还是有一个bug 就是调出shift+p之后 esc退不出 2.0.1版本

**Comment by MuiseDestiny** [comment]
> 实现了 太强大了 但是我觉得还是有一个bug 就是调出shift+p之后 esc退不出 2.0.1版本

我可以的啊，点击输入命令那里多按几次esc。

**Comment by GFDGIT** [comment]
> > 我看了一下啊 zoterosytle文件是可以同步的 但是另一个设备不显示进度，
> 
> 看看文献库有几个Addon Item，删除其中多余创建的一个。
> 
> 多个设备使用建议等插件产生的条目同步过来后启用插件，不然会出现多个设备创建多个的bug，需要手动删除。

我在两个电脑装了Style，已经同步过Addon Item了，但是新设备上总是会重新生成Addon Item条目，删除之后也不会识别旧的Addon Item，导致无法同步。是否参考Chartero可手动指定记录条目更直观、准确一些？

**Comment by GFDGIT** [comment]
> > 
> 
> 在回收站彻底删除就可以了

已经尝试过在回收站彻底删除了，之后重启zotero就无法加载条目一片空白，再次重启后条目加载正常，但是打开一篇文献，又会重新生成新的addon item。

**Comment by MuiseDestiny** [comment]
> > > 
> > 
> > 
> > 在回收站彻底删除就可以了
> 
> 已经尝试过在回收站彻底删除了，之后重启zotero就无法加载条目一片空白，再次重启后条目加载正常，但是打开一篇文献，又会重新生成新的addon item。

稍后我写一个命令像Chartero那样指定

**Comment by MuiseDestiny** [comment]
> > > 
> > 
> > 
> > 在回收站彻底删除就可以了
> 
> 已经尝试过在回收站彻底删除了，之后重启zotero就无法加载条目一片空白，再次重启后条目加载正常，但是打开一篇文献，又会重新生成新的addon item。

抱歉，多写了一个空格导致的问题。你现在可以把同步过来的那个条目重命名为`AddonItem`，然后彻底删除新生成的。这样就可以了。

**Comment by MuiseDestiny** [comment]
> > > 
> > 
> > 
> > 在回收站彻底删除就可以了
> 
> 已经尝试过在回收站彻底删除了，之后重启zotero就无法加载条目一片空白，再次重启后条目加载正常，但是打开一篇文献，又会重新生成新的addon item。

先把想要的`Addon Item`改名为`AddonItem`(去掉空格，代码里少打了空格)。然后彻底删除其它的，应该就会成功。

**Comment by GFDGIT** [comment]
新生成条目名称似乎原本就是有空格的？

我把旧条目下的记录笔记，拖到新条目里面了，也能成功识别。

对了，我提议更新说明提一下，旧版本切换到新版本时，如果旧版的记录在回收站，要首先迁移记录，不然后面清空回收站旧的记录就丢失了。

**Comment by MuiseDestiny** [comment]
> 新生成条目名称似乎原本就是有空格的？
> 
> 我把旧条目下的记录笔记，拖到新条目里面了，也能成功识别。
> 
> 对了，我提议更新说明提一下，旧版本切换到新版本时，如果旧版的记录在回收站，要首先迁移记录，不然后面清空回收站旧的记录就丢失了。

突然想到，但是这样不能同步的。同步这块确实没做好，我设备有限，没法测试。见谅。

**Comment by GFDGIT** [comment]
<
> 我把旧条目下的记录笔记，拖到新条目里面了，也能成功识别。

但似乎存在一个问题，我在新设备上用新生成的addonitem，记录同步回旧设备肯定就把旧addonitem清空了同时产生一个我现在生成的addonitem。一样会同时存在两个addonitem，倒时我还是无法切换到我现在生成且合并了旧记录的addonitem。

我想问下识别addonitem是先识别条目名称，然后记录zotero内部的key吗？如果同时存在两个条目，以哪个为准？

**Comment by MuiseDestiny** [comment]
在`出问题设备`的Zotero里选中从`没出问题设备`同步过来的`Addon Item`，点击`工具`->`开发者`->run javascript

输入以下代码，点击run，重启Zotero就解决了。如果写命令行也是这个逻辑。

这是一定可以解决问题的。

```js
i = ZoteroPane.getSelectedItems()[0]
Zotero.Prefs.set("Zotero.AddonItem.key", i.key)
```

**Comment by GFDGIT** [comment]
> 
> `AddonItem`(去掉空格，代码里少打了空格)。

修好这个bug，只要保证库里面只有一个Addon Item就可以识别并同步了吧。或者把手动指定item的命令，加到shift+p面板上？

**Comment by MuiseDestiny** [comment]
> 点击`工具`->`开发者`->run javascript

输入这里

**Comment by GFDGIT** [comment]
> > 点击`工具`->`开发者`->run javascript
> 
> 输入这里

好的，这个我理解了。我想提议的是，把这个命令做成按钮，加到shift+p面板上，简化操作。

**Comment by MuiseDestiny** [comment]
> > > 点击`工具`->`开发者`->run javascript
> > 
> > 
> > 输入这里
> 
> 好的，这个我理解了。我想提议的是，把这个命令做成按钮，加到shift+p面板上，简化操作。

会的，现在在重写shift p，现在这个有点不满足需求
