### ISSUE TITLE
我的zotero和zotero style插件都是最新版本，但是这个插件好像并没有起作用，是不是版本不兼容的原因呐，谢谢

### ISSUE THREAD

**Issue by Nancy-sn** [MuiseDestiny/zotero-style#514]
我的zotero和zotero style插件都是最新版本，但是这个插件好像并没有起作用，是不是版本不兼容呀

![1](https://github.com/MuiseDestiny/zotero-style/assets/56101252/7f188b9c-52af-4ab6-b0cb-d2c12b6393f8)
![2](https://github.com/MuiseDestiny/zotero-style/assets/56101252/2dbcea9c-d601-460f-91e4-d94fdbc749a0)
![3](https://github.com/MuiseDestiny/zotero-style/assets/56101252/953ec636-7ab9-4916-8b45-84fcf44c3ec9)

**Comment by MuiseDestiny** [comment]
图2只能看到你安装了style看不到style的版本

**Comment by Nancy-sn** [comment]
我开始安装的是2.7版本的，然后插件没有反应。现在安装了2.6.7版本的可以了

**Comment by MuiseDestiny** [comment]
> 我开始安装的是2.7版本的，然后插件没有反应。现在安装了2.6.7版本的可以了

好的
