### ISSUE TITLE
有多个视图界面，在这视图界面中添加一些列（如：标签），切换到别的试图再切换回来后，添加的列便没有了

### ISSUE THREAD

**Issue by Nancy-sn** [MuiseDestiny/zotero-style#516]
有多个视图界面，在这视图界面中添加一些列（如：标签），切换到别的试图再切换回来后，添加的列便没有了
版本是zotero style2.6.7+zotero6.0.26

https://github.com/MuiseDestiny/zotero-style/assets/56101252/cef58f5e-5e39-4781-85fd-0c619a42ec51

**Comment by MuiseDestiny** [comment]
10s以后 你应该做的事情：
任意列，视图组-添加视图。

而不应该去切换回一个已保存的视图。

**Comment by Nancy-sn** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/56101252/e2e05957-e888-458b-9676-1934fe260665)
这个只有偶尔才会有添加视图这一选项，这次把软件关掉再代开还是没有添加视图这个按钮
