### ISSUE TITLE
new logo版 shift p没有翻译选项

### ISSUE THREAD

**Issue by jlu511** [MuiseDestiny/zotero-style#518]
开发者您好，
感谢开发出这么好用的插件。最新版 new logo，shift+p没有翻译的选项。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/bb48f738-dad2-413a-aefb-30b8e3d2a12f)
使用另一个版本，全文翻译之后，只有摘要，正文要么没有翻译，要么翻译一小部分。重新翻译也是一样。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/b55dc4b8-6a30-421d-b241-4aa3d3cdb022)
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/76a21c76-a3d1-43cd-8c82-65172110d1f8)
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/ea0cd5cc-4596-47b6-94cc-24d1df44aa20)
这个是图片里用的文献
[Zhong 等 - 2023 - Idealizing Tauc Plot for Accurate Bandgap Determin.pdf](https://github.com/MuiseDestiny/zotero-style/files/12179738/Zhong.-.2023.-.Idealizing.Tauc.Plot.for.Accurate.Bandgap.Determin.pdf)

再次感谢开发者的付出。

**Comment by MuiseDestiny** [comment]
这个应该和pdf无关的。或许安装后重启以下呢

**Comment by jlu511** [comment]
重启了几次，仍然是这样，您用我发的pdf试试看，是否正常。

**Comment by MuiseDestiny** [comment]
> 重启了几次，仍然是这样，您用我发的pdf试试看，是否正常。

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/e94b0c1e-5e11-47a1-87a8-76d1371949b3)

翻译是异常的，异常是正常的。因为解析不是100%精确的。

**Comment by jlu511** [comment]
那可能是解析的问题，没有解析出正文，或者正文解析不完全，导致提交给翻译插件的文本不全，最后返回的不全，请问大佬，这个有办法解决吗

**Comment by MuiseDestiny** [comment]
> 那可能是解析的问题，没有解析出正文，或者正文解析不完全，导致提交给翻译插件的文本不全，最后返回的不全，请问大佬，这个有办法解决吗

我没有办法解决。底层是用数据训练的，除非自己标定数据重新训练。

**Comment by MuiseDestiny** [comment]
这是一个公司体量的活。

**Comment by jlu511** [comment]
好的

> 这是一个公司体量的活。

明白，确实工作量巨大，感谢解答
