### ISSUE TITLE
“被引数” 列里面显示空白

### ISSUE THREAD

**Issue by jlu511** [MuiseDestiny/zotero-style#519]
**不礼貌不回复，直接关闭**
文献的被引数这一列内容显示空白，点击这个空白，提示更新，但依然不显示。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/b003df75-58b8-4df1-b88b-63a648031f20)
点击更新被引数，依然不显示
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/9d08a031-9286-46e3-8da5-464e4ae5bc95)
这个提示非常快，即使是几十篇文献，提示也是马上就完成。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/427a69bf-418b-43e0-a6a4-bbc7fb2dd74d)
而点击更新期刊标签，提示信息上有个执行进度1%-100%，但被引数直接就是100%，似乎没有真正更新。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64378673/8b021059-cf9b-416b-9696-ace2a235a1ff)

**Comment by MuiseDestiny** [comment]
尚未发布
