### ISSUE TITLE
Zotero夜晚模式下部分窗口字体和背景均默认白色

### ISSUE THREAD

**Issue by RitaQian-westlake** [MuiseDestiny/zotero-style#520]
如题。夜晚模式下字体默认为白色，插件又默认显示背景为近乎白色，最后导致字符在未选中状态下看不到。
目前发现的部分：
1. Shift+P命令窗口字体/背景颜色
![image](https://github.com/MuiseDestiny/zotero-style/assets/89500047/9e72ded7-6cd4-43a9-850b-25a27c571573)
2. 用于视图切换的点点（鼠标未悬停此处时）和鼠标悬停时显示的视图标题
- 未悬停时：
![Screenshot from 2023-07-27 16-56-44](https://github.com/MuiseDestiny/zotero-style/assets/89500047/0317b2ef-716b-49ef-a59a-24b0c454ed14)
- 悬停时：
![Screenshot from 2023-07-27 16-54-39](https://github.com/MuiseDestiny/zotero-style/assets/89500047/b21a5e31-573b-4c10-b997-8f00981ee809)

这两处看起来均没有可编辑颜色的地方。可能还有其他，待补充。

**Comment by MuiseDestiny** [comment]
夜晚模式，少数人在用，适配这个花费时间精力很大，不会适配。
