### ISSUE TITLE
Add the function of list citation key in zotero7

### ISSUE THREAD

**Issue by MengjiaHe** [MuiseDestiny/zotero-style#523]
**不礼貌不回复，直接关闭**
Hi there,
Thank you for your effort on the useful plug-ins. I'm wondering if you could add the function of list citation key in zotero7 just like zotero6, which is quite convenient for paper reading.
![image](https://github.com/MuiseDestiny/zotero-style/assets/7488514/113a17be-e807-4c81-a41d-528429c36390)

**Comment by MuiseDestiny** [comment]
你说的是bbt插件的功能吗

**Comment by MengjiaHe** [comment]
谢谢及时回复！是的，是不是BBT兼容了7以后才能出现这个CitationKey列表名呀
![image](https://github.com/MuiseDestiny/zotero-style/assets/7488514/4d74c725-f9e7-4055-907a-5c172b85e78c)

**Comment by MuiseDestiny** [comment]
> 谢谢及时回复！是的，是不是BBT兼容了7以后才能出现这个CitationKey列表名呀 ![image](https://user-images.githubusercontent.com/7488514/256966141-4d74c725-f9e7-4055-907a-5c172b85e78c.png)

是的，请等待bbt适配7。style不会加这个功能。
