### ISSUE TITLE
zotero 7 设置界面不显示

### ISSUE THREAD

**Issue by abcvav** [MuiseDestiny/zotero-style#524]
如图所示，重启zotero，重启电脑都没用

![image](https://github.com/MuiseDestiny/zotero-style/assets/47599849/3c05b1a9-1255-4fc0-abd6-11dd30da7887)

**Comment by MuiseDestiny** [comment]
版本号，不然无法提供帮助。

**Comment by abcvav** [comment]
版本是 `Zotero-7.0.0-beta.25+8a7f3645b_win-x64` zip便携版，重装这个插件过后，设置界面现在都不显示了。
![image](https://github.com/MuiseDestiny/zotero-style/assets/47599849/18a8c1c5-dfb0-4915-9067-4b6d219bb0be)

**Comment by MuiseDestiny** [comment]
插件版本。一般安装prerelease的就解决了。

**Comment by abcvav** [comment]
安装的最新的那个2.6.7

**Comment by MuiseDestiny** [comment]
> 安装的最新的那个2.6.7

安装2.7.0,如果还不行等zotero 7更新吧。现在我也是这样。

**Comment by abcvav** [comment]
原来是zotero的问题😂

**Comment by MuiseDestiny** [comment]
> 原来是zotero的问题😂

一开始是因为你插件不是最新的，现在确实是zotero问题。
