### ISSUE TITLE
标签期刊空白

### ISSUE THREAD

**Issue by liluzhang** [MuiseDestiny/zotero-style#528]
Map里原本是一堆乱码，不知道是不是Zotero更新影响因子往“其他”里写东西冲突导致。
但没有恢复初始设置等功能，重新安装了也是这样。版本2.6.7
![image](https://github.com/MuiseDestiny/zotero-style/assets/103313953/4d6df616-fef8-4162-8e5d-e91304d209c5)

**Comment by MuiseDestiny** [comment]
请阅读readme。

**Comment by MuiseDestiny** [comment]
1. es密钥
2. fields填写错误
