### ISSUE TITLE
2.6.7适配zotero7 bug 报告

### ISSUE THREAD

**Issue by CestYYANG** [MuiseDestiny/zotero-style#530]
非常感谢大佬及时适配了zotero7，已充电，下面是两个bug报告：
1. 除了zotfile，其他几个插件在设置界面只有图标没有内容
![image](https://github.com/MuiseDestiny/zotero-style/assets/109470529/18f6ae89-6733-4ece-9f5b-9c7cb0be8fdf)
![image](https://github.com/MuiseDestiny/zotero-style/assets/109470529/1a0a7715-a075-4b52-bfb8-73d0f1420aa8)
2. 2.6.7的style启用后会导致条目列表上方的列宽无法调整
![image](https://github.com/MuiseDestiny/zotero-style/assets/109470529/f12e9e15-8c5c-43ad-9e51-fb2e213d243c)

**Comment by MuiseDestiny** [comment]
请升级到最新版。一般在github的预发布。

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/edcb0bc2-fb9c-4022-a15c-f85f37045fdb)

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/9d0b61df-1417-4fcc-be36-c5ad374b521c)


style的最新版是2.7.0

**Comment by MuiseDestiny** [comment]
其他插件同理。这些适配zotero的插件都没有正式发布，因为正式发布会触发zotero6用户的自动升级。然而支持7的插件**并不支持6**。

**Comment by CestYYANG** [comment]
感谢大佬，安装后显示出来了，不过第二条还是存在，但是目前不知道是个别bug还是啥，不过暂时不影响使用

**Comment by MuiseDestiny** [comment]
> 感谢大佬，安装后显示出来了，不过第二条还是存在，但是目前不知道是个别bug还是啥，不过暂时不影响使用

插件安的太多导致
