### ISSUE TITLE
逐段翻译有bug了

### ISSUE THREAD

**Issue by pengxy0** [MuiseDestiny/zotero-style#531]
逐段翻译出现这样的问题，要怎么解决
![image](https://github.com/MuiseDestiny/zotero-style/assets/130196652/3e542810-9eca-4191-93ca-e18c9e8d03d4)

**Comment by pengxy0** [comment]
是翻译引擎出现问题了

**Comment by MuiseDestiny** [comment]
请详述。
怎么确定这是全文翻译引起？
引起的是什么问题？

**Comment by pengxy0** [comment]
上午是CNKI不能翻译了，所以导致全文翻译不能正常进行。后来换了有道，就好了。现在已经解决了。谢谢大佬回复。
