### ISSUE TITLE
rating是乱码

### ISSUE THREAD

**Issue by ZivNice** [MuiseDestiny/zotero-style#533]
![image](https://github.com/MuiseDestiny/zotero-style/assets/20898065/04dd7dfb-b34a-4de6-983c-43bc92604606)

**Comment by ArtisticZhao** [comment]
Same,
系统是Linux

**Comment by WSQ-GitHub** [comment]
我也一样windows

**Comment by MuiseDestiny** [comment]
阅读readme，进入它的列设置

**Comment by hsumayun** [comment]
这个问题有人解决了吗，求解

**Comment by ArtisticZhao** [comment]
> 这个问题有人解决了吗，求解

<img width="775" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/22850287/ad40f21e-497f-4b6a-b9ae-931b310dad6c">

**Comment by WuHongQiang333** [comment]
更换图标就可以了
https://www.starryfk.com/tec/zotero-settings-and-plugins-for-literature-management-software.html
