### ISSUE TITLE
【FR】增大弹出框字体

### ISSUE THREAD

**Issue by wwjCMP** [MuiseDestiny/zotero-style#536]
希望增加弹出框中文字的字体大小可调功能，现在字体有点小，且不能通过zotero的字体大小设置。

**Comment by MuiseDestiny** [comment]
截下图，不知道是哪里

**Comment by wwjCMP** [comment]
![Snipaste_2023-08-05_10-09-18](https://github.com/MuiseDestiny/zotero-style/assets/32979859/1dc80b1f-4d57-4eb3-9563-12f8dfbfd2da)
