### ISSUE TITLE
zotero7 style和reference在设置页面不显示

### ISSUE THREAD

**Issue by psychologistcy** [MuiseDestiny/zotero-style#540]
**不礼貌不回复，直接关闭**
您好啊，我试着看大佬的B站视频，双线使用zotero7和zotero6，确实切换来去自如！太牛了！感谢感谢！
但是zotero7的reference和style插件都遇到了问题，就是设置页面啥都没有，www~
![image](https://github.com/MuiseDestiny/zotero-style/assets/113295809/475fe96b-fdff-450e-a955-be9abb51f605)
![image](https://github.com/MuiseDestiny/zotero-style/assets/113295809/dbb30af0-6471-4c06-919e-915c10a575d6)
zotero file还可以正常显示
![image](https://github.com/MuiseDestiny/zotero-style/assets/113295809/8bdd2da5-b1ad-4061-940e-9df3e83f024e)

**Comment by MuiseDestiny** [comment]
版本不对，请安装最新版插件，pre-release的。

https://github.com/MuiseDestiny/zotero-style/releases
https://github.com/MuiseDestiny/zotero-reference/releases

**Comment by psychologistcy** [comment]
感谢大佬！
