### ISSUE TITLE
MacOS14 Zotero7 部分功能無法使用

### ISSUE THREAD

**Issue by MaxxHuan9** [MuiseDestiny/zotero-style#543]
#  🫡 (禮貌的敬禮）
---
Hi,這是我使用環境下的問題，在這反應一下。
1.M1 MacbookPro 
MacOS14
Zotero 7
Zotero style 2.7
file：zotero-style-new-logo.xpi
display ：Version 2.7.1

<img width="701" alt="MacOS 14_Zotero7_zoterostyle271" src="https://github.com/MuiseDestiny/zotero-style/assets/70934068/ebd02674-4981-4b94-a49d-5d77d5a180d6">

---
問題：
a.列設置沒有顯示，無法設置。
b.View group 無法使用：無法增加 、刪除。
---
<img width="235" alt="MacOS 14_Zotero7_zoterostyle271_rightclick" src="https://github.com/MuiseDestiny/zotero-style/assets/70934068/05e4c771-cefb-4ebb-afc8-9a702ac1d289">

---
- 我現在是需要更改列設置時，回去zotero6，設置好後，再開啓7,然後重新安裝插件。然後會遇到下面另外一個小問題
- 另一個小問題是，mac環境下，直接關關閉zotero7，再開啓時，插件會進入安全模式，必須進環境設置，重新設置，這好像是Mac環境下，很多7的插件都會發生。
---
其他兩個環境使用都正常：
2. Win11 （ARM）Zotero 7，zotero style 2.7.1，一切正常 
3. MacOS 14，Zotero 6 ，zotero style  2.6.7，一切正常，截圖同 Win11(ARM)。

<img width="202" alt="Win11_ARM_zotero7_zotero271_rightclick" src="https://github.com/MuiseDestiny/zotero-style/assets/70934068/5081cef4-6ecb-4464-8c3e-bb017ddcef74">

**Comment by youngerruan** [comment]
macOS 13.4存在相同的问题。
**```
a.列設置沒有顯示，無法設置。
b.View group 無法使用：無法增加 、刪除。
```**

**Comment by RayKr** [comment]
> macOS 13.4存在相同的问题。
> 
> ```
> **a.列設置沒有顯示，無法設置。**
> **b.View group 無法使用：無法增加 、刪除。**
> ```

我也是同样问题，没有列设置选项

**Comment by MuiseDestiny** [comment]
更新就好了
