### ISSUE TITLE
zotero 7 里面没有列设置

### ISSUE THREAD

**Issue by Zhangxigu** [MuiseDestiny/zotero-style#547]
作者大大，我是 mac，目前在使用 7 版本，但是我发现不可以进行列设置了，期待回复。

**Comment by youngerruan** [comment]
等待大佬慢慢适配吧，这个问题存在很久了，mac端由于大佬手上没有设备，可能适配有点困难

**Comment by Zhangxigu** [comment]
好的，等等吧

**Comment by MuiseDestiny** [comment]
mac用户可以联系我远程修复试试

**Comment by Zhangxigu** [comment]
大佬，请问下怎么联系你呀？

**Comment by Zhangxigu** [comment]
我暂时没有这个软件哎，等我下载一下。

**Comment by MuiseDestiny** [comment]
> 我暂时没有这个软件哎，等我下载一下。

等你

**Comment by Zhangxigu** [comment]
大佬，我弄好了，需要发啥给你？

**Comment by MuiseDestiny** [comment]
> 大佬，我弄好了，需要发啥给你？

在这里发

**Comment by MuiseDestiny** [comment]
发远程控制码

**Comment by Zhangxigu** [comment]
ToDesk:
设备代码:580 862 214

**Comment by Zhangxigu** [comment]
是这个吗？

**Comment by MuiseDestiny** [comment]
> 是这个吗？

是的，但是
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/9e548a8b-4936-4b09-ac73-ab28ea77c546)

**Comment by Zhangxigu** [comment]
我的是 4.0.3版本

**Comment by Zhangxigu** [comment]
我的是 4.0.3版本

**Comment by MuiseDestiny** [comment]
> 我的是 4.0.3版本

更新一下呢

**Comment by Zhangxigu** [comment]
我重新弄下，等我。

**Comment by Zhangxigu** [comment]
ToDesk:
设备代码:580 862 214
大佬，你在试试，我更新了。

**Comment by MuiseDestiny** [comment]
> 

可以了

**Comment by Zhangxigu** [comment]
那就等待大佬好消息了。

**Comment by MuiseDestiny** [comment]
> 

你点一下同意控制啊

**Comment by MuiseDestiny** [comment]
> 

发一下控制密码吧

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/1cc568be-7f77-4134-83cb-a6b55d58903a)

**Comment by Zhangxigu** [comment]
ToDesk:
设备代码:580 862 214
临时密码:898815

**Comment by Zhangxigu** [comment]
我这边没有显示点击控制什么的

**Comment by MuiseDestiny** [comment]
> 我这边没有显示点击控制什么的

还是显示版本太低。

**Comment by MuiseDestiny** [comment]
要不我联系下其他mac用户吧

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/7c2f23b4-7fa9-4509-9cea-d17a52685da6)

**Comment by Zhangxigu** [comment]
我再弄一下

**Comment by MuiseDestiny** [comment]
> 

我是4.7.0.2

**Comment by Zhangxigu** [comment]
ToDesk:
设备代码:580 862 214
临时密码:wf2bs1s1

**Comment by Zhangxigu** [comment]
我能下到的最新版本，你试试可以吗？

**Comment by Zhangxigu** [comment]
可以吗？

**Comment by MuiseDestiny** [comment]
试了好几次，
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/462ab808-b872-4ffe-9585-a675ab38175d)
我联系别人吧

**Comment by Zhangxigu** [comment]
好的，我尽力了，我不知道我这边还需要进行啥设置。

**Comment by Zhangxigu** [comment]
![WechatIMG1265](https://github.com/MuiseDestiny/zotero-style/assets/126659828/66082344-f4f2-4068-84ec-80791d5ea4a7)
按道理来说应该是可以的吧

**Comment by MuiseDestiny** [comment]
已经解决，稍后发布

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/3.0.1
