### ISSUE TITLE
mac新版ethereal styel及crush reference均无法正常安装

### ISSUE THREAD

**Issue by youngerruan** [MuiseDestiny/zotero-style#551]
如题，显示不兼容。

无法安装插件“/Users/youngerruan/Downloads/crush-reference.xpi”。它可能无法与该版本的 Zotero 兼容。

版本：7.0.0-beta.32+5e27a7501
macOS版本：13.4
架构 arm，m1 芯片

**Comment by Jkenwin** [comment]
我是Intel版，我可以装进去，但是有很多不兼容

**Comment by wenlzhang** [comment]
遇到了类似的不兼容问题

**Comment by wanqiang512** [comment]
Beta32 window11也显示无法兼容，最新版

**Comment by MuiseDestiny** [comment]
请等更新。这次将重写style会比较久。

**Comment by WenjieXu2000** [comment]
Beta32 window11同样显示无法兼容

**Comment by z1Ramn** [comment]
7.0.0-beta.32+5e27a7501安装上 可以看到下面的关系图但是tag和#tag功能都消失了 还有影响因子和期刊等级

**Comment by MuiseDestiny** [comment]
已解决，留意github pre-release发布
