### ISSUE TITLE
高能进度条无法显示

### ISSUE THREAD

**Issue by gaoshilin1995** [MuiseDestiny/zotero-style#553]
作者大大您好，#标签和期刊标签的功能非常好用，非常感谢
目前，在Zotero 7.0.0-beta.32+5e27a7501 (64-bit)以及插件的2.7.1版本下，标题列无法显示高能进度条
已经尝试关闭及更新其它其他插件，并无效果
同时尝试对Addon Item条目按Shift+P设置为插件储存条目，也无效果
多次重启以及enable disabled切换也不行
请问有什么解决办法吗？这是否与我使用坚果云Webdav文件同步有关？  
![屏幕截图 2023-08-10 115719](https://github.com/MuiseDestiny/zotero-style/assets/96185368/d85eab03-2471-4df3-883d-bfe914d01ee1)

**Comment by MuiseDestiny** [comment]
插件需要适配这次更新，请耐心等待更新。是插件自己原因，不要做过多尝试。

**Comment by MuiseDestiny** [comment]
安装最新prerelease
