### ISSUE TITLE
[声明] 适配最新 Zotero 7 中

### ISSUE THREAD

**Issue by MuiseDestiny** [MuiseDestiny/zotero-style#554]
我是 Style 插件作者。

如果你是/高于Zotero 7 beta.32，任何插件出现任何问题，请不要发 issue。

这次更新，需要插件适配。适配需要时间，**请大家耐心等待**。

适配期间，将不再接收新issue。

本次更新将重写 Style，删繁就简，去除杂乱无用低频功能。

这也将是第二次重写，重写会加新功能移除无用功能，界面会更友好。

但受限于个人时间，最终适配日期不定，若你暂时离不开 Style 可以尝试安装旧版 Zotero 7。

**敬请期待**

(放弃重新写，代码量太大了，还是适配吧)

**Comment by Amikacin666** [comment]
谢谢大大

**Comment by Zhangxigu** [comment]
大大加油，期待好消息！！！

**Comment by z1Ramn** [comment]
大大加油！

**Comment by huangsh** [comment]
大大加油！

**Comment by MuiseDestiny** [comment]
已转换完成

**Comment by Moriraty** [comment]
现在这个状态是都无法安装吗？我win安装了这个插件都看不见标题栏的那个图标，什么都调用不出来
