### ISSUE TITLE
Zotero PDF Translate和Style自带的栏目无法共存

### ISSUE THREAD

**Issue by Amikacin666** [MuiseDestiny/zotero-style#555]
Zotero版本：7-beta.32 Style版本：2.8.0
![image](https://github.com/MuiseDestiny/zotero-style/assets/103126392/96d2a73a-e60e-4071-b575-2990b093340a)
如图style自带栏目在PDF Translate插件安装后重启软件就会自动消失，并无法重新调用。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/issues/554
