### ISSUE TITLE
安装了最新的版本后标签列显示错误

### ISSUE THREAD

**Issue by huangsh** [MuiseDestiny/zotero-style#558]
刚装好还是好的，关闭后重新打开，就变成下面这个样子了：
<img width="1189" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/3821937/3eb911bd-884a-4be7-8433-8f1410352632">

重复了好几次都是这样。
系统：maoos m2 13.4
zotero beta.32
style 3.0.1

**Comment by MuiseDestiny** [comment]
是冲突哦，需要其它插件升级

**Comment by huangsh** [comment]
试了下可以了，居然正好您修改的zotfile，我更新了就可以了
<img width="667" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/3821937/3d2827ff-4550-4a1e-a31f-341c6be7409d">
顺便弱弱问下评级这列宽度固定不可调，是不是这个插件的问题，其他列都没有问题

**Comment by MuiseDestiny** [comment]
发布写了已知bug，宽度调节异常。还没找到原因

**Comment by Zhangxigu** [comment]
大佬，我找不到下午咱两的对话了，在这里感谢下大大，我已经更新，非常好！感谢您能为 mac 用户专门解决这个问题，辛苦！

**Comment by huangsh** [comment]
非常抱歉没有认真看，感谢大大

> 发布写了已知bug，宽度调节异常。还没找到原因
