### ISSUE TITLE
Beta 33 ＆ v3.0.1 mac状态栏似乎还是有问题

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-style#564]
**不礼貌不回复，直接关闭**
https://github.com/MuiseDestiny/zotero-style/assets/50101175/8eefef97-dfe1-4611-9ead-7c2b669ab532

**Comment by youngerruan** [comment]
同。。。。我也遇到了

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/60cd3eed-1c8f-4d39-9776-6e67a19c6ace)

这是已知问题，请耐心等待更新修复。
