### ISSUE TITLE
聪明智慧的好大大！我的关系网络图谱突然一直这样了，点文献条目也不变，以前是好滴！

### ISSUE THREAD

**Issue by wode0000ai** [MuiseDestiny/zotero-style#569]
**不礼貌不回复，直接关闭**
今天下载了最新的版本覆盖了一下还是这样子
谢谢大大！
<img width="341" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/142288561/3b4076fc-9485-4460-94cc-6458ea160c2b">

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/c3717d38-7da2-4339-a6c5-cc174c65fd2d)
