### ISSUE TITLE
2.0.1按shift+p没有命令出现

### ISSUE THREAD

**Issue by Z0o0o** [MuiseDestiny/zotero-style#57]
![屏幕截图_20230115_104350](https://user-images.githubusercontent.com/121789386/212520295-0b81c25a-83ec-4923-a424-13819773f5db.png)
且按Esc或shift+p均无法退出命令框，必须选中其他条目再按shift+p才能退出

**Comment by MuiseDestiny** [comment]
等一会更新下reference插件就好了。
