### ISSUE TITLE
zotero 7.0 标签显示有限

### ISSUE THREAD

**Issue by Saunak626** [MuiseDestiny/zotero-style#570]
<img width="1244" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/34276206/d11b6254-5362-4533-b011-c25fbe443447">
你好，如上图可见很多标签在标题栏中都不显示，请问能否添加呢？比如这个网站的 https://www.emojiall.com/zh-hans/categories/B

**Comment by MuiseDestiny** [comment]
分配颜色才显示的。
