### ISSUE TITLE
新版本更新不了：3.0.2无法安装插件“%S”。它可能无法与该版本的Zotero兼容；从2.6.7更新到2.8.0之后首选项和主页都找不到Style

### ISSUE THREAD

**Issue by rgkhff** [MuiseDestiny/zotero-style#575]
Zotero 6
从2.6.7更新到2.8.0之后首选项和主页都找不到Style。
附件里面显示有，但是首选项和主页都找不到
![图片](https://github.com/MuiseDestiny/zotero-style/assets/88096362/0f091d19-4170-4d3e-a35f-d853b6ed0a96)
![图片](https://github.com/MuiseDestiny/zotero-style/assets/88096362/25d644eb-c1ff-487b-ac71-88079da6d0a2)
![图片](https://github.com/MuiseDestiny/zotero-style/assets/88096362/f1d2f954-7d1b-449a-b975-3e9749ae3324)

3.0.2无法安装插件“%S”。它可能无法与该版本的Zotero兼容
![图片](https://github.com/MuiseDestiny/zotero-style/assets/88096362/96f1611e-a7fe-4e82-a414-429ae5fdb50a)

**Comment by rgkhff** [comment]
3.0.2装的是 6 的那个版本 QAQ救命
![图片](https://github.com/MuiseDestiny/zotero-style/assets/88096362/41eed281-14d2-4eb3-bb7f-e4ae3367bfa4)

**Comment by MuiseDestiny** [comment]
zotero6请用2.6.7
