### ISSUE TITLE
Shift P 打开命令后 按ESC关闭不了

### ISSUE THREAD

**Issue by YanMing-lxb** [MuiseDestiny/zotero-style#58]

**Comment by MuiseDestiny** [comment]
好多人反馈这个问题，我才发现reference里也有一个prompt。你是不是装了它，稍后等我更新`Zotero Reference`解决这个bug。另外reference有啥建议可以提一下在这里。

**Comment by YanMing-lxb** [comment]
对是的，reference我也装了。reference,目前没咋看文献，所以没怎么用。等遇到问题了再提交。
不过还有个问题，目前在zotero中更新不了style和reference插件，只能偶尔来github看一下是否有更新，然后进行手动更新。
再者就是，新安装插件后，最好还是加上一个重启zotero以启用插件比较好，有时不重启，插件用不了，就会出现下面的问题。

装了Zotero Style插件后，zotero有时候无法打开附加组件选项。
如下所示的界面：
![image](https://user-images.githubusercontent.com/113030089/212533918-d78b19b0-0b16-49ed-970c-793eb68a7de8.png)

关闭zotero后就发现任务管理器中还有zotero在运行。等结束任务管理器的的zotero任务后，再次打开zotero就能打开附加组件选项了
如下所示
![image](https://user-images.githubusercontent.com/113030089/212533577-fb3412fe-bc0f-47fe-a8de-d214e27c83c9.png)

**Comment by YanMing-lxb** [comment]
reference的分栏快速跳转真是太棒了！！！
建议做一个功能，可以设置，图和表显示的默认分栏方式或者显示的位置比如放在侧栏的位置上，位置如下所示：
![image](https://user-images.githubusercontent.com/113030089/212534471-65c944bb-95e5-465f-9fb1-b3e3ff814f91.png)
这两个位置都可以。也可以参考PDF Preview for Zotero的预览位置的设置，并可以额外添加放大缩小显示功能。
还有就是不想看了打开的图片，关闭显示，第一次用的人可能不太清楚怎么关闭分栏，在readme可以提一下。或者设定一个方便的关闭方式。

补充一下上一个反馈：安装style，出现打不开附加组件的问题。如果不关闭任务管理器中运行的zotero，就算再次打开zotero，也依然打不开附加组件选项。

因为没有开发过zotero的插件，所以不清楚我提的意见的可行性如何，如有不妥请无视即可。

**Comment by MuiseDestiny** [comment]
> 这两个位置都可以。也可以参考PDF Preview for Zotero的预览位置的设置，并可以额外添加放大缩小显示功能。 还有就是不想看了打开的图片，关闭显示，第一次用的人可能不太清楚怎么关闭分栏，在readme可以提一下。或者设定一个方便的关闭方式。

这个建议很好，但是支持点击跳转的PDF很少。所有后面准备做一个类似reference的插件识别图表。
但是前期，这个建议可以在reference实现的，谢谢~

**Comment by MuiseDestiny** [comment]
更新了，目前reference style都可以在zo更新的。
