### ISSUE TITLE
Jasminum和zotero-style插件冲突

### ISSUE THREAD

**Issue by Wilhenry777** [MuiseDestiny/zotero-style#581]
Jasminum和zotero-style插件之间有冲突，这两个同时打开的时候，调整条目的宽度会出现异常。
zotero版本：7.0.0-beta.36；
zotero-style版本：3.0.3；
Jasminum版本：1.0.0-3；

https://github.com/MuiseDestiny/zotero-style/assets/103740440/d78438f6-993e-41f4-8c10-d2a7faf0be23

**Comment by MuiseDestiny** [comment]
这个有概率会出现，不久就会修复。等zotero更新修复。
