### ISSUE TITLE
标签疑问。

### ISSUE THREAD

**Issue by tzycsu** [MuiseDestiny/zotero-style#587]
![image](https://github.com/MuiseDestiny/zotero-style/assets/79492862/bfa8b81c-09c6-4dfe-b411-27098e8c3597)
您好，左下角的标签可以只显示当前文件夹里面的吗？他显示了整个库的标签，因为文献是根据标签分类的，这样不好快速找到文献。

**Comment by MuiseDestiny** [comment]
这是zotero的功能

**Comment by tzycsu** [comment]
原来是这样的，设置成了库全部标签，十分感谢
![image](https://github.com/MuiseDestiny/zotero-style/assets/79492862/446a2961-7b16-4fac-8c1f-6eda9e59ed25)
