### ISSUE TITLE
右键没有列设置和视图组选项

### ISSUE THREAD

**Issue by chengyf21** [MuiseDestiny/zotero-style#59]
我的两个主机是同样版本zotero和插件，但其中一台使用正常，另一主机的右键没有显示列设置和视图组选项，shift+p也没有命令出现，请问是否是和哪个插件有冲突？
![1673786135018](https://user-images.githubusercontent.com/112738394/212541095-8fb443bb-f8ce-4843-bf36-c8eebf89cac8.jpg)
![1673786519031](https://user-images.githubusercontent.com/112738394/212541226-2cbd2bb0-648b-4b44-a0da-45b9a0b757b8.jpg)
![1673786604290](https://user-images.githubusercontent.com/112738394/212541298-bc75751d-df4f-49ba-9bf2-ab2365e29470.jpg)

**Comment by MuiseDestiny** [comment]
会不会安装包下载错了，感觉是任何功能都没生效

**Comment by MuiseDestiny** [comment]
更新一下reference插件

**Comment by chengyf21** [comment]
您好，按照您提供的思路重新更新了reference插件、下载了新的安装包，还是没有解决问题。于是我又调了输出日志发现可正常使用的那台机器是没问题的，但右键没有显示列设置和视图组选项的机器的输出日志有style相关报错，如下：
![1673799358804](https://user-images.githubusercontent.com/112738394/212552830-6640b884-4254-4d54-bdc6-2b7f3a8a7236.jpg)

**Comment by chengyf21** [comment]
看样子是因为未知原因，style和reference冲突了吗？

**Comment by MuiseDestiny** [comment]
禁用ref style会正常吗。感谢你反馈的截图，这对bug修复十分重要

**Comment by chengyf21** [comment]
很遗憾，禁用ref后还是没能正常运行，以下是输出日志：
![1673836203519](https://user-images.githubusercontent.com/112738394/212585986-f6b9fcfa-95b4-4c05-a278-b154cb28c203.jpg)
您客气了，很高兴能为如此优秀的插件作出贡献~

**Comment by chengyf21** [comment]
话说回来，我这台机器的其他插件好像也出现了一些未知bug（比如zotfile的自动重命名功能），我决定重新安装配置一下zotero软件，再试试您的插件~

**Comment by MuiseDestiny** [comment]
> 话说回来，我这台机器的其他插件好像也出现了一些未知bug（比如zotfile的自动重命名功能），我决定重新安装配置一下zotero软件，再试试您的插件~

好的，如果还不可以用，可以继续反馈

**Comment by chengyf21** [comment]
重新安装后一切正常了，真是很好用的一个插件，期待您继续维护更新~

**Comment by MuiseDestiny** [comment]
> 重新安装后一切正常了，真是很好用的一个插件，期待您继续维护更新~

OK的，但是代价有点大，需要重新安装

**Comment by majing2020** [comment]
<img width="505" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/63554459/e316d07a-b112-4b39-84cd-7f7859533be3">
<img width="709" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/63554459/d0999d5e-f7e0-48df-8762-c8b86d9eb644">

您好，我是mac设备，安装style插件后，也没有列设置，但是有阅读进度条。

**Comment by UUaUU** [comment]
求助大佬，Win也出现了一样的问题，卸载重装3次，没有解决
