### ISSUE TITLE
mac zotero7最新测试版 标签显示问题

### ISSUE THREAD

**Issue by mjcyolo** [MuiseDestiny/zotero-style#590]
**不礼貌不回复，直接关闭**
你好 mac端首次打开zotero 标签即在题目前显示 又在特定的标签列显示 
必须点击一下任意位置 题目前的标签才可以消失

**Comment by MuiseDestiny** [comment]
因为没刷新导致的。但是刷新会导致列宽调节bug，等zotero更新吧。
