### ISSUE TITLE
大大，mac 的被引数显示不出来，请问下这是 bug 吗？

### ISSUE THREAD

**Issue by Zhangxigu** [MuiseDestiny/zotero-style#592]
**不礼貌不回复，直接关闭**

**Comment by MuiseDestiny** [comment]
https://www.bilibili.com/video/BV1ZP411p7ko/?spm_id_from=333.999.0.0&vd_source=5a8c42dfa6d28820002ecae5a4a4fa64 见简介

**Comment by Zhangxigu** [comment]
我刚刚看完的这个视频，但是没有介绍哎。

**Comment by Zhangxigu** [comment]
看到了，感谢大大！

**Comment by Zhangxigu** [comment]
作者大大，小破站下单啦！麻烦您处理下，感谢！
