### ISSUE TITLE
mac下载最新版失败？如何寻找对应版本？

### ISSUE THREAD

**Issue by Unclece** [MuiseDestiny/zotero-style#595]
你好，mac电脑上一直下载失败，提示如图片所示。
- zotero版本：6.0.26
- zotero style版本：3.0.5

<img width="442" alt="WechatIMG1481" src="https://github.com/MuiseDestiny/zotero-style/assets/46061250/e4748974-739a-4167-aab0-dd14cc10a0a1">

**Comment by MuiseDestiny** [comment]
Zotero 6：https://github.com/MuiseDestiny/zotero-style/releases/tag/2.6.7

Zotero 7: https://github.com/MuiseDestiny/zotero-style/releases/tag/3.0.5
