### ISSUE TITLE
请问使用zotero style后打开文档直接无法高亮选取文字注释是为什么呀？排查了其他插件，发现只要使用zotero style颜色标注那一栏会直接消失，无法注释

### ISSUE THREAD

**Issue by 13062333948** [MuiseDestiny/zotero-style#596]

**Comment by MuiseDestiny** [comment]
zotero 版本 插件版本

**Comment by 13062333948** [comment]
> 

感谢回复，刚刚看了，zotero是6.0版本，style是用的2.6.7版本，是这两个版本不兼容吗

**Comment by MuiseDestiny** [comment]
> > 
> 
> 感谢回复，刚刚看了，zotero是6.0版本，style是用的2.6.7版本，是这两个版本不兼容吗

停用标注颜色更改就可以。

**Comment by 13062333948** [comment]
> > > 
> > 
> > 
> > 感谢回复，刚刚看了，zotero是6.0版本，style是用的2.6.7版本，是这两个版本不兼容吗
> 
> 停用标注颜色更改就可以。



> > > 
> > 
> > 
> > 感谢回复，刚刚看了，zotero是6.0版本，style是用的2.6.7版本，是这两个版本不兼容吗
> 
> 停用标注颜色更改就可以。
是在首选项-style里划掉annotation colors是吗？好像可以了也，感谢感谢！这样还能自定义颜色名字吗

**Comment by 13062333948** [comment]
> 是在首选项-style里划掉annotation colors是吗？好像可以了也，感谢感谢！这样还能自定义颜色名字吗

**Comment by 13062333948** [comment]
> > > 是在首选项-style里划掉annotation colors是吗？好像可以了也，感谢感谢！这样还能自定义颜色名字吗
> 
> 不能了，你升级到zotero 7，后，这个功能可以继续使用。

好的谢谢回复
