### ISSUE TITLE
“阅读时间”命令面板小建议

### ISSUE THREAD

**Issue by Dirtyuri** [MuiseDestiny/zotero-style#60]
1. 可否将“查看”放在“重置”之上，或者干脆在命令面板第一级菜单添加“查看阅读时间”命令？这样查看起来就快捷多了。

![1673833588349](https://user-images.githubusercontent.com/68465099/212581751-6372460e-e1a6-4762-a40e-4293c678d44d.png)

2. 可否让显示每页具体阅读时间的界面可跳转，也就是点击某页后打开对应的pdf页？看到阅读时长较久的某一页，就想点开来看下。这个实现起来是不是有些难度……

![1673833828310](https://user-images.githubusercontent.com/68465099/212582506-39164877-e70c-4195-9884-2cee684296a2.png)

感谢做了这么好的插件~

**Comment by MuiseDestiny** [comment]
> 1. 可否将“查看”放在“重置”之上，或者干脆在命令面板第一级菜单添加“查看阅读时间”命令？这样查看起来就快捷多了。
> 
> ![1673833588349](https://user-images.githubusercontent.com/68465099/212581751-6372460e-e1a6-4762-a40e-4293c678d44d.png)
> 
> 2. 可否让显示每页具体阅读时间的界面可跳转，也就是点击某页后打开对应的pdf页？看到阅读时长较久的某一页，就想点开来看下。这个实现起来是不是有些难度……
> 
> ![1673833828310](https://user-images.githubusercontent.com/68465099/212582506-39164877-e70c-4195-9884-2cee684296a2.png)
> 
> 感谢做了这么好的插件~

好建议，就这么做。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/212656954-73e736b4-3768-488b-ba27-d48d2a7f7015.png)

![image](https://user-images.githubusercontent.com/51939531/212657004-f6bcdd7c-5463-4d83-a54d-2dc754e39815.png)

实现了。

**Comment by Dirtyuri** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/212656954-73e736b4-3768-488b-ba27-d48d2a7f7015.png)
> 
> ![image](https://user-images.githubusercontent.com/51939531/212657004-f6bcdd7c-5463-4d83-a54d-2dc754e39815.png)
> 
> 实现了。

tql，再次感谢！

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.0.2
已发布
