### ISSUE TITLE
为什么nested tag都只有一个字

### ISSUE THREAD

**Issue by Hanawa-Kazuhiko** [MuiseDestiny/zotero-style#602]
以前还好好的。现在只有一个字了，而且每个字都会变成一个子集，怎么调回去呢

![image](https://github.com/MuiseDestiny/zotero-style/assets/41327633/070370f4-85ed-4218-925a-0f720f2c4502)
![image](https://github.com/MuiseDestiny/zotero-style/assets/41327633/24664324-2e5f-4261-bbb5-668f3fe91f95)

**Comment by MuiseDestiny** [comment]
高级 编辑器 搜索symbol 重置它
