### ISSUE TITLE
嵌套标签显示问题

### ISSUE THREAD

**Issue by l7ee** [MuiseDestiny/zotero-style#605]
[[大佬们好，我这个嵌套标签突然就显示不全了，只能显示单个字，以前是正常的，请问什么问题呢？
<img width="147" alt="微信图片_20230828111513" src="https://github.com/MuiseDestiny/zotero-style/assets/131570220/69e6df8f-162a-49ed-8a4f-31b389a73b95">
<img width="186" alt="微信图片_20230828111534" src="https://github.com/MuiseDestiny/zotero-style/assets/131570220/580456e7-33dc-4512-ada2-c4301a577c27">
以上是问题图片
装的是Zotero Style 2.6.7，zotero  6.0.26版本的

**Comment by githubonmylab** [comment]
我遇到了同样的问题，难以解决，有什么解决办法吗？

**Comment by MuiseDestiny** [comment]
Zotero://ztoolkit-debug/?run=window.alert(Zotero.Prefs.set("zoterostyle.nestedTags.linkSymbol", "/"))

**Comment by githubonmylab** [comment]
> Zotero://ztoolkit-debug/?run=window.alert(Zotero.Prefs.set("zoterostyle.nestedTags.linkSymbol", "/"))

您好，非常感谢您的回复！请问这段代码具体如何使用呢？感谢指导！！

**Comment by githubonmylab** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/264510011-237602ba-e3fe-4b16-a4cb-f99796f78e9a.png)

请问这个页面是在哪里呢？

**Comment by githubonmylab** [comment]
“高级 编辑器 搜索symbol 重置它”

已经解决，非常感谢您的解答！

**Comment by l7ee** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/264510011-237602ba-e3fe-4b16-a4cb-f99796f78e9a.png)

感激  已解决
