### ISSUE TITLE
阅读状态与非阅读状态的粗体切换显示

### ISSUE THREAD

**Issue by liut14** [MuiseDestiny/zotero-style#608]
作者您好，我是从 endnote 转移到 zotero 的用户（被zotero 强大的功能吸引，最简单zotero插入一条文献及其附件比endnote 方便很多）。使用一段时间体验之后，感觉endnote 的文献是否已读标记还是挺直观醒目的。
如图所示，加粗表示未读，并且列设置里面有一个可以筛选阅读状态。
![image](https://github.com/MuiseDestiny/zotero-style/assets/52646263/44f6212e-dcf2-4753-a0c8-6ffa4aaa4e6a)

 zotero 中也有很多标记文献阅读状态的方式，其中一个非常好的方式就是 zotero-sytle 中的标签功能（这个标签显示功能真的很不错），如图所示
![image](https://github.com/MuiseDestiny/zotero-style/assets/52646263/b8d7159a-be89-44ee-94a1-7da7e0069a15)

但是其实我个人感觉，有时候看过多的标签反而有点眼花缭乱的感觉，远不如最简单的 加粗、非加粗状态更直接，视觉冲击与感官性更强（个人感觉哈），看到条目标题的同时，就能反应过来这篇文献看没看，而不需再去看旁边的标签状态

目前我自己探索到的一个方式就是 通过在文献标题前后加入 <b></b> 可以手动实现加粗的功能，如图所示
![a0dc59433255356d80432a50da575bf](https://github.com/MuiseDestiny/zotero-style/assets/52646263/97144e86-af84-4460-abf6-01b446a055c3)

但是我不会写zotero 插件。不清楚您觉得这个提议是否有必要加入 zotero-style 后续的功能开发中。

祝好

更新： 上述 <b></b> 的方式可能会有一个问题，在插入文献时，也会加粗。这可能导致这个功能实现起来有点困难。
![image](https://github.com/MuiseDestiny/zotero-style/assets/52646263/66dc0234-846f-436f-8f4f-10846caa4faa)

**Comment by MuiseDestiny** [comment]
收到，开发中...

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/bd5f51ba-80d6-4230-bc2a-055dc72434ad)

**Comment by Justin-ShanJ** [comment]
如何能像zotero-tag一样，自动添加是否已经阅读的标签，自动变颜色，表示已经打开或者没有打开

**Comment by CharlesChowlee** [comment]
这个功能怎么实现

**Comment by MuiseDestiny** [comment]
> 这个功能怎么实现

最新版插件移除了这个功能。因为UI上会有bug，且只能表示已读/未读两种状态。现在推荐使用「状态列」，点击（条目和状态列交叉）空白处，自动弹出可设置的状态，可设置多种状态。

<img width="443" height="271" alt="Image" src="https://github.com/user-attachments/assets/ec046aa7-8d50-40ab-9e97-efce2e4eecb8" />

**Comment by CharlesChowlee** [comment]
感谢您的回复！
          由于状态列还是会占用显示空间，并且感觉没有“未读加粗”直观，希望后续能更新。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
