### ISSUE TITLE
按shift+p没有内容。

### ISSUE THREAD

**Issue by zqdave1993** [MuiseDestiny/zotero-style#61]
![image](https://user-images.githubusercontent.com/28385719/212606009-e0b76d08-331b-4970-97cb-8d03408cf566.png)
![image](https://user-images.githubusercontent.com/28385719/212606040-5f4d32ae-1716-4688-b80d-2c84ff245db9.png)
如图，虽然显示进度，但是命令行啥都木有。这个怎么解决呀。而且我看别人的命令行下面都是中文，而我是英文。

**Comment by MuiseDestiny** [comment]
如果安装了reference，更新下它

**Comment by zqdave1993** [comment]
> 如果安装了reference，更新下它

多谢！没想到那个插件也是大佬开发的。已解决。
