### ISSUE TITLE
新增的阅读状态栏无法改变列宽

### ISSUE THREAD

**Issue by 664787022** [MuiseDestiny/zotero-style#611]
**不礼貌不回复，直接关闭**
鼠标左右拖动无法改变列宽

**Comment by VectorZhao** [comment]
确实如此，我以为这里操作问题。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/3.0.6

**Comment by MuiseDestiny** [comment]
重新下载即可。已修复。

**Comment by VectorZhao** [comment]
只有添加日期可以改变，其他还是无法改变列宽

**Comment by MuiseDestiny** [comment]
> 只有添加日期可以改变，其他还是无法改变列宽

禁用其它插件/
