### ISSUE TITLE
关于后续版本保留“全文翻译”的请求。

### ISSUE THREAD

**Issue by PhoenixHwang** [MuiseDestiny/zotero-style#618]
大佬好！虽然我已经用上了“沉浸式全文翻译”（Magic）插件，但依旧觉得Style提供的全文翻译功能很好用，在某些场景下，Style提供的全文翻译直接写入笔记的方式能够和Magic插件互补。

不知是否可以考虑在后续版本中保留Style的全文翻译功能？感谢大佬！

**Comment by tutou2356** [comment]
求问magic是哪个插件呀，谢谢啦！

**Comment by MuiseDestiny** [comment]
以前，style有gpt问答功能，后来写了gpt插件，移除style的gpt功能。
同样，这次的全文翻译会移动到magic，并在magic更新。
