### ISSUE TITLE
插件安装失败最新版本

### ISSUE THREAD

**Issue by SmartNan** [MuiseDestiny/zotero-style#619]
老哥！
Win11系统，Zotero是6.0.26的版本。
在安装最新版本的时候出现：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

但是可以安装zotero style2.5.2的版本，不过这个版本没有阅读时间条，想要有进度条的版本qaq。
老哥看到后，麻烦回复一下下，感谢！！！

**Comment by 476857578** [comment]
同样的报错 求解答

**Comment by songjiezhang** [comment]
插件版本错了，选2.6.7的release版本

**Comment by SmartNan** [comment]
我换成了Zotero7之后，安装新的版本就可以了







在 2023-09-01 17:48:56，"songjiezhang" ***@***.***> 写道：

插件版本错了，选2.6.7的release版本

**Comment by SmartNan** [comment]
作者说，插件版本错了，选2.6.7的release版本。我重新装了zotero7，然后装了最新的插件。



在 2023-08-31 13:47:16，"Baodi-Yu" ***@***.***> 写道：

同样的报错 求解答

**Comment by MuiseDestiny** [comment]
release是zotero 6的

pre-release是zotero 7的

**Comment by SmartNan** [comment]
好的！谢谢提醒！！！！



在 2023-09-01 20:10:15，"Polygon" ***@***.***> 写道：

release是zotero 6的

pre-release是zotero 7的

**Comment by haojieya** [comment]
我是zotero7 安装[chartero]插件时报错与目前版本不兼容，但我安装的就是2.6.2版本的插件，请问这个是什么问题呀
