### ISSUE TITLE
关于pdf背景色设置为深色后pdf中的参考文献和图片超链接点击后无法跳转

### ISSUE THREAD

**Issue by Darcake** [MuiseDestiny/zotero-style#621]
hello，想问一下
1.有人遇到过将pdf视图背景设置为深色模式后，pdf中的参考文献和图片的超链接点击后跳转失效的问题吗？有人知道如何解决吗？
2.同样将pdf设置为深色模式后，笔记使用高亮颜色会被修改，比如使用绿色高亮，在深色背景下会被修改为紫色，请问能否改为深色模式后不修改高亮颜色
win11+zotero6

**Comment by Darcake** [comment]
sorry，应该是pdf源文件的问题

**Comment by SoufSilence** [comment]
> sorry，应该是pdf源文件的问题

应该不是pdf的问题，我也有同样的问题
