### ISSUE TITLE
无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容

### ISSUE THREAD

**Issue by McKinleyLu** [MuiseDestiny/zotero-style#627]
版本是6.0.26，请大佬解决一下

**Comment by MuiseDestiny** [comment]
你下载错版本

**Comment by octoue** [comment]
我也遇到了这个问题，请问应该下哪个版本？

**Comment by McKinleyLu** [comment]
你好作者：
Zotero 版本： 6.0.26
Zotero-style版本：2.6.7
文档中未找到Zotero-style版本适应Zotero 版本的说明，请问Zotero-style应该使用哪个版本？
祝好

**Comment by McKinleyLu** [comment]
> 请使用2.6.7版本
