### ISSUE TITLE
切换视图组可以考虑设置一下快捷键吗？

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-style#63]
切换查看的方便度会大大提升，

**Comment by MuiseDestiny** [comment]
> 切换查看的方便度会大大提升，

快捷键有什么建议嘛，不冲突的，好用好记的

**Comment by 17816712353** [comment]
> > 切换查看的方便度会大大提升，
> 
> 快捷键有什么建议嘛，不冲突的，好用好记的

可能考虑从某个功能键+12345，😂。刚使用这个功能我第一直觉就想12345去切换，但是12345估计会冲突，所以考虑什么shift+12345 或者 cmd+shift+12345 之类的。。。

**Comment by 17816712353** [comment]
> > 切换查看的方便度会大大提升，
> 
> 快捷键有什么建议嘛，不冲突的，好用好记的

再反馈一个小问题：标题列设置颜色似乎不起作用。透明度改了倒是能生效，颜色改完再打开设置又变回默认颜色了。

**Comment by MuiseDestiny** [comment]
已添加
触发：Alt+</>
翻译：按住Alt再按<或>键，就会切换到上一个/下一个视图

Q：为什么不把快捷键定义交给用户？
A：容易冲突，Zotero Tag一般可以自定义数字Alt+0来指定一个标签，视图组再用Alt+数字势必会冲突。

Q：shift，ctrl呢？
A：在zotero条目面板都不如alt好用，shift，ctrl一般有特殊用途，已经被Zotero官方用了。

Q：为什么不是方向键而是><号？
A：1.尝试添加方向键，但触发失败；2.向style老版本的`>`按钮致敬。
