### ISSUE TITLE
建议增加一个“阅读时间”的列字段

### ISSUE THREAD

**Issue by wqfuian** [MuiseDestiny/zotero-style#632]
阅读文献的时候已经能记录阅读时间了，是否可以增加这样一个列字段，实现按照阅读时间排序
目前是这种状态，

![image](https://github.com/MuiseDestiny/zotero-style/assets/58714360/bfa15b5b-6456-47c1-aa43-ab00f356a99b)

加一个列字段，像这样

![image](https://github.com/MuiseDestiny/zotero-style/assets/58714360/06db7e7f-c490-4707-a9f3-d8072d8dae05)

**Comment by yzy1228682367** [comment]
附议~

**Comment by MuiseDestiny** [comment]
收到

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/60c905ac-dd1f-4cd3-83f1-46f60063af45)

与影响因子列列一致，可以设置ui 数字显示

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/3.6.8
