### ISSUE TITLE
Read/Unread 功能

### ISSUE THREAD

**Issue by sleepymalc** [MuiseDestiny/zotero-style#635]
最新的插件裡面有個Read/Unread功能，但具體的功能在README裡面沒找到，直接觀察也不太確定功能。

**Comment by MuiseDestiny** [comment]
我更新一下readme

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style#readunread-status

**Comment by sleepymalc** [comment]
但有時上下滾動後狀態會直接消失
