### ISSUE TITLE
3.0.9版本插件仍然存在列宽调整异常的情况

### ISSUE THREAD

**Issue by opacscdbph44** [MuiseDestiny/zotero-style#637]
大佬您好，看最新版本的更新应该是您找到了解决列宽异常的方法，目前只有标签这一列仍然异常，具体情况如视频
我的zotero版本为7.0.0-beta.39+ecba25be0 (64-bit)
zotero style插件版本为3.0.9
https://github.com/MuiseDestiny/zotero-style/assets/131225543/aa4a74de-582c-4297-a189-4856123a9dd3

2023/09/10 update
通过逐一实验，已探明的可能导致列宽bug的插件有
1. Jasminum (升级到1.0.0-6后貌似已解决，但是偶尔还是不行)
2. Green Frog (尚未解决)

目前我自己在使用不存在冲突的插件（仅供参考，建议升级到pre release最新版本）：
![image](https://github.com/MuiseDestiny/zotero-style/assets/131225543/1fbce484-0226-406f-b289-8813c66678c8)
![image](https://github.com/MuiseDestiny/zotero-style/assets/131225543/d3602618-7ef8-4ece-be68-2be32bf289c4)
P.S. Jasminum 偶尔还是不行

**Comment by huangsh** [comment]
使用jasminum的时候也是无法调整列宽

**Comment by GFDGIT** [comment]
我这边是`进度`一列异常。

**Comment by GFDGIT** [comment]
> 我这边是`进度`一列异常。

突然间它就好了😂

**Comment by ccyx1997** [comment]
我也遇到了相同的问题，关闭了其他所有插件问题依然存在，进度一列变的特别窄且无法调整。

**Comment by Anastasiauu** [comment]
我也是这个问题，而且目前还无法解决

**Comment by Ash-Shy** [comment]
我也发现了，有时候打开软件会发现某些列变得极窄并且无法调节宽度，在关闭jasminum并重启后恢复了正常

**Comment by cesaryuan** [comment]
> 在关闭jasminum并重启后恢复了正常

感谢，实测关闭jasminum并重启后就恢复了正常！

**Comment by MuiseDestiny** [comment]
茉莉花原因。

**Comment by wakanda-wang** [comment]
我也是，困扰了两天的问题在关闭茉莉花后就好了，谢谢uu分享
