### ISSUE TITLE
删除文献之后会异常

### ISSUE THREAD

**Issue by holaxys** [MuiseDestiny/zotero-style#64]
如果把文献从库移到回收站, 然后再清空回收站, 下一次打开zotero的时候必loading... 长期loading
只能退出重进. 然后重进之后删掉的文献又回出现

**Comment by MuiseDestiny** [comment]
> 如果把文献从库移到回收站, 然后再清空回收站, 下一次打开zotero的时候必loading... 长期loading 只能退出重进. 然后重进之后删掉的文献又回出现

感谢反馈，尽快修复！

**Comment by MuiseDestiny** [comment]
我测试不存在这个问题，停用插件再这么操作试试呢

**Comment by holaxys** [comment]
我删掉然后重装了，后面好了在 2023年1月19日，01:23，Polygon ***@***.***> 写道：﻿
我测试不存在这个问题，停用插件再这么操作试试呢
