### ISSUE TITLE
高能进度条突然消失

### ISSUE THREAD

**Issue by drxxy98** [MuiseDestiny/zotero-style#641]
大大您好，我是用的2.6.7版本的插件，正常抓取文献的时候，zotero卡了一下，然后所有的高能进度条都不见了。
准确来说是被清空了一样，因为在进度条消失后，我又打开文献，文献的阅读进度重新开始被记录。
现在就是很焦灼 很懊恼，高能进度条对我来说真的很重要
请问这种情况应该怎么处理呢
谢谢!期待回复

**Comment by drxxy98** [comment]
再补充一小点
现在选中任意文献，shfit+P后都不显示高能进度条这个选项了。。。

**Comment by ppnpp** [comment]
我也有遇到你最开始提到的情况

**Comment by ppnpp** [comment]
感谢回复，根据您的回复解决了这个问题。解决问题以后，我对addon item这个东西进行了一些了解，进而明白了我的问题出在我在ipad端把addon item给删掉了。总之感谢作者！

**Comment by fengjunkang** [comment]
大大您好，我是用的2.6.7版本的插件，不显示进度，有时候打开了读一下进度条有了，但是会突然消失
