### ISSUE TITLE
3.0.6以后版本删除全文翻译

### ISSUE THREAD

**Issue by vw911** [MuiseDestiny/zotero-style#644]
作者你好，觉得全文翻译功能很好用，不知作者出于什么考虑在3.0.6以后版本中删除了这个功能，谢谢！

**Comment by MuiseDestiny** [comment]
全文翻译调用grobid的demo，不适宜大范围使用

> Warning: Some quota and query limitation apply to the demo server! Please be courteous and do not overload the demo server. For any serious works, you will need to deploy and use your own Grobid server, see the [GROBID and Docker containers documentation](https://grobid.readthedocs.io/en/latest/Grobid-docker/) for doing that easily and activate some Deep Learning models.

https://github.com/kermitt2/grobid#demo-server
