### ISSUE TITLE
有关标签不显示的问题

### ISSUE THREAD

**Issue by YYY7C** [MuiseDestiny/zotero-style#65]
标签列表显示为空白，请问是需要在哪里开启这个功能吗？
![1](https://user-images.githubusercontent.com/85858495/213411121-ae22a3ec-207d-45c1-b557-66792f4e7579.png)

**Comment by MuiseDestiny** [comment]
指派颜色的标签才会显示，这是Zotero的设定。

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/213727147-e6707442-6d97-459a-af73-02beef900558.png)

也可以在任意自定义列显示，方法：借助zotero IF的“归档”或“标签集”功能（以前需要手动设置，IF更新后现在自动化了）

**Comment by 1067237855** [comment]
如果可以开发出这个功能的话，建议“指派颜色”和“未指派颜色”的标签有所区分（最好让用户选择显示哪一种）。比如，我现在用的IF的办法是“指派颜色”和“未指派颜色”的标签全都显示，而我希望的是只显示“未指派颜色”的标签。Style只能显示“指派颜色”的标签。另外，新版Style强行占用了“其它”列，我现在只能被迫禁用style了/(ㄒoㄒ)/~~，期待早日完善。

**Comment by 1067237855** [comment]
> 强烈推荐＃标签，代替在其他里显示，不指派颜色也可以的。另外，其他列用于存一些小数据，是以后插件的大势所趋。
style插件现在   不指派颜色的标签   也可以显示在"#标签"列了吗？

**Comment by MuiseDestiny** [comment]
> > 强烈推荐＃标签，代替在其他里显示，不指派颜色也可以的。另外，其他列用于存一些小数据，是以后插件的大势所趋。
> 
> style插件现在 不指派颜色的标签 也可以显示在"#标签"列了吗？
可以

**Comment by 1067237855** [comment]
> > > 强烈推荐＃标签，代替在其他里显示，不指派颜色也可以的。另外，其他列用于存一些小数据，是以后插件的大势所趋。

> > style插件现在 不指派颜色的标签 也可以显示在"#标签"列了吗？
> > 可以

对于未加#的旧标签不管用、不显示
![image](https://user-images.githubusercontent.com/104330036/213863260-16461f5a-0320-4696-b015-58389cdfd0f1.png)
我有hao'duo好多旧标签/(ㄒoㄒ)/~~
我相信其它zotero的老用户也会有这个问题：旧标签太多，不可能每篇文献翻一遍，都重新把旧标签加上#

**Comment by 1067237855** [comment]
> > > 强烈推荐＃标签，代替在其他里显示，不指派颜色也可以的。另外，其他列用于存一些小数据，是以后插件的大势所趋。
> > 
> > 
> > style插件现在 不指派颜色的标签 也可以显示在"#标签"列了吗？
> > 可以

点赞！！！

**Comment by dapengl** [comment]
如果想要显示没有任何标注的标签，可以在列设置中的match里填入~~/

**Comment by dapengl** [comment]
> > > > 强烈推荐＃标签，代替在其他里显示，不指派颜色也可以的。另外，其他列用于存一些小数据，是以后插件的大势所趋。
> 
> > > style插件现在 不指派颜色的标签 也可以显示在"#标签"列了吗？
> > > 可以
> 
> 对于未加#的旧标签不管用、不显示 ![image](https://user-images.githubusercontent.com/104330036/213863260-16461f5a-0320-4696-b015-58389cdfd0f1.png) 我有hao'duo好多旧标签/(ㄒoㄒ)/~~ 我相信其它zotero的老用户也会有这个问题：旧标签太多，不可能每篇文献翻一遍，都重新把旧标签加上#

> 如果想要显示没有任何标注的标签，可以在列设置中的match里填入~~/
