### ISSUE TITLE
关于阅读时间数字显示不全的问题

### ISSUE THREAD

**Issue by seaclauss** [MuiseDestiny/zotero-style#652]
当我的阅读时间超过100min时，会在阅读时间显示进度条后显示出“1...”
希望作者能改善这个问题。
<img width="80" alt="2dcdcb1998fe9921825a2d9112164ae" src="https://github.com/MuiseDestiny/zotero-style/assets/119683425/b0df4c77-787b-4622-b2d1-abc86e06ff27">

**Comment by jiuwu-zzx** [comment]
这个问题是已经沉没了嘛，你开issue这么久了为啥作者大大不理嘞😭，每天打开zotero都会想到这个问题

**Comment by MuiseDestiny** [comment]
优化中...

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi

已修复

**Comment by seasonzhao** [comment]
请问阅读时间这个功能在哪里啊，没有找到，谢谢作者大大

**Comment by aulline13** [comment]
同问，最近一直找不到这个功能了，以前明明有啊
