### ISSUE TITLE
命令面板不显示全文翻译选项

### ISSUE THREAD

**Issue by xchyyb** [MuiseDestiny/zotero-style#661]
![image](https://github.com/MuiseDestiny/zotero-style/assets/78303344/9ad6a285-0cae-4748-97f7-bcd7edb2d8dd)
zotero7，三个需要的插件安装的版本均符合要求，但是shift+P后命令面板如图所示，没有全文翻译选项，请问这种问题如何解决？

**Comment by ananzibian** [comment]
我的也是，而且zotero figure 不能打开单独窗口

**Comment by MuiseDestiny** [comment]
7版本插件，移除了这一功能。6版本，还保存。

**Comment by ananzibian** [comment]
所以7版本是不能进行全文翻译了吗
