### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by Ying-Zi66** [MuiseDestiny/zotero-style#663]
**不礼貌不回复，直接关闭**
![image](https://github.com/MuiseDestiny/zotero-style/assets/64450726/bca6c5e7-4b97-45f4-b709-4493c00bfbab)
无法兼容zotero，我的zotero版本是6.0.27，下载的xpi版本是最新版

**Comment by Hr2306000** [comment]
最新版xpi是适用于zotero7的
