### ISSUE TITLE
多设备同步失败

### ISSUE THREAD

**Issue by batman47steam** [MuiseDestiny/zotero-style#67]
在笔记本上安装zotero-style后，未分类条目下会有一个addonitem，但是在实验室台式机上安装好zotero-style后，又会在未分类条目下生成一个addonitem，好像没办法共用同一个，删除任意一个后，会出现注释的记录直接出现在条目外的情况，pc2的注释直接在外面
![image](https://user-images.githubusercontent.com/36287035/213696431-91897526-afbc-4d9c-9667-d2ab18c4e68d.png)

**Comment by batman47steam** [comment]
![image](https://user-images.githubusercontent.com/36287035/213700237-5da271e0-711f-4923-96a9-6ece71a58180.png)
pc1和pc2会各种的生成自己的addon item条目，无法实现设备间同步

**Comment by MuiseDestiny** [comment]
选中同步过来的addon item，按shift p，指定一下插件储存条目

**Comment by batman47steam** [comment]
![image](https://user-images.githubusercontent.com/36287035/213702284-cf5d6fb0-3074-43ef-8441-3e508248aaf0.png)
笔记本上可以直接指定存储条目，但是另一台电脑上好像shift+p显示不出命令

**Comment by MuiseDestiny** [comment]
> ![image](https://user-images.githubusercontent.com/36287035/213702284-cf5d6fb0-3074-43ef-8441-3e508248aaf0.png) 笔记本上可以直接指定存储条目，但是另一台电脑上好像shift+p显示不出命令

如果有reference插件，升级一下它重启

**Comment by batman47steam** [comment]
这下可以了，谢谢
