### ISSUE TITLE
请问能否在标签导航栏中设置仅文件夹中存在的标签可见？

### ISSUE THREAD

**Issue by guo2060** [MuiseDestiny/zotero-style#670]
![image](https://github.com/MuiseDestiny/zotero-style/assets/75665593/b154eaa1-d340-42e3-b459-a59de776f334)
如图，个人感觉查看不太方便。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/3.1.4
