### ISSUE TITLE
全文翻译回归

### ISSUE THREAD

**Issue by Jonashoney06** [MuiseDestiny/zotero-style#671]
请问可以继续全文翻译功能吗？

**Comment by BoBo-YunYun** [comment]
新出了插件magic可以全文翻译，付费的，但是不仅包括全文翻译，还有GPT自动总结，以后似乎还会出很多新功能，我认为还是挺值的

**Comment by MuiseDestiny** [comment]
https://gitee.com/zotero-chinese/zotero-magic-for-user/blob/master/zotero-magic-for-user.xpi
