### ISSUE TITLE
3.1.5 右侧边笔记渲染，跟随嵌套标签过滤， 没有懂怎么使用这个功能

### ISSUE THREAD

**Issue by Elodie-0117** [MuiseDestiny/zotero-style#693]
我猜测意思是我选中一个标签， 会出现所有有这个标签的条目，然后选中条目，笔记侧边栏只显示带有这个标签的注释预览，可以安装可这个最新版本以后，没有任何变化诶，就还是预览的所有注释，不知道如何筛选注释预览？

**Comment by skipskipthree** [comment]
还有一个小问题，笔记预览窗口能否跟随侧边栏做到一致缩放？最新的这个版本可以预览，侧边栏可预览，但是不显示完整的缩放，只有滑动左右滑块才行。

**Comment by BoBo-YunYun** [comment]
> 我猜测意思是我选中一个标签， 会出现所有有这个标签的条目，然后选中条目，笔记侧边栏只显示带有这个标签的注释预览，可以安装可这个最新版本以后，没有任何变化诶，就还是预览的所有注释，不知道如何筛选注释预览？

首先你的标签必须是带#的嵌套标签；
其次你必须在左下角以嵌套标签的形式（即有标签树）筛选。

**Comment by Elodie-0117** [comment]
> > 我猜测意思是我选中一个标签， 会出现所有有这个标签的条目，然后选中条目，笔记侧边栏只显示带有这个标签的注释预览，可以安装可这个最新版本以后，没有任何变化诶，就还是预览的所有注释，不知道如何筛选注释预览？
> 
> 首先你的标签必须是带#的嵌套标签； 其次你必须在左下角以嵌套标签的形式（即有标签树）筛选。

谢谢，了解了，想问一下因为我现在所有标签都是没有#在前面的，有什么方便的办法把所有标签前面添加上#，或者有哪里可以设置取消#识别嵌套吗

**Comment by Elodie-0117** [comment]
噢 我好像知道了 去#Tags列Match设置为空白好像可以

**Comment by BoBo-YunYun** [comment]
👍👍👍
