### ISSUE TITLE
自定义期刊数据库显示不到的问题

### ISSUE THREAD

**Issue by jasonandjack1997** [MuiseDestiny/zotero-style#697]
首先非常感谢您开发这么好的一个软件。
我在easy scholar 自己手动录入了一个133条数据的数据集（非数据库集市， 是自己手动输入的）。是新闻传播分级数据库。但是遗憾的是我似乎没办法在zotero style里成功显示标签。

我调用了easy scholor开放接口的api，显示是正确的。我阅读了相关issues去除了标题以及分级等的中文，但是依然无法解决。

数据库的缩写为comm
数据库详细信息
<img width="474" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/5700223/b2fc0b0b-200a-4f23-a719-43d306516dbc">
zotero里不显示该数据集
<img width="509" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/5700223/73dac4d6-7e38-4267-a497-b515e42964fa">

版本信息
zotery style: 3.1.5
zotero : 7.0.0-beta.44+64a78412c (64-bit)
windows 11

这是easy scholar 调用的结果：
{"code":200,"msg":"SUCCESS","data":{"customRank":{"rankInfo":[{"uuid":"1646134626621235200","abbName":"ABS","oneRankText":"4*","twoRankText":"4","threeRankText":"3","fourRankText":"2","fiveRankText":"1"},{"uuid":"1711167066913546240","abbName":"comm","oneRankText":"A*","twoRankText":"A","threeRankText":"B","fourRankText":"BCN"}],"rank":[]},"officialRank":{"all":null,"select":null}}}

非常希望能解决这个问题，谢谢！

**Comment by MuiseDestiny** [comment]
收到，正在处理

**Comment by MuiseDestiny** [comment]
能给一个你录入数据库的示例期刊吗

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/ffe68681-c96c-4a70-b382-c304d22f8537)

根据你的返回，这是一个空返回。

**Comment by MuiseDestiny** [comment]
非空是这样子

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/00fffb53-190b-48cd-8796-e0d70c8846a3)

**Comment by MuiseDestiny** [comment]
rankInfo只是记录了用户添加的自定义数据集

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/323fb9c8-c9cb-45d6-bcab-58e7d2bf8b8d)

你可以试试 `新闻与传播研究` ，这个是可以的

**Comment by jasonandjack1997** [comment]
> 能给一个你录入数据库的示例期刊吗

谢谢你这么快回复。下面两个等级分别是1和2
Journal of Comunication
Journal of Advertising

另外，刚才看到zotero通知有显示调取comm数据库，但是没有显示值。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/d886a6d6-2500-4ec8-a458-6d38a6a06dfc)


都是正常的，我是zotero 7 插件3.1.5。

**Comment by MuiseDestiny** [comment]
请更新到zotero 7 插件3.1.5解决此问题。zotero6版本插件将不在维护。

**Comment by jasonandjack1997** [comment]
> 请更新到zotero 7 插件3.1.5解决此问题。zotero6版本插件将不在维护。

你好 我是zotero 7 , 3.15. 
我按你的方法手动添加了一些在自定义数据库中的item，发现有的可以显示，有的不行。
下面这些都在这个数据库里，但是有的可以获取有的不行
<img width="684" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/5700223/b3167dfe-3b31-4ac2-98f5-71de9b78c214">

这个api返回了rank和official rank两个，会不会这样就不能显示？但是有的我看也没有冲突。
https://www.easyscholar.cc/open/getPublicationRank?secretKey=2a63ab921852413380437ea1150fb53e&publicationName=Human%20Communication%20Research

**Comment by jasonandjack1997** [comment]
> 能给一个你录入数据库的示例期刊吗

这是几档期刊的信息
AList = '''Journal of Computer-Mediated Communication
Information Communication and Society
Journal of Advertising
Comunicar
Political Communication
Communication Theory
Media Psychology
Public Relations Review
International Journal of Advertising
International Journal of Press-Politics
Public Understanding of Science
Communication & Sport
Journal of Advertising Research
Journalism
Telecommunications Policy
Science Communication
Public Opinion Quarterly
Communication Monographs
Research on Language and Social Interaction
Journal of Broadcasting & Electronic Media
International Journal of Mobile Communications
Journalism Studies
Health Communication
Journalism & Mass Communication Quarterly
Journal of Social and Personal Relationships
Journalism Practice
Journal of Health Communication
Mass Communication and Society
Mobile Media & Communication
International Journal of Business Communication
European Journal of Communication
Games and Culture
'''.splitlines()


BList = '''
Feminist Media Studies
Management Communication Quarterly
International Journal of Public Opinion Research
Environmental Communication-A Journal of Nature and Culture
Journal of Public Relations Research
Discourse & Society
Media Culture & Society
Written Communication
Journal of Language and Social Psychology
Chinese Journal of Communication
Technical Communication
Discourse Context & Media
Television & New Media
International Journal of Communication
Journal of Media Psychology-Theories Methods and Applications
Argumentation
Language & Communication
Discourse Studies
International Journal of Conflict Management
Journal of Applied Communication Research
Personal Relationships
Convergence-The International Journal of Research into New Media Technologies
Interaction Studies
Critical Discourse Studies
Critical Studies in Media Communication
Discourse & Communication
Continuum-Journal of Media & Cultural Studies
Visual Communication
IEEE Transactions on Professional Communication
Social Semiotics
Journal of Business and Technical Communication
Communications-European Journal of Communication Research
International Communication Gazette
Javnost-The Public
Quarterly Journal of Speech
Journal of Mass Media Ethics
Asian Journal of Communication
Communication Culture & Critique
Journal of African Media Studies
Media International Australia
Communication and Critical-Cultural Studies
Translator
Rhetoric Society Quarterly
Text & Talk
Tijdschrift Voor Communicatiewetenschap
Journal of Media Economics
Narrative Inquiry
African Journalism Studies
'''.splitlines()

BCNList = '''中国社会科学
中国软科学
心理学报
社会学研究
北京大学学报
清华大学学报
厦门大学学报
武汉大学学报
中国人民大学学报
南京大学学报
复旦学报
浙江大学学报
南开学报
中山大学学报
北京师范大学学报
上海交通大学学报
西安交通大学学报
新闻与传播研究
国际新闻界
现代传播
新闻大学
传播与社会学刊（香港）
新闻学研究（台湾）
'''.splitlines()
BCNList

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/2f93fe6b-1585-49b0-8f8d-83a6663560f6)

可以的
