### ISSUE TITLE
“标题”字段会显示已翻译的标题内容[titleTranslation: ]，请问如何设置显示 item 的原始标题[未翻译内容]？

### ISSUE THREAD

**Issue by Derekmini** [MuiseDestiny/zotero-style#704]
## 软件环境：

Zotero: `7.0.0-beta.45+64a78412c`
zotero-style: `3.1.5`
系统: `macOS`

## 问题描述：

使用 zotero-pdf-tranlate 插件翻译标题后，zotero-style 插件会一直显示前者在“其他”字段中自动添加的：`titleTranslation: 这篇文章的题目` 内容，而不能显示 item 的原标题。

## 已经尝试的操作：

1. 重装 zotero-style 插件；
2. 重装 zotero-pdf-translate；
3. 禁用除 zotero-style 以外的所有插件；
4. 尝试将 `titleTranslation: ` 修改为其他内容，只要有变动，就能让 zotero-style 显示 item 的原标题，哪怕只删除冒号后面的空格也能奏效，**所以确认与 `titleTranslation: ` 字段有关联**。

## 问题复现：

在任意位置手动新建一个条目，设置其题目为 “The title of this item”，进行如上问题复现：

当“其他”字段中不存在“titleTranslation: ”时[第1张图]，
item标题内容显示为原始内容，
即 “The title of this item”

当“其他”字段中存在“titleTranslation: ”时[第2张图]，
item标题内容显示为“其他”字段中相关内容，
即 “这篇文章的题目”

<img width="400" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/30514323/48b1bcbc-3c8a-4398-bb2b-c3815779c355"><img width="400" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/30514323/fda02872-b2de-429c-99a7-0083d7410b70">

### 已禁用了其他所有插件：
关闭其他插件，并且重新启动 Zotero 7，只启用 zotero-style 插件：
<img width="500" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/30514323/988abd95-41c1-4178-b90e-704d8a366b00">

**Comment by Derekmini** [comment]
使用3.1.8版本即可解决该问题。

#703

**Comment by chengda1229** [comment]
现在已经解决问题，在style列设置中能够勾选显示翻译还是原文

**Comment by WYHunstoppable** [comment]
> 现在已经解决问题，在style列设置中能够勾选显示翻译还是原文

👍

**Comment by zhaojianan166** [comment]
> 现在已经解决问题，在style列设置中能够勾选显示翻译还是原文

厉害

**Comment by songhaosun3-glitch** [comment]
可以试试ctrl+alt+t
