### ISSUE TITLE
更新7版本后shift p没有全文翻译选项

### ISSUE THREAD

**Issue by menmeng-wong** [MuiseDestiny/zotero-style#706]
已经设置好了translate和note 但还是不行
![image](https://github.com/MuiseDestiny/zotero-style/assets/128115110/dbe2945f-414d-4d0d-9bea-11349e1a4558)

**Comment by MuiseDestiny** [comment]
https://gitee.com/zotero-chinese/zotero-magic-for-user/blob/master/zotero-magic-for-user.xpi

**Comment by menmeng-wong** [comment]
> https://gitee.com/zotero-chinese/zotero-magic-for-user/blob/master/zotero-magic-for-user.xpi

![image](https://github.com/MuiseDestiny/zotero-style/assets/128115110/41f55f6a-deb0-4bed-b7fd-1e9e31fbe4ff)
