### ISSUE TITLE
选中文本后，顶部栏和侧栏消失，pdftranslate也不自动翻译

### ISSUE THREAD

**Issue by Crush-RY** [MuiseDestiny/zotero-style#707]
无文本选中时：
![](https://fyzfly.oss-cn-beijing.aliyuncs.com/img/202310111921960.png)
选中文本时：
![](https://fyzfly.oss-cn-beijing.aliyuncs.com/img/202310111920789.png)
侧栏和顶部栏都消失， 也不会自动翻译了

关闭zotero-style后恢复正常

**Comment by MuiseDestiny** [comment]
shift+P
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/18d3103a-2a13-4848-aa50-048b2ad27957)

**Comment by 666charon** [comment]
我也遇到了这个问题 请问是怎么解决的啊

**Comment by 666charon** [comment]
已解决 开发者是正确的
