### ISSUE TITLE
[BUG] 最近添加和最近阅读

### ISSUE THREAD

**Issue by 7oud** [MuiseDestiny/zotero-style#708]
- OS: Win10
- Zotero Version: 7.0.0
- Plugin Version: 3.1.5
英文操作系统，Zotero语言也是英文，但是BN添加的两个搜索项是`最近添加`和`最近阅读`，而非`Recent Added` and `Recent Readed`. 另外支持Zotero6的BN版本能否也添加一个配置选项，以便关掉Recent搜索

**Comment by MuiseDestiny** [comment]
BN？

**Comment by 7oud** [comment]
这功能是style添加的吧，我描述的时候写错了
