### ISSUE TITLE
enable style后 zotero转彩虹圈很容易卡，请问如何解决？

### ISSUE THREAD

**Issue by hannah037** [MuiseDestiny/zotero-style#709]
您好！我很想使用style，但启用style后，Zotero很容易卡顿。请问有什么解决方法吗？

**Comment by hannah037** [comment]
有些回复提到了禁用某些功能的可能性。我该如何操作呢？你有哪些建议可以提供，指出应该禁用哪些功能呢？

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/955c52fa-8afd-41ec-bfa4-f447e7192488)


这里开启你想用的就可以了。用不到的关闭。

你最想用style的什么功能呢

**Comment by hannah037** [comment]
您好，我关闭了一些功能后发现仍然有卡顿，但情况好了许多。我正在逐一重新开启它们，以期找到最佳平衡状态。总体而言，我最喜欢的是影响因子和分区的直观呈现方式，在文献列表中非常直观和美观。
非常感谢您

**Comment by refined-fish** [comment]
> 您好，我关闭了一些功能后发现仍然有卡顿，但情况好了许多。我正在逐一重新开启它们，以期找到最佳平衡状态。总体而言，我最喜欢的是影响因子和分区的直观呈现方式，在文献列表中非常直观和美观。 非常感谢您

问题解决还请关闭哦
