### ISSUE TITLE
全文翻译问题

### ISSUE THREAD

**Issue by Xiao-Y29** [MuiseDestiny/zotero-style#710]
开发者您好，很高兴能体验到如此便捷的插件来帮助我阅读文献，为您献上感谢。在Zotero-Style的2.7版本中新增了与better notes共同使用的全文翻译功能，但是最更新的版本中我不知道在哪里找到全文翻译功能，请您指教。

**Comment by MuiseDestiny** [comment]
移除了
这里有https://gitee.com/zotero-chinese/zotero-magic-for-user/blob/master/zotero-magic-for-user.xpi
