### ISSUE TITLE
Zotero7 #tag 缺失/显示不全

### ISSUE THREAD

**Issue by JohannaXiao** [MuiseDestiny/zotero-style#718]
**不礼貌不回复，直接关闭**
您好,在zotero7上标签显示不全, 能不能帮忙看一下是怎么回事?
<img width="1382" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/62994240/c15a0d7b-e901-47fa-b7d8-6df72f6007d2">
正常是有很多标签的,如下图
<img width="1382" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/62994240/cc73598e-17ba-40e6-b25d-1a7055df1194">

**Comment by summmeer** [comment]
同问 怎么解决的
