### ISSUE TITLE
求助，打开文档之后没有注释栏

### ISSUE THREAD

**Issue by zqdave1993** [MuiseDestiny/zotero-style#721]
**不礼貌不回复，直接关闭**
大神你好！我打开任意文献，只要鼠标在文档上长按准备高亮文本等操作，上面的菜单栏就会直接消失。卸了style就正常，请问这个怎么解决。
![image](https://github.com/MuiseDestiny/zotero-style/assets/28385719/39317169-6a95-4be8-828a-a13ce56912c8)

**Comment by MuiseDestiny** [comment]
插件不是最新
