### ISSUE TITLE
Tab Manager神器！P大🐂🍺！但是已经打开的文献太多的话，没有办法显示“tab group”耶？

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-style#722]
**不礼貌不回复，直接关闭**
![CleanShot 2023-10-18 at 00 19 58@2x](https://github.com/MuiseDestiny/zotero-style/assets/50101175/cf75c3cd-16cd-42dd-a60e-220e4a80756d)

**Comment by MuiseDestiny** [comment]
已修复，请等待github更新

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/3.1.9

**Comment by yzy1228682367** [comment]
多谢P大~
