### ISSUE TITLE
blank Publication tags 

### ISSUE THREAD

**Issue by Merguerrero** [MuiseDestiny/zotero-style#726]
Firstly, I would like to than you for the effort and the time spend in this amazing tool.

I'm not a Chinese speaker, so I'm trying my best to understand the documentation. I noticed that I can not see Publication tag, neither the IF. 

Furthermore, I can not also access to the settings of the complement. Can this be due to the last update?

![Captura de pantalla 2023-10-18 a las 17 01 46](https://github.com/MuiseDestiny/zotero-style/assets/26326308/febe8112-aadf-41c1-b9ad-b62966649bdf)

Info :
zotero Version: 7.0.0-beta.46+c27bac2ad
zotero-style version: 2.6.7

Thank you in advance,
Mercedes

**Comment by hj1982** [comment]
This looks like an awesome plugin, thank you for your effort.
I have the same problem, but I can't use the asset you provided in the link as Zotero rejects using it.

![Image](https://github.com/user-attachments/assets/2ba976ef-0e46-4436-b5f1-18ec3ccde5f7)
