### ISSUE TITLE
和 zotero-citation 一起使用，标签列消失

### ISSUE THREAD

**Issue by cjlCMU** [MuiseDestiny/zotero-style#73]

**Comment by MuiseDestiny** [comment]
更新下style

**Comment by Z0o0o** [comment]
> 更新下style
已更新2.0.5没有标签栏进度栏
![屏幕截图_20230129_111811](https://user-images.githubusercontent.com/121789386/215303509-18bfe1dc-23a7-4c3e-ac13-7dbc5644e67d.png)

**Comment by MuiseDestiny** [comment]
> > 更新下style
> > 已更新2.0.5没有标签栏进度栏
> > ![屏幕截图_20230129_111811](https://user-images.githubusercontent.com/121789386/215303509-18bfe1dc-23a7-4c3e-ac13-7dbc5644e67d.png)

可能和better notes冲突，有时间解决
