### ISSUE TITLE
功能小疑惑🤨：zotero 阅读器工具栏旁边的小圆点，会变色，这个功能不理解啥意思，阅读时间咩？

### ISSUE THREAD

**Issue by aka-phrankie** [MuiseDestiny/zotero-style#730]
功能小疑惑🤨：zotero 阅读器工具栏旁边的小圆点，会变色，这个功能不理解啥意思，记录阅读时间的插件吗？点击还有热爱可抵岁月漫长的弹窗。
![zotero_231020_1611_4](https://github.com/MuiseDestiny/zotero-style/assets/44957887/c49b6e96-76ec-4db5-8142-2fb6fdb44e75)
各位大佬，请问这个圆点是啥意思，色彩变化代表啥，鼠标覆盖的时间，似乎时间长了绿色还会变成红色。

点击之后变灰色以后再回复颜色的时间我发现和设置里面的这个[^1]是相等的，但是我具体啥功能我没猜到，我还以为是名言警句呢。

[1]：The time interval recorded while reading (unit: seconds) **10**

先谢谢路过的各位大佬回答。

**Comment by MuiseDestiny** [comment]
就是记录阅读状态 阅读时间
