### ISSUE TITLE
希望能在Word等软件内插入引文时选择窗口显示style插件列

### ISSUE THREAD

**Issue by refined-fish** [MuiseDestiny/zotero-style#731]
**不礼貌不回复，直接关闭**
已阅读并确认
## 预期功能
在Word等软件中点击插入引文时会有一个引文选择窗口，用来选择想要插入的引文，希望能在这个窗口也显示style添加的信息列，尤其是“#标签”
![image](https://github.com/MuiseDestiny/zotero-style/assets/93998080/3f0a3f44-aae0-4bcc-b19d-f018832f712a)
## 目前现状
引文选择窗口目前和Zotero主界面相似，但是信息列仅显示Zotero原生的信息列，style信息列（例如#标签等列）均无法显示，如下图：
![image](https://github.com/MuiseDestiny/zotero-style/assets/93998080/364a4227-a716-4b96-a851-3eb85a2c19f2)
## 其他补充
因为很多引文用了“#标签”列做备注，如果少了这一列在选择引文时会有些麻烦，无法及时找到想要的引文。但引文插入功能依赖Zotero的office加载项，我不是很懂，如果是该功能无法凭借Zotero插件实现请无视，抱歉打扰。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation

了解一下这个插件

**Comment by refined-fish** [comment]
> https://github.com/MuiseDestiny/zotero-citation
> 
> 了解一下这个插件

原来如此，感谢大大
