### ISSUE TITLE
全文翻译等功能标签不显示

### ISSUE THREAD

**Issue by ihahya** [MuiseDestiny/zotero-style#733]
哈喽大大，先用zotero7，插件版本3.1.9，在使用shift+P时没有全文翻译功能，而且会出现很多better note的功能，请问如何关闭better note，以及如何恢复全文翻译功能，感谢解答！
<img width="881" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/129815867/2c647935-d14d-4c07-a84c-d7d4d6f536ba">
<img width="879" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/129815867/c99ab0e1-e628-47c0-bb5f-8c6b4afaabd3">

**Comment by MuiseDestiny** [comment]
https://gitee.com/zotero-chinese/zotero-magic-for-user/blob/master/zotero-magic-for-user.xpi

功能迁移
