### ISSUE TITLE
关于命令面板的快捷键

### ISSUE THREAD

**Issue by CMD-cmd** [MuiseDestiny/zotero-style#74]
- 现在是 `shift`+`P` 唤出命令面板，但是有时在打标签的时候要打大写的 P 时，会误唤出命令面板（英文输入法下）
- 可以参考 OB 的快捷键 `cmd`+`P` 唤出命令面板

**Comment by MuiseDestiny** [comment]
> * 现在是 `shift`+`P` 唤出命令面板，但是有时在打标签的时候要打大写的 P 时，会误唤出命令面板（英文输入法下）
> * 可以参考 OB 的快捷键 `cmd`+`P` 唤出命令面板

是的哦，忘记考虑这个了，但是在输入框应该不会唤醒吧。

**Comment by CMD-cmd** [comment]
在输入框也会唤醒呢，就是在英文输入法下，见视频
https://picture-cmd-1305141350.cos.ap-nanjing.myqcloud.com/pic/202301281458480.mp4

**Comment by MuiseDestiny** [comment]
> 在输入框也会唤醒呢，就是在英文输入法下，见视频 https://picture-cmd-1305141350.cos.ap-nanjing.myqcloud.com/pic/202301281458480.mp4

哈哈哈辛苦录个视频，尽快解决
