### ISSUE TITLE
优化 Tab Manager：显示PDF文件名而不是条目名

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-style#740]
# 参考福昕阅读器Tab Manager，显示PDF文件名而不是条目名
# 原因：显示PDF文件名可以展示更多信息
Tab Manager结合zotero file显示PDF文件名可以实现以下效果：显示文献编号、PDF附件类型（PDF原文件、支持信息、笔记文件）、年份、标题翻译、期刊、#标签、笔记等等
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/84ea8dc0-10a6-41c6-a6fd-db34e46d9182)
最终效果：参考福昕阅读器的Tab Manager
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/5b09ca59-c008-42f0-90a7-4a003c1ae712)
我设置的zotero file重命名规则如下图所示
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/0e9af5db-750b-44a7-8eb7-79abc21a73e2)
# 其他
另外，福昕阅读器高级搜索功能也很棒，希望大佬体验一下，如果能够加入到zotero中就太棒啦
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/87425176-2096-42ac-b3a0-2c0976473b67)

**Comment by MuiseDestiny** [comment]
1. style效果比你说的更好
2. 做不了

**Comment by 1067237855** [comment]
可能我没表达明白/(ㄒoㄒ)/~~

显示PDF文件名而不是条目名
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/0beee6da-6ccd-4e49-b38b-7f90f34fef74)


类似于设置里面的“显示标签页”的这种区别
![image](https://github.com/MuiseDestiny/zotero-style/assets/104330036/af83ecb0-a88e-4214-b22d-2c18bc921275)
