### ISSUE TITLE
关于影响因子和列设置的一些建议

### ISSUE THREAD

**Issue by KikkiZ** [MuiseDestiny/zotero-style#741]
亲爱的作者您好，我有一些建议，它在我目前使用的版本(2.6.7)上没有实现，我不清楚它们是否在预览版中实现了，但我还是选择提出我的建议。
1. 对于影响因子列，可以根据具体的数值生成生成标签，这样可以更加直观的展示影响因子的数值。
2. 然后根据影响因子的数值分段赋予不同颜色的标签，这样可以一眼看出影响因子的大致范围。
3. 可以给某些列设置固定列宽，当我调整某些列时，其他的一些列总是被动改变列宽，导致我们需要反复调整列宽。同样的问题在不同的视图切换时也存在。
![image](https://github.com/MuiseDestiny/zotero-style/assets/64997288/67956fd2-03d2-4a01-a75a-e25711b16481)

**Comment by MuiseDestiny** [comment]
1. 期刊标签 可以显示影响因子，是根据数值区分颜色的
2. 见1
3.  不是插件bug
