### ISSUE TITLE
mac上“标题翻译”、“标签”及“#标签”几栏均无法显示

### ISSUE THREAD

**Issue by Crescent0813** [MuiseDestiny/zotero-style#769]
大佬您好，我电脑是mac m2
zotero6和7都试过了，也试了不同版本的插件，均无法显示“标题翻译”、“标签”及“#标签”这三栏~求解决办法5555谢谢大佬！
![Xnip2023-11-18_13-35-34](https://github.com/MuiseDestiny/zotero-style/assets/91669948/85690cf7-a4e3-4ff2-8bac-ebf08eb5864d)

**Comment by jiangbo198602** [comment]
我的也是同样的问题，请问解决了吗

**Comment by Crescent0813** [comment]
> 我的也是同样的问题，请问解决了吗

没有解决...看来是共性问题？希望大佬有空时看看我们~~TAT

**Comment by xcfcode** [comment]
不知道是不是更新了os sonoma的原因

**Comment by xcfcode** [comment]
@jiangbo198602 @Crescent0813 @FakeTrader @Rphone 我右键列设置，把match的#删除之后标签好使了。
![image](https://github.com/MuiseDestiny/zotero-style/assets/42307427/c840dbdb-d461-4c75-aae1-8c8390066133)

**Comment by Crescent0813** [comment]
@jiangbo198602 
已经全都解决了！好像有的是更新后好使了，有的是之前我不会用QAQ
1.标题翻译：是要右键条目，点那个”标题翻译“才会填入这列
2.标签：更新后试了几次就好使了（虽然偶尔还会抽风消失，但问题不大~
3.#标签：就是要先打”#“再加你想写的内容才会显示（估计是为了和其它tag作区分？）

**Comment by Suasy** [comment]
那个标签我现在还是不显示

![image](https://github.com/MuiseDestiny/zotero-style/assets/63626169/fb8fadaf-13a1-4865-b029-5863777919de)
