### ISSUE TITLE
如何删除已设置的pdf颜色

### ISSUE THREAD

**Issue by wyxogo** [MuiseDestiny/zotero-style#770]
**不礼貌不回复，直接关闭**
添加的背景色如何删除
<img width="219" alt="image" src="https://github.com/MuiseDestiny/zotero-style/assets/61509470/baedc74a-126e-49fd-9812-984156e9201f">

**Comment by kyshen** [comment]
Mac版zotero 7，长按要删除的颜色，弹出编辑窗口即可删除
![image](https://github.com/user-attachments/assets/6b87ca46-be4a-45e1-93b8-b70d1cf65a1e)
