### ISSUE TITLE
作者您能不能添加一个备注栏

### ISSUE THREAD

**Issue by MrGongqi** [MuiseDestiny/zotero-style#783]
您好，如您所见（下图），我的Tags栏是用来做重要性标注的，#Tags栏是用来对主题相同或相近的文献进行归纳的：这样将#Tags和文件夹进行结合使用，可以大大减少文件夹的个数，避免繁杂，要找相似的文章，就只需在左下角标签中选择需要的主题内容即可。
![image](https://github.com/MuiseDestiny/zotero-style/assets/49467246/0a2d03be-3c85-4687-81fa-91d3cc99f211)
我想再添加一个视图组，该试图组能够直接在条目中简单的写上简要的阅读概要，这样，在读文献时候就能够很清晰明了的快速了解和定位文章（详细的内容就展开note查看），但是该阅读概要又不能当作标签使用，也不需要在左下角标签栏中显示（否则就会使标签栏内容过于多和杂乱，进而失去了作为标签的简洁方便功能），进而该功能需要与Tags或#Tags完全区分开。所以我想您能不能添加一个功能栏，可以取名“备注—Remark”。（如下图）
![image](https://github.com/MuiseDestiny/zotero-style/assets/49467246/4b981fdc-fbdb-4f8f-8b73-57fd394f3716)
我不知道对此需求的人多不多，如果您觉得提议的还是有点必要或用处的话，您可以尝试一下，非常感谢

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/6bc4819d-147a-4bc2-acd2-c25a2e71d50f)

**Comment by 16TWQ** [comment]
作者您好感谢您添加了Remark一栏
<img width="1178" height="94" alt="Image" src="https://github.com/user-attachments/assets/1674462d-81bb-4220-ae2e-23ca5f33f57d" />
请问能否让Remark的内容在以上页面中换行全部显示出来，remark有时包含的内容较多，我也希望保留其他列的内容，所以没办法将列宽无限拉长，remark无法完全显示让我非常困扰,非常感谢！
