### ISSUE TITLE
和zotero betternote插件冲突

### ISSUE THREAD

**Issue by cjlCMU** [MuiseDestiny/zotero-style#79]
老师您好，我发现在启用windingwind老师的zotero betternotes 的情况下，标签和#标签 colunm就消失了，希望老师有时间看看能不能解决

**Comment by MuiseDestiny** [comment]
> 老师您好，我发现在启用windingwind老师的zotero betternotes 的情况下，标签和#标签 colunm就消失了，希望老师有时间看看能不能解决

等better notes更新，先用它的0.8.6版本。
