### ISSUE TITLE
探索栏中摘要单词之间的空格特别大

### ISSUE THREAD

**Issue by cesaryuan** [MuiseDestiny/zotero-style#793]
感谢大佬的扩展，请问探索栏中的摘要，有的单词之间的空格特别大，可以调整成release里展示的那样吗？

看样子是需要把 `text-align: justify;` 去掉才行🥰

![image](https://github.com/MuiseDestiny/zotero-style/assets/35998162/941f5bed-ea56-45f7-94ca-79bd66fd9e40)

调整为

![image](https://github.com/MuiseDestiny/zotero-style/assets/35998162/8bd464bb-fdfc-41b3-afcf-16c917dccade)

**Comment by MuiseDestiny** [comment]
可

**Comment by MuiseDestiny** [comment]
已去除，随下个版本发布
