### ISSUE TITLE
插件存在启动Bug

### ISSUE THREAD

**Issue by Saunak626** [MuiseDestiny/zotero-style#80]
![image](https://user-images.githubusercontent.com/34276206/215418784-d3dc3997-7e9d-4630-8800-8c66c4dd7d05.png)

之前用的老版本，直接安装2.06的后没有任何的功能采单，shift+p后是空白。但是在插件管理界面remove zotero style后，再undo缺可以启动插件，但是在重启zotero之后又无法启动该插件了。并且迁移了zoterostyle的数据之后，即便是undo启动了插件，也没有正常的显示以前的数据。

推测这个插件的启动有bug，我disable zotero reference之后似乎可以正常启动，但是功能不清楚是否正常。因为我没开发过zotero插件，只是推测是否是插件启动的id字段冲突

**Comment by MuiseDestiny** [comment]
这个版本有大问题，我在排查。reference是最新的吗

**Comment by Saunak626** [comment]
reference是0.2.5的，应该最新的。并且原始条目有些是中文的，迁移之后的只有条目代码，不清楚是否是命名规则变化，还是迁移错误。我感觉以前的一些进度没有识别出来，之前那个没留档，不太确定

还出现一个标识错误的情况，把阅读进度标识到了文件上。这个bug我目前只遇到一次，不太好复现
![image](https://user-images.githubusercontent.com/34276206/215423951-1aafaec0-2919-4277-beb7-8b9953591957.png)

**Comment by Saunak626** [comment]
那就很奇怪，我使用的2.06

**Comment by wangfh5** [comment]
我是第一次安装，也是安装之后没有效果，`shift+p`之后没有可用的命令，remove之后undo，主页上才会弹出来关系图谱。

**Comment by Saunak626** [comment]
> 我是第一次安装，也是安装之后没有效果，`shift+p`之后没有可用的命令，remove之后undo，主页上才会弹出来关系图谱。

你是不是也装了reference那个插件？

**Comment by wangfh5** [comment]
> 

没有，但我装了better notes

**Comment by MuiseDestiny** [comment]
> > 
> 
> 没有，但我装了better notes

用0.8.6

**Comment by wangfh5** [comment]
> > > 
> > 
> > 
> > 没有，但我装了better notes
> 
> 用0.8.6

OK，不过我发现这几个月不咋用better notes，先disable了。期待后续修复吧。
