### ISSUE TITLE
视图组功能问题-无法新建多个

### ISSUE THREAD

**Issue by LeonLrz** [MuiseDestiny/zotero-style#805]
![image](https://github.com/MuiseDestiny/zotero-style/assets/59362482/a742f400-e6aa-433f-91a9-da8a2b424697)
如图所示，Zotero7里使用Style插件的功能时，添加一个视图组之后就不再有新建视图组的Tab了。
不知道有没有朋友遇到类似的问题。
请问我应该如何操作来添加多个视图呢？
如果是存在Bug的话，烦请作者大佬修复一下~

**Comment by MuiseDestiny** [comment]
开启/关闭 某一列后才可以创建新的
