### ISSUE TITLE
Issue with tag and read/unread column when not first columns

### ISSUE THREAD

**Issue by kamarianakis** [MuiseDestiny/zotero-style#808]
Dear developer, 

Thank you very much for this zotero tool which is a great tool for zotero power-users. It would be great if you also create an english version of the 40-minute video, as it will help wide-spread this plugin (and also help us unravel its secrets, as I spent 1 week trying to translate chinese comments and pictures in english:D just to check how annotations work!) 

In mac (Monterey), using Zotero 7.0.0-beta.54+6b996d4f9, and Zotero-Style 3.3.1.1, the tags column does not center items properly, especially if the tags column is after the title column. Same issue with the read/unread column. Only if tags or read column is first column will it properly work (tags have issues with margins in this case too) Pictures attached below: 
![SCR-20231231-rmzz](https://github.com/MuiseDestiny/zotero-style/assets/13041399/e5f0e6f0-1987-4892-b35e-8ce6d7414b5e)
![SCR-20231231-rmwz](https://github.com/MuiseDestiny/zotero-style/assets/13041399/8dad346e-e536-4fe9-a85b-771db5f93946)
![SCR-20231231-rmtt](https://github.com/MuiseDestiny/zotero-style/assets/13041399/c0fd10a9-00f0-4245-96fd-e10262fe5f1c)
<img width="234" alt="SCR-20231231-rjjv" src="https://github.com/MuiseDestiny/zotero-style/assets/13041399/e0088f56-b9f3-4a23-b277-c11e9aad63b0">
![SCR-20231231-rjhm](https://github.com/MuiseDestiny/zotero-style/assets/13041399/4ce24e36-6805-4852-adce-81a6a306ba34)
![SCR-20231231-rive](https://github.com/MuiseDestiny/zotero-style/assets/13041399/45f99fc3-f998-45c5-8876-6b4e8f530bab)

Many thanks for this plugin again, kindly let us know if we can buy pro outside china to support you!

**Comment by MuiseDestiny** [comment]
Thanks. I'll fix it.

**Comment by MuiseDestiny** [comment]
Please test https://musetransfer.com/s/y09y2z6sk

**Comment by kamarianakis** [comment]
Both 3.3.3.9-b1 and 3.3.4 work great in my laptop (16 inches), but in my external monitor (27 inches) I get this: 
![image](https://github.com/MuiseDestiny/zotero-style/assets/13041399/f3ad8615-885a-49b9-bdad-5f8643f79908)

Thanks for your effort !!!

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/921b9d07-6c77-4a6f-a1c7-294dbf76f12f)

Try it.

**Comment by kamarianakis** [comment]
Full Margin: 
![image](https://github.com/MuiseDestiny/zotero-style/assets/13041399/f32ffbc2-dad6-4b51-a9a8-f97225582e1a)
They are cut up and down
![image](https://github.com/MuiseDestiny/zotero-style/assets/13041399/0b9f1d7c-81ab-439c-a841-cbcdf79098d5)
