### ISSUE TITLE
您好，进度条的参数我改坏了，导致整个文件夹下面的文献全没了，目前尝试的只有把style插件移除才可以解决

### ISSUE THREAD

**Issue by liwang20030906** [MuiseDestiny/zotero-style#809]
**不礼貌不回复，直接关闭**
您好，进度条的参数我改坏了，导致整个文件夹下面的文献全没了，目前尝试的只有把style插件移除才可以解决，请问如何解决这个问题，插件的xpi文件删除再下载仍然不能够解决。（不好意思这是我第一次尝试用github解决问题，如果有哪里做的不对请见谅）
![Uploading 屏幕截图_20240101_170612.png…]()

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/b0d716d3-8245-4890-84fd-57284238be52)


按照步骤修改好后，升级插件到最新https://gitee.com/MuiseDestiny/plugins/raw/master/zotero-style.xpi

**Comment by liwang20030906** [comment]
您好，已经在您的帮助下解决了问题，感谢！
