### ISSUE TITLE
请问未读文献打开后不会自动变成已读是本来就是这样还是插件的bug呀？

### ISSUE THREAD

**Issue by kabuda2077** [MuiseDestiny/zotero-style#810]
**不礼貌不回复，直接关闭**
请问未读文献打开后不会自动变成已读是本来就是这样还是插件的bug呀？
插件版本3.3.1.1
zotero版本7.0.0-beta.54

**Comment by MuiseDestiny** [comment]
本就是这样，已读未读 手动的
