### ISSUE TITLE
请问为何一直卡在Parsing paper  structure...

### ISSUE THREAD

**Issue by INDEX108** [MuiseDestiny/zotero-style#811]
之前一直都可用，今天突然就发现新增的文献用全文翻译会卡在Parsing paper  structure...
Zotero style2.6.7
Better notes1.0.4
PDF translate 1.0.25
Zotero6.0.30

**Comment by Fancici0502** [comment]
我也是，版本都重装了一遍，还是翻译不了

**Comment by Fancici0502** [comment]
我也是，重新装了软件和插件，还是一样的，翻译不了...怎么解决呢？

**Comment by SuperMaxine** [comment]
我也是，今天突然出现的，也是全部更新、重装了一大通，还是没修好😂

**Comment by cccccharlie** [comment]
me,too

**Comment by MuiseDestiny** [comment]
api挂了，全文翻译请关注https://wiki.magiczotero.top/

**Comment by SuperMaxine** [comment]
> api挂了，全文翻译请关注https://wiki.magiczotero.top/

首先谢谢您的辛勤付出创造了这么好用的软件🙏不过现在才知道原来一直PDF解析使用的是在线服务😂有点好奇想问下是否有可能将解析的部分换成一些更可靠的本地服务？有很多类似pdf.js这类项目也可以获取pdf文件的逐段内容，但是不是这类解析提供的信息很难和原文位置关联所以不足以使用现在的形式用better notes与原文相互链接呢？

**Comment by MuiseDestiny** [comment]
> > api挂了，全文翻译请关注https://wiki.magiczotero.top/
> 
> 首先谢谢您的辛勤付出创造了这么好用的软件🙏不过现在才知道原来一直PDF解析使用的是在线服务😂有点好奇想问下是否有可能将解析的部分换成一些更可靠的本地服务？有很多类似pdf.js这类项目也可以获取pdf文件的逐段内容，但是不是这类解析提供的信息很难和原文位置关联所以不足以使用现在的形式用better notes与原文相互链接呢？

使用的grobid是可以本地部署的。

**Comment by SuperMaxine** [comment]
谢谢解答！！🙏🙏🙏我试着在本地docker拉了个grobid，虽然体积很大但搭建确实还挺方便的，而且可以使用本地GPU感觉也挺快的，但是我在咱们插件的设置和仓库的源代码里都没有找到api接口在什么地方，可以请教一下如何替换嘛？还是说原本使用的在线服务做了额外的封装不是很简单能替换的😂

**Comment by INDEX108** [comment]
> api挂了，全文翻译请关注https://wiki.magiczotero.top/

已经用上了，功能比原来这个齐全很多

**Comment by SuperMaxine** [comment]
> > api挂了，全文翻译请关注https://wiki.magiczotero.top/
> 
> 已经用上了，功能比原来这个齐全很多

请问是换了zotero 7嘛？

**Comment by INDEX108** [comment]
> > > api挂了，全文翻译请关注https://wiki.magiczotero.top/
> > 
> > 
> > 已经用上了，功能比原来这个齐全很多
> 
> 请问是换了zotero 7嘛？

是的，我换了最新的zotero7

**Comment by reallyyyyy12** [comment]
> api挂了，全文翻译请关注https://wiki.magiczotero.top/

所以style的全文翻译功能用不了了吗？
