### ISSUE TITLE
视图组里面新建视图选项没有，重启无效

### ISSUE THREAD

**Issue by klucius1218** [MuiseDestiny/zotero-style#812]
**不礼貌不回复，直接关闭**6.0版本的，麻烦看看是怎么回事~

**Comment by klucius1218** [comment]
![907f555331fc1cd32168f022f45898a](https://github.com/MuiseDestiny/zotero-style/assets/135409766/fa235094-2b39-4a63-bf60-7a57079de65e)

**Comment by MuiseDestiny** [comment]
变更视图后，才能新建。请打开或关闭某一列 后重试
