### ISSUE TITLE
创建自己的标注后，可以使用但是一直报错，求大佬解决

### ISSUE THREAD

**Issue by Jessica-HH** [MuiseDestiny/zotero-style#814]
![QQ图片20240105162455](https://github.com/MuiseDestiny/zotero-style/assets/155720220/f2ae3fc8-688f-416c-9b77-15b2b040a00f)

**Comment by MuiseDestiny** [comment]
1. 你没创建好，颜色，名称都要写，重新填写就可以
2. 你可以恢复默认的颜色，以修复这个错误

**Comment by Jessica-HH** [comment]
感谢感谢，解决了
