### ISSUE TITLE
parser paper structure卡住~~

### ISSUE THREAD

**Issue by xchouzhang** [MuiseDestiny/zotero-style#816]
感谢博主开发出方便的一键翻译文献功能，对很多看论文的科研人员提供了很大帮助。现在api挂掉之后，博主给出了magic的替代方案，但是只支持zotero 7 ，我身边的绝大多数同学都在用正式版的6，因为zofile插件对附件管理的不可替代性，所以希望博主尽快出magic for zotero 6版本，或者方便的化把本地化部署grobid的api调用教程指导一下，谢谢！

**Comment by MuiseDestiny** [comment]
https://b23.tv/sV8Hktd

关注zotero attanger插件
