### ISSUE TITLE
请问Find pdfs from sci-hub能用吗？

### ISSUE THREAD

**Issue by pisceswb** [MuiseDestiny/zotero-style#833]
请问这个“Find pdfs from sci-hub”选项能用吗？
刚测试了一下，今天只有ru网址输入浏览器能打开，但是在zotero中使用“查找可用的PDF”不能下载。
发现https://wellesu.com/这个网址能用，但是不能自己更改添加。
请问能否允许用户自定义sci-hub网址？
谢谢！

![image](https://github.com/MuiseDestiny/zotero-style/assets/104658457/bb9d89f2-8806-43db-9a2e-2babc7987a4f)

**Comment by MuiseDestiny** [comment]
可以去高级-编辑器-搜索extensions.zotero.findPDFs.resolvers 去更改。

另外下个版本会把wellesu加入，感谢提供

**Comment by pisceswb** [comment]
请问能否把这个选项做成一个小文本框，自己填写网址呀，sci-hub经常会失效，如果的一个文本框的话，很方便修改，就不用再去编辑器中修改了

**Comment by shjiang** [comment]
请问zotero 7.0版本的插件，Find pdfs from sci-hub这一功能应该怎么用呢，在条目上右键没有出现“查找可用的PDF”？

**Comment by pisceswb** [comment]
> > 请问能否把这个选项做成一个小文本框，自己填写网址呀，sci-hub经常会失效，如果的一个文本框的话，很方便修改，就不用再去编辑器中修改了
> 
> 基本就那几个能用的，把所有能用的写入插件就可以了

仍然建议能够自定义网址，sci-hub的网址还是变化挺多的，例如：sci-hub.shop，www.et-fine.com等 
@MuiseDestiny

**Comment by pisceswb** [comment]
请问能否在使用“查找可用的PDF”功能时，增加一个从哪个网站查找PDF的提示？
今天在使用“查找可用的PDF”功能时，弹出了好几次Elsevier的是否为真人的验证，一度怀疑style的设置没有起作用
@MuiseDestiny
