### ISSUE TITLE
更新到最新版本2.0.7之后无法添加标签列和#标签列（右键菜单中无）

### ISSUE THREAD

**Issue by xchyyb** [MuiseDestiny/zotero-style#84]
![image](https://user-images.githubusercontent.com/78303344/215720100-5ed77f01-5bf5-4eab-9758-83f6e2c13af3.png)

**Comment by MuiseDestiny** [comment]
有citation插件吗，如果有也更新一下它

**Comment by MuiseDestiny** [comment]
更新后重启一下zotero
