### ISSUE TITLE
4.0.2 期刊标签列不显示

### ISSUE THREAD

**Issue by zzlb0224** [MuiseDestiny/zotero-style#847]
感谢作者大大出的这么好的插件。

更新到4.0.2之后期刊标签列不显示
zotero版本 7.0.0-beta.56

**Comment by Arlene00** [comment]
遇到了同样的问题

**Comment by CC-githubs** [comment]
@MuiseDestiny 求问最新版本中，更新插件和easyscholar密钥后，期刊标签只能显示北核这一个标签（有的不只是北核），但是点击标签“北核”后右下角没有显示文献的其他期刊标签（没有反应），并且SHIFT+P中也没有更新期刊标签选项，但是有style的其他可选项，请问期刊标签的这个问题怎么处理呢？
![image](https://github.com/MuiseDestiny/zotero-style/assets/156210884/af6071e9-8a50-4529-9dd4-088c4a14aea1)

**Comment by zzlb0224** [comment]
@MuiseDestiny 龙年快乐。给您拜年了。

更新到B58+4.0.5，还是不能更新期刊标签

![image](https://github.com/MuiseDestiny/zotero-style/assets/8912444/ac2c456c-81ee-48f0-8ad1-a98aa0d06715)

**Comment by zzlb0224** [comment]
感谢大神更新。

**Comment by Rubylyp** [comment]
请问一下4.0.3是zoterostyle的最新版本吗？在哪里可以找到哇？
