### ISSUE TITLE
style图标消失以及pdf背景颜色更换的图标消失

### ISSUE THREAD

**Issue by may010** [MuiseDestiny/zotero-style#854]
Zotero 7.0.0-beta.57
Zotero-style 3.3.6

能看见关系图和期刊标签所以确定插件是开了的，但是导航栏我记得6的时候有图标，包括进去pdf文献以后现在也不能调整背景颜色了，因为没有style图标也不能隐藏关系图。

![Capture01](https://github.com/MuiseDestiny/zotero-style/assets/97866192/9a41b4a2-1afa-48fc-8b88-dece12dfddfb)
![Capture02](https://github.com/MuiseDestiny/zotero-style/assets/97866192/cf73ab85-1421-41e2-8093-95a96f85a849)

已经参考了#232 但是问题没有解决，谢谢！

**Comment by icearchimage** [comment]
能问下是怎么解决的吗，我也遇到pdf style主题按钮消失的情况
