### ISSUE TITLE
更新到2.0.7最新版本后没有任何显示，进度条也消失了

### ISSUE THREAD

**Issue by 18098867226** [MuiseDestiny/zotero-style#86]
![image](https://user-images.githubusercontent.com/124160978/216048647-7fe3ca16-632c-475f-9329-de4db6e32efd.png)

**Comment by MuiseDestiny** [comment]
方便用排除法disable下其他插件，说一下跟谁冲突吗

**Comment by MuiseDestiny** [comment]
重点关注下citation插件

**Comment by 18098867226** [comment]
我没有这个插件

**Comment by 18098867226** [comment]
需要安装一个吗？

**Comment by 18098867226** [comment]
![image](https://user-images.githubusercontent.com/124160978/216051891-2d6ac02c-ec16-4dbe-9ecb-68e3c183a550.png)

**Comment by 18098867226** [comment]
![image](https://user-images.githubusercontent.com/124160978/216051958-a6c14a62-9cd5-4460-ba87-8579616aa390.png)

**Comment by MuiseDestiny** [comment]
是这样，zotero软件上如果只有style一个插件，是绝对可以运行成功的，之所以不成功是因为冲突。现在的冲突主要是多个插件用了公共代码导致的。

你可以尝试禁用reference，better notes和翻译插件，然后重启试试。

**Comment by MuiseDestiny** [comment]
> 我没有这个插件

不用装的，只是它和style冲突可能性比较大。

**Comment by 18098867226** [comment]
![image](https://user-images.githubusercontent.com/124160978/216054255-be5bf6d0-81a7-425c-a3c7-c77cf6ad4a88.png)

**Comment by 18098867226** [comment]
还是没有进度条显示

**Comment by 18098867226** [comment]
![image](https://user-images.githubusercontent.com/124160978/216057042-5ea537e0-5383-4256-861e-484396b9960b.png)

**Comment by 18098867226** [comment]
好像是这个插件

**Comment by MuiseDestiny** [comment]
> 好像是这个插件

那就是它和style有冲突，禁用后就可以用了吧
