### ISSUE TITLE
设置里style界面丢失

### ISSUE THREAD

**Issue by FanTacyTutu** [MuiseDestiny/zotero-style#864]
**不礼貌不回复，直接关闭**
![image](https://github.com/MuiseDestiny/zotero-style/assets/43268469/3d70bccb-06c8-425b-b74e-22629b71f21e)
 
大佬开发辛苦，感谢！
最近是重新安装过的win10系统，zotero7，style插件刚安装时还可以看到界面，版本印象中显示是4.0.7，但是界面上没有之前下方设置奇偶行颜色的选项，因此我删除了重新装了2.6.7和3.3.6，就发现变成设置里只有图标没有内容的情况了。

其实之前cite的那个插件也有丢失界面的情况，但是style一直能用，cite的功能也能用，就没有理会。电脑是联想小新pro14 2021 intel款，zotero是7.0.0-beta.58+2665090aa (64-bit)。感谢~

**Comment by B1INGO** [comment]
我和你的情况一样，也无法使用。

**Comment by MuiseDestiny** [comment]
zo b54请使用：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style-b54.xpi
zo 最新>b54请使用：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi
