### ISSUE TITLE
标签列和标题列均显示标签

### ISSUE THREAD

**Issue by xchyyb** [MuiseDestiny/zotero-style#87]
![image](https://user-images.githubusercontent.com/78303344/216202701-e23a0131-b639-4aae-a15d-b3770905cbc9.png)

**Comment by MuiseDestiny** [comment]
关闭就可以
![image](https://user-images.githubusercontent.com/51939531/216203903-e78e64c1-9fd7-4943-b396-f48e32aeaa53.png)

**Comment by xchyyb** [comment]
谢谢答复，可以了
