### ISSUE TITLE
pdf style 功能 消失了

### ISSUE THREAD

**Issue by racingrain** [MuiseDestiny/zotero-style#870]
**不礼貌不回复，直接关闭**
mac os zotero 7 
<img width="1624" alt="截屏2024-02-25 01 09 52" src="https://github.com/MuiseDestiny/zotero-style/assets/161151770/71b49e39-83e2-495c-a246-8893db175947">

**Comment by Ellenscode719** [comment]
一样的问题 好像是变成pro功能了
