### ISSUE TITLE
重启自动升级4.1.4版本，导致style本身插件功能失效

### ISSUE THREAD

**Issue by Artisun-2020** [MuiseDestiny/zotero-style#873]
**不礼貌不回复，直接关闭**

**Comment by FreeYiran** [comment]
同

**Comment by Artisun-2020** [comment]
已收，祝好。

**Comment by RealMoonHunter** [comment]
同

**Comment by LiuJ00** [comment]
同

**Comment by bigsun-sun** [comment]
同，Mac zotero升级后 style升级为最新版本后 所有功能直接失效

**Comment by bigsun-sun** [comment]
同，希望能尽快得到解决

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins

根据你zo版本安装插件。如是b54，安装后禁用插件自动更新

**Comment by bigsun-sun** [comment]
您好，我是曹维，已经收到您的邮件，我会尽快阅读并处理。谢谢~Dear sender，Thank you for your email.I will reply you as soon as I’ve handled it.                    yours  sincerely                  cao wei
