### ISSUE TITLE
安装新版本后，以前旧版本的高能进度条不见了

### ISSUE THREAD

**Issue by wzhyyk** [MuiseDestiny/zotero-style#878]
之前一直使用1.几版本的zotero style，重新安装成2.6.7以后之前阅读文献的高能进度条不见了，但重新阅读有新的进度条产生，请问怎么样才能恢复以前的进度条呢

**Comment by 13071558875** [comment]
beta55版本以后也没有高能进度条了，也更新了最新版的zotero style了

**Comment by hannahlulu057** [comment]
+1，这个什么时候修复啊

**Comment by MuiseDestiny** [comment]
搜索文献，标题：Addon Item，选中它，shift+P，设置为插件储存条目。重启zo即可

**Comment by wzhyyk** [comment]
> 搜索文献，标题：Addon Item，选中它，shift+P，设置为插件储存条目。重启佐即可

按这样的操作也还是不行呢，而且新的进度条突然一晚上之后又全部消失了

**Comment by yangwenjiehenniu** [comment]
以前阅读的高能进度清除了咋整啊  只显示最新阅读

**Comment by Matt-V50** [comment]
@MuiseDestiny 
Addon Item这个删除了是不是阅读进度就没了

**Comment by WWWzq-01** [comment]
> 搜索文献，标题：Addon Item，选中它，shift+P，设置为插件储存条目。重启zo即可

请问zotero7 on mac也是这样操作吗，我按shift+p出现的是select a command，是这正确的吗？如果是，我应该输入什么呢

**Comment by WWWzq-01** [comment]
> > 搜索文献，标题：Addon Item，选中它，shift+P，设置为插件储存条目。重启zo即可
> 
> 请问zotero7 on mac也是这样操作吗，我按shift+p出现的是select a command，是这正确的吗？如果是，我应该输入什么呢

我没有设置为插件存储条目这个命令

**Comment by WWWzq-01** [comment]
> > > 搜索文献，标题：Addon Item，选中它，shift+P，设置为插件储存条目。重启zo即可
> > 
> > 
> > 请问zotero7 on mac也是这样操作吗，我按shift+p出现的是select a command，是这正确的吗？如果是，我应该输入什么呢
> 
> 我没有设置为插件存储条目这个命令

addon item下的内容大部分丢失了，只剩下一个pdf的阅读数据
