### ISSUE TITLE
多设备同步功能

### ISSUE THREAD

**Issue by chengyf21** [MuiseDestiny/zotero-style#88]
请问目前有没有多设备的同步功能，如果有的话在哪里实现，谢谢~

**Comment by MuiseDestiny** [comment]
有的，A设备上生成`Addon Item`后，在B上把`Addon Item`同步过来后，在B上安装style插件。

也可以不用管顺序，如B上有多个`Addon Item`自行判别哪个是从A同步过来的，然后选中，shift P设置为插件条目就可以实现同步。

**Comment by chengyf21** [comment]
谢谢解答，已经设置成功了~
