### ISSUE TITLE
标题列设置的translate不起作用了

### ISSUE THREAD

**Issue by pisceswb** [MuiseDestiny/zotero-style#882]
在3.3.6版本中，标题列设置的translate不起作用了，请修复一下，谢谢！
![image](https://github.com/MuiseDestiny/zotero-style/assets/104658457/e73c6795-3545-4271-b685-85b09dfef98e)
![image](https://github.com/MuiseDestiny/zotero-style/assets/104658457/bc93751e-6860-4362-8675-ede47629e678)
![image](https://github.com/MuiseDestiny/zotero-style/assets/104658457/bdf0db95-c119-4743-ae0e-baed33c0dfc9)

**Comment by MuiseDestiny** [comment]
style老https://gitee.com/MuiseDestiny/plugins

**Comment by pisceswb** [comment]
> style老https://gitee.com/MuiseDestiny/plugins

4.1.7能够正常使用题目的译文显示。
但开启publication tag后，很容易造成zotero卡死或页面空白，publication tag一列还常常不能显示，也调整不出来。
而且，也不能显示文档前面的tags。
望您修复一下，谢谢！
@MuiseDestiny

**Comment by pisceswb** [comment]
而且，storage功能好像是不能用呢
