### ISSUE TITLE
重启zotero后出现视图组长度无法拖动

### ISSUE THREAD

**Issue by supercharlie888** [MuiseDestiny/zotero-style#885]
**不礼貌不回复，直接关闭**
设置好视图组内容后，重启zotero后出现视图组长度无法拖动，视图组的位置出现频繁变动，等到无法拖动 后就无法变动了，bug反复存在出现，无法解决
<img width="901" alt="截屏2024-03-05 00 15 00" src="https://github.com/MuiseDestiny/zotero-style/assets/160762693/f5a17fe8-6b70-4719-9374-4349f8e09ba0">

**Comment by Anastasiauu** [comment]
同出现此问题，请问您解决了吗？

**Comment by MuiseDestiny** [comment]
其他插件影响导致。

**Comment by Anastasiauu** [comment]
谢谢！经过排查，是与这个插件有冲突（Add-on Market for Zotero）

**Comment by supercharlie888** [comment]
> 谢谢！经过排查，是与这个插件有冲突（Add-on Market for Zotero）

卸载此软件后目前仍然存在此问题
