### ISSUE TITLE
新版本的标题翻译功能会造成页面空白

### ISSUE THREAD

**Issue by pisceswb** [MuiseDestiny/zotero-style#890]
启用显示标题翻译的功能，文献篇数超过50篇，向下滚动页面，在第43篇文献后有一个空行(不能点击的空白行)，点击该空白行上面或下面的文献条目，都会导致页面变为空白。
希望作者修复，谢谢！
style 4.2.1
zotero 7 beta 65

**Comment by hujie12306** [comment]
+1也出现了页面空白的现象，禁用style后恢复正常

**Comment by MuiseDestiny** [comment]
更新到4.2.6.1(在zo里检查更新即可)
