### ISSUE TITLE
每次重启zotero7后评级栏和标签栏的长度都会变长，无法保持自己所设置的长度

### ISSUE THREAD

**Issue by Diiyuu** [MuiseDestiny/zotero-style#895]
**不礼貌不回复，直接关闭**
![PixPin_2024-03-11_11-31-19](https://github.com/MuiseDestiny/zotero-style/assets/145085823/122632f6-46a6-4ec4-995f-155cc62ccb82)

**Comment by MuiseDestiny** [comment]
现在最新版已经可以。请在zo内检查更新。不要下载github上的。
