### ISSUE TITLE
最新版style插件4.2.4.1，zotero是7.0.0-beta.67+92a04fcff

### ISSUE THREAD

**Issue by bigsun-sun** [MuiseDestiny/zotero-style#896]
你好 我的zotero style最新版无法使用，zotero软件内自动更新后，所有stly的功能都不能使用，换上以前的旧style版本，会导致其他插件使用障碍，例如出现笔记无法打开等问题。谢谢

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins
