### ISSUE TITLE
请求评级字段改回保存在Extra（其他）字段中

### ISSUE THREAD

**Issue by xjtusjtu** [MuiseDestiny/zotero-style#901]
P佬好，我非常喜欢Style插件的评级功能，我觉得**旧版本**将“评级”字段的键值对保存在Extra字段非常好，这样便于我在将Zotero数据导出为markdown文件时，通过读取Extra字段直接将评级字段的值导入到MD笔记元数据；

目前的版本似乎是改成给item添加对应标签，这样导致两个问题：
1. 影响了标签体系，我个人觉得标签和评级不是一个体系，标签是这篇文章的关键字或者话题具有相当的一致性（不同人对同一篇文章归纳的标签比较接近），评级是这篇文章是我个人对其水平的评价（纯粹的个人意见）
2. 在我导出为markdown文件时，不得不增加两个操作：①在导出的标签中过滤掉“评级标签”，②根据“评级标签”的取值添加“评级”字段

恳请P大考虑，万分感谢！

**Comment by Sean19899999** [comment]
顶，遇到同样的问题，现在版本似乎放到Info里的，但是没法提取啊。
![image](https://github.com/MuiseDestiny/zotero-style/assets/129134672/0c4d899d-cb81-4f17-af8a-22fc17073e49)

**Comment by MuiseDestiny** [comment]
现在是作为标签存在，目前以及以后没有在extra存数据打算。

**Comment by MuiseDestiny** [comment]
> 现在是作为标签存在，目前以及以后没有在extra存数据打算。

你可以写一个action tags脚本提取这些数据，或者把他们写入extra
