### ISSUE TITLE
插件卡顿严重，高亮有时会禁用

### ISSUE THREAD

**Issue by yunmiumiu** [MuiseDestiny/zotero-style#912]
**不礼貌不回复，直接关闭**
好像是最近的版本出现的问题。高亮选了自定义颜色之后，有时候页面会卡住，或者PDF的工具栏变成灰色，左侧高亮文本上有锁定符号，无法再使用批注工具。重启或者关掉重新打开页面会好，但故障很频繁。
其他地方也会卡，有时候点击条目无法打开PDF。不知道是否是这个插件的原因。

**Comment by yunmiumiu** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/157546504/9e9fe8a3-6053-4e1b-9b6d-076f6d647f9c)
补充故障图片

**Comment by yunmiumiu** [comment]
故障常常发生在改变高亮颜色之后

**Comment by MuiseDestiny** [comment]
首选项-style 请自行关闭一些功能，首先你需要关闭Annotation Colors。其次根据你使用情况关闭其它

**Comment by yunmiumiu** [comment]
抱歉没太听明白……我有使用自定义高亮色的需求，但是打开之后会出现卡顿。关闭相当于不使用这个功能了吗……
