### ISSUE TITLE
更新后丢失简记的相关入口

### ISSUE THREAD

**Issue by Ash-Shy** [MuiseDestiny/zotero-style#913]
从3.3更新到4.2之后简记功能没有入口了，右键的“更新”下没有，shift+p也没有ai生成简记了

**Comment by Ash-Shy** [comment]
软件自动更新到4.2.6.3就解决了，但github上怎么不再发布了？

**Comment by pengxy0** [comment]
@Ash-Shy 我现在这4.3.5版本条目信息里有简记，右侧面板里找不到，你最后怎么解决了
