### ISSUE TITLE
最新版zotero，style出现列宽无法调整，锁定的情况

### ISSUE THREAD

**Issue by yufusang** [MuiseDestiny/zotero-style#914]
大佬您好！我经常遇见#标签，或者期刊标签锁定列宽，无法拖动和调整宽度的情况：
![image](https://github.com/MuiseDestiny/zotero-style/assets/142525457/47753de8-e20f-48e6-8f92-242385b0f121)

尝试拖动后，别列会被拉近，带动其他列一起向该锁定的列移动：

![image](https://github.com/MuiseDestiny/zotero-style/assets/142525457/efeb6b42-3c5b-47f7-806a-ecb40690c05e)

求助大佬！感谢！

**Comment by MuiseDestiny** [comment]
禁用茉莉花

**Comment by yufusang** [comment]
禁用后解决了，谢谢大佬帮助！

**Comment by 1nihao8** [comment]
> 禁用后解决了，谢谢大佬帮助！

请问是直接关闭茉莉花插件吗   我也遇到了和你一样的问题求解答

**Comment by Yolo9958** [comment]
> > 禁用后解决了，谢谢大佬帮助！
> 
> 请问是直接关闭茉莉花插件吗 我也遇到了和你一样的问题求解答

我也是，排列组合关闭插件没用
