### ISSUE TITLE
Please add the support for fields: sciUpSmall, sciUpTop, etc.

### ISSUE THREAD

**Issue by Xuekai-Dong** [MuiseDestiny/zotero-style#918]
Dear developers,
Support documentation for the software easyscholar is updated.
![image](https://github.com/MuiseDestiny/zotero-style/assets/84670034/526364ca-3435-4035-8132-15545b7708db)
The addition of these fields will surely enhance the experience of the add-on zotero-style.
Thanks!
Best regards,
Dong

**Comment by loucdvet123** [comment]
相同的请求

**Comment by MuiseDestiny** [comment]
zo里检查更新 已经支持

**Comment by Xuekai-Dong** [comment]
请问是支持zotero7吗？我使用的是zotero6，更新不了呀

**Comment by MuiseDestiny** [comment]
仅仅更新适配zotero 7的插件。6的不再更新
