### ISSUE TITLE
标注颜色的一些小建议

### ISSUE THREAD

**Issue by Z0o0o** [MuiseDestiny/zotero-style#92]
希望增加一键恢复默认颜色按键，
或者可以每五个颜色创建一个标注组，几个标注组配合使用，这样不用每次都要修改颜色代码了

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/216867446-afc49655-5387-4674-914a-e6c221e9dd4a.png)
![image](https://user-images.githubusercontent.com/51939531/216867467-e487dce6-90ea-4392-ae97-7e2c6f0df8d1.png)

2.1.0

**Comment by MuiseDestiny** [comment]
标注颜色组（图1）数量是没有限制的，一个组内的颜色（图2）也是没有限制的，但我建议所有组颜色数量一致，不然排版起来很错落。也邀请你把自己的搭配上传到https://github.com/MuiseDestiny/zotero-style/issues/48
