### ISSUE TITLE
大大您好，断网情况下Zotero style插件无法使用，请问是正常现象嘛？

### ISSUE THREAD

**Issue by cytwzn** [MuiseDestiny/zotero-style#922]
**不礼貌不回复，直接关闭**

    作者大大你好，非常感谢你开发了Zotero style插件，好看又实用，但是使用过程中我发现一点问题：
    在联网的情况下打开Zotero，Zotero style可以正常使用，包括高亮颜色的设置以及影响因子的显示。
    但是在没网的情况下打开Zotero，尽管插件还在，但Zotero style完全无法使用，影响因子就不见了，高亮文本也变成Zotero原版的颜色。
    麻烦大大有空帮忙看一下，感恩！！！我使用的版本是Zotero7 beta54，Zotero style 3.3.5。再次感谢！！！
![微信图片_20240324010749](https://github.com/MuiseDestiny/zotero-style/assets/164663366/91511954-6149-41ff-baed-37f7f7f9faaa)

**Comment by MuiseDestiny** [comment]
检查更新（不是在gitee，在zo内部检查更新）到4.2.7.3

**Comment by cytwzn** [comment]
> 检查更新（不是在gitee，在zo内部检查更新）到4.2.7.3
可以了！！大大我爱你！！！！！！！
