### ISSUE TITLE
请问一不小心完全删除zotero 7客户端下面的addon item的, 导致进度条无法显示怎么办

### ISSUE THREAD

**Issue by YaoLiMuMu** [MuiseDestiny/zotero-style#925]
**进度条消失了**
第一次研究zotero-style, 在自己配置脚本和写程序时, 发现Library里面有个addon item条目, 以为是自己的脚本配置出错原因, 就把这个项目搬入垃圾站并且清空了, 后面才发现现在所有条目没有显示进度了, 更新了最新版本的xpi插件也无法解决, 在config editor里面的progreeeColumn也是正确的
![image](https://github.com/MuiseDestiny/zotero-style/assets/32826811/a693f626-1a0c-4ab7-ac25-5754e527f48c)

**Comment by zzlb0224** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/8912444/9b355c98-8e82-4a3d-8401-a34aa3fb01c6)

我猜测你可以创建一个 这个试一试

**Comment by YaoLiMuMu** [comment]
@zzlb0224 尝试了, 好像不行, 目前addon Item 里面是空的
