### ISSUE TITLE
关于笔记存储

### ISSUE THREAD

**Issue by sjads** [MuiseDestiny/zotero-style#93]
addon item下生成的文件收到一个里面 
[image](https://user-images.githubusercontent.com/96932407/216750930-a2b5e99c-dd3a-44e7-90af-66ccac7fa5bb.png)

**Comment by sjads** [comment]
要不然太多了

**Comment by MuiseDestiny** [comment]
> 要不然太多了

文献库是不是有多个addon item，可以删除没用的一个，你这里展示的应该是多出来的，真正被使用的不会在这里显示。

**Comment by sjads** [comment]
好的 大佬 我去看看

**Comment by sjads** [comment]
大佬，没有，我只有这一个addon item ，并且 我打开一个文献，自动就会在所有笔记那出现一个
[image](https://user-images.githubusercontent.com/96932407/216751852-762bc1bf-6028-4490-863a-3ab51bf0ba22.png)
[image](https://user-images.githubusercontent.com/96932407/216751862-732d5c08-9e34-4a35-8acc-ad2c2f5d64e8.png)

**Comment by MuiseDestiny** [comment]
我看生成的笔记还不算多，把addon item删除，然后在回收站彻底删除，重启zo，会重新建立一个条目，到时候看看侧边栏还会显示它的笔记不。

**Comment by sjads** [comment]
还是一样，我刚才全都删除了，并且再回收站里面也清除了，





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-style] 关于笔记存储 (Issue #93)





 
我看生成的笔记还不算多，把addon item删除，然后在回收站彻底删除，重启zo，会重新建立一个条目，到时候看看侧边栏还会显示它的笔记不。

**Comment by MuiseDestiny** [comment]
生成addon item后，把它删除，但不要在回收站删除，也可以隐藏。
