### ISSUE TITLE
没有“期刊标签”列

### ISSUE THREAD

**Issue by wulidede** [MuiseDestiny/zotero-style#937]
作者你好，之前用着一直挺好的，但是今天更新到了Zotero 7.0.0-beta.71+03d0ea436 (64-bit)之后，style的期刊标签就没有了，试了style最新的几个版本，选项也都选中了，如图所示。系统是Win11，请问该怎么解决这个Bug？
![1712660302700](https://github.com/MuiseDestiny/zotero-style/assets/90752609/1f093228-8f25-4042-bb3b-f7b4f7de52c1)

![屏幕截图 2024-04-09 185651](https://github.com/MuiseDestiny/zotero-style/assets/90752609/bb2c8d1b-eac9-4f22-bdaa-6757d15bbb7f)

**Comment by zhouzinan** [comment]
我今天更新新版Zotero也出现这个问题了

**Comment by Water-Disappear** [comment]
求助

**Comment by LiyiEasy** [comment]
同样出现这个问题，我还以为是我插件的问题，结果重新安装了最新的还是没有期刊标签页。

**Comment by Chikit-L** [comment]
等插件更新或者回到上一个版本zotero

**Comment by jianghuchuanshuo** [comment]
开始收费了吧

**Comment by MuiseDestiny** [comment]
更新插件
