### ISSUE TITLE
 标题标签不显示

### ISSUE THREAD

**Issue by Shawn9703** [MuiseDestiny/zotero-style#944]
![QQ截图20240410205050](https://github.com/MuiseDestiny/zotero-style/assets/166522778/6ee025f7-b92b-40aa-bbc6-06f9c7e230f6)
![QQ截图20240410205104](https://github.com/MuiseDestiny/zotero-style/assets/166522778/6fbfbe36-cae8-4445-8d6f-30e6aa2e00ac)
![QQ截图20240410205334](https://github.com/MuiseDestiny/zotero-style/assets/166522778/edcad0bd-db1c-4032-bb2e-73fa89d73aea)
![QQ截图20240410210424](https://github.com/MuiseDestiny/zotero-style/assets/166522778/b7a8c38d-abc6-4a98-aaca-15c176da1dfc)

插件版本为4.3.0，软件版本为zotero7 beta72

标题标签始终无法显示，在标题列设置中也没有勾选标签的选项，禁用本插件之后则可以在题目前正常显示标签。
自查标签正确设置且赋了颜色，title column tags显示也为true
请求解答，感谢作者的贡献

**Comment by Shawn9703** [comment]
已经依次尝试禁用了所有的插件，除非禁用style才能正常显示，寻求问题的解决办法，谢谢！

**Comment by Shawn9703** [comment]
插件4.3.9版本问题已解决

**Comment by BlankSeed** [comment]
你好，碰到同样的问题，打开style插件标题前的颜色标签不显示，禁用就显示了，请问应该怎么设置呢？

**Comment by BlankSeed** [comment]
另外我的Addon Preference Manager里面没有titleColumn.tags这一项，请问有办法设置嘛，谢谢！

**Comment by Shawn9703** [comment]
我没再继续设置了，直接更新zotero7和新版插件，问题解决。




上海大学&nbsp;邓文龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-style"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 上午6:24
***@***.***&gt;;
抄送:&nbsp;"上海大学 ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-style]  标题标签不显示 (Issue #944)





 
你好，碰到同样的问题，打开style插件标题前的颜色标签不显示，禁用就显示了，请问应该怎么设置呢？
