### ISSUE TITLE
Style在PDF阅读界面与Translate for Zotero冲突

### ISSUE THREAD

**Issue by pekideer** [MuiseDestiny/zotero-style#947]
# 作者你好，报告Bug：
Style在PDF功能按钮会随我选择文本翻译时消失，具体如GIF所示。（已通过开关插件功能排除与其他插件的冲突，不知是Style还是Translate的问题@windingwind）
![屏幕录制-2024-04-12-094128](https://github.com/MuiseDestiny/zotero-style/assets/27672078/c56cd33e-0b51-4796-94d6-32ebede72b99)
# Debug Output：

1712886387261	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1712886388014	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1712886388030	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1712886388030	addons.webextension.zoterostyle@polygon.org	WARN	Loading extension 'zoterostyle@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1712886389089	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "r is undefined" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoteropdftranslate@euclpts.com.xpi!/chrome/content/scripts/zoteropdftranslate.js" line: 145}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "TypeError: _0x5487e5[_0x17d5e9[0]] is undefined" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 1}]

[JavaScript Error: "TypeError: _0x1aaa62 is null" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 1}]

[JavaScript Error: "[React Intl] An `id` must be provided to format a message." {file: "resource://zotero/react-intl.js" line: 4243}]

[JavaScript Error: "[React Intl] An `id` must be provided to format a message." {file: "resource://zotero/react-intl.js" line: 4243}]

[JavaScript Error: "TypeError: _0x1aaa62 is null" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 1}]

[JavaScript Error: "TypeError: _0x5487e5[_0x17d5e9[0]] is undefined" {file: "jar:file:///C:/Users/lulid/AppData/Roaming/Zotero/Zotero/Profiles/p44z4y11.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/zoterostyle.js" line: 1}]

[JavaScript Error: "[React Intl] An `id` must be provided to format a message." {file: "resource://zotero/react-intl.js" line: 4243}]

[JavaScript Error: "[React Intl] An `id` must be provided to format a message." {file: "resource://zotero/react-intl.js" line: 4243}]

appName => Zotero, version => 7.0.0-beta.73+398454f85, os => Windows 10.0 22631, locale => zh-CN, extensions => Translate for Zotero (1.1.0-beta.41, extension), Ethereal Style (4.3.0, extension), Jasminum (1.0.0-14, extension, disabled), Ethereal Reference (0.7.5, extension, disabled), Easier Citation (0.4.3, extension, disabled), Sci-PDF (1.1.1, extension, disabled), 蒲公英 (1.0.0-8, extension, disabled), Green Frog (0.18.0, extension, disabled), Zoplicate (2.3.0, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.37, extension, disabled), Zotero Reading List (1.2.0, extension, disabled), Zotero 插件市场 (1.6.0, extension, disabled), Obsidian Note for Zotero (1.0.1, extension, disabled), Notero (0.5.15, extension, disabled), ZotCard (3.0.10, extension, disabled), Better BibTex for Zotero (6.7.173, extension, disabled), Linter for Zotero (1.16.4, extension, disabled), Chartero (2.7.0, extension, disabled), Better Notes for Zotero (1.1.4-beta.62, extension, disabled)

(3)(+0041219): Notifier.trigger('start', 'sync', []) called [observers: 3]

(3)(+0000001): Stopping full-text content processor

(4)(+0000008): Beginning DB transaction 0IgrSzun

(4)(+0000009): Committed DB transaction 0IgrSzun

(4)(+0000000): Beginning DB transaction IP2OlT6p

(4)(+0000001): CREATE TEMPORARY TABLE tagDelete AS SELECT tagID FROM tags WHERE tagID NOT IN (SELECT tagID FROM itemTags)

(4)(+0000001): CREATE INDEX tagDelete_tagID ON tagDelete(tagID)

(4)(+0000001): SELECT tagID AS id, name FROM tagDelete JOIN tags USING (tagID)

(4)(+0000000): DROP TABLE tagDelete

(4)(+0000001): Committed DB transaction IP2OlT6p

(4)(+0000000): Beginning DB transaction 7DeeYLqe

(4)(+0000001): Committed DB transaction 7DeeYLqe

(3)(+0000001): Purged data tables in 15 ms

(3)(+0000000): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000001): HTTP GET https://api.zotero.org/keys/current

(3)(+0000278): HTTP GET https://api.zotero.org/keys/current succeeded with 200

(3)(+0000001): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(3)(+0000000): { "userID": 8861918 "username": "lulidi" "displayName": "" "access": { "user": { "library": true "files": true "notes": true "write": true } "groups": { "all": { "library": true "write": true } } } }

(4)(+0000000): Beginning DB transaction sZVnVwHE

(3)(+0000001): [ConcurrentCaller] All tasks are done

(4)(+0000003): Committed DB transaction sZVnVwHE

(3)(+0000001): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000000): HTTP GET https://api.zotero.org/users/8861918/groups?format=versions

(1)(+0000021): Error: [React Intl] An `id` must be provided to format a message. invariant@resource://zotero/react-intl.js:4243:13 formatMessage@resource://zotero/react-intl.js:5095:14 SelectionPopup/<@resource://zotero/reader/reader.js:21637:17 Array.prototype.map@resource://zotero/reader/reader.html:17:26 SelectionPopup@resource://zotero/reader/reader.js:21633:24 renderWithHooks@resource://zotero/react-dom.js:15015:29 mountIndeterminateComponent@resource://zotero/react-dom.js:17841:15 beginWork@resource://zotero/react-dom.js:19079:18 callCallback@resource://zotero/react-dom.js:3942:16 invokeGuardedCallbackDev@resource://zotero/react-dom.js:3991:18 invokeGuardedCallback@resource://zotero/react-dom.js:4053:33 beginWork$1@resource://zotero/react-dom.js:23994:30 performUnitOfWork@resource://zotero/react-dom.js:22809:14 workLoopSync@resource://zotero/react-dom.js:22737:24 renderRootSync@resource://zotero/react-dom.js:22700:9 performSyncWorkOnRoot@resource://zotero/react-dom.js:22323:20 flushSyncCallbackQueueImpl/<@resource://zotero/react-dom.js:11357:28 unstable_runWithPriority@resource://zotero/react.js:2764:14 runWithPriority$1@resource://zotero/react-dom.js:11306:12 flushSyncCallbackQueueImpl@resource://zotero/react-dom.js:11352:28 flushSyncCallbackQueue@resource://zotero/react-dom.js:11339:5 scheduleUpdateOnFiber@resource://zotero/react-dom.js:21923:11 dispatchAction@resource://zotero/react-dom.js:16169:28 _updateState@resource://zotero/reader/reader.js:42942:125 onSetSelectionPopup@resource://zotero/reader/reader.js:43345:12 _handlePointerUp@resource://zotero/reader/reader.js:28545:20

(1)(+0000004): Error: [React Intl] An `id` must be provided to format a message. invariant@resource://zotero/react-intl.js:4243:13 formatMessage@resource://zotero/react-intl.js:5095:14 SelectionPopup/<@resource://zotero/reader/reader.js:21637:17 Array.prototype.map@resource://zotero/reader/reader.html:17:26 SelectionPopup@resource://zotero/reader/reader.js:21633:24 renderWithHooks@resource://zotero/react-dom.js:15015:29 mountIndeterminateComponent@resource://zotero/react-dom.js:17841:15 beginWork@resource://zotero/react-dom.js:19079:18 callCallback@resource://zotero/react-dom.js:3942:16 invokeGuardedCallbackDev@resource://zotero/react-dom.js:3991:18 invokeGuardedCallback@resource://zotero/react-dom.js:4053:33 beginWork$1@resource://zotero/react-dom.js:23994:30 performUnitOfWork@resource://zotero/react-dom.js:22809:14 workLoopSync@resource://zotero/react-dom.js:22737:24 renderRootSync@resource://zotero/react-dom.js:22700:9 performSyncWorkOnRoot@resource://zotero/react-dom.js:22323:20 flushSyncCallbackQueueImpl/<@resource://zotero/react-dom.js:11357:28 unstable_runWithPriority@resource://zotero/react.js:2764:14 runWithPriority$1@resource://zotero/react-dom.js:11306:12 flushSyncCallbackQueueImpl@resource://zotero/react-dom.js:11352:28 flushSyncCallbackQueue@resource://zotero/react-dom.js:11339:5 scheduleUpdateOnFiber@resource://zotero/react-dom.js:21923:11 dispatchAction@resource://zotero/react-dom.js:16169:28 _updateState@resource://zotero/reader/reader.js:42942:125 onSetSelectionPopup@resource://zotero/reader/reader.js:43345:12 _handlePointerUp@resource://zotero/reader/reader.js:28545:20

(3)(+0000275): HTTP GET https://api.zotero.org/users/8861918/groups?format=versions succeeded with 200

(3)(+0000000): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(3)(+0000000): Local groups:

(3)(+0000001): []

(3)(+0000000): Final libraries to sync:

(3)(+0000000): [ "0": 1 ]

(3)(+0000000): Starting data sync for 我的文库

(4)(+0000001): SELECT setting, value FROM syncedSettings WHERE synced=0 AND libraryID=? [1]

(3)(+0000000): [ConcurrentCaller] All tasks are done

(3)(+0000000): No settings to upload in 我的文库

(4)(+0000000): SELECT O.collectionID FROM collections O WHERE libraryID=? AND synced=0 [1]

(4)(+0000001): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'collection']

(3)(+0000000): No collections to upload in 我的文库

(4)(+0000000): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 1]

(3)(+0000001): No collection deletions to upload in 我的文库

(4)(+0000000): SELECT O.savedSearchID FROM savedSearches O WHERE libraryID=? AND synced=0 [1]

(4)(+0000000): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'search']

(3)(+0000000): No searches to upload in 我的文库

(4)(+0000000): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 4]

(3)(+0000001): No search deletions to upload in 我的文库

(4)(+0000000): SELECT O.itemID FROM items O LEFT JOIN itemAttachments IA USING (itemID) LEFT JOIN itemNotes INo ON (O.itemID=INo.itemID) LEFT JOIN itemAnnotations IAn ON (O.itemID=IAn.itemID) WHERE libraryID=? AND synced=0 AND (IAn.isExternal IS NULL OR IAN.isExternal=0) [1]

(4)(+0000000): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'item']

(3)(+0000001): 2 items to upload in library 1

(4)(+0000000): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 3]

(3)(+0000000): No item deletions to upload in 我的文库

(3)(+0000000): {"item":[120,6870]}

(4)(+0000000): Registering notifier observer 'itemsUpload_Nb' for [item]

(4)(+0000000): Beginning DB transaction QZ0a7Rej

(4)(+0000001): SELECT data FROM syncCache WHERE libraryID=? AND key=? AND version=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'XZJJR86V', 36226, 'item']

(4)(+0000017): Committed DB transaction QZ0a7Rej

(4)(+0000000): Beginning DB transaction d0pL4FBf

(4)(+0000000): SELECT data FROM syncCache WHERE libraryID=? AND key=? AND version=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'D6K3DLUM', 36228, 'item']

(4)(+0000001): Committed DB transaction d0pL4FBf

(3)(+0000000): UPLOAD BATCH:

(3)(+0000001): [ "0": { "key": "XZJJR86V" "version": 36226 "tags": [ "0": { "tag": "文献综述" } "1": { "tag": "air temperature" } "2": { "tag": "Convection" } "3": { "tag": "Cooling" } "4": { "tag": "Cooling capacity" } "5": { "tag": "Direct measurements" } "6": { "tag": "EVO" } "7": { "tag": "Floor" } "8": { "tag": "Globe thermometer" } "9": { "tag": "Heat exchange" } "10": { "tag": "Heat transfer" } "11": { "tag": "Heating" } "12": { "tag": "Indoor environment" } "13": { "tag": "Mean Radiant Temperature" } "14": { "tag": "Measurement" } "15": { "tag": "Model" } "16": { "tag": "Modeling" } "17": { "tag": "MRT" } "18": { "tag": "notion" } "19": { "tag": "Radiant floor" } "20": { "tag": "Radiant heat exchange" } "21": { "tag": "Radiant heat transfer" } "22": { "tag": "Radiation" } "23": { "tag": "Review" } "24": { "tag": "Simulation" } ] "dateModified": "2024-04-12T01:47:48Z" } "1": { "key": "D6K3DLUM" "version": 36228 "note": "XZJJR86V\n{\"readingTime\":{\"page\":15,\"data\":{\"0\":210}}}" "dateModified": "2024-04-12T01:47:52Z" } ]

(3)(+0000000): Uploading 2 items

(3)(+0000000): Sending If-Unmodified-Since-Version: 36228

(3)(+0000000): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000000): HTTP POST "[{"key":"XZJJR86V","version":36226,"tags":[{"tag":"文献综述"},{"tag":"air temperature"},{"tag":"Convection"},{"tag":"Cooling"},{"tag":"Cooling capacity"},{"tag":"Direct measurements"},{"tag":"EVO"},{"tag":"Floor"},{"tag":"Globe thermometer"},{"tag":"Heat exchange"},{"tag":"Heat transfer"},{"tag":"Heating"},{"tag":"Indoor environment"},{"tag":"Mean Radiant Temperature"},{"tag":"Measurement"},{"tag":"Model"},{"tag":"Modeling"},{"tag":"MRT"},{"tag":"notion"},{"tag":"Radiant floor"},{"tag":"Radiant heat exchange"},{"tag":"Radiant heat transfer"},{"tag":"Radiation"},{"tag":"Review"},{"tag":"Simulation"}],"dateModified":"2024-04-12T01:47:48Z"},{"key":"D6K3DLUM","version":36228,"note":"XZJJR86V\n{\"readingTime\":{\"page\":15,\"data\":{\"0\":210}}}","dateModified":"2024-04-12T01:47:52Z"}]" to https://api.zotero.org/users/8861918/items

(3)(+0000084): Writing reader state to D:\Program Data\Zotero\storage\KP75264D\.zotero-reader-state

(3)(+0000414): HTTP POST https://api.zotero.org/users/8861918/items succeeded with 200

(3)(+0000001): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(4)(+0000002): Creator in position 0 hasn't changed

(4)(+0000001): Creator in position 1 hasn't changed

(4)(+0000000): Creator in position 2 hasn't changed

(4)(+0000000): Creator in position 3 hasn't changed

(4)(+0000000): Creator in position 4 hasn't changed

(4)(+0000000): Creator in position 5 hasn't changed

(4)(+0000002): Tags haven't changed

(4)(+0000000): Relations have not changed for item 1/XZJJR86V

(4)(+0000001): Field 'dateAdded' has not changed

(4)(+0000000): Field 'dateModified' has not changed

(3)(+0000000): Collections have not changed for item 120

(4)(+0000001): Tags haven't changed

(4)(+0000000): Relations have not changed for item 1/D6K3DLUM

(4)(+0000000): Field 'dateAdded' has not changed

(4)(+0000001): Field 'dateModified' has not changed

(4)(+0000000): Note hasn't changed

(3)(+0000000): Saving to sync cache:

(3)(+0000002): [ "0": { "key": "XZJJR86V" "version": 36229 "library": { "type": "user" "id": 8861918 "name": "lulidi" "links": { "alternate": { "href": "https://www.zotero.org/lulidi" "type": "text/html" } } } "links": { "self": { "href": "https://api.zotero.org/users/8861918/items/XZJJR86V" "type": "application/json" } "alternate": { "href": "https://www.zotero.org/lulidi/items/XZJJR86V" "type": "text/html" } } "meta": { "creatorSummary": "Guo et al." "parsedDate": "2020" "numChildren": 3 } "data": { "key": "XZJJR86V" "version": 36229 "itemType": "journalArticle" "title": "On the understanding of the mean radiant temperature within both the indoor and outdoor environment, a critical review" "creators": [ "0": { "creatorType": "author" "firstName": "Hongshan" "lastName": "Guo" } "1": { "creatorType": "author" "firstName": "Dorit" "lastName": "Aviv" } "2": { "creatorType": "author" "firstName": "Mauricio" "lastName": "Loyola" } "3": { "creatorType": "author" "firstName": "Eric" "lastName": "Teitelbaum" } "4": { "creatorType": "author" "firstName": "Nicholas" "lastName": "Houchois" } "5": { "creatorType": "author" "firstName": "Forrest" "lastName": "Meggers" } ] "abstractNote": "Mean radiant temperature is central to our understanding of the radiant heat exchange between the human body and surrounding environment. This paper will present a review of the concept's evolution including its qualitative definition, methods of quantitative evaluation and corresponding challenges. In the process, this review suggests that more effort needs to be invested in addressing the geometric complexities of radiant heat transfer in research into MRT; the ASHRAE definition is broad and is liable to simplification, and research which uses the definition relies on a variety of simplifications, often without acknowledging the degree of geometric complexity which exists in reality. Existing means of obtaining an estimate of mean radiant temperature range from direct measurements using globe thermometers or net radiometers, to computational simulations, and are widely used for studies within indoor and outdoor environments. Previous literature studying the correlation between air temperature and MRT has found equivalence ratios, the relative importance of convection to radiation, ranging from 0.71 to 1.4, however, it is often assumed to be 1.0 in current research practices. We also identified a rapid increase in the usage of MRT in biometeorological studies during the last ten years on top of the increased usage in indoor environment sensing and modeling in light of recent developments in heating and cooling systems. Recent efforts to include the short-wave component in indoor MRT characterization have shown an increase in cooling capacity of radiant floors from 32 to 110 W/m2; significantly decreasing peak energy demand." "publicationTitle": "Renewable & Sustainable Energy Reviews" "volume": "117" "issue": "" "pages": "109207" "date": "01/2020" "series": "" "seriesTitle": "" "seriesText": "" "journalAbbreviation": "Renew Sustain Energy Rev" "language": "en-US" "DOI": "10.1016/j.rser.2019.06.014" "ISSN": "13640321" "shortTitle": "" "url": "https://linkinghub.elsevier.com/retrieve/pii/S1364032119304071" "accessDate": "2021-12-09T10:06:26Z" "archive": "" "archiveLocation": "" "libraryCatalog": "" "callNumber": "" "rights": "" "extra": "76 citations (Crossref/DOI) [2024-03-11]" "tags": [ "0": { "tag": "Convection" } "1": { "tag": "Cooling" } "2": { "tag": "Cooling capacity" } "3": { "tag": "Direct measurements" } "4": { "tag": "EVO" } "5": { "tag": "Floor" } "6": { "tag": "Globe thermometer" } "7": { "tag": "Heat exchange" } "8": { "tag": "Heat transfer" } "9": { "tag": "Heating" } "10": { "tag": "Indoor environment" } "11": { "tag": "MRT" } "12": { "tag": "Mean Radiant Temperature" } "13": { "tag": "Measurement" } "14": { "tag": "Model" } "15": { "tag": "Modeling" } "16": { "tag": "Radiant floor" } "17": { "tag": "Radiant heat exchange" } "18": { "tag": "Radiant heat transfer" } "19": { "tag": "Radiation" } "20": { "tag": "Review" } "21": { "tag": "Simulation" } "22": { "tag": "air temperature" } "23": { "tag": "notion" } "24": { "tag": "文献综述" } ] "collections": [ "0": "VFQXB5RS" "1": "9CIIT7Z5" ] "relations": {} "dateAdded": "2021-12-09T10:06:26Z" "dateModified": "2024-04-12T01:47:48Z" } } "1": { "key": "D6K3DLUM" "version": 36229 "library": { "type": "user" "id": 8861918 "name": "lulidi" "links": { "alternate": { "href": "https://www.zotero.org/lulidi" "type": "text/html" } } } "links": { "self": { "href": "https://api.zotero.org/users/8861918/items/D6K3DLUM" "type": "application/json" } "alternate": { "href": "https://www.zotero.org/lulidi/items/D6K3DLUM" "type": "text/html" } "up": { "href": "https://api.zotero.org/users/8861918/items/8TP4EMFR" "type": "application/json" } } "meta": { "numChildren": 0 } "data": { "key": "D6K3DLUM" "version": 36229 "parentItem": "8TP4EMFR" "itemType": "note" "note": "XZJJR86V\n{\"readingTime\":{\"page\":15,\"data\":{\"0\":210}}}" "tags": [] "relations": {} "dateAdded": "2024-04-12T01:31:42Z" "dateModified": "2024-04-12T01:47:52Z" } } ]

(4)(+0000001): INSERT OR REPLACE INTO syncCache (libraryID, key, syncObjectTypeID, version, data) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?) [1, 'XZJJR86V', 3, 36229, '{"key":"XZJJR86V","version":36229,"library":{"type":"user","id":8861918,"name":"lulidi","links":{"alternate":{"href":"https://www.zotero.org/lulidi","type":"text/html"}}},"links":{"self":{"href":"https://api.zotero.org/users/8861918/items/XZJJR86V","type":"application/json"},"alternate":{"href":"https://www.zotero.org/lulidi/items/XZJJR86V","type":"text/html"}},"meta":{"creatorSummary":"Guo et al.","parsedDate":"2020","numChildren":3},"data":{"key":"XZJJR86V","version":36229,"itemType":"journalArticle","title":"On the understanding of the mean radiant temperature within both the indoor and outdoor environment, a critical review","creators":[{"creatorType":"author","firstName":"Hongshan","lastName":"Guo"},{"creatorType":"author","firstName":"Dorit","lastName":"Aviv"},{"creatorType":"author","firstName":"Mauricio","lastName":"Loyola"},{"creatorType":"author","firstName":"Eric","lastName":"Teitelbaum"},{"creatorType":"author","firstName":"Nicholas","lastName":"Houchois"},{"creatorType":"author","firstName":"Forrest","lastName":"Meggers"}],"abstractNote":"Mean radiant temperature is central to our understanding of the radiant heat exchange between the human body and surrounding environment. This paper will present a review of the concept's evolution including its qualitative definition, methods of quantitative evaluation and corresponding challenges. In the process, this review suggests that more effort needs to be invested in addressing the geometric complexities of radiant heat transfer in research into MRT; the ASHRAE definition is broad and is liable to simplification, and research which uses the definition relies on a variety of simplifications, often without acknowledging the degree of geometric complexity which exists in reality. Existing means of obtaining an estimate of mean radiant temperature range from direct measurements using globe thermometers or net radiometers, to computational simulations, and are widely used for studies within indoor and outdoor environments. Previous literature studying the correlation between air temperature and MRT has found equivalence ratios, the relative importance of convection to radiation, ranging from 0.71 to 1.4, however, it is often assumed to be 1.0 in current research practices. We also identified a rapid increase in the usage of MRT in biometeorological studies during the last ten years on top of the increased usage in indoor environment sensing and modeling in light of recent developments in heating and cooling systems. Recent efforts to include the short-wave component in indoor MRT characterization have shown an increase in cooling capacity of radiant floors from 32 to 110 W/m2; significantly decreasing peak energy demand.","publicationTitle":"Renewable & Sustainable Energy Reviews","volume":"117","issue":"","pages":"109207","date":"01/2020","series":"","seriesTitle":"","seriesText":"","journalAbbreviation":"Renew Sustain Energy Rev","language":"en-US","DOI":"10.1016/j.rser.2019.06.014","ISSN":"13640321","shortTitle":"","url":"https://linkinghub.elsevier.com/retrieve/pii/S1364032119304071","accessDate":"2021-12-09T10:06:26Z","archive":"","archiveLocation":"","libraryCatalog":"","callNumber":"","rights":"","extra":"76 citations (Crossref/DOI) [2024-03-11]","tags":[{"tag":"Convection"},{"tag":"Cooling"},{"tag":"Cooling capacity"},{"tag":"Direct measurements"},{"tag":"EVO"},{"tag":"Floor"},{"tag":"Globe thermometer"},{"tag":"Heat exchange"},{"tag":"Heat transfer"},{"tag":"Heating"},{"tag":"Indoor environment"},{"tag":"MRT"},{"tag":"Mean Radiant Temperature"},{"tag":"Measurement"},{"tag":"Model"},{"tag":"Modeling"},{"tag":"Radiant floor"},{"tag":"Radiant heat exchange"},{"tag":"Radiant heat transfer"},{"tag":"Radiation"},{"tag":"Review"},{"tag":"Simulation"},{"tag":"air temperature"},{"tag":"notion"},{"tag":"文献综述"}],"collections":["VFQXB5RS","9CIIT7Z5"],"relations":{},"dateAdded":"2021-12-09T10:06:26Z","dateModified":"2024-04-12T01:47:48Z"}}', 1, 'D6K3DLUM', 3, 36229, '{"key":"D6K3DLUM","version":36229,"library":{"type":"user","id":8861918,"name":"lulidi","links":{"alternate":{"href":"https://www.zotero.org/lulidi","type":"text/html"}}},"links":{"self":{"href":"https://api.zotero.org/users/8861918/items/D6K3DLUM","type":"application/json"},"alternate":{"href":"https://www.zotero.org/lulidi/items/D6K3DLUM","type":"text/html"},"up":{"href":"https://api.zotero.org/users/8861918/items/8TP4EMFR","type":"application/json"}},"meta":{"numChildren":0},"data":{"key":"D6K3DLUM","version":36229,"parentItem":"8TP4EMFR","itemType":"note","note":"XZJJR86V\n{\"readingTime\":{\"page\":15,\"data\":{\"0\":210}}}","tags":[],"relations":{},"dateAdded":"2024-04-12T01:31:42Z","dateModified":"2024-04-12T01:47:52Z"}}']

(3)(+0000000): [ConcurrentCaller] All tasks are done

(4)(+0000018): Beginning DB transaction a009HGrU

(4)(+0000001): Item 120 has not changed

(4)(+0000000): Item 6870 has not changed

(4)(+0000001): Updating database with new library data

(4)(+0000000): UPDATE libraries SET version=?, storageVersion=? WHERE libraryID=? [36229, 36229, 1]

(4)(+0000003): UPDATE items SET version=36229 WHERE itemID IN (?, ?) [120, 6870]

(4)(+0000000): UPDATE items SET synced=1 WHERE itemID IN (?, ?) [120, 6870]

(4)(+0000011): Committed DB transaction a009HGrU

(4)(+0000001): DELETE FROM syncCache WHERE ROWID IN (SELECT SC.ROWID FROM syncCache SC LEFT JOIN items O USING (libraryID, key, version) WHERE syncObjectTypeID=? AND SC.libraryID=? AND (O.libraryID IS NULL OR SC.version < O.version)) [3, 1]

(2)(+0000007): Failed: 0

(4)(+0000000): Unregistering notifier observer in notifier with id 'itemsUpload_Nb'

(3)(+0000000): Done uploading items in library 1

(3)(+0000000): {}

(4)(+0000000): Upload result is 1

(4)(+0000001): Updating database with new library data

(4)(+0000000): Beginning DB transaction mrNs4N7I

(4)(+0000002): UPDATE libraries SET lastSync=? WHERE libraryID=? [1712886476, 1]

(4)(+0000005): Committed DB transaction mrNs4N7I

(3)(+0000000): Done syncing 我的文库

(4)(+0000000): REPLACE INTO version (schema, version) VALUES ('lastsync', ?) [1712886477]

(3)(+0000004): Starting file syncing

(3)(+0000000): Done with file syncing

(3)(+0000000): Starting full-text syncing

(3)(+0000001): Done with full-text syncing

(3)(+0000000): Done syncing

(3)(+0000000): Notifier.trigger('finish', 'sync', []) called [observers: 3]

(4)(+0000000): SELECT libraryID AS id FROM feeds WHERE refreshInterval IS NOT NULL AND ( lastCheck IS NULL OR (julianday(lastCheck, 'utc') + (refreshInterval/1440.0) - julianday('now', 'utc')) <= 0 )

(3)(+0000019): Running update for feeds:

(3)(+0000000): All feed updates done

(3)(+0000001): Scheduling next feed update

(4)(+0000000): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000000): No feeds with auto-update

(3)(+0002921): WebSocket message: {"event":"topicUpdated","topic":"/users/8861918","version":36229}

(3)(+0000000): Library is already up to date

(4)(+0002525): SELECT A.itemID FROM items A WHERE 1 AND A.itemID NOT IN (SELECT itemID FROM deletedItems) AND libraryID=? [1]

**Comment by MuiseDestiny** [comment]
你应该是自定了标注，但定义错了。

1. `Shift + P` -> 标注
2. 如图
3. 点击加号
4. 点击新建的Untitled以恢复

![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/1f66648f-3447-48b8-bca8-13bfaad1575f)


![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/f1ebc77e-7fee-48e8-aff8-c8269ebeebe7)

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/5b844b9f-49b9-4d31-a4bc-143b3d28b20d)

记得名称，颜色都要填写。

**Comment by pekideer** [comment]
哦！已解决，麻烦了，感谢
