### ISSUE TITLE
无法自定义标注颜色

### ISSUE THREAD

**Issue by standingo** [MuiseDestiny/zotero-style#95]
shift+p调出窗口没有标注选项
![WeChat6c69351c5efc15448ca9a3425d97296c](https://user-images.githubusercontent.com/117378943/216781344-57285f1e-4186-40cf-a0d4-4972e4f3967b.png)

**Comment by standingo** [comment]
提个小建议关系图谱可否设置一个黑暗模式的按钮呢？
![WeChat004410443c61dbf86a4a4f9893f13299](https://user-images.githubusercontent.com/117378943/216781526-01a55a11-18f0-45a0-b359-32a177885e1b.png)

**Comment by MuiseDestiny** [comment]
> 提个小建议关系图谱可否设置一个黑暗模式的按钮呢？ ![WeChat004410443c61dbf86a4a4f9893f13299](https://user-images.githubusercontent.com/117378943/216781526-01a55a11-18f0-45a0-b359-32a177885e1b.png)

https://github.com/MuiseDestiny/zotero-style/releases/tag/0.2.9

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/216801022-e4d8ee12-2b64-42a8-95f7-6c8f80dfaec5.png)

更新，自动切换
点击`Zotero Night`提供的按钮
![image](https://user-images.githubusercontent.com/51939531/216801030-b816946c-4d47-4215-bc00-9f687f2cac50.png)
