### ISSUE TITLE
请问为什么安装插件后不能展开附件了

### ISSUE THREAD

**Issue by linghei** [MuiseDestiny/zotero-style#956]
**不礼貌不回复，直接关闭**
![QQ截图20240416153044](https://github.com/MuiseDestiny/zotero-style/assets/53417697/27921107-af51-48da-b448-7fbf20063f57)
以前标题左边应该可以展开看文件什么的，我安装插件后就没有那个标志了，应该也没动过什么设置

**Comment by UpsilonYHZ** [comment]
我也遇到了这个问题，而且拖入本地pdf生产新条目以后也找不到按钮取消新条目的展开
