### ISSUE TITLE
快捷键冲突ctrl+T

### ISSUE THREAD

**Issue by wytWangLei** [MuiseDestiny/zotero-style#957]
最新版本@zotero7，ctrl+T会跳出什么select tags

**Comment by shao12781566** [comment]
目前有三个功能涉及这个快捷键
插件本身的标签功能和标题翻译功能
以及标题首字母大写功能

**Comment by verve91** [comment]
对，同样的问题，还很卡，希望可以关掉，不好用

**Comment by MuiseDestiny** [comment]
> 对，同样的问题，还很卡，希望可以关掉，不好用

建议卸载插件

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-style/assets/51939531/e1cc6d32-ac99-4385-8556-91f993cbbdff)

检查更新到4.3.6，支持自定义。记得重启。如检查不到自己下载更新https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi
