### ISSUE TITLE
shift+P后显示不完全且无法操作

### ISSUE THREAD

**Issue by Cshining21** [MuiseDestiny/zotero-style#96]
只显示：标签，标注，影响因子，关系图谱四项，没有阅读进度选项
而且也无法上下操作和进入编辑.....

**Comment by MuiseDestiny** [comment]
选中有有阅读记录的条目才会有查看阅读进度命令，无法上下操作是什么意思，详细描述下

**Comment by Cshining21** [comment]
刚刚重启了上下操作可以了。。估计中午是卡了- -
阅读记录是要从安装了插件后算起吗？就我选中的都是有阅读过的，但都没显示进度

**Comment by MuiseDestiny** [comment]
> 

对的，插件有记录的逻辑zotero不会记录。

**Comment by Cshining21** [comment]
> > 
> 
> 对的，插件有记录的逻辑zotero不会记录。

偶偶好的，谢谢答复！
