### ISSUE TITLE
“简记”栏在右侧面板不显示了

### ISSUE THREAD

**Issue by pengxy0** [MuiseDestiny/zotero-style#962]
大佬好，我目前style更新到最新版（4.3.5），zotero还是之前的54版本。这个“简记”列在条目信息里是可以找到的，但是在右侧面板里没有“简记”的信息栏，如下图所示。请问下这个可以解决下不。感谢大佬！
![image](https://github.com/MuiseDestiny/zotero-style/assets/130196652/4271c506-b542-4183-9dac-0af1cdbbbc8a)

**Comment by Danielsolucky** [comment]
我也发现了，简记直接没了，哎，上几版本的zotero很不好用，现在插件适配也很难

**Comment by pengxy0** [comment]
> 我也发现了，简记直接没了，哎，上几版本的zotero很不好用，现在插件适配也很难

貌似这里添加remark：就能显示了。但是这样添加起来还是很麻烦的
![image](https://github.com/MuiseDestiny/zotero-style/assets/130196652/332acf53-b339-4600-aa34-6cb679416c45)

**Comment by loseyourself99** [comment]
我的也是这样，请问解决了吗？

**Comment by Spittongue** [comment]
我也遇到了，重装了一下style就回来了

**Comment by hhh3321** [comment]
我也遇到这个问题了

**Comment by songquanshuai** [comment]
> 我也遇到了，重装了一下style就回来了

请问重装之后之前的简记会消失么

**Comment by Spittongue** [comment]
> > 我也遇到了，重装了一下style就回来了
> 
> 请问重装之后之前的简记会消失么

我是在插件商店里面直接重装的，都还在，其他的设置也都没变。

**Comment by songquanshuai** [comment]
> > > 我也遇到了，重装了一下style就回来了
> > 
> > 
> > 请问重装之后之前的简记会消失么
> 
> 我是在插件商店里面直接重装的，都还在，其他的设置也都没变。

是第三方软件商店么？

**Comment by songquanshuai** [comment]
> > > 我也遇到了，重装了一下style就回来了
> > 
> > 
> > 请问重装之后之前的简记会消失么
> 
> 我是在插件商店里面直接重装的，都还在，其他的设置也都没变。

重装一下原来的插件已经好了，谢谢！感觉是它自动更新后出问题了

**Comment by Spittongue** [comment]
<img width="902" alt="截屏2024-11-18 12 04 13" src="https://github.com/user-attachments/assets/b4528922-3be1-4df5-a5e5-936b63fa766b">
也是一个插件 可以下载的

**Comment by Spittongue** [comment]
> > > > 我也遇到了，重装了一下style就回来了
> > > 
> > > 
> > > 请问重装之后之前的简记会消失么
> > 
> > 
> > 我是在插件商店里面直接重装的，都还在，其他的设置也都没变。
> 
> 重装一下原来的插件已经好了，谢谢！感觉是它自动更新后出问题了

OKOK wo shuo d我说的那个也是一个插件
<img width="915" alt="截屏2024-11-18 12 06 06" src="https://github.com/user-attachments/assets/bd38b96b-4718-4bb0-9ec4-b3221c337805">

**Comment by hhh3321** [comment]
请问重装是在zotero里把插件先remove，然后再从插件商店里安装最新的吗？

**Comment by songquanshuai** [comment]
> 请问重装是在zotero里把插件先remove，然后再从插件商店里安装最新的吗？

我是直接重新安装一下原来下载好的那个插件，把它覆盖一下就好了

**Comment by hhh3321** [comment]
> > 请问重装是在zotero里把插件先remove，然后再从插件商店里安装最新的吗？
> 
> 我是直接重新安装一下原来下载好的那个插件，把它覆盖一下就好了

试了一下成功了！太感谢了！

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/5.2.9

**Comment by 8pengzhen** [comment]
设置那里点击“修复”，然后重启zotero，我的是这样弄好的

![Image](https://github.com/user-attachments/assets/92992974-d3c7-4edb-9ceb-cd8bb2097d3d)

**Comment by chongyiyang1117** [comment]
> > 我也发现了，简记直接没了，哎，上几版本的zotero很不好用，现在插件适配也很难
> 
> 貌似这里添加remark：就能显示了。但是这样添加起来还是很麻烦的 ![image](https://github.com/MuiseDestiny/zotero-style/assets/130196652/332acf53-b339-4600-aa34-6cb679416c45)

天才

**Comment by H-yfan** [comment]
6.0.79也出现同样的问题，回滚至6.0.4就好了
