### ISSUE TITLE
一些页数比较多的PDF背景色无法改变

### ISSUE THREAD

**Issue by wefuiwheoi** [MuiseDestiny/zotero-style#965]
大佬，不知道为什么，我在使用过程中发现有的PDF背景色无法改成绿色等这些颜色，但前三个日间、夜间都能应用，唯独后面的几个根本不起作用，不知道是不是bug。
![IOzvqE3b67](https://github.com/MuiseDestiny/zotero-style/assets/166273614/6cbddd82-2e97-487a-8ada-c195a03ebca4)

**Comment by MuiseDestiny** [comment]
显然你这是扫描的pdf

**Comment by wefuiwheoi** [comment]
> 显然你这是扫描的pdf
大佬，但我记得以前是能改的啊，因为这本书是我过年前一直在看的，我没记错的话，年前我是正常换背景没问题的，所以后面更新换不了我才有点疑惑，来反映一下看看是不是bug。而且前三种背景色都能换的，我是觉得原理应该是一样的，就后面几种换不了，所以来跟大佬反映一下看看是咋回事。
