### ISSUE TITLE
标题翻译切换快捷键Alt+T与Tools下拉菜单冲突

### ISSUE THREAD

**Issue by panhaoyu** [MuiseDestiny/zotero-style#969]
刚刚更新的版本修复了标题的翻译的切换功能，非常好用，作者辛苦了。

一个小问题是切换标题的时候，Alt+T会同时打开Tools下拉菜单（中文界面里面的“工具”），建议可以屏蔽下相应的事件的冒泡。

不是一个紧急的问题，如果顺手的话可以修一下。

**Comment by MuiseDestiny** [comment]
首选项可以设置快捷键

**Comment by panhaoyu** [comment]
可以考虑默认快捷键换成其它的按键，这样会更符合用户习惯

**Comment by MuiseDestiny** [comment]
> 可以考虑默认快捷键换成其它的按键，这样会更符合用户习惯

好
