### ISSUE TITLE
0.29版本标签分列功能失效

### ISSUE THREAD

**Issue by standingo** [MuiseDestiny/zotero-style#97]
![WeChat2935c7ed1742a9bc2e0de4afa62b2ae8](https://user-images.githubusercontent.com/117378943/216805812-23a6f56f-17b8-4c4c-b1a6-4f048dc32e5f.png)
退回0.28版本后仍无法恢复

**Comment by MuiseDestiny** [comment]
> ![WeChat2935c7ed1742a9bc2e0de4afa62b2ae8](https://user-images.githubusercontent.com/117378943/216805812-23a6f56f-17b8-4c4c-b1a6-4f048dc32e5f.png) 退回0.28版本后仍无法恢复

看起来是插件冲突了。试试逐个禁用其他重启zotero

**Comment by standingo** [comment]
> 

是和better notes插件冲突了
