### ISSUE TITLE
使用zotero的自带的“添加文件”功能会使zotero未响应

### ISSUE THREAD

**Issue by heliu226** [MuiseDestiny/zotero-style#971]
安装了最新版的zotero-style 4.4.1后，发现了该问题。这种情况在4.3.5版本不会发生。经过不断尝试，我觉得可能和其他插件有冲突，尤其是zotero attanger。希望作者可以解决该问题。在此表示感谢！

**Comment by Apiketheworld** [comment]
我这里也是，确实关掉attanger之后就好了

**Comment by heliu226** [comment]
我现在一直用的4.3.5，不敢升级。等待作者处理吧！

**Comment by heliu226** [comment]
作者在4.4.3版本已经解决了该问题，感谢作者！
