### ISSUE TITLE
进度可以单独显示，但无法在标题上显示高能进度条。插件和zotero都是最新版

### ISSUE THREAD

**Issue by uniquekoukou** [MuiseDestiny/zotero-style#983]
各位好，我安装style插件后，进度可以单独显示，但无法在标题栏上显示高能进度条。
zotero版本为6.0.36，style版本为2.6.7
目前已经尝试更新插件、重装插件、设置addon条目、修改颜色代码大小写、重启zotero、重启电脑等，均不成功。

**Comment by uniquekoukou** [comment]
请问下有人清楚这个问题该怎么解决吗？求帮助，谢谢！

**Comment by uniquekoukou** [comment]
已解决

**Comment by isongme** [comment]
你好，请问是怎么解决的呀？

**Comment by uniquekoukou** [comment]
你好，我把style移除之后重新装了一遍，然后把addon设置了一下，再读文献就有了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [MuiseDestiny/zotero-style] 进度可以单独显示，但无法在标题上显示高能进度条。插件和zotero都是最新版 (Issue #983)




 
你好，请问是怎么解决的呀？

**Comment by liudaye1** [comment]
你好，那之前的阅读进度还在么
