### ISSUE TITLE
出现阅读时间条目以及弹窗

### ISSUE THREAD

**Issue by nbugs** [MuiseDestiny/zotero-style#99]
![image](https://user-images.githubusercontent.com/59156652/216810298-59ded1fa-c5f8-43fc-97e3-5901c2f60407.png)
![image](https://user-images.githubusercontent.com/59156652/216810327-5651e5f8-9d25-4351-9f21-4b728ae77a51.png)
![image](https://user-images.githubusercontent.com/59156652/216810345-c5669e69-fb69-4b85-8259-32884359d200.png)

不知道是什么原因，今天更新最新版的style就出现这个

**Comment by MuiseDestiny** [comment]
重新安装下最新版，上传错了
